### ISSUE TITLE
Child Works should show the link to their parent in the search results page.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1001]
### Descriptive summary

This is to denote that a work is a child of another work.

**Comment by CGillen** [comment]
QA:
- [ ] Add work as child to another work
- [ ] Search for child work
- [ ] Find parent work linked from child work search result in list view mode
- [ ] Inspect search result in desktop and mobile resolutions for reasonable reflow

**Comment by shieldsb** [comment]
QA pass.
