### ISSUE TITLE
Work show page metadata field value links to search aren't working

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1006]
### Descriptive summary

On a work show page, when clicking a metadata field to perform a search and find other works with that metadata, the search returns no results.

### Expected behavior

Clicking the linked search term performs a search for that value on the given field and returns appropriate results.

### Steps to Reproduce

1. go to work show page like https://staging.oregondigital.org/concern/images/df65x7762
2. click any linked metadata field, example: Family:
"Saxifragaceae"
3. view no results

**Comment by shieldsb** [comment]
QA fail.  Still getting no results.

**Comment by shieldsb** [comment]
@straleyb Linking worked for subjects, creator, collector, family, genus, admin set.  It did not work for Institution, Repository, or Local Collection Name.

**Comment by straleyb** [comment]
QA is good again once #1104 is in

**Comment by straleyb** [comment]
This is ready for QA. All _label fields should search as expected from show page.

**Comment by shieldsb** [comment]
QA pass.
