### ISSUE TITLE
Replace File Set & Children views to work show page

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1024]
### Descriptive summary
Work for #644 removed the children view and the file set view from the work show page. It would be nice to have those back in for testing at the very least. POSM & Madison Avenue will make a further decision whether we keep these in.

### Expected behavior
From a work, you can reach the file sets and children works.

### Related work
#644

### Accessibility Concerns
Careful with HTML in view

**Comment by CGillen** [comment]
QA:
- [ ] File Sets are visible
- [ ] Child Works are visible

**Comment by shieldsb** [comment]
QA pass.
