### ISSUE TITLE
Update Help Text and Form Labels for Dates

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1026]
### Descriptive summary

MAP for quick access: https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0

- [x] Date Created Help Text
- [x] Date Created Form Label
- [x] Date Collected Form Label

**Comment by sseymore** [comment]
QA pass
