### ISSUE TITLE
Administrative Help Text and Form Labels

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1030]
### Descriptive summary

- [x] Modified Missing from form
- [x] Original Filename Label misspelling and Help Text missing
- [x] Date Uploaded Missing from form

**Comment by sseymore** [comment]
Metadata team wants to keep Date Modified and Date Uploaded on the form and work. Would like to have that data system generated and auto-filled.

**Comment by sseymore** [comment]
Additional clarification: Both Date Modified and Date Uploaded will be locked/un-editable. Move Date Modified and Date Uploaded to the bottom of the form.

**Comment by straleyb** [comment]
QA:
- [ ] Go to edit page and check the bottom of the form for locked date submitted and date modified
- [ ] Should have dates in them.
- [ ] Save the work and dates should show up on show page

**Comment by shieldsb** [comment]
QA pass.  Date modified and date submitted were locked/uneditable.  Once I saved the work, a new date modified was automatically generated for the work.
