### ISSUE TITLE
Fix postgres environment vars

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1033]
### Descriptive summary

I started from scratch today and postgres wouldn't start:

```
db-dev_1           | Error: Database is uninitialized and superuser password is not specified.
db-dev_1           |        You must specify POSTGRES_PASSWORD to a non-empty value for the
db-dev_1           |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
db-dev_1           |
db-dev_1           |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
db-dev_1           |        connections without a password. This is *not* recommended.
db-dev_1           |
db-dev_1           |        See PostgreSQL documentation about "trust":
db-dev_1           |        https://www.postgresql.org/docs/current/auth-trust.html
```

I hacked in the easy fix, `POSTGRES_HOST_AUTH_METHOD=trust`, and all's well again.  But pg ***really*** doesn't like that, so I'm thinking we want to set a password.  Since that password would be in our repo, we don't want the same password in dev/staging as production.

### Expected behavior

Postgres... um... actually starts up?  I mean, do we really need "Expected behavior" here?

### Accessibility Concerns

Actually, maybe we shouldn't fix this.  Having no database is a big accessibility win.  If the website is inaccessible to *everybody*, it's equally usable by all!

**Comment by CGillen** [comment]
QA:
- [ ] Your development environment comes up and doesn't complain about `POSTGRES_PASSWORD` or `POSTGRES_HOST_AUTH_METHOD`
- [ ] Same with test environment

**Comment by luisgreg99** [comment]
The update #1038 worked for me locally. The test environment also worked. I ran rspec and it went well.

**Comment by jechols** [comment]
I haven't run tests yet, but dev works properly now.  And presumably tests worked for circle to allow the PR to merge.  I think we can call this a QA pass.
