### ISSUE TITLE
Image server not loading any images on staging

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1041]
### Descriptive summary

No images are loading from the image server. Manifest seems structurally ok, as one work was showing the multiple pages still in the Universal Viewer, just no images loaded.

Possibly related: sometimes seeing in browser:
```
504 Gateway Time-out
openresty/1.15.8.1
```

### Expected behavior

Images load on work show page: https://staging.oregondigital.org/concern/images/df70bm87b?locale=en

**Comment by jechols** [comment]
Looks like something isn't mounted into the IIIF pod properly.  I can kick off bash within the container, and `ls` works fine... right until I try to see the images directory.  `ls /var/local` just hangs.

A pod restart could help, but I have no idea - and I want to wait to see if @decimalator can do any digging to figure out what might be causing this to happen.  I'm pretty sure this isn't the first time the filesystem has dropped out for an extended period of time.

**Comment by jechols** [comment]
@DeadCatLady this is in your domain, too, I think.

**Comment by wickr** [comment]
The rais deployment config hadn't been updated to point to new back-end location for data storage, but it was and the image server is working as expected.
