### ISSUE TITLE
Create indexer for Location Combined Facet. 

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1043]
Descriptive summary
To create the location combined facet we will need to index all the metadata together into one new solr field. Blacklight will then query that solr field to build the facet and search all values at the same time.

Expected behavior
All metadata in column Q of the MAP that matches creator is indexed into one field in solr

Related work
Subticket of #50

Accessibility Concerns
N/A

**Comment by CGillen** [comment]
Fixed by #1056

**Comment by CGillen** [comment]
QA:
- [ ] Create new or re-save existing work.
- [ ] Work still save
- [ ] Metadata still indexes (appears with labels) some time later

Extra Credit:
- [ ] Port forward with kubectl `kubectl port-forward statefulset/solr 8984:8983`
- [ ] Connect to solr `localhost:8984`
- [ ] Query for work and find `location_combined_label` field with all location fields indexed

**Comment by CGillen** [comment]
QA'd with: https://staging.oregondigital.org/concern/images/vm40xr61f
