### ISSUE TITLE
Create Indexer for Date Combined Facet

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1046]
Descriptive summary
To create the Date combined facet we will need to index all the metadata together into one new solr field. Blacklight will then query that solr field to build the facet and search all values at the same time.

Expected behavior
All metadata in column Q of the MAP that matches creator is indexed into one field in solr

Related work
Subticket of #50

Accessibility Concerns
N/A

**Comment by CGillen** [comment]
@CGillen Has been QAing indexers
QA:
- [ ] Create new or re-save existing work.
- [ ] Work still save
- [ ] Metadata still indexes (appears with labels) some time later

Extra Credit:
- [ ] Port forward with kubectl `kubectl port-forward statefulset/solr 8984:8983`
- [ ] Connect to solr `localhost:8984`
- [ ] Query for work and find `date_combined_label` field with all creator fields indexed

**Comment by CGillen** [comment]
QA with: https://staging.oregondigital.org/concern/images/vm40xr61f

**Comment by sseymore** [comment]
Additional clarification: The UI/functionality of this facet will resemble the Date facet in Scholars Archive with the filtering and slider functionality. 

This can be tested by service managers at a later point. 

<img width="1015" alt="Screen Shot 2020-03-24 at 2 44 44 PM" src="https://user-images.githubusercontent.com/7328774/77480004-1b83a100-6dde-11ea-8bf6-4b8aed568612.png">
