### ISSUE TITLE
Create Indexer for Copyright Combined Facet

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1047]
Descriptive summary
To create the Copyright combined facet we will need to index all the metadata together into one new solr field. Blacklight will then query that solr field to build the facet and search all values at the same time.

Expected behavior
All metadata in column Q of the MAP that matches creator is indexed into one field in solr

Related work
Subticket of #50

Accessibility Concerns
N/A

**Comment by straleyb** [comment]
QA:
- [ ] Ingest a work or update another work by filling out the license and rights statement fields
- [ ] The data should be indexed.

@CGillen This some more of that "backend" QA you were talking about

**Comment by CGillen** [comment]
QA'd with: https://staging.oregondigital.org/concern/images/vm40xr61f?locale=en
