### ISSUE TITLE
Configure Creator combined facet in catalog controller

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1048]
### Descriptive summary
After the Creator combined field is indexed in solr, blacklight can be configured to facet and search it. The original Creator facet will need to be reworked or all the sub-facets will need to be removed as facets.

### Expected behavior
The search index page presents a new facet for Creators that provides a combination of values for all creator types.

### Related work
subticket of #50
depends on #1042 

### Accessibility Concerns
Blacklight should handle facet HTML, but double check it.

**Comment by CGillen** [comment]
QA:
- [ ] Search results page provides a `Creator` facet
- [ ] `arranger artist author cartographer collector composer creator contributor dedicatee donor designer editor illustrator interviewee interviewer lyricist owner patron photographer print_maker recipient transcriber translator` Are not longer facets
- [ ] `Creator` facet may only have very few values for now (until a reindex occurs) At time of writing it should have two values that facet to the same work. That work should have those two values in its creator field
- [ ] If more metadata is added to the currently facetable work, or other works are reindex, values from checkbox 2 should appear in the creator facet

**Comment by shieldsb** [comment]
QA pass.
