### ISSUE TITLE
Configure Scientific Names combined facet in catalog controller 

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1049]
### Descriptive summary
After the Scientific Names combined field is indexed in solr, blacklight can be configured to facet and search it.

### Expected behavior
The search index page presents a new facet for Scientific Names that provides a combination of values for all Scientific Names.

### Related work
subticket of #50
depends on #1044 

### Accessibility Concerns
Blacklight should handle facet HTML, but double check it.

**Comment by CGillen** [comment]
QA:
- [ ] Search results page provides a `Scientific Name` facet
- [ ] `taxon_class family genus order species phylum_or_division` Are no longer facets
- [ ] If a new work is created, an old work is updated, or other works are reindexed values from checkbox 2 should appear in the creator facet

**Comment by shieldsb** [comment]
QA pass.
