### ISSUE TITLE
Configure Topic combined facet in catalog controller

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1050]
### Descriptive summary
After the Topic combined field is indexed in solr, blacklight can be configured to facet and search it.

### Expected behavior
The search index page presents a new facet for Topicthat provides a combination of values for all Topic.

### Related work
subticket of #50
depends on #1045 

### Accessibility Concerns
Blacklight should handle facet HTML, but double check it.

**Comment by CGillen** [comment]
QA:
- [ ] Search results page provides a `Topic` facet
- [ ] `keyword subject` Are no longer facets
- [ ] If a new work is created, an old work is updated, or other works are reindexed values from checkbox 2 should appear in the creator facet

**Comment by shieldsb** [comment]
QA pass.
