### ISSUE TITLE
Configure Location Combined Facet in Catalog Controller

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1051]
Descriptive summary
After the Location combined field is indexed in solr, blacklight can be configured to facet and search it.

Expected behavior
The search index page presents a new facet for Location that provides a combination of values for all Scientific Names.

Related work
subticket of #50
depends on #1043

Accessibility Concerns
Blacklight should handle facet HTML, but double check it.

**Comment by CGillen** [comment]
QA:
- [ ] Search results page provides a `Location` facet
- [ ] `ranger_district water_basin location` Are no longer facets
- [ ] If a new work is created, an old work is updated, or other works are reindexed values from checkbox 2 should appear in the creator facet

**Comment by shieldsb** [comment]
QA pass.
