### ISSUE TITLE
Configure Date Combined Facet in Catalog Controller

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1052]
Descriptive summary
After the Date combined field is indexed in solr, blacklight can be configured to facet and search it.

Expected behavior
The search index page presents a new facet for Date that provides a combination of values for all Scientific Names.

Related work
subticket of #50
depends on #1046

Accessibility Concerns
Blacklight should handle facet HTML, but double check it.

**Comment by straleyb** [comment]
QA:
- [ ] Fill out all the dates in a new work or updated work
- [ ] Create an empty search and go to the search page.
- [ ] Check the "Date" facet and verify all the dates show up in the list.

**Comment by shieldsb** [comment]
QA pass.
