### ISSUE TITLE
Configure Copyright Combined Facet in Catalog Controller. 

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1053]
Descriptive summary
After the Copyright combined field is indexed in solr, blacklight can be configured to facet and search it.

Expected behavior
The search index page presents a new facet for Copyright that provides a combination of values for all Scientific Names.

Related work
subticket of #50
depends on #1047 

Accessibility Concerns
Blacklight should handle facet HTML, but double check it.

**Comment by straleyb** [comment]
QA:
- [ ] Ingest a work filling out rights statement and license
- [ ] Go to empty search results by searching with an empty search box
- [ ] Copyrights facet should show up with the proper data

**Comment by shieldsb** [comment]
QA pass.
