### ISSUE TITLE
Enable and configure full text extraction

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1055]
### Descriptive summary
#850 wants to display full text in the search results list view with highlighting. This will require full text extraction and indexing.

This will also allow for general search to search inside documents.

Will likely have something to do with configuration: https://github.com/OregonDigital/OD2/blob/master/config/initializers/hyrax.rb#L101

### Expected behavior
Full text is extracted from text documents and is indexed into solr

### Related work
Blocks #850

### Accessibility Concerns
Displaying full text or partial text from documents may produce any number of issues in display.
Be careful with how the full text field is rendered

**Comment by CGillen** [comment]
QA:
- [ ] Attach a file with text to work (PDF, txt, doc maybe?)
- [ ] Work still saves
- [ ] File appears on work page (may take some time to process)
- [ ] Search unique text from inside file, work is in results (may require approving work)

**Comment by shieldsb** [comment]
QA pass.  Created and tested work titled OSU test 023.
