### ISSUE TITLE
Index fileset file format

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1065]
### Descriptive summary

File Format in fileset metadata needs to be indexed for searching and faceting.

### Expected behavior

File Format metadata is automatically generated in fileset metadata. It appears as a facet in Format and is searchable. 

### Related work

[Fileset Metadata #1069](https://github.com/OregonDigital/OD2/issues/1069)

### Accessibility Concerns

Not sure

**Comment by CGillen** [comment]
QA:
- [ ] File format is searchable
- [ ] File format displays as facet (require reindex/resave of work)

**Comment by shieldsb** [comment]
QA pass.
