### ISSUE TITLE
Index fileset OCR

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1066]
### Descriptive summary

OCR in PDF files is in fileset metadata. That OCR is indexed and searchable. 

### Expected behavior

OCR is searchable.

### Related work

[Fileset Metadata #1069](https://github.com/OregonDigital/OD2/issues/1069)
[Enable and configure full text extraction #1055](https://github.com/OregonDigital/OD2/issues/1055)

### Accessibility Concerns

Not sure.

**Comment by CGillen** [comment]
Fixed by #1055 
Any text in text docs and PDFs are indexed into `all_text_timv` on the fileset for searchability and `all_text_tsimv` on the work for text highlighting.

OCR will need to be included into the PDF as part of #1100
