### ISSUE TITLE
Make user activity private

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1067]
### Descriptive summary

Fileset metadata includes user activity. Make this information private to only admin users that are logged in.

### Expected behavior

See use events for changes to file with versioning, and changes to metadata with user and timestamp.

We do not need annotation for events right now- can be future enhancement.

### Related work

[Fileset Metadata #1069](https://github.com/OregonDigital/OD2/issues/1069)

### Accessibility Concerns

Not sure.

**Comment by CGillen** [comment]
QA:
- [ ] From a fileset page (https://staging.oregondigital.org/concern/parent/gb19f586c/file_sets/n583xv03w) I can view the User Activity section if I am an admin
- [ ] From a fileset page, I can not view the User Activity section if I am NOT an admin

**Comment by shieldsb** [comment]
QA pass.
