### ISSUE TITLE
Configure Audio Work Type

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#109]
### Descriptive summary

Metadata Presenter Indexer

**Comment by luisgreg99** [comment]
Customize metadata given [Metadata Application Profile](https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0)
- [ ] 1. Generate Audio work type --> done by https://github.com/OregonDigital/OD2/pull/67
- [ ] 2. Set labels and help text
- [ ] 3. Define model, form, and presenter class in controller
- [ ] 4. Define metadata in the model
- [ ] 5. Modify the Edit Form
- [ ] 6. Modify the Show Page 
- [ ] 7. Configure a property or properties to be shown in the search results for a work

**Comment by wickr** [comment]
QA done and OK.
