### ISSUE TITLE
OCR'ing of text at ingest

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1100]
### Descriptive summary

We would like to have OCR happen at ingest in OD2 if the file is not already OCR'ed. @CGillen mentioned other institutions have implemented ingest OCR with Tesseract.

### Expected behavior

If a document is ingested with OCR, the original OCR is kept with the file. If a document is ingested without OCR text, that OCR'ing happens at ingest. 

### Related work

Not sure.

### Accessibility Concerns

Not sure... well... OCR usually sucks....

**Comment by CGillen** [comment]
Princton used tesseract at some point: https://github.com/pulibrary/plum/

but they migrated to stack that's only partly hyrax, basically Valkyrie without the hyrax. Still possibly useful: https://github.com/pulibrary/figgy/

**Comment by CGillen** [comment]
OCRing is happening at fileset level, getting indexed on the fileset, and promoting to the work level for better searching. Any new functionality or issues should be a new ticket
