### ISSUE TITLE
Investigate other job-processing options

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1106]
### Descriptive summary

From slack on April first (I know, but this is real): it seems that sidekiq does *not* guarantee fault-tolerance.  It uses a redis queue, and pops items off the queue for processing, adding them back to the queue if the job is terminated gracefully.  @CGillen mentioned that redis allows for a way to be more graceful about such things, but that appears not to be used for the free sidekiq - you have to pay for sidekiq pro.

The risk of data loss is pretty low (worst-cases would be a handful of jobs lost - in many cases we'd know if these jobs were lost, such as a bulk ingest), and the risk of this happening is pretty low (power failure, OOM, other relatively rare events?).

So do we look at alternatives?  If we do, how much time is it worth to investigate?  How much time is it worth to replace sidekiq?

One option might be RabbitMQ: https://blog.stanko.io/rabbitmq-is-more-than-a-sidekiq-replacement-b730d8176fb

### Expected behavior

I think right now we just want to answer questions.

**Comment by wickr** [comment]
Potentially paying for Sidekiq Pro is worth it, even over several years it could be less than the developer time/money needed to get something else in place.

**Comment by decimalator** [comment]
working on adding Sidekiq metrics, which would alert us to any potential lost jobs.
