### ISSUE TITLE
Add On Pages property

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1112]
### Descriptive summary

As part of the metadata remediation we discovered that On Pages (onPages) had been used in OD1 but wasn't a part of the Metadata Dictionary and hadn't been included when the OD2_MAP was made. The predicate was changed along with others. It's now listed and ready to be added to the system and the Document model, forms, etc.

https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0&range=135:135

### Expected behavior

On Pages is included in OD2, visible, and editable according to the MAP.

Also add it to https://github.com/OregonDigital/OD2/blob/master/lib/tasks/oregon_digital/create_full_metadata_work.rake

### Related work

https://github.com/OregonDigital/oregondigital/issues/1241

**Comment by CGillen** [comment]
QA:
- [ ] On Pages exists on as metadata on the form for document work type
- [ ] On Pages shows on work show page
- [ ] Check with Metadata if On Pages is in an acceptable location of work show page
- [ ] On Pages does not show in search or facets and is not searchable

**Comment by sseymore** [comment]
@wickr @carakey @KevinJonesMeta Do ya'll have opinions about location on work show page? You can edit my test item to determine where you want it: https://staging.oregondigital.org/concern/documents/z603qx43s?locale=en#?c=0&m=0&s=0&cv=0&xywh=-3146%2C-2%2C9591%2C3300

**Comment by wickr** [comment]
QA pass (thanks Sarah)

After chatting in Slack we're good with the location. If we wanted it adjusted it would likely be part of a bigger Publishing fields reorder which would be a separate ticket.
