### ISSUE TITLE
Change Universal Viewer and integrated download

### ISSUE THREAD

**Issue by raybrarian** [OregonDigital/OD2#1115]
### Descriptive summary

Remove UV download button:
![image](https://user-images.githubusercontent.com/4460510/78943314-74a33400-7a70-11ea-9071-6428d4521746.png)

Change OD2 downloads to be integrated on the showpage- no separate action dropdown under item to download - it should all be in one place, under Downloads. 

Pull the Items section (example resource): https://staging.oregondigital.org/concern/images/df719p38s?locale=en#?c=0&m=0&s=0&cv=0&xywh=799%2C2324%2C3124%2C1377 

### Expected behavior

No downloads through UV, only through the Downloads section. The download options should be the ones we decided on in the wireframing and workflow stage - https://drive.google.com/drive/folders/1Hb0xiIWz5EwCuKeQTnQuSOyE1c-FAKzL 

- Standard (file with .csv)
- High resolution (file with .csv)
- Metadata only (.csv)

### Accessibility Concerns

Need to ensure all links have useful ink text

**Comment by CGillen** [comment]
Reviewed By: @petersec 
ready to be worked on.

**Comment by CGillen** [comment]
QA:
- [ ] Go to a work show page
- [ ] See Universal Viewer does not allow the option to download image (bottom left)
- [ ] Download is still an option in the download section of page

**Comment by shieldsb** [comment]
QA pass.
