### ISSUE TITLE
Fix Universal Viewer locales

### ISSUE THREAD

**Issue by raybrarian** [OregonDigital/OD2#1117]
### Descriptive summary

Current UV is toggling between Great Britain (GB) and Welsh for locales.
![image](https://user-images.githubusercontent.com/4460510/78944019-d6b06900-7a71-11ea-9308-68b657cdcabe.png)

### Expected behavior
No locale change function present, if possible

### Accessibility Concerns

Remove dropdown entirely - no hidden content

**Comment by petersec** [comment]
The option is identified as location, but functions as language. The option other than English (GB) is Cymraeg, or Welsh. Selecting it changes all text within UV to Welsh.

**Comment by CGillen** [comment]
QA:
- [ ] Go to work show page
- [ ] Select UniversalViewer options (cog, top right)
- [ ] See no more drop down for locale

**Comment by shieldsb** [comment]
QA pass.
