### ISSUE TITLE
Universal Viewer - investigate "mouse click to zoom" "preserve zoom" settings

### ISSUE THREAD

**Issue by raybrarian** [OregonDigital/OD2#1118]
### Descriptive summary

In the UV settings config (the gear in the UV interface), there is a setting called "mouse click to zoom". If this is an accessibility accommodation we need to keep it - otherwise, we should determine if we need it. The same is true for "preserve zoom" in the same interface.

### Accessibility Concerns

As noted

**Comment by CGillen** [comment]
Settings functionality:

- Mouse click to zoom allows the user to click and zoom on the image.
  - When selected, a single click will zoom the image, a click and drag will not zoom and will move the image. Double click zooms the image twice. Scroll wheel zooms
  - When un-selected, a single click will do nothing, a click and drag will not zoom and will move the image. Double click does not zoom the image. Scroll wheel zooms

- Preserve zoom preserves the zoom level when change the selected canvas/image in the same Universal Viewer session, such as going from page 1 to page 2 of a pdf. This isn't effective across viewing sessions or for sharing urls (the zoom is baked into the url already)

**Comment by CGillen** [comment]
These settings have little to do with a11y, they're fairly descriptive and make almost NO difference to users. If someone finds it helpful and they find the options then they can get at them.
