### ISSUE TITLE
Update Location URI Labels and hierarchy

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1124]
### Descriptive summary

Labels for Location URIs referencing GeoNames should provide enough information in the hierarchy to disambiguate, but not too much that the strings are too long. GeoNames provides the hierarchy structure, but we need to place some limits to ensure that only the information we want is included.

We want the hierarchy display to stop at Country. This ends up being 3 (added) levels max. (it looks like this should be working now, but maybe the GeoNames response update to include 'https' is breaking the `top_level_codes` check)

Continents and other higher-level values should not display as part of the hierarchy, but are fine if that is the URI put in: Asia, North America, Earth, etc.

When going up the hierarchy, make sure to *only* use the 'Administrative hierarchy' values, not the 'Parents' values. For example, for Oregon: https://www.geonames.org/5744337/oregon.html
(click 'Hierarchy' button) see the 'Administrative hierarchy' has United States listed as country. But click over to 'Parents' and see 'West', 'Pacific Northwest' and 'Pacific states', which are all ones we do not want to display or follow.

Feature code labels should not display.

County names should include 'County': Deschutes County

### Expected behavior
(several examples here, not meant to be exclusive)

valid forms:
  - [City] >> [County] >> [State] >> United States
  - [River] >> [County] >> [State] >> United States
  - [County] >> [State] >> United States
  - [State] >> United States
  - [City] >> [Province] >> [Country]
  - [Country]

also valid:
  - Northwest >> United States
  - Pacific Northwest >> United States
  - Asia

### Accessibility Concerns

N/A

**Comment by CGillen** [comment]
QA:
After a work is newly ingested or reindexed:
- [ ] Location metadata never references above the country level
- [ ] Location metadata used `>>` instead of ` , `
- [ ] Each of the "valid forms" and "also valid" patterns are followed when starting from the left most location.

**Comment by shieldsb** [comment]
QA fail.  County does not fully display with state and country name.  All other tests (city, river, state, country, and Pacific Northwest all displayed as expected and pass QA.)

**Comment by shieldsb** [comment]
QA pass.

**Comment by CGillen** [comment]
After `https` fix, @sseymore  to QA

**Comment by sseymore** [comment]
QA pass. With https, the valid labels are fetching.
