### ISSUE TITLE
Improved more facets A-to-Z view

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1133]
### Descriptive summary
In the 'more' pop-over in the facet, one of the sorting options is A-to-Z.
The display should include an alphabet select at the top to further filter the results by first letter.

### Expected behavior
A-to-Z has an easy way to jump to facet values based on first letter.

### Related work
N/A

### Accessibility Concerns
Alphabet list are notoriously bad for a11y. They're a pain to skip pass and provide little context for what's going on as you're tabbing through. Make sure there is at least a header immediately after the list so keyboard users can jump pass it by headers.

Also, live updating content is difficult to get right. Be sure to follow [live-regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) and do some research on properly implemented a-to-z lists.

**Comment by sseymore** [comment]
Metadata Team thinks that this is an enhancement, but OK with it.

**Comment by wickr** [comment]
Just found the latest Blacklight has this built-in.

Go to http://demo.projectblacklight.org/
Find Topic facet
click More
click A-Z Sort

There's no buttons for items that start with #s though. 'All' covers that, maybe not effectively enough.

**Comment by wickr** [comment]
Facet prefix does work with numeric values: http://demo.projectblacklight.org/catalog/facet/subject_ssim?facet.prefix=1&facet.sort=index

So maybe adding to the list of buttons would be 'easy'

**Comment by CGillen** [comment]
From the catalog controller generator: https://github.com/projectblacklight/blacklight/blob/v6.23.0/lib/generators/blacklight/templates/catalog_controller.rb#L74
There's an example of adding prefix facet filtering with `:index_range`

**Comment by wickr** [comment]
We probably don't need separate buttons for numbers, even our Creator and Topic only have a handful of values starting with a number, which would show by default under 'All'

https://oregondigital.org/catalog/facet/desc_metadata__lcsubject_label_sim?_=1588891590121&facet.page=1&facet.sort=index

**Comment by CGillen** [comment]
@megwalt @jechols Maybe a skip-nav link, like we have at the beginning of the main page, might be appropriate here?
We could have a screen-reader only link before the A-Z list that says something like `Skip A to Z prefix navigation`?

I know this functionality sucks for a11y, but we really need it so users can deal with >1700 pages of topics

**Comment by jechols** [comment]
Skip or heading would improve accessibility, and honestly I’d push for the heading over a skip link: headings are the primary mode of navigation for screen-reader users, and a hidden skip link is awful for sighted keyboard users – which means coming up with a hidden-but-reveal-on-focus link, which is potentially confusing, etc....

But the question I have is why a huge pile of buttons in the first place? A live filter where people can start typing is more accessible and most likely more user-friendly for all users. If they don’t know what they’re looking for, A-Z list doesn’t actually help. If they do, A-Z list doesn’t help as much as a live filter.

**Comment by KevinJonesMeta** [comment]
QA fail.

On staging, A-Z buttons appear at top of Topics facet list but does not appear on other facets after A-Z sort.

**Comment by megwalt** [comment]
@KevinJonesMeta it is intended to be there. Looking at what I have, it's probably missing from the 'Institution' facet as well. I will have to fix that.

**Comment by KevinJonesMeta** [comment]
QA pass. A-to-Z options shows on Collections and Institutions now as well.
