### ISSUE TITLE
Default a-to-z sort for more facets view

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1134]
### Descriptive summary
In the 'more' pop-over in the facet, the default sorting option should be A-to-Z.

### Expected behavior
A-to-Z is show first and selected when 'more' is clicked on a facet.

### Related work
#1133 

### Accessibility Concerns
Hopefully A-to-Z is just as accessible as Numerical Sort

**Comment by sseymore** [comment]
The metadata team has a slight preference for numerical sort, but really just want both facet interfaces to have the same default for consistency.

**Comment by petersec** [comment]
After POSM meeting of 5-7-20, decided to keep at numerical, but needs user testing.
