### ISSUE TITLE
Item showpage URI links on metadata only display for depositors and above

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1135]
### Descriptive summary
The link out icon is confusing and should not be used by regular system users. It's main purpose is to be useful to collection managers and other system users.

Let's hide it for most users for now.

### Expected behavior
The link out to the vocabulary term only displays for those with the depositor role and above (collection curator and admin).
Unauthenticated users and community users (osu/uo roles) only see the link to search the catalog.

### Related work
N/A

### Accessibility Concerns
A11y improvement to not have back-to-back links, where read as one link by vision it looks like one of the links goes somewhere it doesn't.

**Comment by sseymore** [comment]
The Metadata Team feels strongly about this and would like to keep this functionality for several reasons:

- We do not think it is a terrible usability or visual hindrance to users.
- This shows connections with external websites, which demonstrates real-world authority, item and collection relationships, and richness of our metadata. 
- Other websites like Wikipedia have similar links, so users are already used to seeing this functionality.
- This has potential for future data integration. 
- There is great potential for collection/item reuse with this feature. For example: Users adding our digital collections items to Wikipedia/Wikidata/other authoritative (or not!) websites. 
- Open to improving the UI/interface of this linking

**Comment by petersec** [comment]
After POSM meeting of 5-7-20, decided that this ticket needed to be refined and that a user story needed to be created for this use. Also need to create something for MAC to incorporate into their wireframes. Consensus is that this functionality is ok to remain but needs to be redesigned from current staging view. @jsimic will be taking the lead on this, including identification of individual(s) that we can enlist for user testing.

**Comment by jsimic** [comment]
Added user story. This has been MVP since early planning of OD2.

**Comment by jsimic** [comment]
As per discussion with MAC, we want to keep this functionality and work on the presentation. POSM and Mac will continue to work on this.
