### ISSUE TITLE
Item metadata accordion

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1136]
### Descriptive summary
It's possible to display WAAAAAAY too much metadata by default. Users may be interested in specific pieces of metadata for research purposes, but general browsers are going to be overwhelmed.

We can hide some metadata behind an accordion and only display the top 10 pieces by default.

### Expected behavior
First 10 rendered pieces of metadata are displayed without further action.
A show more button is available to accordion out and expand out the rest of the metadata.

### Related work
N/A

### Accessibility Concerns
Check online if link or button is better in this situation for a11y. Also make sure hiding content behind an accordion or expandable box meets a11y standards.

**Comment by sseymore** [comment]
The Metadata Team also feels strongly about this. We do not want to hide any metadata, but we are open to finding a middle ground that works for most users. Our thoughts:

- 10 fields seems very arbitrary as the metadata between collections varies so much.
- We do not want another click for users- want to see it all or most of it with the digital item at first glance.
- Most importantly, we feel that we have rich metadata to show and that's vital to what a digital collections repository is. 

Potential solutions:

- Short previewing/truncating long metadata fields like Description (maybe based off of character counts?) or fields with a lot of values (like if there are more than X number of URIs in Subject)
- Open to reordering metadata on work (push longer metadata to the bottom?) or highlighting some fields over others
- The IIIF core metadata manifest in UV can represent those core/minimal fields for users and be more prominent at the top of the work page

**Comment by petersec** [comment]
After POSM meeting of 5-7-20, decided we don't want an accordion -- going with two column MAC layout instead.
