### ISSUE TITLE
Metadata display order for top 10 accordion style

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1137]
### Descriptive summary
Because #1136 will have only the top 10 metadata terms displayed by default, we want to make sure those 10 are really important to the user.

Reorder metadata so that certain fields or groups of fields will be pushed to the top or not display at all if not filled out.

Title
Date
Creator (Artist, Illustrator, Composer, etc. would render here if they exist within the record, but wouldn’t render at all if they don’t exist)
Description
Location
Copyright
Use Restrictions (As Needed)
Subjects
Genre
Identifier
Digital Collection (Set currently) 
Archival (Local) Collection
Institution
Citation

### Expected behavior
The above terms come first on the work show page. Some include groupings, like Creator should be all the terms that are in the combined Creator facet.

### Related work
#1136 

### Accessibility Concerns
N/A

**Comment by sseymore** [comment]
Please see comments from Metadata Team in #1136

**Comment by petersec** [comment]
After POSM meeting of 5-7-20, decided to get rid of accordion and to do user testing to determine arrangement and terminology for display of metadata fields.
