### ISSUE TITLE
Date range selection on date facet

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1141]
### Descriptive summary
The date facet should be a date range selection widget. This is a format that is more user friendly and more familiar to many users.

https://github.com/projectblacklight/blacklight_range_limit is an option for implementing the widget

The work done in this file should be applied to OD2: https://github.com/osulp/Scholars-Archive/blob/master/app/models/concerns/scholars_archive/date_operations.rb
The goal is to have the same date slider facet, based on the years, that SA has.

### Expected behavior
The date facet can be narrowed to a range of dates, either by slider or text boxes.
The granularity should at least be to the year level, month may be a bit too granular.

### Related work
The combined date facet may have made this a little more difficult. #1052 
https://github.com/osulp/Scholars-Archive/blob/master/app/models/concerns/scholars_archive/date_operations.rb

### Accessibility Concerns
The widget needs to be usable by keyboard and understandable by screen readers. Look for other examples and their WCAG compliance.

**Comment by CGillen** [comment]
QA:
- [ ] Ingest work with multiple dates
  - [ ] One date in EDTF (yyyy-mm-dd)
  - [ ] One date in non-standard format (Jan dd, yyyy)
  - [ ] One date that is not a date (bacon)
- [ ] Date facet appears
  - [ ] Is similar to SA, date range facet
  - [ ] Filtering to year range that includes EDTF date presents work
  - [ ] Filtering to year range that excludes EDTF date does not presents work
- [ ] Decade facet appears
  - [ ] Selecting decade that EDTF date is in presents work

**Comment by shieldsb** [comment]
QA pass.
