### ISSUE TITLE
UX Test for Metadata display

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1142]
### Descriptive summary
The order and terminology around metadata display is most of the way there from Metadata's design. We should verify our selection with some UX testing. Some questions to consider:
- Do users understand the label for the metadata?
- Can a user find the pieces of metadata most important to them? Can they find it easily?

Once a preferred order is identified a separate ticket can be created to finalize the changes.

### Expected behavior
Metadata is clear and understandable by a significant amount of users.

### Accessibility Concerns
Better usability doesn't necessarily mean better accessibility. Any new labels and orders need to be understandable by screen readers and other low-vision tools/circumstances.

**Comment by jsimic** [comment]
Related ticket #764
