### ISSUE TITLE
[MyShelf] Allow an unprivileged authenticated user to create collections

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1143]
### Descriptive summary
As part of My Shelf functionality, a user should be allowed to create a collection (the shelf) of a `User Collection` type.
User collections should require no more metadata input than title and description.

### Expected behavior
Any authenticated user can create a personal collection.

### Related work
Subticket of:
#643

**Comment by straleyb** [comment]
QA: As a typical registered user, with no extra privileges, you should be able to go to the dashboard, click collections, click create new collection.

This should take you to the new User Collection page only displaying the title and description fields. Once saved it should create the collection.

**Comment by shieldsb** [comment]
Update: It  does add additional works to a collection even though I receive the ack message.  This comment has been added to ticket #1150 where this issue is addressed.

**Comment by shieldsb** [comment]
QA pass.  Note: when selecting create a new collection from the modal on the work show page, the resulting modal does not appear.
