### ISSUE TITLE
[MyShelf] MyShelf create & add item modal

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1144]
### Descriptive summary
As part of the MyShelf work, a modal is to be displayed when a user selects items to add to their shelf.

See latest MAC wireframe for modal design

### Expected behavior
The modal should have the option to add these works to an existing collection OR add these items to a new collection.
The new collection option should provide a new form for creating the collection
Duplicate items should not be added.
Collections may be added to these collections (as is ootb functionality for Hyrax), this may only be possible from the search results page (no design needed for collection landing page).

### Related work
Subticket of:
#643

Comprised of:
- [x] #1150 
- [x] #1151 
- [x] #1158 

### Accessibility Concerns
Modal should be keyboard accessible and give proper context to SR users.

**Comment by jsimic** [comment]
Is it intended that adding collections add only parents or all works in the collection?

**Comment by CGillen** [comment]
All issues resolved
