### ISSUE TITLE
[MyShelf] Export whole shelf

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1146]
### Descriptive summary
A user should be able to export a whole shelf at a time. It would be smart to write this in such a way that it can be reused to download any arbitrary multiple selection of works.

It makes the most sense that this option would be present on the MyShelf dashboard, when a single shelf is selected.

This may cause performance issues with larger collections, we should explore options such as preparing the download and emailing a link or setting a maximum number of works to export at one time.

### Expected behavior
Similar to how a user can download a single work as a zip of metadata + images, a user can download a whole shelf of works of metadata + images.

### Related work
#759 & #760 

### Accessibility Concerns
Link should be obvious and clear what it will do without additional context

**Comment by mellinma** [comment]
Set a quota for size of download. Email later to accommodate processing time. Assume this is for end-users not curators.

**Comment by raybrarian** [comment]
Investigate Bulkrax functionality before going to far down the downloads path.
