### ISSUE TITLE
Design for login modal

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1148]
### Descriptive summary
The login interface will be a modal that pops over the current page and presents the user with several login options.
* Three initial radio buttons, one for UO, OSU, and local login.
  * UO and OSU options should present a 'Login with your institution' link that presents the institutional login page
  * The local login option should present a user & password form, the option to create an account, and a forgot your password link

### Expected behavior
The login modal looks and feels like the MAC design

Latest MAC design:
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938484

### Accessibility Concerns
Modals may be confusing to keyboard navigation. Look up and pay attention to where keyboard focus goes and what a11y guidelines exist for modal functionality.

**Comment by straleyb** [comment]
QA: 
- [ ] UO login works
- [ ] OSU login works
- [ ] local login works
- [ ] Style green line exists. 
- [ ] Radio button selects only 1 at a time and leads to proper login button
- [ ] Icons and text for login radio buttons exists

**Comment by jsimic** [comment]
Sarah and I have successfully logged in!

**Comment by shieldsb** [comment]
QA pass
