### ISSUE TITLE
Design for exploring collections

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1149]
### Descriptive summary
The exploring collections interface will have be a distinct page and present the user with available collections to browse.
* Four filter tabs: All, OSU, UO, and My collections (my shelf)
* Two displays: Grid, and Masonry
  * Grid displays 3 columns: Name, Institution, Item count
  * Masonry displays thumbnails with name below and item count in parens

### Expected behavior
The exploring collections page looks and feels like the MAC design

Latest MAC design:
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938480

**Comment by CGillen** [comment]
Some work completed by #1166 
Moving back to ready for further work later

**Comment by CGillen** [comment]
QA:
- [ ] About 80%+ match to wireframes - https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938480

**Comment by shieldsb** [comment]
QA fail. 

General comment: 

Masonry View: 

List View:

**Comment by shieldsb** [comment]
QA fail. 

General comment: 

Masonry View: 

List View:

**Comment by CGillen** [comment]
@shieldsb I think we're at a point where any new issues found should be tickets and we can put this one to rest after QA

**Comment by shieldsb** [comment]
QA pass, with the exception of one item that we can make a ticket for if it should still be part of the design. 

List View:
In WF, collection title has an orange down arrow next to it, maybe for sorting purposes
