### ISSUE TITLE
MyShelf modal

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1150]
### Descriptive summary
A short form with add to collection functionality for a work. This modal will be reused in a couple locations.

### Expected behavior
Modal that presents a form for adding a work to a collection. At the bottom of the modal, a link to change the form to create a new collection and add this work to it.

### Related work
Part of #1144 

### Accessibility Concerns
See #1144

**Comment by CGillen** [comment]
QA:
- [ ] A button exists on the work show page called 'Save to...'
- [ ] The button brings up a modal
- [ ] When logged in: the modal presents like MAC's design (https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938486)
- [ ] When not logged in: the modal presents a message to the user to log in
- [ ] The modal allows a user to add a work to a collection they manage

'View my collections' and 'create new collection' links are not relevant to this PR

**Comment by shieldsb** [comment]
QA fail.  Can not add work to a user collection I've already created. All other items pass. 

Should we link "log in" in the message for users not already logged in?

**Comment by shieldsb** [comment]
Update: It does add the work to a collection even though I receive the ack message when I try to add it.

**Comment by shieldsb** [comment]
Still receiving the ack message when trying to save works to an existing myshelf collection.  Also, received the message when I tried to view my collections (clicking view my collections takes me to my dashboard and when I click on the collection name the message appears.  
![image](https://user-images.githubusercontent.com/53542788/83902661-ac95c300-a711-11ea-9cde-8530510adad3.png)

**Comment by CGillen** [comment]
Ok, the issue was coming from landing on the hyrax dashboard collection page. Only users that are able to deposit something are suppose to be able to get there and that was causing a crash.
I've fixed the routing so a user gets routed back to where they created the work from, not the hyrax dashboard

**Comment by shieldsb** [comment]
QA pass.
