### ISSUE TITLE
Hook up MyShelf links to modal

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1151]
### Descriptive summary
The modal created in #1150 needs to be linked from several places.

### Expected behavior
- [x] Work show page as 'Save to...' link
- [x] Search results page as 'Save selected to...' link
- [x] Search results page as 'Save' link on single search result item

### Related work
Part of #1144 
Depends on #1150

### Accessibility Concerns
See #1144

**Comment by straleyb** [comment]
QA: 
- [ ] Make sure a save button exists for each result in search results
- [ ] Save button exists at top of search results page next to number of hits
- [ ] Save button exists with other action buttons on work show page
- [ ] All 3 allow modal pop up to show up

**Comment by shieldsb** [comment]
QA pass.
