### ISSUE TITLE
MyShelf create empty collection from dashboard

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1153]
### Descriptive summary
Add a link on MyShelf dashboard (#1152) to pop-up collection creation modal (#1144)

### Expected behavior
Link at top of MyShelf dashboard OR a placeholder panel at the end of collections where use can open the create collection modal and create and empty collection.

### Related work
Part of #1145 
May depend on #1149 

### Accessibility Concerns
See #1145 & #1149

**Comment by CGillen** [comment]
QA:
- [ ] Button to create new collection appears in explore collection page (https://staging.oregondigital.org/explore_collections), under my collection tab only
- [ ] Modal appears on button press
- [ ] Modal allows a new User Collection to be created
- [ ] New User Collection appears in My Collections tab
- [ ] New User Collection can have a work added to it

**Comment by shieldsb** [comment]
QA pass.  I could add a work to the new collection, but still received the ack message which is being addressed in #1150.
