### ISSUE TITLE
[MyShelf] Hook up check boxes to modal form to submit items to add to collection

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1164]
### Descriptive summary

In order for the save functionality to work for MyShelf, we need to be able to hook up the check boxes in the search results to the modal that exists on the search results page.

**Comment by straleyb** [comment]
QA: On the search results page, find a work that is not a part of a collection. Check the box and click the top "Save Selected To" button. Choose a collection and hit save. It should add that work to a collection.

**Comment by shieldsb** [comment]
QA pass.
