### ISSUE TITLE
Nested collection modal breaks scrolling

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1167]
### Descriptive summary
When following the recommended path for transitioning modals in BS (using data-toggle+data-target and data-dismiss in the same element), there's a bug which prevents the screen from scrolling the window on the second modal.

This is causing the collection creation modal to not allow users with sufficiently tall screens from finding or clicking the save collection button.

### Expected behavior
Secondary and beyond modals can scroll the screen to see more of the modal.

### Related work
Introduced in #1162 

### Accessibility Concerns
Make sure not to break modal a11y.

**Comment by shieldsb** [comment]
QA pass.
