### ISSUE TITLE
Plan to upgrade to Hyrax 3.0-RC1

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1171]
### Descriptive summary
In preparation for Hyrax 3.0 release, and because we are not an actively live site, we should investigate, consider the required work for, and plan to upgrade to Hyrax 3.0 release candidates.

The sooner we are on the 3.0 release candidate track and upgrade path to full 3.0 release, the sooner we can incorporate many blocking changes (Universal Viewer for example) and investigate any other improved features we may have been expected or wanting.

### Expected behavior
Ultimately, OD2 is based on Hyrax 3.0 release candidates and in line to upgrade to the official release.

Start with identifying what may need to change and the scope this work may take (how many WCs, how in depth each team will need to be involved).

**Comment by CGillen** [comment]
To be explored and investigated late into WC11

**Comment by straleyb** [comment]
https://github.com/OregonDigital/OD2/pull/824/files

This may be helpful. It includes a few pieces of problem solving I had to go through in order to get it running initially. Feel free to reference this if needed in order to get 3.0 loading proper.

**Comment by luisgreg99** [comment]
The update is looking good, I just tested a migration run with hyrax-migrator and it worked well so far. I only found a bug in FetchGraphWorker when I was checking the jobs queue: https://github.com/OregonDigital/OD2/issues/1231

**Comment by straleyb** [comment]
We are on rc1 already, we have new release candidates but we can make a new ticket for that. We can continue our upgrade to 3.0
