### ISSUE TITLE
Zipped download major performance issues and system lock-out

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1172]
### Descriptive summary
Choosing download Images+metadata zipped causes MAJOR hang while the images are fetched and processed. It even stalls the entirety of staging while this process is blocking.

I don't recall this blocking behavior before, but have no idea when it may have started or if it's even new.

We should expect to investigate Bulkrax as a possible new base for work exporting and download.

### Expected behavior
Downloading item metadata and images zipped does not cause complete system blocking. Download processing either takes a reasonable time or can be provided asynchronously, depending on investigation and what is feasible.

### Related work
Blocks #1146

**Comment by CGillen** [comment]
QA:
- [ ] Try downloading some zipped downloads from some large works (>100mb)
- [ ] Download does not stall out (Previously confirmed to happen with a work at ~300mb, has been seen on works as small as ~80mb)
- [ ] Downloading a truly massive file (>1gb) does not block other users (or yourself) from viewing other pages in the system

**Comment by shieldsb** [comment]
QA fail.  Tried to download zip file and metadata only file for two works and received the message "Oops! Looks like we can't find the page you asked for. Head back home and search again!" I could download the individual audio files though. 
https://staging.oregondigital.org/concern/audios/df70j777v?locale=en
https://staging.oregondigital.org/concern/audios/6q182k79w?locale=en

**Comment by shieldsb** [comment]
QA pass.
