### ISSUE TITLE
Remove User Collections from search results

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1174]
### Descriptive summary
A user can see their private collections, and other user's public collections from the search results. We need to keep the search results clean of user collections because they have no curated grouping and may clutter the user experience.

### Expected behavior
User Collection collection types do not return in public search results under any conditions.

**Comment by straleyb** [comment]
QA: Make sure there are user collections created. Do a basic search and see whether or not any user collections show up in the search.

**Comment by shieldsb** [comment]
QA fail.  My user collections still appear under the collections facet when I am not logged in.

**Comment by straleyb** [comment]
QA: Verify no user collections show up in the facets.

**Comment by shieldsb** [comment]
QA fail.  1 of 3 user collections still appears in the facets list.  The two created as a non-affiliated user do not appear.  The one created under my admin account still appears when I am searching and not logged in.

**Comment by shieldsb** [comment]
QA pass.
