### ISSUE TITLE
MyShelf dashboard collection delete action

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1180]
### Descriptive summary
A collection should have an delete action from #1154. Deleting should include a confirmation modal before deletion. The action buttons should be toggle-able per collection.

### Expected behavior
Collections can be deleted with confirmation from the explore collections my collections page.

### Related work
Child of #1154 

### Accessibility Concerns
Button and modals should be accessible

**Comment by CGillen** [comment]
QA:
- [ ] Actions in my collections under explore collection dashboard (https://staging.oregondigital.org/explore_collections) includes delete button
- [ ] Delete action produces a modal with warning
- [ ] Delete modal destroys the collection

**Comment by shieldsb** [comment]
QA pass.
