### ISSUE TITLE
MyShelf dashboard collection share/unshare action

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1181]
### Descriptive summary
A collection should have a share action from #1154. Sharing should allow the user toggle the collection between public and private visibility. The action buttons should be toggle-able per collection.

### Expected behavior
Collections can be shared from the explore collections my collections page. A message should be displayed to alert the user that the URL may now be shared when the collection is set to public

### Related work
Child of #1154 

### Accessibility Concerns
Button and modals should be accessible

**Comment by CGillen** [comment]
QA:
- [ ] My collections under explore collection dashboard (https://staging.oregondigital.org/explore_collections) action buttons includes 'share'
- [ ] Share action for unshared collections produces a modal populated with instructions, a sharable link, and a share button
- [ ] Share action for share collections produces a modal populated with instructions, a sharable link, and an unshare button
- [ ] Closing and reopening a modal loads the new collection's data
- [ ] Sharable link takes user directly to collection landing page
- [ ] Shared work is viewable by non-admin different user
- [ ] Unshared work is not viewable by non-admin different user

**Comment by shieldsb** [comment]
QA pass.
