### ISSUE TITLE
MyShelf dashboard collection view action

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1182]
### Descriptive summary
A collection should have a view action from #1154. Viewing should take the user directly to the collection search results page. The action buttons should be toggle-able per collection.

### Expected behavior
Collections can be viewed directly from the explore collections my collections page, skipping the collection landing page.

### Related work
Child of #1154 

### Accessibility Concerns
Button and modals should be accessible

**Comment by CGillen** [comment]
QA:
- [ ] My collections page has a view action
- [ ] View action takes user to the collection landing page

**Comment by shieldsb** [comment]
QA pass.
