### ISSUE TITLE
MyShelf dashboard collection export action

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1183]
### Descriptive summary
This depends on performance issues with the current download functionality: #1172 

A collection should have an export action from #1154. Exporting should allow a user to download all images and metadata for all works in a collection into a single zip file. The action buttons should be toggle-able per collection.

### Expected behavior
Collections can be exported to a single zip file containing images and metadata.csv in a reasonable structure.

### Related work
Child of #1154 

### Accessibility Concerns
Button and modals should be accessible

**Comment by CGillen** [comment]
QA:
- [ ] My collection dashboard has export action
- [ ] Export action brings up export modal
- [ ] Export button in modal allows user to download whole collection
- [ ] Can export collection of just works
- [ ] Can export collection with subset collections
- [ ] Collections with expected size > ~1GB may take a long time but does eventually complete
- [ ] Too large collections (> ~1GB) doesn't freeze the system for other users

**Comment by shieldsb** [comment]
QA fail.  Receive not authorized page when attempting to export using a non-affiliate account (it does allow export with my admin account).  Also, times out when trying to save an entire collection to myself in order to test entire collection export.

**Comment by shieldsb** [comment]
QA fail.  Receive ack message when attempting to export collections.

**Comment by CGillen** [comment]
@shieldsb I'm guessing you tried to export the trees collection?
Please remove this work from the collection and try again: https://staging.oregondigital.org/concern/images/df66zb247

That work has a controlled vocabulary term that doesn't exist in our cache OR in the authority website. It needs more metadata clean up and will probably cause unexpected breakages elsewhere. The term is a subject: http://vocab.getty.edu/aat/300128360, it's probably supposed to be http://vocab.getty.edu/aat/300128361
