### ISSUE TITLE
Adding work to a collection causes controlled metadata to drop from work

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1196]
### Descriptive summary
Adding a work to collection causes a save on the work. This causes the controlled metadata to drop from the work in anticipation for it to be updated. The metadata fetch job is not kicked off in this instance and the metadata is being lost.

### Expected behavior
Metadata fetch job is kicked off when work is saved while being added to a collection.

Better, if possible, find a way to not drop metadata on collection adding saves, or only drop metadata when metadata changes.

**Comment by straleyb** [comment]
QA: Make sure a work has a Controlled Vocabulary value. Add that work to a collection. After a short duration of time, like a minute?, the work should still contain the linked data.

**Comment by shieldsb** [comment]
QA pass.
