### ISSUE TITLE
Add groupings to ingest form

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1201]
### Descriptive summary

The metadata team decided that groupings on the ingest form like on OD1 would be useful and needed due to the length of the form. We still want the required fields at the top of the form. This will be for all resource types. 

### Expected behavior

The ingest form will have groupings with section titles that match the MAP. The fields in the groups/sections will also match the ordering in the [MAP.](https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0) 

These groupings will exclude the required fields that are at the top of the ingest form.

### Related work

We would like a table of contents-like feature on the form to assist with navigation. See https://github.com/OregonDigital/OD2/issues/1202

### Accessibility Concerns

Not sure.

**Comment by CGillen** [comment]
@sseymore I'm guessing the groupings should be collapsible?
Like this: https://jsfiddle.net/Wc4xt/1052

**Comment by sseymore** [comment]
@CGillen We were thinking all visible/expanded actually and the ToC would help with navigation, but this is neat, if it's possible. I am open to it. @wickr @carakey @KevinJonesMeta @jsimic what do you think about the collapsible example?

**Comment by KevinJonesMeta** [comment]
I don't have a strong opinion on collapsible option. If someone else has a strong opinion I'm happy to defer. If that is easier to implement I'm happy to use a collapsible ToC

**Comment by sseymore** [comment]
Also, I'm assuming this collapsing will work with adding more fields- the "+" in the form to add more fields/values.

**Comment by CGillen** [comment]
My assumption would adding more fields would just work too.

Ok, we'll make part of this work to take a surface level attempt at collapsible groups. The required fields at the top would not be in a collapsible group (always shown) and all groups would be shown by default.

If adding collapsibility to the groupings is any amount of significantly difficult, we'll cut it.

**Comment by sseymore** [comment]
@CGillen We talked as a group and decided that we actually do not want anything collapsible. We want it all visible with the ToC-like navigation to assist with metadata input.

**Comment by straleyb** [comment]
QA:

- [ ] Typing "https://staging.oregondigital.org/concern/generics/new?locale=en#formats" should take you down to formats (materials)

**Comment by KevinJonesMeta** [comment]
QA Pass and a question.

Once I typed it in and it took me down to formats (materials) I scrolled back up and retyped it and it did not go back down. I had to go back to https://staging.oregondigital.org/concern/generics/new?locale=en first then retype to use navigation function. Is that expected?
