### ISSUE TITLE
Investigate visibility of Private user collections showing up in search results

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1215]
### Descriptive summary

@raybrarian Saw that private works that the current user had created show up in the search results. We need to verify that is the case and make sure that private user collections aren't showing up in search results.

**Comment by straleyb** [comment]
QA: Run a search and see if your user collection shows up. Check the facets and make sure your user collections dont show up.

**Comment by shieldsb** [comment]
QA fail. 1 of 3 user collections still appears in the facets list. The two created as a non-affiliated user do not appear. The one created under my admin account still appears when I am searching and not logged in.  That collection is marked as private.

**Comment by straleyb** [comment]
These are not showing up. @shieldsb and myself did QA with multiple collections and they did not show up
