### ISSUE TITLE
Facet modal generation title collision. 

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1222]
### Descriptive summary

The way that we are filtering out the user collections from the facets is broken. Since titles are not definitive and don't need to be unique. We cant pull a collection by its title and expect the response to be the exact work. We need to dig into the way that the modal is populated which in my understanding is done primarily in blacklight. In order to ensure that we are looking at the proper collections, we need to have access to their ids and not just their titles. This is why our current solution is unsustainable.

**Comment by straleyb** [comment]
Our proposed fix is to add another index field that would be the same as `member_of_collections` except it would contain a subset of the collections which doesn't include user_collections. Then anywhere we are using `member_of_collections` as a search piece, would be swapped with this new index field. This would ensure anywhere, user facing, searching would occur could guarantee no user_collections would be a part of it. 

@wickr We would like some feedback and your perspective on this problem. If you have any questions about whats going on here, I can chat about it.

**Comment by shieldsb** [comment]
QA pass.
