### ISSUE TITLE
Users cannot delete collections from My Collection page

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1240]
### Descriptive summary
During a refactor of the action buttons, the delete button lost its `post-delete-url` attribute. This attribute needs to be added again to allow users to delete their collections.

### Expected behavior
`post-delete-url` attribute exists on delete button. Users can delete their collections

**Comment by CGillen** [comment]
QA:
- [ ] Visit staging.oregondigital.edu/explore_collections#my
- [ ] Choose a collection to delete
- [ ] Go through delete button and modal
- [ ] Collection is deleted
- [ ] No ack message

**Comment by shieldsb** [comment]
The collection deleted and I didn't receive an ack message, but I did get a 504 timeout error message.

**Comment by CGillen** [comment]
Timeout caused by a MUCH bigger issue. New ticket at #1266
