### ISSUE TITLE
My collection share rework

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1241]
### Descriptive summary
The share button is currently very confusing and should be reworked to follow this workflow.

- Share button does not produce a pop-up
- The share button changes from `share` to `unshare` based on public/private status
- A toast/notification appears that lets the user know which collection has been altered, what state it is in now (shared/unshared), and if shared the sharable URL is presented (view url)
- Near the action buttons, a copyable share URL is visible while shared

### Expected behavior
User can understand what is shared and what isn't and can retrieve a copyable URL

**Comment by CGillen** [comment]
QA:
- [ ] Visit My Collection page: https://staging.oregondigital.org/explore_collections#my
- [ ] Click `share` button on a collection
- [ ] User is alerted that their collection is shared
- [ ] Shared collection's `share` button now reads `unshare`
- [ ] Shared collection's actions area includes a copyable link
- [ ] Copy button copies link to clipboard

**Comment by shieldsb** [comment]
QA pass.
