### ISSUE TITLE
Remove three-dots action expansion on my shelf

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1242]
### Descriptive summary
Three dots from wireframes deemed too confusing. Actions should be always visible.

### Expected behavior
Actions are visible without three dot expansion

**Comment by CGillen** [comment]
QA:
- [ ] Explore collections page: staging.oregondigital.org/explore_collections#my
- [ ] In masonry and list view:
  - [ ] actions (edit, share, delete, etc) appear without an expandable button (...)
  - [ ] shared collections display copyable URL without an expandable button

**Comment by shieldsb** [comment]
QA pass.
