### ISSUE TITLE
Properties on my shelf forms should not display as multivalue

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1243]
### Descriptive summary
The option to add another description should be disabled for my shelf forms. A user should only be able to include one description.

### Expected behavior
My shelf create and edit forms only allows user to set one description

**Comment by straleyb** [comment]
On the "Create collection" modal, description should be single valued. (I.E. no way to add a second value)

Go to the search results page, Click the Save selected to button, click create a new collection button, description should be single valued.

**Comment by shieldsb** [comment]
QA pass.  During collection creation I can only add one description.  However, in the dashboard collection edit function, I can add additional descriptions.
