### ISSUE TITLE
"Total items" added to item count parenthetical on explore collections page

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1244]
### Descriptive summary
The parenthetical number next to collection title in the wireframes is not clear enough. The words "total items" should be added inside the parenthetical to provide more context.

### Expected behavior
Item count is represented like so:
`<Collection Title> (# total items)`

**Comment by CGillen** [comment]
QA:
- [ ] Visit explore collections page: https://staging.oregondigital.org/explore_collections
- [ ] Look at collections in masonry view
- [ ] Parenthetical contains word "items" such as: `(# items)`
- [ ] Look at collections in list view
- [ ] No parenthetical but column is labeled with "items"

**Comment by shieldsb** [comment]
QA pass.
