### ISSUE TITLE
Titles are appearing as activetriple relations in work edit form

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1245]
### Descriptive summary
When you go to edit a work, the title appears similar to `#<ActiveTriples::Relation:0x00007fb233ab0ad0>`. This indicates the form is rendering the activetriples relationship instead of the underlying value. This occurred when we changed to Hyrax 3.0-RC1

### Expected behavior
Work edit form displays title and all other metadata VALUES not activetriple relation objects or similar.

### Related work
#1224

**Comment by CGillen** [comment]
This is fixed in RC2

**Comment by CGillen** [comment]
Fixed by #1260 
QA:
- [ ] Open work in edit form
- [ ] Title no longer displays as `#<ActiveTRiples::Relation:0x0#################>`
- [ ] Title displays as original title
- [ ] Save work, title stays the same

**Comment by shieldsb** [comment]
QA pass.
