### ISSUE TITLE
Fix factorial expansion of saving multiple works to collection

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1249]
### Descriptive summary
When you select multiple works to save to a collection, for each work saved the last thing it does is re-index the collection. The problem here is when a collection is indexed it also re-indexes each work inside itself. This causes a factorial expansion of inline re-indexing when saving multiple works to a collection.

For example: I save 3 works (A, B, and C). A saves, triggers a re-index of the collection, A is re-indexed. Inefficient but not terrible. Now B saves, triggers a re-index of the collection, A is re-index, B is re-index. Now C saves, triggers a re-index of the collection, A is re-index, B is re-index, C is re-index.
That's a lot of wasted time re-indexing stuff that JUST got index.

### Expected behavior
When saving multiple works to a collection The collection and each work is indexed as few times as possible. Preferably once each.

**Comment by straleyb** [comment]
QA: 
- Navigate to the search results page.
- check 5 to 10 works to add to a collection
- click the `save selected to` button
- find a collection and click the save button
- [ ] a popup should show up informing the user that their works are being added to the collection
- [ ] wait a minute and you SHOULD NOT be navigated away from the search page
- [ ] the works should be added to the collection (check the collection in the collections tab from the dashboard)

**Comment by shieldsb** [comment]
QA pass.  I still get the ack message when I click on collections in the dashboard, but I can see they have been added there by the number of items in the collection and actually viewing through https://staging.oregondigital.org/explore_collections.
