### ISSUE TITLE
Update to new Release Candidate 2

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1259]
### Descriptive summary
Lets stay on top of releases and get on Hyrax 3.0-RC2
https://github.com/samvera/hyrax/releases/tag/v3.0.0.pre.rc2

### Expected behavior
Hyrax 3.0-RC2

### Related work
#1224

**Comment by CGillen** [comment]
QA: Mostly the big stuff and ongoing issues
- [ ] Create a new work, any funny business?
- [ ] Update a work
- [ ] Create a new collection (from the dashboard)
- [ ] Add a work to a collection
- [ ] Search on your new works/collections
- [ ] Check metadata display and facets/facet-ability of your new works/collections

**Comment by CGillen** [comment]
The deploy failed, wait for the staging footer to read `Powered by Samvera Hyrax 3.0.0-rc2`

**Comment by shieldsb** [comment]
QA pass.  Controlled metadata still not displaying or searchable. This is being addressed in ticket #1231
