### ISSUE TITLE
Run yarn install on entry in production

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1262]
### Descriptive summary
Universal Viewer needs to be installed on production, otherwise it won't load.

Move this line out of the production exemption block:
https://github.com/OregonDigital/OD2/blob/master/build/entrypoint.sh#L12

### Expected behavior
UV loads where expected and doesn't give an ACK iframe

**Comment by CGillen** [comment]
QA:
- [ ] After a fresh deploy, UniversalViewer loads fine without ack message
- [ ] A deploy is successful (corey)
- [ ] Check build and deployment logs for yarn install, check for double install or failure to install (corey)

**Comment by shieldsb** [comment]
QA fail.  I don't receive an ack message, but UV is still not displaying images.

**Comment by shieldsb** [comment]
UniveralViewer passes QA, looks like the other two items are for you @CGillen.

**Comment by CGillen** [comment]
I'm going to give the build logs one more deploy to see if it was a caching issue, but this may be another QA fail

**Comment by CGillen** [comment]
QA fail. Production image building still doesn't install UV correctly

**Comment by CGillen** [comment]
QA fail. Still not there, looks like two lines too early

**Comment by CGillen** [comment]
QA Pass. Built twice, but first fails and second succeeds. UV shows up on staging now.
