### ISSUE TITLE
Deleting user collections with lots of works can timeout

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1266]
### Descriptive summary
~With a work in collection A and B, deleting collection A causes a reindex of collection B and its works. This causes a timeout for the user.~ This turned out to not be true. A collection I deleted as a test contained another collection which is not possible any more.

~WORSE STILL,~ These reindexes don't trigger the metadata update callback, so our FetchGraphWorker isn't getting enqueued and we're losing controlled metadata!

### Expected behavior
Lets AJAX the delete form too (might as well just do all the user collection forms). _This is still necessary because collections can be quite large_ 
We need to explore callbacks and the new pub-sub interface in RC2 to figure out if there's a index hook or some other hook that's either more robust or also covers this case.

### Related work
#1261 - AJAXing PR
#1249 - Ticket where AJAXing was decided

**Comment by CGillen** [comment]
QA:
- [ ] Visit https://staging.oregondigital.org/explore_collections#my to see my collections
- [ ] Click `Delete` on one collection, see modal still comes up
- [ ] Confirm delete of collection
- [ ] Receive notice of delete pending
- [ ] Refresh page several seconds to a minute later, collection actually deleted

**Comment by shieldsb** [comment]
QA pass.
