### ISSUE TITLE
Add wikidata vocab to Publisher CV, rename vocab to 'Wikidata'

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1297]
### Descriptive summary

It wasn't on the initial list for Publisher CV but after some remediation we've got Publisher URIs from wikidata, such as the Orange Media Network: http://www.wikidata.org/entity/Q30639119

I also think the WdEntity vocab should be renamed to 'Wikidata' to better match the MAP and for easier searching of the codebase. I don't foresee there being separate wikidata vocabs so the 'wd' prefix isn't needed, and 'entity' isn't the name of anything.

### Expected behavior

Publisher field and CV can accept wikidata URIs.

**Comment by shieldsb** [comment]
QA fail.  URI/publisher did not appear in work metadata.

**Comment by wickr** [comment]
This does look to be working, newer Barometers have Orange Media Network wikidata URI in Publisher: https://staging.oregondigital.org/concern/documents/fx71b903k?locale=en
