### ISSUE TITLE
Investigate the being logged in on staging as a different user.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1301]
### Descriptive summary

@shieldsb popped on to staging and got logged on as @CGillen. The way it was remedied was by logging out and back in. We need to investigate why a user might get logged on as a different user. We aren't entirely sure how to reproduce this and don't know where this hiccup came from. So we'll need to do a bit of investigation regarding this.

**Comment by wickr** [comment]
Doesn't appear to still be happening.
