### ISSUE TITLE
[Collection Landing Page Wireframe] Replace placeholder university logo from pink to logo

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1303]
### Descriptive summary

<img width="1484" alt="Screen Shot 2020-09-10 at 9 22 59 AM" src="https://user-images.githubusercontent.com/6424683/92762461-78045980-f347-11ea-9b84-899d2ea05a10.png">

**Comment by CGillen** [comment]
Institutional logos are in place
