### ISSUE TITLE
[Remediation] Post-migration remediation needs

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1306]
### Descriptive summary

Metadata team-identified remediation needs for post-migration OD2 (not MVP). 

### Expected behavior

Physical extent:
Sheet music: Can be cleaned up; moved to pages and description and measurements
Rocky Shore: Keep as is; more discussion needed  
Fairbanks: Could move to Measurements

Measurements: 
Standardize to cm and in w/o periods
H x W x D (lowercase x and spaces b/t x)

Copy Location: UO remediation for sheet-music is needed

### Related work

N/A

### Accessibility Concerns

N/A

**Comment by sseymore** [comment]
See scrapes for future remediation: https://github.com/OregonDigital/oregondigital/issues/1368

**Comment by KevinJonesMeta** [comment]
Superseded by later work.
