### ISSUE TITLE
MAP updates

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1307]
### Descriptive summary

There are several changes to the MAP after discussing the ingest form help text revision and fileset metadata specifications in Hyrax. 

### Expected behavior

MAP: https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0

- [x] Update help text on ingest form with new help text from MAP (column M). 

- [x] Update groupings /ordering to match MAP:
- Moved to new groups: ID verification status and Copy Location
- Formats has been updated
- Groupings and Administrative merged grouping (also reordered)

- [ ] Deleted predicates/moving to fileset metadata in OD2:

- Number of Pages 
- Format (https://github.com/OregonDigital/OD2/issues/1065)
- Extent (move data to Measurements; see ticket below)
- Orientation
- Color Space
- Contents
- File Size
- Height
- Width
- Modified
- Submission Date

These predicates and OD1 data values will be deleted and regenerated with fileset metadata during migration to OD2.

- [x] Update labels:

- Edited Full Text

### Related work

Help text review: https://github.com/OregonDigital/OD2/issues/529

Fileset Metadata: https://github.com/OregonDigital/OD2/issues/1069

Extent remediation: https://github.com/OregonDigital/OD2/issues/1305

Post-migration remediation needs: https://github.com/OregonDigital/OD2/issues/1306

### Accessibility Concerns

N/A

**Comment by straleyb** [comment]
QA:

- [ ] All help text should resemble that in the MAP
- [ ] Fields on the ingest form should be in the same order as the MAP, which adheres to the groupings. ToC and groupings arent in but order is correct.
- [ ] Label for edited full text is correct
- [ ] Filesets have the proper metadata to adhere to MAP.

**Comment by sseymore** [comment]
QA fail

Help Text:
- Creator not updated
- Photographer not updated
- Artist- sorry we had a typo in this! Can you update?
- Composer: Delete "Format for names according to RDA guidelines: Last Name, First Name Middle Name/Initial, yyyy-yyyy (include middle name/initial and years of life span if known)."
- Layout help text is incorrect
- MODS Note - I don't think we want N/A on the form. I think this is a mistake. Please update form label to MODS Note. I have updated the MAP to reflect this. Sorry!
- Location not updated
- Copy Location help text is incorrect
- Shelf Location help text is incorrect
- Type-- confirming with metadata team if we need to change this. TBD

I don't see these fields in the form-- and I did check the appropriate work types and these are all form visible in the MAP:
Instrumentation
Photography Orientation
Table of Contents
View
Creation Date
Rights Note
Contained in journal
Has Number
Is Volume
On Pages
Larger Work
Color content
Conversion
Date Digtized
Edited Full Text (Can't QA label for this)
Exhibit
Institution
OAI Set
Original Filename
Resolution
Set -- This is in Relationships, TBD

The ordering looks to be correct for what's visible.

I have not QA'ed fileset metadata since can't access that view in staging right now...

**Comment by sseymore** [comment]
Thank you! 

Still can't find these in the form (checked Generic and Image Work forms):

- Photography Orientation
- Edited Full Text

Conversion help text should be: Use for information regarding the digitization of the original object.

Updates after talking with metadata team:

- oEmbed URL helptext (please add to files tab): Fileset may have one oEmbed URL attached or file(s), but not both. 
- Set helptext (please add to relationships tab): Use for all digital collections to which the work belongs. URI required.
- Please change Collection Date to Collected Date in ingest form.

The views for filesets are still turned off so I can't QA that yet. 

We have two remaining questions about Date Digitized and OAI Set for the metadata team. Will update on 4/13.

**Comment by sseymore** [comment]
Update: We are taking Date Digitized off of work and only having on fileset. Please remove from form. Updates reflected in MAP

**Comment by sseymore** [comment]
@straleyb some more updates from Metadata team conversation.

**Comment by sseymore** [comment]
Another change-- can be done after staging refresh-- Full Size Download label change. MAP updated.

**Comment by straleyb** [comment]
Most updates have happened. workType has a small update and oembed_url wants to be on work as well as fileset.

**Comment by wickr** [comment]
Closing in lieu of MVP QA work
