### ISSUE TITLE
Remove Universal Viewer Share and Integrate into Item View

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1311]
### Descriptive summary
UV allows the user to embed from the viewer. This fragments our share section on the work view page. We should move the embed option to the share section.

### Expected behavior
UV does not display share option.
User can grab embed link from the share section of the work view page.

**Comment by CGillen** [comment]
QA:
- [ ] Visit item show page
- [ ] Universal Viewer no longer has embed/share option (bottom left)
- [ ] Downloads section has new embed button
- [ ] Embed button provides a pop-over with a copy link field
- [ ] Copy link button copies link to clipboard

**Comment by shieldsb** [comment]
QA pass.
