### ISSUE TITLE
Better user feedback for link copying

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1313]
### Descriptive summary
People might not be able to easily recognize an action occurred when they click the current copy URL links. We should improve the feedback with toasts and a text box for the paranoid.

### Expected behavior
User can see URL they are about to copy in an input box.
Input box auto-selects all text when entered into.
Clickable 'copy URL' button adjacent to box.
Toast or other clear messaging when 'copy URL' button is clicked. 

### Related work
#1312 

### Accessibility Concerns
The current JS copy library doesn't do a great job at using things like the `title` field. Make sure `title` and other HTML components are used properly.

**Comment by azle** [comment]
@shieldsb and @CGillen  We don't have a mockup for this. However, when we were initially talking about how it should work. We used the YouTube popup for what we were aiming for.

So when you clicked any of our social media or copied link it would open a popup that looks similar to YouTube, see screen snap below:

<img width="635" alt="Screen Shot 2022-10-03 at 9 13 33 AM" src="https://user-images.githubusercontent.com/8353860/193626966-fff10d31-ac2e-45e3-86c9-31ff2633fa09.png">

The icons available for our site would be Facebook, twitter and copy link. If you clicked on Facebook or twitter it would take them directly to that page if you clicked on copy link it would show the link in the pop up with the copy button.

**Comment by jsimic** [comment]
QA fail. User needs other elements below.

- [ ] User can see URL they are about to copy in an input box.
- [ ] Input box auto-selects all text when entered into.
- [ ] Clickable 'copy URL' button adjacent to box.
- [x] Toast or other clear messaging when 'copy URL' button is clicked.

**Comment by jsimic** [comment]
@straleyb All requirements are met, but the bit of visual finesse is needed. Please make the text box smaller (325px) and position it before the icons. So:
Share this: [325px text box and Copy button] [Facebook icon] [Twitter icon]

**Comment by azle** [comment]
@straleyb, can we middle align the copy button, Facebook and twitter icon to the middle of the url textbox.

<img width="479" alt="Screen Shot 2022-11-30 at 11 58 26 AM" src="https://user-images.githubusercontent.com/8353860/204896111-8e95a51a-225d-49ba-8578-676a878ac07b.png">

**Comment by azle** [comment]
@straleyb, its looking like this for me in Safari, firefox and Chrome on a MAC

<img width="619" alt="Screen Shot 2022-12-05 at 12 26 40 PM" src="https://user-images.githubusercontent.com/8353860/205736425-0248bbbe-56d6-4ffd-901f-0ea0c0a49e81.png">

**Comment by straleyb** [comment]
Both Corey and I looked on multiple browsers including Firefox, chrome and safari and they all looked fine. Maybe this is updated now on production and can be re-QA'd?

**Comment by jsimic** [comment]
The work show page has the correct positioning. The collection landing page does not, in all browsers. See below:

<img width="1163" alt="Bogart_socialMedia" src="https://user-images.githubusercontent.com/6344086/206725233-238e1e1d-ed25-4c3f-b209-2e87ecf724e5.png">

**Comment by jsimic** [comment]
Still not quite centered, on all browsers: 
<img width="493" alt="ShareThisCentering" src="https://user-images.githubusercontent.com/6344086/208119937-28e09516-f332-4eb6-9f14-813bb698e019.png">

**Comment by jsimic** [comment]
QA pass
