### ISSUE TITLE
Stream zip downloads

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1314]
### Descriptive summary
As a last ditch effort to avoid building zips as derivatives and bloat our storage, lets trip `zip_tricks` and this blog post to stream zips as files are added.
https://piotrmurach.com/articles/streaming-large-zip-files-in-rails/

### Expected behavior
Work and collection downloads use zip file streaming to download. Downloads start in <5 seconds.

**Comment by CGillen** [comment]
QA:
- [ ] Search for a **_large_** work
- [ ] Enter work show page
- [ ] Download 'Files + Metadata (ZIP)'
- [ ] Download starts quickly, but takes time to download (~4mb/s)

- [ ] Go to my collections page: https://staging.oregondigital.org/explore_collections#my
- [ ] Export collection
- [ ] Export on pop-up
- [ ] Download starts quickly, but takes time to download (~4mb/s)

**Comment by shieldsb** [comment]
QA pass.
