### ISSUE TITLE
Override save to collection deeper in hyrax to speed up factorial save process.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1324]
### Descriptive summary

When adding to a collection, the whole collection is reindex + all works already in the collection. We should be able to solve this by setting the `#reindex_extent`
```
collection.reindex_extent = Hyrax::Adapters::NestingIndexAdapter::LIMITED_REINDEX
```

**Comment by CGillen** [comment]
This is already happening, yay! Each work that is added causes two reindexes, one for the work, one for the collection. The collection does not do a nested index anymore!
That's still twice the work, but it's probably the best we're going to get.

**Comment by CGillen** [comment]
Note: kubernetes logs show MANY reindexes, but Loki logs show those log messages are duplicate logs, not duplicate work
