### ISSUE TITLE
itis terms failing when querying blazegraph

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#1325]
### Descriptive summary
Migration of assets that use Itis are failing.  Assets persist correctly, i.e. the full itis url is present, but fail at the point at which the system is attempting to check blazegraph, and the error only shows the url up to, but not including the '&'
Here is beginning of the backtrace from the rake task create_full_metadata_work
ERROR [line 1] Expected subject (found: "<https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN")
rake aborted!
RDF::ReaderError: Expected subject (found: "<https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN")
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/util/logger.rb:91:in `log_error'
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/reader.rb:526:in `fail_subject'
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/ntriples/reader.rb:221:in `block in read_triple'
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/ntriples/reader.rb:215:in `loop'
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/ntriples/reader.rb:215:in `read_triple'
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/reader.rb:507:in `read_statement'
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/reader.rb:402:in `block in each_statement'
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/reader.rb:402:in `loop'
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/reader.rb:402:in `each_statement'
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/util/aliasing.rb:46:in `block in alias_method'
/usr/local/bundle/gems/rdf-3.0.13/lib/rdf/mixin/countable.rb:23:in `count'
/usr/local/bundle/bundler/gems/triplestore-adapter-ae58b56a6d0c/lib/triplestore_adapter/triplestore.rb:92:in `fetch_cached_graph'
/data/lib/oregon_digital/triplestore.rb:34:in `fetch_cached_term'
/data/lib/oregon_digital/controlled_vocabularies/resource.rb:56:in `in_triplestore?'
/data/app/indexers/oregon_digital/deep_indexing_service.rb:27:in `block (2 levels) in fetch_external'

**Comment by lsat12357** [comment]
The problem happens in this method
https://github.com/osulp/triplestore-adapter/blob/8299db67e9e48d4815f13113c66ea50a6c17f990/lib/triplestore_adapter/providers/blazegraph.rb#L56
: the uri is fine as it enters get_statements, but the reponse from blazegraph shows the incomplete uri. Replacing '&' with ' %26' fixes the problem.
Since the docs suggest not using URI.escape, an alternative might be ERB::Util.url_encode

**Comment by lsat12357** [comment]
[107] pry(main)> clean = ERB::Util.url_encode af.taxon_class.first.rdf_subject.to_s
=> "https%3A%2F%2Fwww.itis.gov%2Fservlet%2FSingleRpt%2FSingleRpt%3Fsearch_topic%3DTSN%26search_value%3D99208"
[108] pry(main)> uri = URI.parse(format("%{uri}?GETSTMTS&s=<%{subject}>&includeInferred=false", {uri: @uri, subject: clean}))
=> #<URI::HTTP http://blazegraph-dev:8080/bigdata/namespace/kb/sparql?GETSTMTS&s=%3Chttps%3A%2F%2Fwww.itis.gov%2Fservlet%2FSingleRpt%2FSingleRpt%3Fsearch_topic%3DTSN%26search_value%3D99208%3E&includeInferred=false>
[109] pry(main)> request = Net::HTTP::Get.new(uri)
=> #<Net::HTTP::Get GET>
[110] pry(main)> response = @http.request(uri, request)
=> #<Net::HTTPOK 200 OK readbody=true>
[111] pry(main)> response.body
=> "<https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=99208> <http://www.w3.org/2004/02/skos/core#prefLabel> \"Insecta\"^^<http://www.w3.org/2001/XMLSchema#string> .\n"

**Comment by CGillen** [comment]
https://github.com/osulp/triplestore-adapter/blob/master/lib/triplestore_adapter/providers/blazegraph.rb#L58
Change 
`subject = URI.escape(subject.to_s)` 
to 
`subject = ERB::Util.url_encode(subject.to_s)`

**Comment by lsat12357** [comment]
Tested on staging, ken-gray and lichens colls successfully migrated
