### ISSUE TITLE
/collections page route should resolve, same as /explore_collections

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1332]
### Descriptive summary

The route for `/collections` should resolve to the Explore Collections page (`/explore_collections`)

It's shorter, and it's also part of the path for the actual Collections: https://staging.oregondigital.org/collections/osu-baseball?locale=en

### Expected behavior

`/collections` resolves to the Explore Collections page

### Accessibility Concerns

Duplicate pages can cause confusion or problems for search engines, so we should choose one to be the canonical URL and point the other one to it: https://support.google.com/webmasters/answer/139066?hl=en

**Comment by CGillen** [comment]
Remove `/explore_collections` route in favor of `/collections`

**Comment by shieldsb** [comment]
QA pass.
