### ISSUE TITLE
N-triples view for Collection metadata

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1333]
### Descriptive summary

Viewing the n-triples for Collection metadata can help with QA and troubleshooting.

### Expected behavior

Visiting https://staging.oregondigital.org/collections/osu-athletics.nt should download an n-triples file with the Collection metadata statements.

### Related work

Same on work level: #360

### Accessibility Concerns

This feature is intended for staff use and while we could expose it more publicly (for other metadata workers or technologists) it shouldn't be one of the favored download or display options.

**Comment by straleyb** [comment]
QA: The collection show page (not the dashboard show page but the public show page) responds to the .nt extension and downloads the ntriples file.

**Comment by shieldsb** [comment]
QA pass.
