### ISSUE TITLE
Logging of administrative metadata

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1334]
### Descriptive summary

Based off of MVP checklist: "Recording of user name and date/time information when object is created, as well as all modifications to both file and metadata." Some investigation and discussion is needed. 

### Expected behavior

Work:
Date Submitted (public view; currently implemented)
Date Modified (public view; currently implemented)
User info/activity (admin view; not yet present): This information is in Fedora and/or database and needs to be exposed. We would like to see if the user info/activity functionality on the fileset can be implemented for the work. Investigation and discussion is needed.

Fileset:
Date Submitted (public view; currently implemented)
Date Modified (public view; currently implemented)
User info/activity (admin view; not yet present): see example in [Scholar's Archive](https://ir.library.oregonstate.edu/concern/parent/kd17ct94m/file_sets/qf85nc230)
(Metadata note: This will map to dce:creator; keep Depositor label; MAP update needed)

### Related work

Not sure.

### Accessibility Concerns

N/A

**Comment by CGillen** [comment]
QA:
- As an admin
- [ ] Create a work and attach a file
- [ ] Visit work show page
- [ ] Find history of updates at bottom of work show page (below file manager)
- [ ] Visit your file's page
- [ ] Find history of updates to files
- As a role-less user
- [ ] Find the same work show page
- [ ] See no history of updates
- [ ] Copy the URL from your file page
- [ ] Either be kicked out OR at least see no file history

**Comment by sseymore** [comment]
I am trying to QA this but can't attach a file to a work @CGillen

**Comment by sseymore** [comment]
QA pass.

https://staging.oregondigital.org/concern/images/9z902z939?locale=en
