### ISSUE TITLE
Split login modal button into "Log In" and "Sign Up"

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1337]
### Descriptive summary
MAC wireframes has two account related buttons when you're logged out:
- Log In - Login modal including a "Create and account" link on the other affiliation tab
- Sign Up

### Expected behavior
An anonymous user sees two account related options in the header
- Log In
- Sign Up

### Related work
#1148

**Comment by CGillen** [comment]
QA:
- [ ] Login and Sign Up appear as separate buttons
- [ ] Sign Up takes you directly to sign up page
- [ ] Login provides modal & user can still sign in from modal
- [ ] header seems appropriately sized and doesn't overlap or format poorly in:
  - [ ] homepage
  - [ ] work show page
  - [ ] search page
  - [ ] admin dashboard

**Comment by shieldsb** [comment]
QA fail.  Buttons are too large and do not quite align with the search box.

**Comment by shieldsb** [comment]
Appears the same as last QA check.  

Current view
![image](https://user-images.githubusercontent.com/53542788/99720436-97fc7b80-2a62-11eb-93e4-92faa6767419.png)

WF 
![image](https://user-images.githubusercontent.com/53542788/99720502-afd3ff80-2a62-11eb-9dd1-a06705167fb6.png)

**Comment by CGillen** [comment]
@shieldsb I think we're at a point where any new issues found should be tickets and we can put this one to rest after QA

**Comment by shieldsb** [comment]
QA pass.  Header looks good at 100% display resolution, any larger and the formatting is off.  Brandon has already created a ticket about this issue.
