### ISSUE TITLE
Changes to homepage design

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1339]
### Descriptive summary
Service Managers have identified a few changes to MAC wireframes for the homepage

### Expected behavior
- Remove 'First time here?' section
- Remove 'Dig deeper' section
- Replace above with 'How to use Oregon Digital'
  - section for link to 'About' page
  - section for link to faq/how-to guides
- Footer
  - Remove donate button
  - Remove social media (for now)
  - Links in second column:
    - Contact Us
    - How-to Use Oregon Digital
    - About Oregon Digital
 - Wireframes to come from Azle from UO for all new static content pages

### Related work
#1147

**Comment by shieldsb** [comment]
QA fail. Footer has not been updated to match changes identified by SMs.

**Comment by azle** [comment]
Location for the final wireframes: https://drive.google.com/drive/folders/12mphWVRe01oO5bffK7RhLUGyJ201drlI?usp=sharing
