### ISSUE TITLE
UO works showing in search results for OSU user

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1340]
### Descriptive summary
[This work](https://staging.oregondigital.org/concern/audios/df661w41j?locale=en#metadata) (and others) are showing up for OSU users while searching. The view page properly informs the user that they do not have permission to view the record, but the permission matrix says they should not see it in searches.

This is not happening for anonymous users.

It is unknown about unaffiliated users

### Expected behavior
UO works do not display in search results for OSU users

**Comment by shieldsb** [comment]
QA pass.  This work did not appear in search results as OSU user, OSU affiliate, or anonymous user. When I tried the direct link using those roles, I received an access denied message.
