### ISSUE TITLE
Zip standard size files into collection exports, not full quality

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1341]
### Descriptive summary
At this point, it is believed user collections could be quite large. To save on bandwidth and site resources, standard size derivatives should be zipped into collection exports, not the full archival copy.

~This ticket will pend SM review once we find out how slow/expensive large downloads are.~

### Expected behavior
My Collection exports give the user standard size files. If the user wants archival copies, they must export the items one-by-one

### Related work
#759 
blocked by: #1235

**Comment by kmthorn** [comment]
This is Shelf related, not for all digital collections.

**Comment by shieldsb** [comment]
QA fail.  Exported 9 items and at least one image was full size, not standard.

**Comment by shieldsb** [comment]
QA fail.  All file types ok except video which is still scaling up.

**Comment by shieldsb** [comment]
QA pass
