### ISSUE TITLE
Override Review Submissions table to include facet information

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1343]
### Descriptive summary
`app/views/hyrax/admin/workflows/index.html.erb` defines the table that the displays the review queue. Metadata would like a new column that indicates which facets will be used by the work and what values will be added to that facet.

We can pull facet config from `CatalogController.blacklight_config.facet_fields` and extract which values are in the `field` sub-property.

### Expected behavior
A reviewer knows what facet values a work will facet on during review.

**Comment by sseymore** [comment]
@CGillen This needs to be prioritized in order for trial migration and MVP QA to continue.

**Comment by CGillen** [comment]
Outdated, refer to #1460
