### ISSUE TITLE
Fix oEmbed errors dashboard after oEmbed move to FileSet

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1346]
### Descriptive summary
Moving oEmbed to the FileSet level broke the oEmbed errors dashboard. We can fix this by moving a few key fetches and checks to check the FileSet on the record and still storing the oEmbed Error with the parent work information.

### Expected behavior
oEmbed Errors dashboard still functions and allows users to see the error, address the error, and jump to the complete work.

### Related work
#1316 
#247

**Comment by CGillen** [comment]
QA:
- [ ] Create a work with a oEmbed URL that does not point to a oEmbed provider (https://www.google.com)
- [ ] Work ingests
- [ ] Work show page renders error message 
- [ ] oEmbed dashboard provides an oEmbed status for the work
- [ ] oEmbed status is error
- [ ] oEmbed errors tab displays the work and the error

**Comment by shieldsb** [comment]
QA fail.  Receive the ack message upon saving the work.

**Comment by shieldsb** [comment]
QA fail.  I tried three different links and received an error for each one saying there is no embeddable content.  
Links tested: 
https://www.google.com 
https://library.oregonstate.edu/files/campusmap.png?1313008827  
https://blogs.oregonstate.edu/scarc/2020/10/27/a-dive-into-the-archive-inspecting-farmers-of-the-sea/ 

![image](https://user-images.githubusercontent.com/53542788/98873537-75001500-242d-11eb-9671-3b7075415457.png)

**Comment by CGillen** [comment]
Error on show page is expected. Same error should appear in oEmbed dashboard: https://staging.oregondigital.org/oembeds?locale=en

**Comment by shieldsb** [comment]
QA pass.  I am not sure that the Return to Editing this Work button is functioning, but it was not part of the QA list.
