### ISSUE TITLE
Design for Compound Objects - 70%

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1354]
### Descriptive summary
Implement these altered versions of wireframes for compound/complex objects

### Expected behavior
Compound/Complex objects display as the linked wireframes
https://drive.google.com/drive/u/1/folders/1c4mylcxJtsEODlcC1hCcDIeaWc3QNQB2

### Related work
#1326

**Comment by straleyb** [comment]
QA: if #1326 passes, then this passes.

**Comment by shieldsb** [comment]
QA fail.  Compound object pages do not match wireframe designs. 

Search results in grid view does not show "Is part of" under the title. 
Work show page says "contained" in "Is part of" 
Spacing needs to be adjusted on work show page between the "is Part of" and "related items" sections
Search results in list view does not include number of items, rights, etc. in compound object as shown on wireframes.
Contents section with image on work show page does not have index and thumbnail subsections as displayed on wireframe.

**Comment by straleyb** [comment]
It was suggested that if #1325 passes then this passes as well. This could have another QA look to see whether or not the work show page design is at a good spot to punt down along with any other view related work after MVP QA is done. Id suggest this is 70% of the way done.
