### ISSUE TITLE
[MVP QA] Create/edit in a user interface

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1355]
### Descriptive summary

Currently, compound objects can only be created during bulk ingest. This feature will allow compound objects to be created and edited from content already ingested (add children to an existing object). Represents parent/child relationships between objects.

### Expected behavior

Create/edit a complex object in the form
- [x] Use "Find a child work" to add an existing work as a child
- [x] Use "Deposit new work as a child of this work" button to create and relate a child
- [x] Confirm child works appear under "Other Works in this Work" in form
- [x] Confirm child works appear in the front end

Remove a child object from a complex object in the form
- [x] Use  "Remove from this work" button to delete relationship
- [ ] Confirm (former) child work no longer appears under "Other Works in this Work" in form
- [ ] Confirm (former) child not longer appears in parent show page in the front end
- [x] Confirm the (former) child is still discoverable via search and browse

### Related work

#1354

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by sseymore** [comment]
QA fail. 

There is some sort of bug that isn't actually deleting the children (both deposited as new and adding an existing child work). They are still appearing in the relationship tab in backend and on the show page. 

![Screen Shot 2020-12-08 at 3 02 14 PM](https://user-images.githubusercontent.com/7328774/101552125-229c1080-3967-11eb-81bd-e80dfaac1243.png)

**Comment by sseymore** [comment]
https://github.com/OregonDigital/OD2/issues/1412

**Comment by sseymore** [comment]
QA fail

Create/edit a complex object in the form
- [] Use "Find a child work" to add an existing work as a child

"Find a child work" is not working to search for existing items, at least I can't find the item I am searching for. "No matches found."

- [x] Use "Deposit new work as a child of this work" button to create and relate a child
- [x] Confirm child works appear under "Other Works in this Work" in form
- [x] Confirm child works appear in the front end

Remove a child object from a complex object in the form
- [x] Use  "Remove from this work" button to delete relationship
- [x] Confirm (former) child work no longer appears under "Other Works in this Work" in form
- [x] Confirm (former) child not longer appears in parent show page in the front end
- [x] Confirm the (former) child is still discoverable via search and browse

**Comment by sseymore** [comment]
QA pass ---Use "Find a child work" to add an existing work as a child is now working

https://staging.oregondigital.org/concern/generics/bv73c043w?locale=en#content
