### ISSUE TITLE
[MVP QA] Compound objects appear in search results

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1356]
### Descriptive summary

Currently in OD, both parent and child works show up in search results. Also in Hyrax. Compound objects need to be discoverable.

### Expected behavior

- [x] Perform a search or browse to locate a complex object
- [ ] Confirm presence of complex object icon and number of child works appear under the title in the results, as per [wireframe](https://drive.google.com/file/d/1tXX9PwQ8_mU106xZpnBxr_ZuM4ww1w_e/view?usp=sharing)
- [x] Perform a search or browse to locate a child work
- [x] Confirm presence of "Is Part of" and title under the title in the search results, as per [wireframe](https://drive.google.com/file/d/1aydv5mO2ixOUmhM5o1g3zZHUEStsu1TJ/view?usp=sharing)

### Related work

#46, #1001, #1354

**Comment by kmthorn** [comment]
Used [https://staging.oregondigital.org/concern/generics/df70j7830?locale=en](https://staging.oregondigital.org/concern/generics/df70j7830?locale=en)

- Searched the word interview to bring up compound objects. 
- Presence of compound object exists
- Icon for compound objects does not mirror the wireframes
- Confirmed search or browse to locate a child work
- Presence of "Is Part of" and title under the title in the search results is there, but incorrect working and location. Terminology needs to be user-tested. End users will not understand the meaning of the predicate.

**Comment by kmthorn** [comment]
QA Fail

Yes, the presence of complex object icon and number of child works appear under the title in the results, but it should be above copyright. This is according to the wireframe.

**Comment by jsimic** [comment]
@straleyb @azle  In the wireframes there is no media icon for complex objects. If it's a problem to not display this for one type of media, then we might want to eliminate the boxes icon next to the number of items. Especially if that is easier to do. Two boxes icons looks odd. Thoughts Azle?

**Comment by jsimic** [comment]
QA pass
