### ISSUE TITLE
On Edit form, Visibility section, 'Oregon State University' and 'University of Oregon' labels are gone

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1358]
### Descriptive summary

When creating or editing a work, in the Visibility section, the labels for 'Oregon State University' and 'University of Oregon' are no longer showing up.

![image](https://user-images.githubusercontent.com/2293544/98031602-92970400-1dc7-11eb-9c42-e18ee079fafd.png)

### Expected behavior

'Oregon State University' and 'University of Oregon' labels are color-coded and appear for the correct form options.

**Comment by CGillen** [comment]
Fixed by #1528
