### ISSUE TITLE
[MVP QA] Interface for managing users and assigning roles

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1367]
### Descriptive summary

Add, remove, edit user data fields (name/email/password/etc.), including roles. Roles are hard coded in the app, and are x,y,z

### Expected behavior

Add a new test user
_There does not currently appear to be a way to create a new user from the dashboard_
- [x] Create a new user using Signup

Edit test user
- [x] Edit the name of the test user

Assign workflow role "depositing" to a user
- [x] Choose the new test user from the User pull-down
- [x] Assign the role of "depositing" for an admin set
- [x] As that user, create a new item in the same admin set
- [x] Confirm new item is listed in the "Review submissions" queue

Assign workflow role "approving" to a user
- [x] Choose the new test user from the User pull-down
- [x] Assign the role of "approving" for an admin set
- [x] As that user, find or browse an unreviewed item in the same admin set
- [x] Approve the submission
- [x] Confirm that the item is discoverable in the front end

Assign workflow role "managing" to a user
- [x] Choose the new test user from the User pull-down
- [x] Assign the role of "managing" for an admin set
- [x] As that user, confirm access and viewability of reports

### Related work

#22, #24, #25, #26, #117, #130, #694, #753, #804, #1170

**Comment by jsimic** [comment]
Admin dashboard has no way to create a new user, edit user information, or change/disable user privileges other than Workflow Roles. See #1170

**Comment by sseymore** [comment]
QA pass, I was able to edit the name of a test user-- last checkbox to be checked
![Screen Shot 2022-10-04 at 11 59 42 AM](https://user-images.githubusercontent.com/7328774/193903579-2663ff3e-e905-4ea2-9a4a-4b6e82a8c00e.png)
![Screen Shot 2022-10-04 at 11 59 30 AM](https://user-images.githubusercontent.com/7328774/193903584-7ef7563e-7f16-471c-8929-ad71ba4f375e.png)
