### ISSUE TITLE
[MVP QA] Facets: Combined Facets 

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1368]
### Descriptive summary

Combine multiple predicates into a single facet in the user interface, for example: Creator facet would include Creator, Photographer, Lyricist, etc.

### Expected behavior

- [ ] Identify a name that exists only as a specific type of creator (photographer, lyricist, etc., such as Bayes, Nora, 1880-1928)
- [ ] On browse all, confirm name is listed in Creator facet
- [ ] Repeat for Scientific Names, Topic, Location, and Copyright facets

### Related work

#28, #45, #50, #1042, #1043, #1044, #1045, #1046, #1047, #1048, #1049, #1050, #1051, #1052, #1053, #1093

**Comment by kmthorn** [comment]
We cannot test this well yet until more diverse works are published to staging.

**Comment by kmthorn** [comment]
Can someone provide a name that exists only as a specific type of creator (photographer, lyricist, etc., such as Bayes, Nora, 1880-1928). Can you also provide specific examples for Scientific Names, Topics, Copyright, and Location?

We will run the test after we have this information.

**Comment by jsimic** [comment]
Using [https://staging.oregondigital.org/concern/images/7h149p88r](https://staging.oregondigital.org/concern/images/7h149p88r) for testing.

QA pass for Copyright (license, rights)

QA fail for Location (tgn pass; location, ranger district, water basin fail): Geonames is not loading in webform

QA fail for Topic (subject fail, keyword pass): Subject terms do not appear, keywords do

QA fail for Scientific Names (phylum, taxon class, order, family, genus, species, common name): Combined facet "Scientific Names" does not appear on search results page

QA fail for Creator (photographer, artist, arranger, author, cartographer, collector, composer, contributor, dedicatee, designer donor, editor, illustrator, interviewee, interviewer, lyricist, owner, patron, print maker, recipient, transcriber and translator pass; landscape architect fail): Landscape Architect is on map but not on webform

**Comment by jsimic** [comment]
Copyright: QA pass
Location: QA pass
Subject: QA pass
Scientific Names: QA pass; facet visible; Phylum, Genus, Common Name not displaying opns label (new ticket will be made)
Creator: QA pass
