### ISSUE TITLE
[MVP QA fail] Show what's under review 

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1369]
### Descriptive summary

Display all or some subset of items waiting for review

### Expected behavior

- [x] Confirm visibility of "Review Submissions" in dashboard
- [x] Search for terms applied to individual or groups of records
- [x] Use facets to filter records

### Related work

#22, #24, #25, #26, #48, #761, #792, #1343

### Accessibility Concerns

**Comment by sseymore** [comment]
https://github.com/OregonDigital/OD2/issues/1343

**Comment by sseymore** [comment]
QA pass. Final MVP QA review.
