### ISSUE TITLE
[MVP QA] Configuration of Facets on string fields (in code)

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1370]
### Descriptive summary

Currently, in OD, only linked data fields are configurable as facets. This feature would allow string values to be faceted such as Box Number and Folder Number, and is included in Hyrax.

### Expected behavior

- [x] Identify fields/predicates in the MAP where the Faceted value is "yes" and the Expected Type is "text"
- [x] Confirm the presence of populated facets for each of these fields

### Related work

#28, #45, #49, #532, #550, #1141

**Comment by kmthorn** [comment]
This connects to the archival arrangement needs in OD. 

- Creator Display: FAIL
- Former Owner: FAIL
- Mode of Issuance: FAIL
- Keyword (was: Subject): PASS This is a successful facet. [](https://staging.oregondigital.org/catalog?f%5Btopic_combined_label_sim%5D%5B%5D=ASOSU&locale=en&q=&search_field=all_fields)
- Box Number: FAIL
- Folder Name: FAIL
- Folder Number: FAIL
- Has Number: FAIL
- Is Volume: FAIL
- Series Name: FAIL
- Series Number: FAIL
- Exhibit: FAIL

All failing facets are not in a combined facet. We need to find out where the decision was made about dropping non-combined facets. Example: Creator display did not fall under the combine facet but is still identified as facetable on the MAP.

**Comment by kmthorn** [comment]
We do not see the presence of populated facets for each of the facets identified in this ticket, except for Topic (once called Keyword).

Are there items in staging that have these metadata fields populated? 

Creator Display
Former Owner
Mode of Issuance
Box Number
Folder Name
Folder Number
Has Number
Is Volume
Series Name
Series Number
Exhibit

**Comment by kmthorn** [comment]
QA FAIL

We could not find these three fields anywhere: Mode of Issuance, Series Number, Exhibit. Below are the two places where we looked. In addition we noted that Keyword, Topic, and Subject are used interchangeable depending on where you are at in the database.

**Search Results Page**: [https://staging.oregondigital.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q%5B%5D=#content](https://staging.oregondigital.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q%5B%5D=#content)
Creator Display: Pass
Former Owner: Pass
Mode of Issuance: Fail
Keyword (was: Subject):  Fail. On a search results it is listed as Topic. It is called Keyword on the item show page. It is called Subject and Topic on the collection landing page.
Box Number: Pass
Folder Name: Pass
Folder Number: Pass
Has Number: Pass
Is Volume: Pass
Series Name: Pass
Series Number: FAIL
Exhibit: FAIL

**Collection Landing Page**: [https://staging.oregondigital.org/collections/mss-rb#content](https://staging.oregondigital.org/collections/mss-rb#content)
Creator Display: Pass
Former Owner: Fail
Mode of Issuance: Fail
Keyword (was: Subject): Fail. On a search results it is listed as Topic. It is called Keyword on the item show page. It is called Subject and Topic on the collection landing page.
Box Number: Pass
Folder Name: Pass
Folder Number: Pass
Has Number: Fail
Is Volume: Fail
Series Name: Pass
Series Number: Fail
Exhibit: Fail
