### ISSUE TITLE
[MVP QA] Admin UI / database control of what available Facets are displayed

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1371]
### Descriptive summary

Build a user interface available for Administrators and Collection curators to configure Facets in the public user interface.

### Expected behavior

Enable facet control on a new collection
- [x] Create a collection using the Digital Collection with Configurable Facets type
- [x] Enable desired facets and move into customized order
- [x] Confirm facets are visible and in the correct order on collection landing page

Add other facets
- [x] Edit facets on a collection with configurable facets
- [x] Add facets that are non-core and re-order
- [x] Confirm that new facets appear and in the correct order on collection landing page

### Related work

#43, #49, #532, #533, #1395

**Comment by jsimic** [comment]
@CGillen In the above second set of QA, it is assumed that a curator can change the collection type. If that is not possible, then we should by default have every new collection with configurable facets enabled, and all the core facets enabled in a default order so that curators have the option of configuration after the collection is created.

**Comment by CGillen** [comment]
You can not change a collection's type after it is created, so you can't control the configurability of facets after the collection is created.
The change you are suggesting is when a collection is created with configurable facets, the default state for all facets should be on, and they should be sorted the same way our simple search facets are ordered?

**Comment by jsimic** [comment]
Yes, exactly.

**Comment by jsimic** [comment]
Edited out QA section regarding changing the collection type as per conversation above

**Comment by jsimic** [comment]
Facets available under Dashboard/Collections/Edit View/Facets include only core facets. All facets should be listed, enable-able and movable

**Comment by jsimic** [comment]
Added ticket #1438

**Comment by sseymore** [comment]
@jsimic #1438 is QA pass. Ready to QA again.

**Comment by jsimic** [comment]
QA fail.

See #1643

**Comment by sseymore** [comment]
QA pass with #1715

**Comment by sseymore** [comment]
Closing after reviewing that all attached tickets are also closed.... for final MVP review
