### ISSUE TITLE
[MVP QA fail] Linked data supported fields

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1372]
### Descriptive summary

Save URI, validate, display any errors, and display labels and URIs for reference. Validation: compare URI to controlled vocabularies. 

### Expected behavior

Create/edit a work record
- [x] Add a value to a field requiring a URL (see MAP)
- [x] Confirm value appears with correct label on front end, and the more info icon links to the external authority
- [x] Confirm value appears correctly in nts

### Related work

#35, #42, #45, #500

**Comment by sseymore** [comment]
Adding ".nt" to the end of the OD item URI isn't working like it does in OD1. Will this be the same functionality in OD2?

**Comment by KevinJonesMeta** [comment]
#360 needed to complete QA for this ticket.

**Comment by jsimic** [comment]
nt download appears to be working if you remove everything after the ? in the URL. Re-QA'd and works as expected.
