### ISSUE TITLE
Design for search results - list view

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1376]
### Descriptive summary
Implement design for search list view

### Expected behavior
Latest MAC wireframe: https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938489

### Accessibility Concerns
Careful with implementation

**Comment by CGillen** [comment]
- [ ] Copyright
- [ ] Facet box
- [ ] Facet selection
- [ ] Search Header (Sort, Show, Save selected to)
- [ ] Pager
- [ ] Breadcrumb

**Comment by CGillen** [comment]
Add the masonry/list icons back in

**Comment by CGillen** [comment]
QA:
List the differences you find between staging and the wireframes below. Ignore the header and footer, and the size of thumbnails

Desktop: https://drive.google.com/drive/u/1/folders/1SEvxPs8DA1Z3FomxLnwvWqNKS2MMbASt
Mobile: Guess? No mobile wireframe exists for search results, so anything that feels off, non-functional, or a hindrance to UX can be listed.

**Comment by shieldsb** [comment]
QA fail. 

- Save Selected to button: text is black, its dark blue in the WF
- Works have a save button on the right side, this is not in the WF 
- No icon for the works listed as no copyright 
- Filters section does not have a search box with the text "Type a keyword" which is included in the WF 
- There are more filter types displaying than are shown on the WF, also WF has "show more filters" at the bottom of the filter list that is not on staging 
- The line between works seems slightly more pronounced on the WFs 
- Copyright text is blue in WF, black in staging
- font/spacing for "show #items" does not match WF 
- "Is part of" display does not match MF, staging has line break and bullet point 
- No part of this ticket, but noticed for a while that works display the creator field with the label "Creator Label Sim" 

I checked this ticket on my phone and ipad for mobile display.  Without WFs its hard to tell much.  I did notice on my phone that the save check box displays above the thumbnail.

**Comment by CGillen** [comment]
The ones that weren't fixed:
- Works have a save button on the right side, this is not in the WF - new save button has been approved by posm
- No icon for the works listed as no copyright - Our version of Font Awesome does not have the appropriate icon & Hyrax won't let us upgrade. More thought needs to go into this
- Filters section does not have a search box with the text "Type a keyword" which is included in the WF - I don't have the search box ready yet

I'll open a few tickets

**Comment by CGillen** [comment]
QA:
- [ ] save selected to button is blue
- [ ] line between works is more pronounced
- [ ] Copyright text is blue
- [ ] 'show item #' has better font/spacing
- [ ] Is Part Of is no longer a bulleted list
- [ ] Creator isn't displaying as 'Creator Label Sim' anymore

**Comment by shieldsb** [comment]
QA fail.  Sorry I didn't point this out last round, but the top of the search results list with the filter menu doesn't quite match the newest wireframe. 

WF: 
![image](https://user-images.githubusercontent.com/53542788/106193611-9639ed00-6162-11eb-875b-3606731e79be.png)


Staging: 
![image](https://user-images.githubusercontent.com/53542788/106193536-80c4c300-6162-11eb-89f1-afb46c29cd10.png)

**Comment by shieldsb** [comment]
QA fail.  "Select All" and "None" text is black and should be blue. "Showing # items" should be heavier and raised slightly.  Items should be changed to works, but that may be taken care of in another ticket.

**Comment by shieldsb** [comment]
QA pass.
