### ISSUE TITLE
Design for search results - grid view

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1377]
### Descriptive summary
Implement design for search grid view

### Expected behavior
Latest MAC wireframe: https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938490

### Accessibility Concerns
Careful with implementation

**Comment by CGillen** [comment]
Pausing work on this to work on work show page and get print CSS unblocked.
Still need to:
- [ ] Make sure mobile looks good
- [ ] Even out rows?
- [ ] Top border CSS for individual items
- [ ] Search box above search on list & mason

**Comment by shieldsb** [comment]
QA fail.  WF has four rows with four works on each row.  Currently there are three rows, the first two have four items but the third row has only two items. Also, has the same resolution issue as other pages (we decided this is similar to mobile adjustments) that cause the top menu row to split.  See image: 
![image](https://user-images.githubusercontent.com/53542788/107653750-d3a87b00-6c36-11eb-9894-62fc033c721f.png)

**Comment by shieldsb** [comment]
QA pass.  Also, question/comment about a thumbnail display difference I noticed.  Works that only have icons as thumbnails display the checkable box but works with thumbnail images do not show the box until hovered over.  An example can be seen in the screenshot of the comment above.

**Comment by jsimic** [comment]
The save box should function the same way regardless of having a thumbnail or an icon. Also, looking at the screenshot, I don't think we want entire collections to be savable.
