### ISSUE TITLE
oEmbed through Panopto and Kaltura

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1378]
### Descriptive summary
Youtube, flickr, and imgur seem to work through oEmbed but not Panopto or Kaltura yet.
Here are some example URLs that were not working.

Panopto video: https://uoregon.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=b9ad783e-4932-450b-9da2-ab650137b257
Panopto audio: https://uoregon.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=054a4e6d-2f62-45db-b6b5-ab79014646a8
Kaltura video: https://media.oregonstate.edu/media/t/0_tr1j77t9
Kaltura audio: https://media.oregonstate.edu/media/0_2kxlon5n

### Expected behavior
A user can enter a Kaltura or Panopto video and see the oEmbed show on the work show page.

### Related work
#1316

**Comment by jsimic** [comment]
The embed.ly api appears to work with Panopto. Is this something we could set up for ourselves? https://docs.embed.ly/docs/oembed

**Comment by CGillen** [comment]
Need a decision on if we're going to license embed.ly or ask Panopto to develop their oEmbed endpoint. I need to go back through POSM notes to find the last decision (if there was one).

**Comment by jsimic** [comment]
@CGillen @wickr Here's the Panopto contact: Luchin Lee <llee@panopto.com>

**Comment by jsimic** [comment]
It is on the Panopto roadmap, but not on any timeline. [https://community.panopto.com/discussion/218/responsive-embed](https://community.panopto.com/discussion/218/responsive-embed)

**Comment by jsimic** [comment]
UO SCUA is now using Aviary to deliver time-based media, so better to find a solution using that
