### ISSUE TITLE
[MVP QA fail] Required metadata fields

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1384]
### Descriptive summary

Title is the only descriptive metadata element required by OD1. Other requirements could be added to force compliance with MWDL/DPLA application profile.

### Expected behavior
[Required fields: Title, Identifier, Rights Statement, Type, Admin Set (see MAP)]

Descriptive fields
- [x] Edit a work record
- [x] Leave empty the Title field
- [x] Confirm work does not save or update record until corrected
- [x] Leave empty the Identifier
- [x] Confirm work does not save or update record until corrected
- [x] Leave empty the Rights Statement
- [x] Confirm work does not save or update record until corrected
- [x] Leave empty the Type
- [x] Confirm work does not save or update record until corrected

Administrative field
- [x] Create a new record
- [ ] Leave empty the Admin Set field 
- [ ] Confirm work does not save until corrected

### Related work

#45, #142, #360, #629, #975

**Comment by KevinJonesMeta** [comment]
When missing required field in Descriptions the "Describe your work" Requirement becomes unchecked, the "Save Changes" button is grayed out, and the cursor turns to a Do Not Enter sign when hovering over "Save Changes" button.

***The Admin Set field cannot be left empty in Relationships tab, so I can't test if it won't save without an Admin Set.
It did save with the Default Admin Set without a Collection as expected.

Test record: https://staging.oregondigital.org/concern/images/5h73pw08c?locale=en

**Comment by sseymore** [comment]
I believe we are testing to be sure it doesn't save when Admin Set is blank. This seems correct. Will discuss on Thursday.

**Comment by KevinJonesMeta** [comment]
Admin Set field should not have default value. Currently defaults to "Default Admin Set" and allows saving when a particular Admin Set is not selected.

**Comment by carakey** [comment]
#1428
