### ISSUE TITLE
[MVP QA] Sharing via social media

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1385]
### Descriptive summary

Included in Hyrax

### Expected behavior

- [ ] Confirm frontend matches wireframes ([1](https://drive.google.com/file/d/1HsMfggcl-un-owTMs6VOf6Dl1VYMD2Ie/view?usp=sharing) and [2](https://drive.google.com/file/d/1ppq-VaL1VrX4nouom4yxmrf1FtQQHUBq/view?usp=sharing))
- [x] Confirm clicking Facebook icon sends link to facebook
- [x] Confirm clicking Twitter icon sends link to twitter
- [ ] Confirm clicking embed produces code to copy and a message that link is copied
- [x] Confirm clicking link icon produces a link to copy and message that link is copied

### Related work

#1119, #1311, #1313

**Comment by kmthorn** [comment]
Cannot test Facebook because none of us use that social media platform

No option available for embed code. Reference: #1326 #1354 #1427

[1](https://drive.google.com/file/d/1HsMfggcl-un-owTMs6VOf6Dl1VYMD2Ie/view) and [2](https://drive.google.com/file/d/1HsMfggcl-un-owTMs6VOf6Dl1VYMD2Ie/view) there is no option for embed. The wireframes should represent that this needs to work like YouTube sharing.

**Comment by kmthorn** [comment]
QA Fail

**MAC Wireframes Matching**
Share button does not exist on item pages. Cannot test if frontend matches wireframes ([1](https://drive.google.com/file/d/1HsMfggcl-un-owTMs6VOf6Dl1VYMD2Ie/view?usp=sharing) and [2](https://drive.google.com/file/d/1ppq-VaL1VrX4nouom4yxmrf1FtQQHUBq/view?usp=sharing))

**Embed copy and paste**
Clicking embed produces code to copy and a message that link is copied does not exist.

**Facebook**
Link does send but the visual is not what is expected. There should be an image preview with a title below it. See this example.
![20220303_facebooksuccess](https://user-images.githubusercontent.com/36867009/156671527-d92b9f90-3fef-40a1-8798-e8b507b343c1.png)
- Facebook fail for this photo [Paul Richie](https://staging.oregondigital.org/concern/images/3t945r08v)
![20220303_facebookshare](https://user-images.githubusercontent.com/36867009/156669514-20dd572d-d50e-464f-a9b1-6ad054ccf203.png)
- Facebook fail for a yearbook [The Beaver 1970](https://staging.oregondigital.org/concern/documents/rb68xb881#content)
![20220303_facebookshare_fail2](https://user-images.githubusercontent.com/36867009/156669726-240d3f63-f441-4e25-82f1-27a9132d19ee.png)
- Facebook fail for interview compound object that does not have the viewer active [Interview with Ed Ortega: Audio, University of Oregon Veterans](https://staging.oregondigital.org/concern/audios/df72jn18f?locale=en#content)
![20220303_facebook_fail3](https://user-images.githubusercontent.com/36867009/156670130-364038c3-b496-4c56-ab14-0828b3154f79.png)

**Comment by shieldsb** [comment]
QA fail.  Wireframes show a share button that is supposed to expand to a menu of social media icons.  What appears now on the work show page is a facebook icon and a twitter icon.  Items will post from those, but with the same results shown above in Kate's comments.

**Comment by shieldsb** [comment]
When selecting the facebook icon on my phone, it opens a browser to the log in page and does not open the app. 
Testing from Kenna: the first two are from me posting the link directly. the third is from me clicking the ‘f’ icon on the page
<img width="525" alt="Screenshot 2023-02-10 at 3 33 58 PM" src="https://user-images.githubusercontent.com/53542788/218529026-8310cd3c-0fce-49bb-9686-5e9e0bbf9ddc.png">
<img width="698" alt="Screenshot 2023-02-10 at 3 34 15 PM" src="https://user-images.githubusercontent.com/53542788/218529046-28a86b10-c3fb-4abe-b43f-d8a177f8ef0b.png">
<img width="604" alt="Screenshot 2023-02-10 at 3 35 01 PM" src="https://user-images.githubusercontent.com/53542788/218529088-07477eff-2ce5-4642-8a81-a304647fecc2.png">

**Comment by shieldsb** [comment]
Pass for Facebook.  Twitter did not share an image/thumbnail.  Screenshots for both: 
![Image (003)](https://user-images.githubusercontent.com/53542788/222281139-574cad94-4755-43fb-8b78-00b1395c5284.jpeg)
![Image](https://user-images.githubusercontent.com/53542788/222281179-dc65dc22-cd12-4899-8482-9bf79093bbe5.jpeg)

**Comment by shieldsb** [comment]
QA pass. Twitter now displays with an image.
