### ISSUE TITLE
Header doesnt scale when browser is zoomed in.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1387]
### Descriptive summary

I keep my browser zoomed in because my eye sight is less than preferable. I noticed that the header collides when the browser is zoomed in, so it needs to be set up to scale down when zoomed in.

**Comment by straleyb** [comment]
There are no collisions happening. Fixed by this PR: https://github.com/OregonDigital/OD2/commit/944402358b74ebe8d3c695d76c389009439476cf#diff-9efd67e6e3ea796fd308795e20160852cc8ec58fef1ed4ae0e75d000f17cad7f

**Comment by straleyb** [comment]
QA:
- [ ] Header elements shouldn't overlap and should scale down when shrinking screen.

**Comment by shieldsb** [comment]
QA pass, though the more zoomed in the browser is the more crowded the header looks (nothing overlaps).
