### ISSUE TITLE
Collections should have configurable facets by default

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1395]
### Descriptive summary

All newly created digital collections should have a type with configurable facets. This does not apply to user collections. @wickr suggested this might be able to be done in the code, so we would not have to remember to set this up after every refresh.

### Expected behavior

When a new collection is created in the form or in bulk, the default type should have configurable facets, and the core facets should be enabled. Facets for the collection should be editable through the dashboard.

### Related work

#1371 

### Accessibility Concerns

None

**Comment by CGillen** [comment]
QA:
- [ ] Create new collection type (not a collection) here: https://staging.oregondigital.org/admin/collection_types?locale=en
- [ ] After initial submit, go to settings tab and find configurable facets already checked
- [ ] Create a new collection of this type
- [ ] Find facets tab with list of orderable and togglable facets

**Comment by shieldsb** [comment]
I think the second QA item in the list means that configurable facets should already be checked once the new collection type is created.  If that is correct, than this is a QA fail since I had to check it after new type creation.  Otherwise, everything else worked as expected.

**Comment by CGillen** [comment]
The second checkbox is for this interface:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/11052958/113062179-319e0d00-9168-11eb-8eb1-c780a693811d.png">
That snip is from the newest collection type, so this is a QA Pass
