### ISSUE TITLE
Show more than 10 items on explore collections page

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1399]
### Descriptive summary
Each tab of the explore collections page is only displaying up to 10 items. Let's raise that so all collections display.

### Expected behavior
OSU/UO/Personal collections show on the explore collections page.

**Comment by straleyb** [comment]
QA:

Navigate to the explore collections page. There should be numerous collections under the "ALL" tab

**Comment by shieldsb** [comment]
QA pass.
