### ISSUE TITLE
Rename some media facet values

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1404]
### Descriptive summary
`Moving Image` and `Sound` aren't as descriptive or well understood as `Video` or `Audio`, respectively. We should use the more recognized terms.

### Expected behavior
`Moving Image` => `Video`
`Sound` => `Audio`

**Comment by shieldsb** [comment]
QA fail.  Still shows moving image and sound.

**Comment by wickr** [comment]
The applicable works on staging needed a reindex to use the new values, after doing that the facet values appear as expected.
![image](https://github.com/OregonDigital/OD2/assets/2293544/9228502d-5006-4030-8122-b3ad7e5f88c6)

The icon update in #3035 is useful though.
So probably QA Pass after the icon update.

**Comment by shieldsb** [comment]
QA pass.
