### ISSUE TITLE
Bring in collection code from workshow page for featured collections section.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1411]
### Descriptive summary

This ticket is related to #1147 and is a subticket breaking down work for that. This lays out the section of the featured collections. It needs to be the same as the piece on the work show page that shows the user what collection a work is a part of. The code needs to be optimized in the same way. This way we aren't requesting too many subitems and slowing down the system like last time.

**Comment by CGillen** [comment]
We're not displaying the three image preview on work show pages anymore. Not needed
