### ISSUE TITLE
Manage oEmbeds Dashboard is broken

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1413]
### Descriptive summary

On the admin dashboard, clicking 'Manage oEmbeds' gives the standard broken error message: ACK! LOOKS LIKE OREGON DIGITAL IS TEMPORARILY BROKEN. TRY AGAIN LATER AND LET US KNOW ON THE CONTACT FORM HOW YOU WOUND UP HERE.

Error reported is:
```
ActionView::Template::Error
undefined method `human_readable_type' for nil:NilClass
```

### Expected behavior

https://staging.oregondigital.org/oembeds?locale=en  should show oEmbeds and errors and not give error

### Related work

#1346

**Comment by jsimic** [comment]
QA pass. Test with valid URL and invalid URL. Works as expected.
