### ISSUE TITLE
[MVP QA fail] Validation isn't working for text in date fields

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1414]
### Descriptive summary

Validation didn't work for MVP QA:  Attempt to add text to a field that requires a date.

### Expected behavior

Validation will catch non-EDTF formatted data for date fields. 

### Related work

https://github.com/OregonDigital/OD2/issues/1383

### Accessibility Concerns

N/A

**Comment by CGillen** [comment]
#2199 Validation is being removed for MVP
