### ISSUE TITLE
Item restrictions for UO are broken since late November 2020

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#1415]
### Descriptive summary

UO items that should be accessible while on their VPN are not showing up. They show up when logged in, but are not publicly accessible from UO networks.

From Linda:
```
the entirety of aa-images is restricted
there are 176k+ images in that collection
unless you are logged in, the set page shows zero assets
but you should be able to see them without being logged in if you are on the vpn
in dan-powell, about half of the assets are restricted, same thing, you can only see the restricted items if you are logged in, so it's not just the one coll.
```

When Fedora for od1 was moved to the od2020 cluster, this introduced a proxy between Rails and Fedora. Rather than appearing as localhost, connections to Fedora appear to come from `lib-hydra1`

### Expected behavior

Items accessible from UO should be available while on their VPN without being logged in.

**Comment by raybrarian** [comment]
Tested this - browsing to https://oregondigital.org/sets/aa-images on the UO VPN gives no results. This is preventing students from getting to the images they need for their classes. I'm also getting an insecure connection warning when accessing item pages - http://oregondigital.org/sets/dan-powell/oregondigital:df66z966j:
![image](https://user-images.githubusercontent.com/4460510/102102390-995e6100-3de0-11eb-9043-68d8c35bab57.png)

**Comment by jsimic** [comment]
VPN-only access to aa-images remains broken in my testing as well.

@raybrarian I am not getting the insecure connection message

**Comment by raybrarian** [comment]
@jsimic - gotcha - might be my Chrome browser and being on the VPN in combination.

**Comment by jechols** [comment]
Just to contribute my two cents: I can't reach this even tunneling through a campus system (verified my IP is a UO libraries IP).  Like @jsimic I'm not seeing the insecure warning, but I suspect that's a client-side problem as @raybrarian mentioned.

**Comment by jechols** [comment]
@decimalator Also, I don't believe the problem is connections to Fedora getting the wrong IP address.  As I understand it, Fedora isn't directly accessible from the Internet anyway, and Fedora isn't where we do the group/role-based restrictions.  So long as Rails sees the correct IP address, and the roles' IP addresses are defined correctly, the access should work.

**Comment by CGillen** [comment]
@wickr Is this still an OD1 issue? We're not doing IP restrictions in OD2. If this is still a problem in OD1 can you open it there?

**Comment by wickr** [comment]
To my knowledge this was resolved a while back, and I agree if there are any future issues that's for the OD1 repo.
