### ISSUE TITLE
Exiting UV fullscreen leaves UV frame cropped

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1423]
### Descriptive summary
When Universal Viewer goes fullscreen and is then exited the UV iframe cuts off most of the functionality. The frame stays justified to the top-left corner and the content is zoomed in, the viewer is useless until a the page is refreshed.

### Expected behavior
UV can exit fullscreen and retain functionality in major browsers and OS'
- [ ] ff
- [ ] chrome
- [ ] safari
- [ ] edge

- [ ] macOS
- [ ] windows

### Related work
From QA: #1386

**Comment by jsimic** [comment]
QA fail in Chrome on Mac: Zoom/rotate tools gone at exit on image and text works. Moving to another image or text work does not restore zoom/rotate. Refresh does not restore either. Video and audio not tested.

QA fail in Safari on Mac: No media loading in UV. Hula Hoop of hopelessness.

QA fail in Firefox on Mac: No media loading in UV. Hula Hoop of horror.

QA fail in MS Edge on Mac: No media loading in UV. Hula Hoop of heartbreak.

QA fail on Chrome on PC: No media loading in UV. Seriously.

Safari on PC: No media loading in UV. Jinx.

QA fail on Firefox on PC: No media loading in UV. Yep.

QA fail on MS Edge on PC: No media loading in UV. Gah!

**Comment by CGillen** [comment]
re-fixed by #2326

**Comment by CGillen** [comment]
Maybe I'm misunderstanding what zoom tools mean:
<img width="160" alt="image" src="https://user-images.githubusercontent.com/11052958/176557866-dd46dfd3-4213-47e7-8e7e-195ffa40e799.png">
Are they this +/- in the top left corner?

**Comment by jsimic** [comment]
Yes. Here are three views on my 13.3-inch (2560 × 1600) laptop display. The first is a normal view, the second full screen, and the third with the browser window at ~1/2 of the screen. You will see zoom tools in the second and third, but not the first. Is this a bootstrap issue?
<img width="1188" alt="Screen Shot 2022-06-30 at 8 19 36 AM" src="https://user-images.githubusercontent.com/6344086/176715602-42f07398-f4d0-4d33-8f6b-1c6093f18316.png">

<img width="1440" alt="Screen Shot 2022-06-30 at 8 19 58 AM" src="https://user-images.githubusercontent.com/6344086/176715648-acbe8f4a-cce7-420a-b997-3fe673d46a5a.png">

<img width="759" alt="Screen Shot 2022-06-30 at 8 20 26 AM" src="https://user-images.githubusercontent.com/6344086/176715667-2c559a7f-22ae-495b-8148-961ab43dcda2.png">

**Comment by jsimic** [comment]
QA fail. Nothing appears to have changed from the above example.

**Comment by jsimic** [comment]
YES!
QA pass in Chrome on Mac
QA pass in Safari on Mac
QA pass in Firefox on Mac
QA pass in MS Edge on Mac
QA pass on Chrome on PC
QA pass on Safari on PC (older version)
QA pass on Firefox on PC
QA pass on MS Edge on PC
