### ISSUE TITLE
UV Page number is displaying as canvas label

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1426]
### Descriptive summary
At the top of UV, the page number is displayed as: 
![image](https://user-images.githubusercontent.com/11052958/102125735-fbc65a00-3dfe-11eb-990a-3a883bfcc2db.png)

Toggling `image` changes it to something more familiar: 
![image](https://user-images.githubusercontent.com/11052958/102125796-0c76d000-3dff-11eb-9ff2-54019cffff55.png)

A user cannot read the canvas label when `page` is selected and `- of` is irrelevant.

### Expected behavior
The `- of` is removed when page is selected and the user can access or read the label of the canvas that is selected.

### Related work
from #1386

**Comment by CGillen** [comment]
Huh, I could reproduce this last WC, but I can't now. Can you try again?

**Comment by jsimic** [comment]
This is also working as expect for me now on both staging and prod.

**Comment by CGillen** [comment]
Fixed
