### ISSUE TITLE
Decide on ordering of metadata for the forms. 

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#143]
### Descriptive summary

Now that we have all the metadata in place, we need to decide what order we want it all in. Do we want terms above and below the fold? How do we want to organize them? Do we want them in bigger chunks in the form? An order needs to be established for the way the metadata lays on the form.

**Comment by jsimic** [comment]
The order of the metadata fields on the form should be identical to the order on the MAP.
