### ISSUE TITLE
[MVP QA Fail] Include text for labels when searching in Review Submissions

### ISSUE THREAD

**Issue by carakey** [OregonDigital/OD2#1430]
### Descriptive summary

When using the Review Submissions table, searching for a string that occurs in a label associated with a URI, but not within the URI string itself, does not return results. For instance, [an item](https://staging.oregondigital.org/concern/images/df71b168r?locale=en) has a Creator with the LOC URI 'http://id.loc.gov/authorities/names/n95016439' and the label 'McCune, Bruce'. A search for 'McCune' in Review Submissions returns zero results. 

### Expected behavior

Searching in Review Submissions for a string found in a URI's label will return works that have that URI label. 

### Related work

#1369

**Comment by sseymore** [comment]
QA pass for "Ulmann, Doris, 1882-1934" in review. Final MVP review.
