### ISSUE TITLE
[MVP QA Fail] Update path for Depositor in Review Submissions table

### ISSUE THREAD

**Issue by carakey** [OregonDigital/OD2#1431]
### Descriptive summary

The Review Submissions table has a column for Depositor. Currently the value that is displayed is pulled from records' Creator value (as a URI). 

### Expected behavior

The Depositor value should display the username of the user depositing the work. 

### Related work

#1369

**Comment by jsimic** [comment]
The ability to sort by Depositor was removed when the Review Submission interface was replaced to resemble search results. Metadeities would like to add a filter to isolate works by Depositor. See #1853
