### ISSUE TITLE
Some facet values still showing as URIs

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1432]
### Descriptive summary
Some facets on staging are still displaying as URIs. It's not known if that is a systematic issue with configuration/solr metadata field reference OR if it's one-off issues with some ingested works.

### Expected behavior
Facet values are always user-readable labels

### Related work
From #1409 QA

**Comment by CGillen** [comment]
Fixed by #1565

**Comment by CGillen** [comment]
There are still two URIs in `Topic` because a free-text field has URIs in it, not controlled vocabulary.
QA:
- [ ] No URIs in facets except 2 in `Topic`
- [ ] Create a new work with a location, URI doesn't get added
- [ ] Create a new work with an institution (no longer supports DBPedia), URI doesn't get added
  - Try something new, other than OSU/UO

**Comment by shieldsb** [comment]
QA fail.  When adding location URI, it does not display in work show page or in the facet list- though the URI can be seen when editing the work.  See Orange Test Collection 017 as an example.

**Comment by CGillen** [comment]
QA round 2:
- [ ] Ingest a new work with Location & License
- [ ] Location value is added to facet list
- [ ] Location is displayed on show page (not URI)
- [ ] License is displayed on show page (not URI)

**Comment by shieldsb** [comment]
QA fail.  Location was not added to facet list and is not displayed on the show page.  License displays in work show page as URI (the results page does display it properly though). See work: Orange Test Collection 018. 

![image](https://user-images.githubusercontent.com/53542788/112918286-669f5680-90b9-11eb-9d1b-917bf68fd6c2.png)

**Comment by CGillen** [comment]
I didn't notice that the latest images weren't being deployed. This fix should finally be on staging & needs QA again

**Comment by shieldsb** [comment]
QA fail.  Location does not appear of work show page for new work and does not appear in the facet list. https://staging.oregondigital.org/concern/images/8049g510m?locale=en 

I did notice that the location for my previous QA test item for this ticket (from 3/29) is displaying in the facet list, but still not on the work show page. https://staging.oregondigital.org/concern/images/b8515n42v?locale=en

**Comment by shieldsb** [comment]
QA fail.  Location still not displaying on work show page.  There seems to be a delay, but location does eventually get added to the facet list.

**Comment by CGillen** [comment]
QA:
- [ ] Ingest a new work with a location
- [ ] When dumped to work show page wait 5 minutes
- [ ] Refresh work show page
- [ ] Thumbnail is visible
- [ ] Location is visible (no URI)

**Comment by shieldsb** [comment]
QA fail.  Location is still not visible on the work show page or the location facet after nearly half an hour.

**Comment by CGillen** [comment]
I don't get it. Are you the unluckiest QA'er or what's up?

This could be part of a larger issue with jobs being lost during deploys? I got it to work first try
https://staging.oregondigital.org/concern/documents/dv13zt348?locale=en

**Comment by shieldsb** [comment]
Ugh, I'm not sure what's up with this.  Maybe we can walk through it together when you have time.

**Comment by shieldsb** [comment]
QA pass.

**Comment by kmthorn** [comment]
"Terms instead of URIs need to display" connected to #1432 still seems to be a problem on search result page. Spot checking on item show pages looked good for all field except Location.
![CleanShot 2022-03-09 at 13 39 47](https://user-images.githubusercontent.com/36867009/157540830-f3cd2e2d-9c30-4830-a815-a8d8109f8779.png)
