### ISSUE TITLE
[MVP QA Fail] Include All Configurable Facets in Dashboard

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1438]
### Descriptive summary

Facets available under Dashboard>Collections>Edit View>Facets include only core facets. All OD2 facets should be listed, enable-able and movable

### Expected behavior

A collection administrator should be able to add, enable and reorder any facet in the public interface that applies to items in the collection using the Dashboard for any collection with configurable facets

### Related work

#1371

**Comment by CGillen** [comment]
QA:
- [ ] Create a new collection with configurable facets
- [ ] Configure some facets so they are enabled
- [ ] Configure some facets so they have a new name (non-default)
- [ ] Add works to the collection that have metadata related to those facets
- [ ] Visit collection landing page and see enabled facets
- [ ] Visit collection landing page and see facets with new names
- [ ] Enable a facet from the collection landing page and see works related to facet

**Comment by sseymore** [comment]
This is only enabled on this collection: https://staging.oregondigital.org/dashboard/collections/m900nt48n/edit?locale=en#configurable_facets

Going to QA after staging refresh.

**Comment by sseymore** [comment]
QA pass! 

https://staging.oregondigital.org/collections/j9602064p?locale=en
https://staging.oregondigital.org/concern/images/5t34sj60d?locale=en
https://staging.oregondigital.org/concern/images/vq27zn42r?locale=en

**Comment by sseymore** [comment]
final MVP review complete
