### ISSUE TITLE
[MVP QA Fail] Administrators can edit user information

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1440]
### Descriptive summary

An administrator should be able to edit user information, including username and email, as well as send a password reset link, and enable/disable the user from the Dashboard. This should ensure that users who change or no longer have access to institutional and/or vendor email can request the change to their OD2 account without having to create a new account and losing data. The password reset link option is a backup for a user-generated request for those that can't figure it out (yes, it happens.) The enable/disable option is documented in #844 and #1170 

### Expected behavior

An admin can go to the Dashboard, search for and find a user, and edit their username and email address. In addition there should be a mechanism (button) to send a password reset link to the user, and for the admin to disable the user's account or enable a disabled user's account

### Related work

#844, #1170, #1367

**Comment by shieldsb** [comment]
QA fail. I can change the user name, but there is no option to change email, send reset link, or disable the account.

**Comment by shieldsb** [comment]
QA fail.  Everything functions as expected except for deactivating an account.  After the deactivation option is selected, the user receives the appropriate email notification.  However, going back to their profile there is no indication that the account is disabled. The _deactivate user account_ button still appears and will allow you to select it again.  When you do, the user receives another deactivation notification email. Also, the user (who is supposed to be deactivated) can still log into that account and go to their dashboard.

**Comment by CGillen** [comment]
Can you walk me through your QA process Monday? I deactivated an account and it worked correctly, but didn't test the email 🤣

**Comment by shieldsb** [comment]
QA pass.  Will create an enhancement ticket to add a button to enable a deactivated account.  Reenabling be done on the backend now.
