### ISSUE TITLE
[MVP QA Fail] New user does not have Dashboard

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1441]
### Descriptive summary

Users assigned a Workflow Role need to be given a Dashboard regardless of institutional affiliation or lack thereof. As a test, an admin assigned a Depositing Role to an unaffiliated user and subsequently that user did not have access to a dashboard and could not deposit.

### Expected behavior

When assigned any Workflow Role a user needs access to their Dashboard once logged in and via the My Account dropdown.

### Related work

#1367

**Comment by shieldsb** [comment]
QA pass.
