### ISSUE TITLE
Sign Up link goes to Log In (devise sign_in) page

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1445]
### Descriptive summary

Clicking the Sign Up link goes to the Log In page.

![image](https://user-images.githubusercontent.com/2293544/103701494-f7531400-4f5a-11eb-8b41-37c41ff9b3be.png)

### Expected behavior

Sign Up link goes to Sign Up page

**Comment by straleyb** [comment]
QA: - [ ] when logged out, clicking the sign up button takes you to the sign up page.

**Comment by shieldsb** [comment]
QA pass.
