### ISSUE TITLE
Search Results hit highlighting is not active for Collection results

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1446]
### Descriptive summary

When a search is done and hits in results are highlighted, Collection results are not highlighted even when there's a match.

![image](https://user-images.githubusercontent.com/2293544/103703482-75fc8100-4f5c-11eb-8252-eaf87a2fb93e.png)

### Expected behavior

Keyword highlighting works for Collection results just like Work results.

**Comment by straleyb** [comment]
QA:
- [ ] Searching for Barometer should return "Minorities... Barometer" collection hit with proper title and description highlighting

**Comment by shieldsb** [comment]
QA pass.
