### ISSUE TITLE
[MVP QA] Download options

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1449]
### Descriptive summary

Defined by role etc.

### Expected behavior

- [x] Log into OD2 as a user with Administrator credentials
- [x] Find a work with a full-resolution download option and download full-resolution file + metadata 
  - [x] Confirm file transfer by opening both files
- [x] Find a work and download low-resolution file + metadata 
  - [x] Confirm file transfer by opening both files
- [x] Find a work and download only the metadata file
  - [x] Confirm file transfer by opening file
- [ ] Confirm that download options match and do not exceed permissions as out lined in the [OD2 Roles & Permissions](https://docs.google.com/spreadsheets/d/1-Mk0CUBU3guGLDDFyuS2l6rIku5eZjnNVDMxH9HuqoM/edit#gid=0) doc

Repeat the above logged in as a Curator, Depositor, Authenticated OSU User, Authenticated UO User, Authenticated Community User, and Unauthenticated Community User with reference to the [OD2 Roles & Permissions](https://docs.google.com/spreadsheets/d/1-Mk0CUBU3guGLDDFyuS2l6rIku5eZjnNVDMxH9HuqoM/edit#gid=0) doc.

### Related work

#644, #666, #667, #668, #669, #759, #760, #1115, #1234, #1235, #1314, #1341

**Comment by kmthorn** [comment]
Download does not seem to work for text based objects. It did work for images, audio, and video.

Used for QA:
**Tested download File and Metadata for this digital image**
- [Linus Pauling and Paul Emmett](https://staging.oregondigital.org/concern/images/df719k784)

Downloading worked fine for this record

**Tested download File and Metadata for these publications**
- [Barometer Souvenir Edition 1900](https://staging.oregondigital.org/concern/documents/3t945q968?locale=en)
- [Heather Browning Interview ](https://staging.oregondigital.org/concern/documents/6w924c536)

Downloading did not work for both of these objects. Error 22 invalid argument message appeared when opening the .zip from my desktop

**Tested download File and Metadata for this audio**
- [Interview with Jennifer Esparza: Audio, University of Oregon Veterans ](https://staging.oregondigital.org/concern/audios/df70j754j)

Downloading worked fine for this record

**Tested download File and Metadata for this video**
[Gaston County Board of Commissioners meeting video, November 9, 2006](https://staging.oregondigital.org/concern/videos/df70hn10s#metadata)

Downloading worked fine for this record

**Tested download File and Metadata for this compound object**
- [Danforth Cooke & Co., Patterson, NJ. Engine purchases by OSN](https://staging.oregondigital.org/concern/generics/df727084j?child_page=2&locale=en)

Downloading did not work. Error 22 invalid argument message appeared when opening the .zip from my desktop

**Comment by jsimic** [comment]
Confirm all downloads are working for images. BUT the standard size jpeg file has a .tiff extension.

Confirm all downloads are working for video.

Confirm all downloads are working for text. 

Confirm all downloads are working for audio.

Consult with the metadata team about these issues:
All metadata from controlled vocabs are presented as uris in the downloaded metadata. Do we want labels?
Need to make sure all metadata is in the download. I'm not seeing Collection. Will need to make some test objects.
Complex object metadata has the metadata for the children as well as the metadata of the parent. do we want this?

**Comment by jsimic** [comment]
SMs want labels only in downloaded metadata: "URIs probably not necessary & possibly even a hindrance."

Please configure metadata download to show fetched labels and not URIs for all fields with controlled vocabularies.

**Comment by jsimic** [comment]
Metadeities will test that all metadata is in the downloaded csv file. If there are problems, another ticket will be made.
