### ISSUE TITLE
Review Queue UI [new MVP item]

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1460]
### Descriptive summary

OD1 parity: Create a UI in the Dashboard for Review Submissions that mimics the behavior of OD1's review queue, i.e. works appear in a search-like interface with all facets and a search box limited to works needing review, metadata that would be in a front-end search return is visible, and a button to review a single work.

### Expected behavior

Anyone with an Approving Workflow Role can access Dashboard>Review Submissions, use facets or the search box to find or limit works needing review, look over basic metadata quickly, and review works with a single click without having to go to the work page.

### Related work

#22, #24, #25, #26, #48, $761, #792, #1343, #1369

### Accessibility Concerns

UI should follow other Dashboard templates.

**Comment by CGillen** [comment]
Queue interface like the search results page. The important part is the facets are accurate and functional. This is for faceting down to work with a sub-set of the queue. Facet values need to be accurate to the review-queue, not all works.

Assets pulled in from bulkrax should show in the review submissions queue. Currently bulkrax and OD1 require the entire batch to be reviewed at once, not by item. Sara to check with Notch8 if bulkrax works that non-erroring works do end up in the review queue. Also checking if they are adding checkboxes to queue

Can be out of the dashboard but make sure it is clear that it is the review queue. Being outside the dashboard is not a requirement, but is acceptable if easier.

one-click review can cause page reload. Maybe we can do checkboxes of reviews?

**Comment by CGillen** [comment]
QA:
- [ ] Visit https://staging.oregondigital.org/admin/workflows?locale=en
- [ ] Queue looks like regular search results
- [ ] Results do not include works that have been reviewed (click in and there shouldn't be a badge near the title that says `deposited`)
- [ ] Results include works that need to be reviewed (click in and there should be a badge near the title that says `Pending Review`)
- [ ] Click approve on an item in list view
- [ ] No crash
- [ ] Item exits `Pending Review` and enters `Deposited`
