### ISSUE TITLE
Paginate Explore Collections page

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1461]
### Descriptive summary

Now that we are displaying all the possible collections on the explore collections page, there are over 100 being displayed. This is very heavy handed. So we need to paginate them. On the MAC wireframes, there are 4 rows displayed. So we need to allow 4 rows to be displayed and paginate the rest.

**Comment by straleyb** [comment]
Explore collections all tab should be paginated.

**Comment by shieldsb** [comment]
Pagination is in place and works, but needs formatting work.  The menu bar does not match the wireframe. 

![image](https://user-images.githubusercontent.com/53542788/105874247-39e39b80-5fb1-11eb-9890-ba807a57a2c2.png)

**Comment by shieldsb** [comment]
Also, at the bottom of page 3, the collections text is cut off.

**Comment by straleyb** [comment]
This needs to have a look taken at it. Specifically regarding what we want the pagination to look like for this page. Currently we have a search box at the top right hand corner with the pages under that. Do we want to move the pages location or remove the search box? This would be a good one for @petersec @kmthorn to bring into their discussions and maybe get azle to whip something rad up.

**Comment by kmthorn** [comment]
Needs for Mason View:

- Sort: Number of items, A-Z sort. Text place next to the number of collections dropdown menu.
- Number of Collections per Page: Use the same that we use for search results: 10, 20, 50, 100. The default view is 50 for desktop and mobile.
- Mason Grid layout: 5 columns instead of 6
- Pagination: Needs to be at the top and the bottom. Showing 1 to 50 of XX Collections.
- Search box: “Search collections by keyword” should be in the search box.

**Comment by shieldsb** [comment]
Reviewed at 4/20/21 POSM meeting.  WF will be updated.

**Comment by CGillen** [comment]
QA:
- [ ] Visit explore collection page
- [ ] Each category (ALL, OSU, UO, MY) is a new page load
- [ ] Masonry view
  - [ ] Pagination at bottom causes page loads
  - [ ] Each page is different from the last
- [ ] Repeat for List view
- [ ] Closely resembles wireframes: https://drive.google.com/drive/u/1/folders/1ndau6PwvxSDVrEG6Dj4Je1FgqGq6w_6C

**Comment by shieldsb** [comment]
In masonry view, there are not full rows of icons, see images below (particularly the third one). 

![image](https://user-images.githubusercontent.com/53542788/123696981-3d55aa00-d811-11eb-9ea8-df3597038544.png)
![image](https://user-images.githubusercontent.com/53542788/123697021-4ba3c600-d811-11eb-92ba-ad9a206aba69.png)
![image](https://user-images.githubusercontent.com/53542788/123697101-5cecd280-d811-11eb-9f15-447f7f6ef2ae.png)
