### ISSUE TITLE
[Wireframe][Work Show] UO/OSU branding does not display

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1467]
### Descriptive summary
The institutional branding does not display on the work show page.
Works with UO or OSU institutional administrative metadata should display the related institutional branding image in the top right, above `save to` and `download`

### Expected behavior
institutional branding appears on the work show page.

### Related work
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938487

**Comment by CGillen** [comment]
- [ ] Work without institution field filled display no institutional image
- [ ] Work with `http://id.loc.gov/authorities/names/n80017721` (Oregon State University) displays OSU collection banner at top-right of work show page. Regardless of collection work is in
- [ ] Work with `http://id.loc.gov/authorities/names/n80126183` (University of Oregon) displays UO collection banner at top-right of work show page. Regardless of collection work is in

**Comment by shieldsb** [comment]
QA fail.  Works without institution field still display an institutional image. 
Ex. https://staging.oregondigital.org/concern/documents/df70hn14w?locale=en 

Though test items I've added without an institution do not display an institutional image. 
Ex. https://staging.oregondigital.org/concern/images/v979v3061?locale=en

**Comment by shieldsb** [comment]
QA pass.
