### ISSUE TITLE
[Wireframe][Work Show] Collection preview

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1468]
### Descriptive summary
The collection preview on the work show page does not match the look and feel of the wireframes

### Expected behavior
Collection preview title, count, and view link are correct size and weight
Divider between count and view link is present
~Images are all forced square (crop vs resize?) and the same size~

### Related work
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938487
https://projects.invisionapp.com/share/YJX9Y48C9H3#/screens/417551200

**Comment by CGillen** [comment]
QA: Collection preview at the top of the work show page
- [ ] Title, count, and view link are close in font size
  - [ ] Font weight
  - [ ] Spacing
- [ ] Divider between item count and view all link is present and accurate

**Comment by shieldsb** [comment]
QA fail.  Font weight seems heavier in the WF for these items. It's close though, so let me know if you want someone else to take a look before you do anymore work.

**Comment by CGillen** [comment]
I'm going to call this one close enough. There will probably come a time when we will review fonts and weights more closely.
