### ISSUE TITLE
[Wireframe][Work Show] Copyright Icon

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1469]
### Descriptive summary
Copyright display is missing the copyright icon. Solr Document model has a method built to convert rights statement to fontawesome icon: https://github.com/OregonDigital/OD2/blob/master/app/models/solr_document.rb#L39

### Expected behavior
Icon corresponding to the rights statement and copyright information is displayed in the copyright section

### Related work
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938487
https://projects.invisionapp.com/share/YJX9Y48C9H3#/screens/417551200

**Comment by CGillen** [comment]
QA:
- Copyright icon appears next to copyright statement for various copyright statements
- [ ] In Copyright
- [ ] In Copyright - EU Orphan Work
- [ ] In Copyright - Educational Use Permitted
- [ ] In Copyright - Non-Commercial Use Permitted
- [ ] In Copyright - Rights-holder(s) Unlocatable or Unidentifiable
- [ ] No Copyright - Contractual Restrictions
- [ ] No Copyright - Non-Commercial Use Only
- [ ] No Copyright - Other Known Legal Restrictions
- [ ] No Copyright - United States
- [ ] Copyright Not Evaluated
- [ ] Copyright Undetermined
- [ ] No Known Copyright

**Comment by shieldsb** [comment]
QA fail.  No icon appears for any "No Copyright" statement.

**Comment by shieldsb** [comment]
QA pass.
