### ISSUE TITLE
[Wireframe][Work Show] Tab Pane alignment and look+feel

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1470]
### Descriptive summary
- [x] `Share this` should be fully right-aligned
- [x] Tabs font capitalized & correct font/weight
- [x] Pane width matches UV width
- [x] Links need yellow underline
- [x] link out icon to change to `i` informational icon

### Expected behavior
See above

### Related work
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938487
https://projects.invisionapp.com/share/YJX9Y48C9H3#/screens/417551200

**Comment by CGillen** [comment]
QA

- [x] `Share this` should be fully right-aligned
- [x] Tabs font capitalized & correct font/weight
- [x] Pane width matches UV width
- [x] Links need yellow underline
- [x] link out icon to change to `i` informational icon
- [ ] Metadata shrinks to single column in mobile view
- [ ] Metadata pane resembles wireframe as closely as possible

**Comment by shieldsb** [comment]
Probably a QA pass. A few items to mention: 
- the link out informational icon doesn't match the WF 
- The metadata columns look fine but have more space between them then on the WF, not sure that it needs to be addressed though
- the metadata fonts seem heavier in the WF, but it's hard to be certain

**Comment by CGillen** [comment]
I'm thinking this will be good enough. The `i` MAC suggested is unavailable to us unless we can load two versions of FontAwesome, which there is a ticket for exploring: #1496 
And generally spacing and sizing is too hard to really tell with MAC wireframes. They gave us _**very specific**_ size and styles to use in certain situations, from the style guide, and I have consistently struggled to have those match with the way the wireframes show up. I think it's because the wireframe images themselves have to be scaled down to exactly 1920x1080 for everything to be the size MAC expected it, but the InVision app automatically scales the wireframes up/down to fit browser windows.

**Comment by shieldsb** [comment]
QA pass.
