### ISSUE TITLE
[Wireframe][Work Show] Copyright placement and print button

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1471]
### Descriptive summary
In the current wireframes, there is no print icon/button. It has been suggested that the copyright section be replaced with a print button and the copyright information moved to the next line, right-aligned such that it is under the download button.

### Expected behavior
Copyright section is moved
Print button is available

### Related work
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938487
https://projects.invisionapp.com/share/YJX9Y48C9H3#/screens/417551200

**Comment by CGillen** [comment]
QA: Work show page action buttons (save to, print, download, etc)
- [ ] Edit and Delete still do not show for non-admin and non-editors
- [ ] Buttons include a print button
- [ ] Print button starts system print menu
- [ ] Buttons reflow when window is resized

**Comment by shieldsb** [comment]
QA pass.
