### ISSUE TITLE
Breadcrumb trail for Collection landing page does not include 'Collections' when logged out

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1475]
### Descriptive summary

The Collection landing page breadcrumb trail includes a 'Collections' link when you're logged in, but it does not show up when logged out.

![image](https://user-images.githubusercontent.com/2293544/105095908-2e491f80-5a5b-11eb-8598-80764cb10e0a.png)

### Expected behavior

When logged out, Collection landing page breadcrumb trail still has a 'Collections' link present.

**Comment by CGillen** [comment]
Breadcrumbs lead to dashboard, should lead to collections page

**Comment by shieldsb** [comment]
QA pass.
