### ISSUE TITLE
Search is not working in Dashboard > All Collections or Your Collections

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1477]
### Descriptive summary

The search box has no results with a keyword search in the Collections dashboard: https://staging.oregondigital.org/dashboard/my/collections?locale=en 

### Expected behavior

Search results will appear and correspond to a search in the search box. 

### Related work

N/A

### Accessibility Concerns

N/A

**Comment by CGillen** [comment]
QA:
- [ ] Reach dashboard
- [ ] search for work in my works
- [ ] search for work in all works
- [ ] search for collection in my collections
- [ ] search for collection in all collections

**Comment by shieldsb** [comment]
QA pass.
