### ISSUE TITLE
Metadata for collection records in search results

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1479]
### Descriptive summary

The Metadata team would like the following metadata in the collection records in search results- only this metadata:

Title: 
- Required
- Already visible

Description: 
- Required
- Already visible
- Truncate at 100 characters
- If there is a search result/hit highlight, that preview takes precedence over initial description text.

Date:
- Optional

### Expected behavior

Collection records in search results will have the metadata listed above in order of requirement and visibility.

### Related work

N/A

### Accessibility Concerns

N/A

**Comment by sseymore** [comment]
Updated since not reviewed yet-- removed Subject and Location

**Comment by shieldsb** [comment]
Reviewed at 4/20/21 POSM meeting.

**Comment by jsimic** [comment]
New wireframes will include the following collection metadata above the featured images: 

- Title
- Description
- Date
- Finding Aid

And below the search:

- Creator
- Contributor
- Creation Date
- Subject
- License
- Language
- Repository
- Publisher
- Related URL
- Resource Type
- Institution

**Comment by wickr** [comment]
Mostly done. Ready for MVP QA.

**Comment by jsimic** [comment]
Wait for #2210 to QA. Description is not appearing as indicated in wireframes.

**Comment by jsimic** [comment]
@CGillen QA fail: Date element is appended to the end of Description instead of on a new line
![Screen Shot 2022-08-17 at 6 57 17 AM](https://user-images.githubusercontent.com/6344086/185152854-0586f8b8-69d1-48fd-a3e4-7a371ee7d4a7.png)
.

**Comment by straleyb** [comment]
Need a new line break for collection display before date

**Comment by jsimic** [comment]
QA pass.
