### ISSUE TITLE
Universal view busts when more than 1 child work is associated with a complex object.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1483]
### Descriptive summary

Undefined method #gsub for Array. We need to figure out how to support page finding with multiple works associated with a parent work. Only happens when something isn't a PDF.

**Comment by shieldsb** [comment]
QA pass.  Tested with jpegs.  One of the thumbnails did not appear, but all images displayed in UV. @CGillen Do you want me to test again to see if another ticket needs to be created for the thumbnail issue?

**Comment by CGillen** [comment]
@shieldsb Yeah, can you please try again? It looks like there was a hiccup with the thumbnail. If we find other thumbnails are broken, open a new ticket
