### ISSUE TITLE
[Wireframe][Explore Collections] Row highlighting

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1486]
### Descriptive summary
In list view, the table should highlight the hovered/focused row so users can more easily identify what collection they are seeing information about.

### Expected behavior
Rows in list view tables highlight on hover/focus

### Related work
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938476

**Comment by straleyb** [comment]
QA:
- [ ] Hovering over a row in the list view should highlight the row for better visibility.

**Comment by shieldsb** [comment]
QA fail.  When hover over the row, the linked text becomes underlined but not highlighted as shown in the WF.

**Comment by shieldsb** [comment]
QA pass.
