### ISSUE TITLE
[Wireframe][Explore Collections] Locked out of collection indicator

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1487]
### Descriptive summary
So that users can figure out what may be in the system that they don't have access to without institutional authentication, a lock should be displayed on the explore collections page. The count of items in the collection should represent ALL the items, even if the user can not find access them. The landing page should handle informing the user about institutional authentication and more access.

### Expected behavior
Like the wireframe, a lock should be displayed near collections that require additional authentication to access all the works.
On hover/focus more information should become available (UO Affiliates Only or OSU Affiliates Only)

### Related work
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938476
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938480

### Accessibility Concerns
The affiliation text should be readable by screen readers without focus/hover

**Comment by straleyb** [comment]
QA:
 - [ ] User doesnt have access to UO only collections should see a lock with "UO Afilliates Only" on the locked collection
 - [ ] User doesnt have access to OSU only collections should see a lock with "OSU Afilliates Only" on the locked collection

**Comment by shieldsb** [comment]
QA fail. Ticket specifications need to be revised.

**Comment by straleyb** [comment]
QA:
- [ ] When logged out and looking at the explore collections page, the user should see a lock icon for any collections with works that have visibility set to an institution.
- [ ] Collections with OSU visibility works should show OSU Affiliates Only for the collection explore page on hover
- [ ] Collections with UO visibility works should show UO Affiliates Only for the collection explore page on hover.

**Comment by shieldsb** [comment]
QA fail.  When logged in as UO affiliate, the lock appeared twice in the list view.  It was fine in masonry view.  See image below. 

Some observations:

- the explore collections page is still slow to load (enough to be annoying) 
- under explore collections, the number of items displayed for each collection is maxed out at 10, and once the collection is selected is maxed out at only four items displaying (almost positive that it displays the last four works added to the collection)  
- I think this is known, but selecting view all under a collection = 0 works found 
- When all works contained in a collection are public, but the collection is set to institution: when logged out does not appear in explore collections; when logged in as OSU affiliate appears under the OSU collections tab on explore collections page; when logged in as UO affiliate, collection still appears under OSU tab (we talked previously about OSU being the default) 
- When one item in collection is set to UO and collection is set to institution, the collection still defaults to the OSU collection tab when logged in as admin; does not appear under explore collections when not logged in; when logged in as UO affiliate, the collection is under OSU but has a locked indicator 

![image](https://user-images.githubusercontent.com/53542788/111207019-5ef29480-8586-11eb-9cd7-32dc31bdd380.png)
