### ISSUE TITLE
[Wireframe][List Search] Keyword search box

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1495]
### Descriptive summary
The search results page is missing the keyword search box in the facet/filters section. This search box should add (or replace, not sure what feels natural may require user testing) keywords to the all_fields search field. It should not initiate a new search entirely (that's what the header box is for), so the other facets/filters should remain in place.

Edit: This can probably be done with filter query in solr: https://solr.apache.org/guide/6_6/common-query-parameters.html#CommonQueryParameters-Thefq_FilterQuery_Parameter
By converting all the previous keyword searches to a filter query somehow the latest query can be put into the regular query (`q`) field.

### Expected behavior
Keyword search box appears on search results pages.
Entering keywords does not remove facet/filter selection.

### Related work
Further work from #1376 

### Accessibility Concerns
Box will need a descriptive label, not just placeholder text.

**Comment by kmthorn** [comment]
basic search for the term yearbooks, and then be able to search within the search results by using the keyword box under filters. Type in linus pauling as a keyword to filter within the search results for yearbooks.

**Comment by CGillen** [comment]
QA:
- [ ] Search keyword from header searchbox
- [ ] On search screen, search a deeper keyword from `keyword` box in facets
- [ ] Both search terms are `AND` together

**Comment by shieldsb** [comment]
QA fail.  searching second keyword did not filter search, returned the same number of works on each test search.

**Comment by shieldsb** [comment]
QA pass.
