### ISSUE TITLE
Institution facet doesn't include collections

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1500]
### Descriptive summary

Collections as well as works should be showing up in the institution facet on the search results page.

**Comment by CGillen** [comment]
QA:
- [ ] Create a new collection
- [ ] Add at least two institution values
- [ ] Save collection
- [ ] No errors on save
- [ ] Edit form presents both institution values
- [ ] Both institution values have a label
- [ ] Go to search & facet by those institution labels
- [ ] Collection displays in search results

**Comment by sseymore** [comment]
QA fail. 
![Screen Shot 2021-03-26 at 3 23 48 PM](https://user-images.githubusercontent.com/7328774/112699017-2dac7b00-8e48-11eb-9fdd-450936ca6251.png)

**Comment by sseymore** [comment]
QA pass.

![Screen Shot 2021-04-14 at 10 13 42 AM](https://user-images.githubusercontent.com/7328774/114751536-1d324680-9d0a-11eb-81d2-8eea85bca498.png)

![Screen Shot 2021-04-14 at 10 13 00 AM](https://user-images.githubusercontent.com/7328774/114751540-1dcadd00-9d0a-11eb-9c6e-986b2e5c2327.png)
