### ISSUE TITLE
Institution checks and displays should look at multiple values

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1507]
### Descriptive summary
Right now, most checks against the `institution` metadata field only checks the first value. This was because features assumed `institution` would be used administratively to dictate displays and access. The truth is, some works have institutions that are not UO or OSU.

### Expected behavior
Replace calls to `#institution.first` with `#institution.select` and some logic (`#empty?`, `#first`, etc)

### Related work
example: #1484

**Comment by straleyb** [comment]
QA:
- [ ] If a work has multiple institutions, it should still function as expected
  - [ ] If a collection has either institution uris (http://id.loc.gov/authorities/names/n80017721) in its metadata, it should display the proper logo on the collection's show page
  - [ ] if a collection has multiple institutions including one of the main ones (http://id.loc.gov/authorities/names/n80017721) it should still have the proper institution logo.
  - [ ] It should still display the proper highlight message on locked collections

**Comment by shieldsb** [comment]
QA pass.
