### ISSUE TITLE
Expose my collection download on collection landing page

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1517]
### Descriptive summary
There should be a button (wireframe to come) for users to download User Collections which have been shared (public). This will allow professors and researchers to create collections and their students to download course materials or otherwise interesting collections of works.

### Expected behavior
A user can see a download button and use it on `User Collections` which they have download access to. Users should be able to download any collection which is public/shared. Works that the user shouldn't be able to view, shouldn't be added to the zipped download (standard behavior already)

**Comment by shieldsb** [comment]
QA fail. Download button not available on collection landing page.

**Comment by CGillen** [comment]
@shieldsb @jsimic It looks like @lamtu1's update was to add Digital Collections, but this ticket is specifically for User Collections. If we want to do Digital Collections we'll want to architect this differently since they tend to be huge

**Comment by shieldsb** [comment]
No, it didn't appear on the user collections page either.

**Comment by lamtu1** [comment]
I'm currently checking on staging and user collection download works for me

**Comment by lamtu1** [comment]
If `digital collection` is not part of it. Then I can go in remove it and update the code to do `user collection`.

**Comment by CGillen** [comment]
the ticket requires the user's collection to be shared (public with the green share link on my collections dashboard). This seems to be working for me too.
Does this ticket need to be reworked?

**Comment by lamtu1** [comment]
I don't think so, I changes back to the user collection and seem to be working fine on staging. But I will fixed on some of the feedback you requested in the PR and make update to it and will let you know once it is ready

**Comment by lamtu1** [comment]
Hi @jsimic I have a question about the user collection download. In the future, are we ever will have a time we want to allow full/high res for collection?

If full size is ever going to be allowed, we need exactly who and under what conditions they can download full size. And downloading full size works is already figured out, so if we dynamically decide to add full or low works based on that, we won't be able to re-architect it later to massively conserve resources in the future. Right now downloads for collections are slow, costly to the system, prone to crashing, and not resumable if things crash.

**Comment by jsimic** [comment]
@lamtu1 The consensus from the metadata team is no, we do not want to allow hi-res downloading.

**Comment by shieldsb** [comment]
@CGillen @lamtu1 When I try to download a collection from the collections landing page, I receive an error message. 
![image](https://github.com/OregonDigital/OD2/assets/53542788/0cb25ab2-1407-4c96-9b9c-1b8e7607d275)

**Comment by shieldsb** [comment]
Download does not prompt with option for high res images
