### ISSUE TITLE
Add LOC Organizations vocab and OSU Academic Units vocab to Publisher CV

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1526]
### Descriptive summary

Add support LOC Organizations vocab and OSU Academic Units vocab to Publisher CV.
Based on recent Publisher value remediation, these are very recent additions to the Publisher CV. The MAP has been updated.

### Expected behavior

Publisher controlled vocabulary allows LOC Organizations or OSU Academic Units URIs.

**Comment by shieldsb** [comment]
QA:

 can successfully add LOC Orgs URI to Publisher field: http://id.loc.gov/vocabulary/organizations/orumu
 can successfully add OSU Academic Units URI to Publisher field: http://opaquenamespace.org/ns/osuAcademicUnits/ZaTFzxWC

**Comment by shieldsb** [comment]
QA pass.  I was able to add both of these URIs to the publisher field of a new work.  However, when adding them to an older work they do not display - they can still be seen in the publisher field when editing the work.
