### ISSUE TITLE
Explore collections works count maxed at 10

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1533]
### Descriptive summary
Explore collections dashboard maxes out at 10 in the works count column, when it should display the total count of works, regardless of user access to those works.

We only end up grabbing 10 rows from Solr, then call `#length` on the response to get the works count. We should update this to get the `numDocsFound` value from the Solr response.

### Expected behavior
The absolute total count of works is displayed as the total count of works in the collection.

**Comment by CGillen** [comment]
QA:
- [ ] Go to explore collections page
- [ ] Find collection with more than 10 works
- [ ] Correct number of works show in masonry view
- [ ] Correct number of works show in list view

**Comment by shieldsb** [comment]
QA pass.
