### ISSUE TITLE
Disable search within this item for works with no OCR content

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1537]
### Descriptive summary
UV displays a box to let you search in the work. If the work has no OCR content it should have this box disabled or removed.

![image](https://user-images.githubusercontent.com/11052958/108760500-95e30680-7502-11eb-952d-95a505a804d1.png)

If this is not a simple toggle or JS bit, we can push this to enhancement.

### Expected behavior
If a user can't feasibly search within a work, no OCR or hOCR content, the search box should disappear or be disabled.

**Comment by shieldsb** [comment]
QA pass.
