### ISSUE TITLE
Download CSV metadata on compound object causes server crash

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1538]
### Descriptive summary
https://staging.oregondigital.org/concern/generics/df727084j?locale=en

Downloading CSV metadata for this work causes a system crash. Subsequent pages no longer load. K8s does not help us reboot.

### Expected behavior
Compound object download works. Server doesn't crash.

### Related work
#1539 - Cause pods to restart on server hang/crash

### Accessibility Concerns
N/A

**Comment by CGillen** [comment]
Notes from SM:
```
https://staging.oregondigital.org/concern/generics/df727084j?locale=en 

We got to the compound object. Kate downloaded. It didn’t work. Then we tried downloading again. It came back to life. We tried downloading again, and then all of the staging broke. This isn’t working yet.
```
The first attempt did not crash staging, but did produce an incorrect zip file. Second attempt crashed staging,but was recovered by k8s.

The intended download behavior is this:
- CSV of metadata for parent object
- File attachments for parent object
- File attachments for each child object - to depth of 1

**Comment by CGillen** [comment]
QA:
- [ ] Find a compound object, preferably not a migrated work such as: https://staging.oregondigital.org/concern/images/j3860694x
- [ ] Click download > files and metadata
- [ ] Download begins within ~10 seconds
- [ ] Download progresses at >5mbps (open download pane before clicking download, ctrl+j)
- [ ] Download finishes
- [ ] Extract downloaded zip, extraction succeeds
- [ ] View metadata.csv, it contains lines for the parent and each child
- [ ] All child (and parent if it exists) files are present
- [ ] All files can be opened and do not error

**Comment by shieldsb** [comment]
QA pass.
