### ISSUE TITLE
Server crash not picked up by K8S and pod is not restarted

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1539]
### Descriptive summary
https://staging.oregondigital.org/concern/generics/df727084j?locale=en
Downloading CSV metadata for this work caused a system crash (#1538). After the crash, all pages were unresponsive, the server never received requests or sent responses, browser didn't seem to timeout.

It would be nice if readiness/liveness probes picked up on this (logs can be grabbed to help identify this state) and restarted the pod.

### Expected behavior
Server hangs/crashes starts a pod restart and uptime is minimally affected.

### Related work
#1538 

### Accessibility Concerns
N/A

**Comment by CGillen** [comment]
@rordway I don't know if there's a relevant ticket (in osulp-infra?) but this seems to have been fixed. Do you think it was using two replicas or did you fix some live/ready-probes?
If a ticket exists, can you link it. If not can you give a short explanation here about what change you think fixed this?

**Comment by decimalator** [comment]
oh interesting, I don't remember seeing this ticket even. I didn't purposefully fix it. 

if Rails fully crashes, that's going to trigger a container restart. It can take some time for a new `web`  pod to get created and booted and to reach the point where it can handle traffic. With one replica, that would mean a complete outage while the container restarts.

it makes sense that having multiple replicas would work around this problem. the dead replica gets removed which removes it from the Service that the ingress controller forwards requests to. Only the replica that isn't restarting would be able to receive requests and it would function until it hit the same bug and that replica starts going through the restart process.

one workaround is with multiple replicas. we have two right now which is probably fine for staging. we'll want to test varying numbers of replicas to find the sweet spot. and if we needed to we could configure horizontal pod autoscaling to spin up new `web` pods when we hit a certain threshold.

and we also need to improve the boot times of our containers -- make sure we're not initializing stuff we don't need, gem caching or whatnot so Rails doesn't need to spend as much time initializing so a restart is less painful
