### ISSUE TITLE
#show metadata fields 

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#154]
### Descriptive summary

Metadata field titles need to be set properly on the show page. An example of the current labels can be seen on http://od2-staging.library.oregonstate.edu/concern/documents/3r074t92z?locale=en#?c=0&m=0&s=0&cv=0&xywh=-490%2C0%2C2179%2C750

See the `form label` field in the MAP, could be that the field title just needs a `.humanize`

**Comment by mccallum** [comment]
I can't comment. http://od2-staging.library.oregonstate.edu/ isn't working for my earlier @uoregon.edu login... I've tried Incognito mode and clearing cache but it just flips to Shib saying "no." I created a non-institutional @maymarch.com account and I get logged in but showpage presents a "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

**Comment by mccallum** [comment]
We were asked to leave comments on things in QA column to possibly clear and this was labeled UX.

**Comment by vantuyls** [comment]
@jsimic can you or another metadataoid QA this something this week?

**Comment by jsimic** [comment]
@vantuyls Sure

**Comment by simholt** [comment]
Reopening this -- see spreadsheet below for details. 

https://docs.google.com/spreadsheets/d/1y27Gtcm42qG7mKQTVNhkOIoPTD9viW65n7vhkI2IPGE/edit?usp=sharing

@jsimic Please look over spreadsheet. Some clarification needed about Type vs. Resource Type.

**Comment by mccallum** [comment]
I see why this is labeled UX now.

Metadeities (@simholt @jsimic ) can add a "Top 15-30" column to their spreadsheet above for the metadata. Then we'll expose a full 160 plus possible with a "See all +" make-visible button item or something.  

Or divide them into four user-friendly categories as NU did: https://www.fulcrum.org/concern/file_sets/zc77sq117?locale=en#info

Or both.

**Comment by straleyb** [comment]
Im pretty sure this ticket was for the configuration of the show page, once we get the order in place (if that is even necessary for this ticket), I think maybe this one should be good to go. Then we can make a new ticket for look and feel for the show page, rather than displaying proper info,

**Comment by mccallum** [comment]
That makes sense, Brandon. I'm going to remove UX label from this and will remember my comment to @simholt and @jsimic for some future discussion since it got no response. Thanks.

**Comment by wickr** [comment]
Confirming what's on Sarah's spreadsheet, these are current issues:

- [ ] Contributors (Coming in from Hyrax: https://github.com/samvera/hyrax/blob/master/config/locales/hyrax.en.yml#L27 )
- [ ] Creation Date not showing
- [ ] Geographic Area label not showing, content ok
- [ ] Keyword showing twice
- [ ] License showing twice, once as Label and once as URI
- [ ] Modified not showing
- [ ] Rights Note not showing
- [ ] Subject not showing (likely one of Keywords)
- [ ] Submission Date not showing
- [ ] Resource Type label should be Type

**Comment by revgum** [comment]
It looks like this issue is related to PR #292 which hasn't been completed, @straleyb verify?

**Comment by wickr** [comment]
Closing this with merging of #292
