### ISSUE TITLE
New non-institutional users not receiving emails and format email

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1540]
### Descriptive summary
After account creation, no verification email was sent out. @kmthorn & @petersec created accounts as part of their writers retreat and did not receive emails.

### Expected behavior
New non-institutional users receive an account verification email. Text needs to be sent to Service Managers for review.

### Related work
#986 #971 #992

**Comment by kmthorn** [comment]
Subject: Oregon Digital Account Verification

Body:
Hello [ add person’s name ] 
We received a request to create an Oregon Digital account from [ add email address associated with the user’s account ]. 

Visit https://www.oregondigital.org to get started with curating, building and sharing your own private digital collections from the tens of thousands of freely available digital items held in Oregon Digital.
If you didn't request this, please ignore this email, or contact us at oregondigitalref@uoregon.edu

Thank you,
The Oregon Digital Team

**Comment by CGillen** [comment]
QA:
- [ ] Create a new user with a personal email
- [ ] Receive an email
- [ ] Email text matches closely to above (we don't have a person's name, so that's not in the email)
- [ ] Link is provided to confirm email address
- [ ] Link logs you in and confirms address
- [ ] User cannot login until link is visited

**Comment by shieldsb** [comment]
QA fail.  The link confirms the address, but does not log the user in automatically.  Instead, it takes you to the log in page.  

The email text is similar but not exact.  There is an additional statement in the email about pasting in the link if it does not work, which is not included in the text above.  Not sure how close we want it to be. Not sure I would fail the ticket based on the text.  Here's what I received. 
![image](https://user-images.githubusercontent.com/53542788/115078261-3b3baa80-9eb4-11eb-8397-abb4188c71f3.png)

**Comment by shieldsb** [comment]
QA pass.

**Comment by CGillen** [comment]
Slightly new email template:
```
Subject: Oregon Digital Account Verification

Body:
Hello!

We received a request to create an Oregon Digital account from [ add email address associated with the user’s account ].

Visit https://www.oregondigital.org to get started with curating, building and sharing your own private digital collections from the tens of thousands of freely available digital items held in Oregon Digital.

If you didn't request this, please ignore this email, or contact us at oregondigitalref@uoregon.edu

Thank you,
The Oregon Digital Team
```
@kmthorn and @petersec to create an example email and send to @CGillen that includes HTML styled branding for OD2.

**Comment by CGillen** [comment]
New QA:
- [ ] Create new user
- [ ] Receive email
- [ ] Email text is:
```
Subject: Oregon Digital Account Verification

Body:
Hello!

We received a request to create an Oregon Digital account from [ add email address associated with the user’s account ].

Visit https://www.oregondigital.org to get started with curating, building and sharing your own private digital collections from the tens of thousands of freely available digital items held in Oregon Digital.

If you didn't request this, please ignore this email, or contact us at oregondigitalref@uoregon.edu

Thank you,
The Oregon Digital Team
```

**Comment by shieldsb** [comment]
QA pass. Should we consider providing some type of message on screen stating that they will receive an email.  Now it just goes back to the homepage.  If I didn't have access to my email and get an almost immediate notification, I might think that it hadn't worked.

**Comment by jsimic** [comment]
Agree with Beth that there should be something indicating an email has been sent
