### ISSUE TITLE
New users are sent to the dashboard

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1541]
### Descriptive summary
New users should be redirected to the homepage or their previous page, not the dashboard unless they actually have access to it.

Creating a new user sent a non-institutional user to the dashboard

### Expected behavior
New users do not see the dashboard if they do not have dashboard access.

**Comment by CGillen** [comment]
QA:
- [ ] Register a new user with an email you have access to
  - I'm not 100% sure this works in Hyrax, but if you're out of emails you can try adding a `.` (period) into any part of a gmail address. eg: `corey.jgillen@gmail.com` is not the same in most systems as `coreyjgillen@gmail.com` but will go to the same gmail inbox.
- [ ] Follow the confirmation link
- [ ] You are pushed to the homepage, not the dashboard

**Comment by shieldsb** [comment]
QA pass.
