### ISSUE TITLE
Date range facet should display as though it was submitted with default values

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1542]
### Descriptive summary
![image](https://user-images.githubusercontent.com/11052958/109550986-d6073380-7a84-11eb-91d6-1d51b94eb078.png)
The default display for the date range facet is ugly and confusing. When a user launches a search, the facet should look more like it does when the default values are submitted:
![image](https://user-images.githubusercontent.com/11052958/109551149-0949c280-7a85-11eb-9fe3-e67d799b9354.png)

An easy way to accomplish this is submitting the facet by default. This behavior has already been accepted as a solution if we can not alter the display.

### Expected behavior
Date range facet displays histogram and an appropriate label for number of returned works even when the date facet has not been used yet.

### Related work
#1141

**Comment by CGillen** [comment]
QA:
- [ ] Visit search page
- [ ] Expand date facet
- [ ] See histogram is populated as second image above, not unpopulated like first image (`Unknown` tag is fine)
- [ ] Bonus: Visit advanced search page and the page doesn't crash

**Comment by shieldsb** [comment]
QA pass. Bonus achieved!
