### ISSUE TITLE
Social Media link preview title and image not pulled

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1546]
### Descriptive summary
https://developers.facebook.com/docs/sharing/webmasters/getting-started/basic-link/
Some meta tags need added to work show pages so social media pages know what to show users when a URL is published in a post.

Right now FB grabs the header image. Twitter doesn't even make an attempt.

### Expected behavior
FB & Twitter shows a thumbnail of the work when shared.
![image](https://user-images.githubusercontent.com/11052958/110372214-df534b80-8002-11eb-9dc7-9d574b84db29.png)
![image](https://user-images.githubusercontent.com/11052958/110372374-10338080-8003-11eb-8670-8a997567af62.png)

### Related work
https://developers.facebook.com/docs/sharing/webmasters/getting-started/basic-link/

### Accessibility Concerns
Are meta tags an a11y concern?

**Comment by lamtu1** [comment]
`UPDATE:` - Facebook has it automatically sizing for share link as mention here:
```Images that are at least 470×246 pixels will display as a rectangle with the title and description below. Images that are smaller than 470×246 pixels will display as a square with the title and description to the right.```
So this seems like Facebook does it atuomatically based on the image size and we can't force it into a `rectangle box` card link.

**Comment by sarahfish07** [comment]
![MicrosoftTeams-image (1)](https://github.com/OregonDigital/OD2/assets/114957715/87fd7dfd-a8e0-41bb-be1d-e3df898e479f)
![MicrosoftTeams-image](https://github.com/OregonDigital/OD2/assets/114957715/66265f3c-5e17-4dcc-8424-a6bd3387e03e)

**Comment by lamtu1** [comment]
@sarahfish07 Can I ask which work did you use to test this? If so, can you provide me the link to the work for me to test it out?

**Comment by sarahfish07** [comment]
I used the first work found under the first collection listed in featured collections... it's an OSU work. https://oregondigital.org/concern/images/3f462548s?fbclid=IwAR1eN3PbW_Su-Z1vY2Ff_No0TgVw1Kyj1dC0BWfs9XEsIDmt0Gj_9bCatE4

**Comment by lamtu1** [comment]
Thank you so much for this, I'm in the middle of testing different URL to pinpoint where it went wrong and testing this link would help out a lot.

**Comment by lamtu1** [comment]
Hi @sarahfish07, I tested that link you sent me and it looks like it is a weird case for that link. I was wondering if you could test the sharing functionality with a different works to see if this problem persist? I been testing out many other works and it seems to populate correctly but really weird on that one link. I wanted you to check to see if this affect other works on your end. That would be great! Thank you

**Comment by sarahfish07** [comment]
@lamtu1 
I tested two images:
UO: https://oregondigital.org/concern/images/1544bz56q
![Test2FB](https://github.com/OregonDigital/OD2/assets/114957715/3cec1c1b-2553-412b-bc78-7659ede37c9c)
![Test2X](https://github.com/OregonDigital/OD2/assets/114957715/a7219916-8b5e-43b7-9f32-79db549eade0)

OSU: https://oregondigital.org/concern/documents/fx71bd346
![Test3FB](https://github.com/OregonDigital/OD2/assets/114957715/5c7088f5-a972-4ca5-b1f0-a40a54b977cc)
![Test3X](https://github.com/OregonDigital/OD2/assets/114957715/5d3833fc-64bc-4915-9f7e-bccf4c32b485)

Thumbnail and metadata appear on 3 out of 4 shared posts.

**Comment by lamtu1** [comment]
I just check out the link and yeah some of them are a hit and miss but I inspect the element and they are pulling the meta-tag of each work and it is full data in there. I don't know if we would okay with this or continue to debug it still as it is affecting some works but not all of them.

**Comment by sarahfish07** [comment]
Test 4, image https://oregondigital.org/concern/images/df673f95n?locale=en
fb:
 ![image](https://github.com/OregonDigital/OD2/assets/114957715/f809f6ab-7ada-4a49-b746-3baef500927c)
x: 
![image](https://github.com/OregonDigital/OD2/assets/114957715/5c465aba-34c6-4e0a-8491-cbb947787da2)

test 5, complex object https://oregondigital.org/concern/generics/zk51w7958?locale=en
fb:
![image](https://github.com/OregonDigital/OD2/assets/114957715/f0350645-bff7-4193-884b-2a183959f80c)

x:
![test 5x](https://github.com/OregonDigital/OD2/assets/114957715/88db4133-44b6-47e1-bce5-ac24fc00861f)


test 6, text https://oregondigital.org/concern/documents/1544bv97b?locale=en
fb:
![test 6fb](https://github.com/OregonDigital/OD2/assets/114957715/f4a71621-852b-4864-9222-23fe0d9b4f7c)

x:
![test 6x](https://github.com/OregonDigital/OD2/assets/114957715/b898c6e5-bd2d-4770-9164-f9916f4d4e48)


5/6 posts successful.

**Comment by sarahfish07** [comment]
Success! Re-test 4 (fb).
![test 4fb2](https://github.com/OregonDigital/OD2/assets/114957715/241915a0-ccab-4c9a-a3d5-0f176b499ae2)
