### ISSUE TITLE
Rights Statement/Copyright metadata is not linked

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1548]
### Descriptive summary
`Rights` should be linked to the corresponding rightsstatements.org page in the show page metadata. Right now, the label above Universal Viewer is linked correctly, but the metadata only has plain text.

### Expected behavior
`Rights` metadata is linked to rightsstatements.org link the label above UV.

**Comment by CGillen** [comment]
QA:
- [ ] Visit work show page (existing is fine)
- [ ] Scroll to metadata tab
- [ ] Rights statements is linked to search
- [ ] (i) icon next to rights statement is linked to rightsstatement.org

**Comment by straleyb** [comment]
QA:
All linkable metadata should link to a search that works. Specifically rights statement, license, media.

**Comment by shieldsb** [comment]
QA pass.  However, not working as expected in search results and a new ticket will need to be created.
