### ISSUE TITLE
More citation formats

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1551]
### Descriptive summary
More citation formats are wanted: APA, MLA, Chicago, and Wiki
APA, MLA, and Chicago are covered by citation formatters by Hyrax: https://github.com/samvera/hyrax/tree/master/app/helpers/hyrax/citations_behaviors/formatters

Wiki will require a new formatter. The format is similar to as follows:
```
<ref name=NYPL>{{cite web | url=https://digitalcollections.nypl.org/items/510d47da-7329-a3d9-e040-e00a18064a99 | title= (still image) Phillis Wheatley, (1893) |author=Digital Collections, The New York Public Library |accessdate=March 1, 2021 |publisher=The New York Public Library, Astor, Lenox, and Tilden Foundations}}</ref>
```

### Expected behavior
The work show page, How to Cite tab, contains `APA`, `MLA`, `Chicago`, and `Wiki` citations

**Comment by straleyb** [comment]
QA: 
Visiting the show page for a work, displays the Wiki Citation in the layout described above.

**Comment by shieldsb** [comment]
QA fail.  Wiki citation is displaying URI for creator/author, publisher, etc. 
![image](https://user-images.githubusercontent.com/53542788/114740591-d854e280-9cfe-11eb-9b3c-76bd439539cb.png)

**Comment by straleyb** [comment]
QA:

All Citations should be on show page, displaying in the way hyrax is configured to display them.

**Comment by shieldsb** [comment]
QA pass.

**Comment by kmthorn** [comment]
MLA citation: Collection Name, Institution. "Item Title" _Digital Repository Name_. Date Created. PID

APA citation: Collection Name, Institution. (Date Created). _Item Title_ Retrieved from PID

Chicago citation: Collection Name, Institution. "Item Title" Digital Repository Name. Accessed Date Of. PID

Wikipedia citation: <ref name=NYPL>{{cite web | url=PID | title= (WORK TYPE) ITEM TITLE. (DATE CREATED)|author=CREATOR |accessdate=CURRENT DATE |publisher=Digital REPOSITORY NAME}}</ref>

**Comment by shieldsb** [comment]
@kmthorn @petersec This one is back to you for review.

**Comment by straleyb** [comment]
This should pass after #2093 is merged. Looks like the only update needed were the two spaces.

**Comment by kmthorn** [comment]
This looks good. Ticket is ready to be closed.
