### ISSUE TITLE
Slow load times for explore collections page.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1552]
### Descriptive summary

This problem could be rendered invalid once we make a decision on whether or not we want to go with the normal search vs the current way explore collections is rendered.

Otherwise, if we keep explore collections the way it is, we have to make the search for specific institutions faster to know whether or not a user is locked out based on account info and institution lock on a collection.

This ticket is related to comments on #1487

**Comment by CGillen** [comment]
Each tab (All/OSU/UO/Saved) should be a different controller action/route. This will make the tabs cause a page load, and that's fine.
Converting the search/results/display of collections to use blacklight & solr should also drastically improve performance. This was the method decided on in wireframe discussion with Azle, Julia, and POSM

**Comment by CGillen** [comment]
- [ ] Visit explore collections
- [ ] Page loads < 5 seconds on fast connection (>~25mbps)

**Comment by shieldsb** [comment]
QA pass.
