### ISSUE TITLE
[MVP QA] Types and models (Image, Document, etc.)

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1567]
### Descriptive summary

Structural metadata defines relationships among files

### Expected behavior

Verify all metadata and badges are visible and properly appearing on

- [x] Work show pages
- [x] Search results (list)
- [x] Search results (grid)
- [x] Collection landing pages

### Related work

#21, #27, #45, #66, #71, #87, #88, #107, #108, #109, #110, #111, #146, #211, #234, #409, #452, #996, #999, #1025, #1029, #1041, #1174, #1246, #1480

### Accessibility Concerns

Badges and metadata need to be recognized by screen readers

**Comment by sseymore** [comment]
Waiting to QA this until this is fixed https://github.com/OregonDigital/OD2/issues/1569

**Comment by straleyb** [comment]
This should be ready for QA now since both #1569 and #1574

**Comment by jsimic** [comment]
Will QA after staging refresh (WC16)

**Comment by jsimic** [comment]
QA Fail for Work show page metadata. See #1644 

As per new wireframes, Search results should include Title, Description, Date, copyright icon/text, type icon/text, cpd icon/# of items, is Part of. Will QA after wireframe implementation

Will QA Collection landing page after new wireframe is implemented that includes more metadata than original.

**Comment by jsimic** [comment]
QA pass
