### ISSUE TITLE
[MVP QA] Thumbnails

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1568]
### Descriptive summary

Features needed: Small, lightweight derivative of content for quick-loading and viewing.

### Expected behavior

Confirm derived thumbnail and icons correctly appear on 
- [ ] Compound object work show pages for parent and children
- [x] Simple object work show page
- [ ] Search results (list)
- [ ] Search results (grid)
- [ ] Explore collections (grid)
- [ ] Collection landing
- [ ] Homepage

### Related work

#29, #30, #554, #746, #905, #938, #1000, #1147, #1149, #1376, #1377, #1534, #1536, #1547

### Accessibility Concerns

Alt text should be accessible in screen readers

**Comment by CGillen** [comment]
- Compound Object
  - Blurry
  - Misaligned & too close
  - Needs consistent size
  - Thumbnail is not linked
  - Generic folded corner thumbnail is acceptable for parent icon
- QA to continue next week (4/12)

**Comment by kmthorn** [comment]
QA Fail

### Compound Object show item page [https://staging.oregondigital.org/concern/generics/df72jn73h#content](https://staging.oregondigital.org/concern/generics/df72jn73h#content)
[https://staging.oregondigital.org/concern/generics/df727084j#content](https://staging.oregondigital.org/concern/generics/df727084j#content)
- Still Blurry
- Still Misaligned & too close
- Not sure about "Needs consistent size (search results size is good)"
- Thumbnails **are** linked
- Not sure about the "generic folded corner thumbnail is acceptable for parent icon Folded corner icon should match search results cube icon"

### Search list

- This is still true. "Collections are not aligned."
- Some yearbooks did not generate proper thumbnails: https://staging.oregondigital.org/catalog?locale=en&per_page=100&q%5B%5D=yearbook&search_field=all_fields
![CleanShot 2022-03-18 at 14 47 54](https://user-images.githubusercontent.com/36867009/159087392-28ab7d1c-de76-4089-bbb9-6231887ff4e2.png)
- This is true "Blue cube for compound object is acceptable"
- Border around thumbnails preferred
![CleanShot 2022-03-18 at 14 50 08](https://user-images.githubusercontent.com/36867009/159087831-d9caee83-6ac2-40cd-ac84-529c05d071bc.png)

### Search grid

- This is still true. "Fuzzy thumbnails (double the resolution to ~240px on smallest side)"
- This is true. "Visual inconsistency with sizing in the rows. Thumbnails should be consistent size"
![CleanShot 2022-03-18 at 14 52 00](https://user-images.githubusercontent.com/36867009/159088435-77c1978b-9e5a-4735-b5b9-924ab6383cb2.png)

### Explore Collections
- Is this for a curator (not user) to be able to do? "Cube thumbnails should not be displayed. User can pick thumbnails to display or OD2 picks the first thumbnail."

## Homepage
- Presuming that this needs to match MAC wireframes. "Featured collection thumbnails are too small"
![CleanShot 2022-03-18 at 15 10 26](https://user-images.githubusercontent.com/36867009/159091340-2a1a493a-63a3-4d46-8bda-73c57ec0d79e.png)
- Mobile sizes should have a space if the images will stack
![CleanShot 2022-03-18 at 15 10 26](https://user-images.githubusercontent.com/36867009/159091439-2666822f-a342-4897-bf7d-14e50957ab62.png)

**Comment by azle** [comment]
Explore Collection Grid, is blown up. The thumbnail images are gigantic. See screen snap. Using Firefox on a Mac.
 
<img width="1028" alt="Screen Shot 2022-06-13 at 1 23 07 PM" src="https://user-images.githubusercontent.com/8353860/173438845-385532f0-bc4f-4ba1-b436-78f9bebb10da.png">
