### ISSUE TITLE
[MVP QA] Controlled fields show URIs alongside labels

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1569]
### Descriptive summary

Link for users to find external authority records.

### Expected behavior

- [ ] Confirm link icons appear for all descriptive metadata with controlled vocabularies
- [ ] Confirm that linking function sends user to the correct authority record

### Related work

#35, #36, #42, #45, #160, #162, #163, #271, #313, #316, #317, #318, #319, #335, #364, #370, #376, #377, #378, #379, #380, #381, #382, #383, #384, #385, #386, #391, #408, #421, #429, #437, #462, #469, #490, #570, #963, #991, #1014, #1020, #1124, #1198, #1297, #1325, #1342, #1372, #1406

**Comment by sseymore** [comment]
QA Fail:

Location: Not appearing at all
Ranger District: Not appearing at all
TGN: Not appearing at all
Water Basin: Not appearing at all
Place of Production: Not appearing at all
Place of Publication: Not appearing at all
Worktype: No label, no icon, but resolving
Language: No link or icon
License: No label, no icon, but resolving
Format: No label, no icon, but resolving
Rights:  No link or icon
Type/Media: No link or icon
Set: Not appearing at all
OAI Set: Did not QA

**Comment by straleyb** [comment]
- [ ] location
- [ ] ranger district
- [ ] tgn
- [ ] water basin
- [ ] place of production
- [ ] place of publication
- [ ] work type
- [ ] language
- [ ] license
- [ ] format
- [ ] rights
- [ ] media/type
- [ ] set

**Comment by sseymore** [comment]
@straleyb asking a metadata team question about this later today--- will get back to you soon.

**Comment by sseymore** [comment]
Forgot to update. Waiting until after staging refresh to complete QA of this.

**Comment by sseymore** [comment]
OD1 Set/OD2 Hyrax collection is supposed to be visible (as indicated in the MAP) on Works. Why isn't the collection information anywhere on Works? To discuss in WC17.

**Comment by sseymore** [comment]
Same comment as above that was not resolved with staging refresh. @straleyb @CGillen Set/Hyrax collection is work show page visible (see line 183 in the MAP).

**Comment by straleyb** [comment]
QA:
- [ ] When a work belongs to a collection, it shows that collections id as a link to the collection on the work show page.

**Comment by jsimic** [comment]
@straleyb  QA fail. Set label is not shown, only system identifier?

<img width="948" alt="Screen Shot 2021-06-09 at 9 24 01 AM" src="https://user-images.githubusercontent.com/6344086/121392852-9ca45680-c904-11eb-97b6-cf592a0d2727.png">

**Comment by sseymore** [comment]
Also, would like it to be "Collection" and not "Set." Sorry, we wanted to use the Hyrax default settings and kept Set in the MAP, incorrectly. I will update the MAP now. Thanks!

**Comment by jsimic** [comment]
@straleyb  QA Fail:
Access Restrictions is showing as string, not as a controlled vocab as per MAP
Collection is still showing system id, not label
Is Part Of is still showing admin set label

**Comment by CGillen** [comment]
@jsimic @sseymore for MVP re-QA

**Comment by jsimic** [comment]
Numbers should start at 1 not 0
Can we add alternating gray and white rows for easier reading as per [wireframe](https://drive.google.com/file/d/1PqrjgnMQ93jAh0vdkOeexigDHLR0DWf-/view?usp=sharing)?

**Comment by jsimic** [comment]
QA pass
