### ISSUE TITLE
[MVP QA fail] Controlled fields show URIs alongside labels

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1574]
### Descriptive summary

Not all LOD URIs are working - not appearing although in the assets' form, not resolving to display the label, not linking or showing the external authority icon.

### Expected behavior

These URIs should appear and resolve to correct labels. 

### Related work

https://github.com/OregonDigital/OD2/issues/1569

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by sseymore** [comment]
#1569 is moved back to Ready; will QA this when that passes

**Comment by sseymore** [comment]
#1569 is not corrected so not sure why this is in QA. Moving back.

**Comment by jsimic** [comment]
QA Fail. See original ticket #1569  for details:
Access Restrictions is showing as string, not as a controlled vocab as per MAP
Collection is still showing system id, not label
Is Part Of is still showing admin set label

**Comment by jsimic** [comment]
Associated tickets closed
