### ISSUE TITLE
Add Has Finding Aid to Collection

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1600]
### Descriptive summary

Add Has Finding Aid to Collection. The metadata team's MAP review indicated that the Has Finding Aid field is also useful on Collection, not just Work.

### Expected behavior

Has Finding Aid should appear on the ingest form and work show page.

### Related work

https://github.com/OregonDigital/OD2/issues/1307

### Accessibility Concerns

N/A

**Comment by CGillen** [comment]
QA:
- [ ] Open new collection form
- [ ] Find `Finding Aid` metadata and fill in
- [ ] Save collection
- [ ] Find `Finding Aid` on display page

**Comment by sseymore** [comment]
QA fail.

The data is saving in the form, but not visible on the landing page. Let me know if I'm doing something wrong. 

https://staging.oregondigital.org/collections/t722h891g?locale=en

**Comment by sseymore** [comment]
QA pass! https://staging.oregondigital.org/collections/1831cj962?locale=en
