### ISSUE TITLE
Predicate URI changes in MAP

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1602]
### Descriptive summary

The metadata team found some bad URIs and corrected them in column C in the MAP.

Updated URIs in MAP:

Inscription
Cultural Context
State/Edition
Style/Period
GPS Latitude
GPS Longitude
Material
Measurements
Technique
Resolution
Has Finding Aid
Admin set-- this was pointing to the incorrect OD1 mapping, but should just be Hyrax Collection 
Current Repository ID
Full Size Download Allowed

### Expected behavior

These URIs will resolve/map correctly.

### Related work

https://github.com/OregonDigital/OD2/issues/1307

### Accessibility Concerns

N/A

**Comment by CGillen** [comment]
I wrote a pretty naive script that scrapes the MAP and generates our property definitions.

Future friends, you can find this in `tmp/scripts/map_parse` and all you gotta do is download a copy of the MAP as a csv, rename it to map.csv, drop it in the same directory as parse.py and run `python parse.py`. It generates 5 files that you can just copy+paste into the various metadata concern files.

**Comment by sseymore** [comment]
@CGillen WorkType has been updated in the MAP with another predicate URI.
