### ISSUE TITLE
Add issue type: Copyright Question

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1608]
### Descriptive summary
With the contact form on the work show page, users should be able to find the form and submit a question about using the work.

### Expected behavior
`Copyright Question` appears as a select-able issue type.

### Related work
#1550 

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by CGillen** [comment]
Passed by #1649

**Comment by shieldsb** [comment]
QA pass.
