### ISSUE TITLE
Double thumbnail resolution to 240px

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1619]
### Descriptive summary
120px on the smallest side is restricting and makes larger thumbnails blurry. 240px should be large enough to use in search results grid view, which should be our largest size, and keep us under ~2mb thumbnail sizes.

### Expected behavior
https://github.com/OregonDigital/OD2/blob/master/app/services/oregon_digital/file_set_derivatives_service.rb#L81 is set to `240x240>` so that thumbnails are limited to 240px on the longest side.

**Comment by jsimic** [comment]
@CGillen How will this effect the number of thumbs on the grid view? And per page count? 240px is generally considered a vignette, not a thumbnail.

**Comment by CGillen** [comment]
@jsimic We can always downsize the thumbnails when we go to display things like the list view, but currently the grid/masonry/gallery views are displaying 4 thumbs across at 245px with only have a source resolution of 120px, so everything is super blurry. As it is now we would still need to go up to 190px if we wanted that to be up to 6 across.

We can always have as many results per page as we want.

**Comment by CGillen** [comment]
Resolution tripled to 480px - #2242
