### ISSUE TITLE
Hide non-populated Collections from public during user testing

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1633]
### Descriptive summary

Collections with no public works appear as empty and can be confusing for user testing.
Workaround is to temporarily mark Collections -> Discovery as Private.

### Expected behavior

Collections with no public works should not be visible to public users.

**Comment by CGillen** [comment]
From standup 12/2/22: Check if there's any bugs in making collections public=>private=>public or any combo with UO/OSU. If it looks like collections can freely change visibility with NO issues, this ticket can close w/o code change

**Comment by CGillen** [comment]
Changing from public to inst to private to public to private to public to inst to ... doesn't seem to cause any issues
https://staging.oregondigital.org/collections/pub-priv-pub-2?locale=en
