### ISSUE TITLE
Check linked values on search results page

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1635]
### Descriptive summary

links from the search results page aren't linking to the proper search. These probably have to be updated to render like the faceted links like on the show page. Make sure that the values linked on the search results page link to the proper search.

**Comment by straleyb** [comment]
QA: Configured links on search should go to right place.
- [ ] rights should go to rightsstatements.org
- [ ] creator should do a creator search
- [ ] media type (resource type) should do a a media type search.

**Comment by shieldsb** [comment]
POSM would like the rights on the search results to do a rights search, not link to rightsstatement.org.  

The rights should link out to the statement when selecting the i icon in the work show page and at the top of the work show page under the print, download, and save buttons.

**Comment by shieldsb** [comment]
QA pass.
