### ISSUE TITLE
problem when fileset is created with od1 asset id

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#1642]
Evidently, Hyrax allowed me to migrate an asset with the pid "rb68xb881" even though about an hour earlier, it had saved a fileset with that id. No errors were thrown, and the migrator was somehow able to finish and ended in a "success" state.  When the asset did not appear on staging however, I finally did ActiveFedora::Base.find("rb68xb881") and discovered that that id belongs to a fileset.
There are at least two problems here: why does Fedora not complain when we try to create a work with an id that has already been assigned?
Second, for tracking and verification, we are relying on the od1 pid == od2 pid. So we will either need to rethink that assumption or figure out a way to prevent the minter from using an od1 pid.

**Comment by lsat12357** [comment]
D, [2021-04-16T01:30:46.850341 #1] DEBUG -- : [ActiveJob] [AttachFilesToWorkJob] [7ef373fc-5b50-4d46-815a-6a0bf4e6f54f]   [1m [36mJobIoWrapper Create (3.1ms) [0m  [1m [32mINSERT INTO "job_io_wrappers" ("user_id", "uploaded_file_id", "file_set_id", "path", "relation", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id" [0m  [["user_id", 1],["uploaded_file_id", 592], ["file_set_id", "rb68xb881"], ["path", "/data/tmp/shared/uploads/hyrax/uploaded_file/file/592/fx71bs53p_content.pdf"], ["relation", "original_file"], ["created_at", "2021-04-16 01:30:46.846568"], ["updated_at", "2021-04-
16 01:30:46.846568"]]


I, [2021-04-16T02:29:52.217086 #1]  INFO -- : [ActiveJob] [Hyrax::Migrator::Jobs::MigrateWorkJob] [ee1bcaac-e2b4-48a1-bd4d-2fb0ebd86b7b] Performing Hyrax::Migrator::Jobs::MigrateWorkJob (Job ID: ee1bcaac-e2b4-48a1-bd4d-2fb0ebd86b7b) from Sidekiq(hyrax_migrator) with arguments: {:pid=>"rb68xb881", :file_path=>"/od2_migration/osu-yearbooks/rb68xb881"}
I, [2021-04-16T02:29:52.217180 #1]  INFO -- : [ActiveJob] [Hyrax::Migrator::Jobs::MigrateWorkJob] [ee1bcaac-e2b4-48a1-bd4d-2fb0ebd86b7b] Starting main migration job rb68xb881

**Comment by lsat12357** [comment]
it looks like we can create the FileSet with a predetermined id; wicker suggested an "f" prefix with the work pid.
I just tested this (by tweaking the FileSet.create call in AttachFilesToWork and it seemed to go ok

**Comment by lsat12357** [comment]
For QA: I just migrated colver-family children, but any new work will suffice; the fileset id (as seen in the url for the file page) should have an id that is the work pid but prefixed with f0 (assumes that there is only one file attached to the work, otherwise the second digit will be the 0-based index of that fileset)

**Comment by wickr** [comment]
QA pass
FileSet has pid set with `f0` in front:
https://staging.oregondigital.org/concern/parent/df7280362/file_sets/f0df7280362
