### ISSUE TITLE
[MVP QA Fail] Configured facets not showing on work show page

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1643]
### Descriptive summary

Using "Test Collection for Metadeities" collection, enabled and ordered

Work Type (core)
Copyright Combined (core)
Media (core), Composer (controlled)
Mode of Issuance (controlled)
Style / Period (controlled)
Exhibit (string)
Keyword (string)
Archival Folder Number (string)

Only the core fields appeared on the collection landing page search. The three did appear in the specified order

### Expected behavior

All enabled facets should show on collection landing page in specified order

### Related work

#1371

**Comment by sseymore** [comment]
QA pass with #1715

https://staging.oregondigital.org/collections/9k41zd523?locale=en
