### ISSUE TITLE
UV full text searching should use text-stemming or some kind of fuzzy search

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1645]
### Descriptive summary
When searching for `brothers` I would expect to find hits for `brother`. Right now our search algorithm is very basic, full text matching searching each word individually. We should look up other IIIF search implementations or see if we can leverage the power of Solr to help us get fuzzier results.

### Expected behavior
Searching an OCRd document in UV returns stemmed text results. eg: `brothers` => `brother`

### Related work
#1110

**Comment by CGillen** [comment]
QA:
- [ ] Ingest new PDF with already searchable text (searchable from outside OD2) The bigger the better.
- [ ] Wait for ingest to finish and UV displays
- [ ] Search for a single word that shows in the PDF - Use a perfect match
  - [ ] Instances of the word are found
- [ ] Search for a word that is not stemmed (playing vs play, bouncing vs bounce)
   - [ ] Instances of both (and more) words are found. (playing finds play, playful, playing, played, etc)
- [ ] NOT A FAILURE: Search for a short phrase and let me know what kind of weird behavior you see

**Comment by shieldsb** [comment]
QA pass.  Discovered additional work for ticket #1110 - when browsing search results after a few instances it freezes.  The number of instances it says it located doesn't match the actual number found in document or the number of pages the search term is found on.
