### ISSUE TITLE
Universal Viewer page labels should be simple numbers

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1646]
### Descriptive summary
Our UV current displays page one as `#{fs_id}_context.{extension}` and the rest of the pages as `page #{index}`. We want our pages to display similar to this UV instance: https://d.lib.ncsu.edu/collections/catalog/nubian-message-1992-11-30

Bracketed or plain numbers for every thumbnail.

Further improvements may be made as we explore the IIIF standard. The top box for page number would preferably work with user input, the bottom-left indicator would preferably be different (simpler) from the thumbnail titles, and the thumbnail titles could be more complex like `Page #...`

### Expected behavior
UV Page number is at least consistent and readable such as all three spots that page numbers are found do not change from page-to-page.

### Accessibility Concerns
Page titles are readable from SR next to the thumbnail. They should be understandable.

**Comment by CGillen** [comment]
Similar to #1426

**Comment by shieldsb** [comment]
QA pass.
