### ISSUE TITLE
Contact us options

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1649]
### Descriptive summary
The following `contact us` options are not needed:
- Depositing content
- Making changes to my content

The following options should be added to `contact us`:
- Using this/an item for something (copyright and permissions)

The options should be in alphabetical order with `General inquiry or request` at the bottom

On submit, the page should reload to the existing page, not the homepage.

The following message should be sent to the user as a confirmation that their message has been sent:
```
Subject: Oregon Digital Contact Request - [ Title of the Item ] 
Body:
We received a question from you about [TITLE AND ACTIVE LINK TO THE ITEM ].

[QUESTION TYPE]
[THE USER’S QUESTION]

Someone from the Oregon Digital Team will reach out to your with an answer within XX business days.

If you didn’t make this request, please ignore this email, or contact us at oregondigital@uoregon.edu

Thank you,
The Oregon Digital Team
```

### Expected behavior
See above

### Related work
#1590 #1550

**Comment by CGillen** [comment]
QA:
- [ ] The following issue types are the only ones available:
  - Browsing and searching
  - Reporting a problem
  - Using this/an item for something (copyright and permissions)
  - General inquiry or request
- [ ] Submission from `/contact` and from a work show page should redirect back to the page you submitted the form from
- [ ] The above email is sent out to the submitter

**Comment by shieldsb** [comment]
QA pass.
