### ISSUE TITLE
Search box placeholder text

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1650]
### Descriptive summary
The search box text does not lead users to the correct assumptions for what each box will do. The header and homepage search boxes initiate a new search. The search page search box, near facets, searches within the current results.

### Expected behavior
Header search box placeholder text says: `Search Oregon Digital`

The search page search box says: `Search within the results`

**Comment by shieldsb** [comment]
QA pass.  Though with screen resolution at 125% or higher it cuts off the text in the search page search box. 
![image](https://user-images.githubusercontent.com/53542788/122969111-23aff080-d341-11eb-8d3f-a957351e2081.png)
