### ISSUE TITLE
Sort options for catalog search

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1652]
### Descriptive summary
We want feature parity for sort options between OD1 and OD2. The sort options in OD1 and their mapping to OD2 metadata is:
```
Relevance - Existing relevance
Title A-Z - :title
Title Z-A - :title
Date Descending - :date
Date Ascending - :date
Recently Added - :date_uploaded
```

Edit:
the use of `title` for title sort should be a new solr field of the type `*_ssort`. This field type lowercases all characters and replaces non-latin characters with a reasonable latin equivelant. eg: `æ => ae`. This may hold the secret to fixing facet sorting too

### Expected behavior
The above sort options appear on catalog search and sort by their accompanied metadata field.

**Comment by CGillen** [comment]
@jsimic @sseymore 
Which date field would you like to sort on? It can only be one value. First value in `:date`? Oldest value of all date fields? Newest? Something else?

**Comment by sseymore** [comment]
@jsimic and I think oldest date is best.

**Comment by shieldsb** [comment]
I'm getting title sort on the front end of staging @sseymore 
![image](https://user-images.githubusercontent.com/53542788/183477605-ae04bf73-3d34-4a54-a903-3795ce88775c.png)

**Comment by sseymore** [comment]
Yeah, I was on prod. QA pass.
