### ISSUE TITLE
[MVP QA] Review Queue UI

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1654]
### Descriptive summary

Create a UI in the Dashboard for Review Submissions that mimics the behavior of OD1's review queue, i.e. works appear in a search-like interface with all facets and a search box limited to works needing review, metadata that would be in a front-end search visible, and a button to review a single work.

### Expected behavior

- [x] Go to Dashboard > Tasks > Review Submissions 
- [x] Use facets to wrangle a subgroup of works 
- [x] Confirm subgroup is accurate
- 
- [x] Use the search box to find a subgroup of works
- [x] Confirm subgroup is accurate
- [x] Remove the search term from the search 
- 
- [x] Approve a single work using the Approve Button
- [x] Check work showpage to confirm the work has been reviewed and is no longer under review
- 
- [x]  Confirm work metadata showing in review queue matches public search metadata

### Related work

#22, #24, #25, #26, #48, #230, #276, #443, #444, #445, #761, #792, #812, #816, #1343, #1349, #1369, #1430, #1431, #1460, #1562

**Comment by jsimic** [comment]
See #1742 for filter search timeout fail

**Comment by sseymore** [comment]
#1431 and #1562 are still open.

**Comment by jsimic** [comment]
#1562 is still open, but covered in another ticket and not technically part of the MVP ask. Closing ticket
