### ISSUE TITLE
Re-expose file manager and fileset index page for admin users

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1655]
### Descriptive summary
Filesets are important for reviewers, depositors, collection curators, and admins. Anybody that should have elevated permissions (not a content consumer) should be able to easily see and access fileset information from the work show page.
Azle has completed a wireframe for the work show page to expose the filesets, the fileset index page does not need a wireframe since it is admin-only. It should however have all applicable metadata, including that from #1069 

### Expected behavior
The file manager from this wireframe is implemented: https://drive.google.com/drive/u/1/folders/1nSugRmg-TvlVO9CJQ6fBdgy_F1tTunB-
The file set index page exists and displays all fileset metadata, including #1069 

### Related work
#1069 defined extra fileset metadata
#1575 added characterization metadata to the fileset

### Accessibility Concerns
The fileset index page may not be wireframed or accessible to the public, but still must meet accessibility guidelines.

**Comment by CGillen** [comment]
QA:
- [ ] Create a new work with attached files
- [ ] Work ingests & dumps you to the work show page
- [ ] Refresh page after ~5 minutes
- [ ] As an admin, collection curator, or depositor, find list of files at bottom of show page
- [ ] A file manager button appears in-line with the `Works and Files` header
- [ ] Each file can be visited as a file set show page
- [ ] The file set show page displays extra metadata in the `characterization` field.

I have personally seen all 45 lines of metadata show up, though I'm not sure how well `FITS` will actually populate those fields. I suggest metadata QA's the characterization fields against the MAP by creating special files with exif (or what ever relevant file metadata) data that matches

**Comment by sseymore** [comment]
@CGillen Same problem as #1334 -- I can't attach a file to a work on staging right now.

https://staging.oregondigital.org/concern/images/m613mx60p?locale=en

**Comment by sseymore** [comment]
QA pass. https://staging.oregondigital.org/concern/file_sets/qj72p7231?locale=en

Metadata will investigate the characterization field format/mappings and document any decisions in a separate ticket.
