### ISSUE TITLE
Change sidekiq retry count to 3

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1659]
### Descriptive summary

Sidekiq retries jobs that don't succeed. Anything beyond 3 seems overkill, especially for derivatives jobs that either timeout or have a config error, and won't succeed on subsequent tries. If a system outage caused job failures, we can always restart later and intervene manually if needed.

### Expected behavior

Sidekiq jobs are retried up to 3 times.

**Comment by decimalator** [comment]
https://github.com/mperham/sidekiq/wiki/Error-Handling

**Comment by decimalator** [comment]
I don't know if we can configure it per-queue but we can adjust the retry limit very easily globally

there is also a "death handler" we can configure that gets called when a job has exhausted all of its retries. that would be a great place to issue a Honeycomb event and log all of the relevant metadata to guide fixing the job or whatever bug that gets triggered

https://github.com/mperham/sidekiq/wiki/Error-Handling#death-notification

**Comment by decimalator** [comment]
https://github.com/OregonDigital/OD2/commit/cdbea1f562c11a29e3e71eec24b7e0194d1e6d6c

adds a `:max_retries` config with a default of 3 that takes its value from a new SIDEKIQ_RETRY_LIMIT environment variable

Updated the `workers` deployment to add a `SIDEKIQ_RETRY_LIMIT` environment key with value `3`

**Comment by decimalator** [comment]
👏

<img width="647" alt="Screen Shot 2021-05-26 at 5 57 52 PM" src="https://user-images.githubusercontent.com/1882223/119749523-1c81e980-be4c-11eb-8bb6-1ce61c0ac92b.png">

<img width="605" alt="Screen Shot 2021-05-26 at 6 06 03 PM" src="https://user-images.githubusercontent.com/1882223/119749957-13dde300-be4d-11eb-8f24-cdf1e829aef1.png">

**Comment by wickr** [comment]
Fixed with #1675
