### ISSUE TITLE
Migration QA Checklist

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#168]
### Descriptive summary

Let's use this ticket to collect our thoughts and priority on each of the validations that should be checked during migration.

- Work completed migration
- Work includes all original files from the exported BAG
- Work visibility / access matches what was originally set
- Metadata fields were successfully crosswalked

**Comment by revgum** [comment]
@vantuyls @wickr Please add your thoughts

**Comment by vantuyls** [comment]
i'm interested to hear more about how these checks can happen? i think these are all the right things to be thinking about.

**Comment by raybrarian** [comment]
@luisgreg99 - doing issue review and wanted to let you know this is here. If this is covered in other tickets, you could close this. This should also be in our documentation - I think under acceptance criteria for the migration.
