### ISSUE TITLE
some models using isPartOf for relationship to AdminSet predicate

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#1688]
In spite of the work done regarding #357
Image Document and Generic all use dc/terms/isPartOf as the predicate in the belongs_to relationship between the model and admin set
this appears to be set in the model itself. Confusingly, Video and Audio correctly use ons:primarySet

As wickr pointed this out https://github.com/samvera/active_fedora/issues/1296, it appears that _order_ in the Hyrax.config matters. Since Hyrax also sets the config.admin_set_predicate ||= ::RDF::Vocab::DC.isPartOf, is it possible that at the moment a given model is loaded, if our admin_set_predicate instruction has not been read yet, it uses isPartOf?
One workaround that appears to be working is to override models/concerns/hyrax/in_admin_set.rb and force it use primarySet rather than Hyrax.config.admin_set_predicate.

**Comment by CGillen** [comment]
@lsat12357 for QA

**Comment by lsat12357** [comment]
sorry, I missed the request for QA. Retroactively confirming that df71tv773 on production correctly uses primarySet with the admin set.
