### ISSUE TITLE
Save Work/Visibility box changes

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1695]
### Descriptive summary

Metadeities has changes to the Save Work/Visibility box discovered during QA of the ingest form Table of Contents, to reduce its footprint in the sidebar. See #1202. From top to bottom:

- Hide Save Work header 
- Visibility settings: Move explanatory text to the same line as the label and reduce the font size of the explanations
- Deposit Agreement: Reduce font so checkbox and both lines of text fit on one line

### Expected behavior

Save Work/Visibility box is reduced in size to allow for visibility of ToC without the need to scroll to the bottom of the form when viewing on a small (laptop) screen or if the user has increased the font size for readability. 

### Related work

#1202

**Comment by straleyb** [comment]
QA:
@jsimic Can check this on her screen and see if these changes are sufficient. Im concerned going down in font sizes might be an accessibility issue so id like to take this one step by step with small changes.

**Comment by jsimic** [comment]
@straleyb No change from before. I still have to scroll down to the bottom of the form before the ToC is visible. It also does not appear that any of the bullet points above were implemented

**Comment by jsimic** [comment]
ToC is now visible on a 1260x1600 laptop screen
