### ISSUE TITLE
Universal Viewer search box needs to work well with search phrases

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1698]
### Descriptive summary
#1645 and #1697 made single search terms through UniversalViewer use text stemming and stem matching to do full-text searching. Stemming one word and searching is easy.

We now need to find a reasonable stem and search strategy for multiple terms.
We could change these methods to match the first word in the query then start doing a look ahead to match the whole thing: https://github.com/OregonDigital/OD2/blob/master/app/models/concerns/blacklight_iiif_search/annotation_behavior.rb#L50-L78

### Expected behavior
Phrase searches in UniversalViewer return highlights/hits for the whole phrase next to each other.

### Related work
#1645 
#1697

**Comment by CGillen** [comment]
Most version of UV do not do this. Kick to POSM review:

- When searching multiple words in UV, does the whole phrase need to be found?
  - search "Your red ball" and get hits: I like "your" green "ball." I wish it was "red" though. <- ticket
  - or search "Your green ball" and get hits: I like "your green ball." I wish it was red though. <- existing

**Comment by jsimic** [comment]
@CGillen POSM is not clear what this means and would like some more examples

**Comment by CGillen** [comment]
We'd prefer when searching with no quotes to search each word individually.
When quotes are used around a phrase, we'd like that whole phrase to be found.

**Comment by shieldsb** [comment]
QA pass.
