### ISSUE TITLE
New Collection creation should allow setting of ID value

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1699]
### Descriptive summary

Creating a new Digital Collection should allow the creator to specify the ID value. We've created all existing collections manually with specified pids, and don't want to start using opaque IDs. These are very visible parts of the URL for linked and advertised collections. Examples: `or-latino-herit` and `orange-owl`

Since this is already supported from the console when creating a collection, this should just require the form update and attribute handling, it shouldn't need much new code to support. 

### Expected behavior

ID value should be required, validated and restricted to only: `a-z`, `0-9`, `-` and `_`.

This should also be allowed when creating 'OAI Set' collection types.
Metadata Team was thinking not for User Collections though, this box can stay hidden.

### Accessibility Concerns

n/a

**Comment by CGillen** [comment]
Remove collection ID from edit page, leave on creation page

**Comment by sseymore** [comment]
@wickr Testing on staging. I don't see on the creation form where to input/edit the collection ID. Can you assist?

**Comment by wickr** [comment]
@sseymore the initial work for this got reverted back so it's not ready for QA. https://github.com/OregonDigital/OD2/pull/2495

**Comment by jsimic** [comment]
QA pass. I was able to create a new digital collection with a new id through the form and save it on staging and production. I was not able to edit the id. The id was invalidated when I used characters outside the criteria above. The messaging was "we're sorry but something went wrong" so we might think about backend messaging at a later time.
