### ISSUE TITLE
Raw span tags in dashboard filter selection popup

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1701]
### Descriptive summary

Still seeing raw `</span>` tags in some filter selection popups, from the dashboard. 

![image](https://user-images.githubusercontent.com/2293544/122113110-87cd3480-cdd6-11eb-8c46-54d2f47ed1b7.png)

Seems to affect any filter with several options, with the 'more' link active.

### Expected behavior
1. Modal for facet selection doesn't have HTML tags as text

### Steps to Reproduce

1. Visit https://staging.oregondigital.org/dashboard/works?locale=en
2. Select filter for RESOURCE TYPE SIM
3. Click 'more' link
4. Modal popup has span tags at bottom

### Related work

I feel like this was fixed for the public search interface, but I was unable to find an issue or PR.

### Accessibility Concerns

N/A - removing tags as text will help

**Comment by CGillen** [comment]
Oops, I was wrong, not done.
