### ISSUE TITLE
Advanced search filters only show top 5 populated values

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1702]
### Descriptive summary
In advanced search, each filter only shows the top 5 values. We should be able to pop-up the same modal that regular search has that shows all the values, sortable A-Z and Numerical.

### Expected behavior
Advanced Search filters can select facetable values other than that top 5 hits.

**Comment by jsimic** [comment]
Though not ideal, the long list of available terms does show when a filter field is clicked. Future work on the Advanced Search will bring the filters in line with the search results filters. However, I cannot confirm that all terms are present as the filters elsewhere on staging have disappeared.

**Comment by jsimic** [comment]
QA pass. The list in the Advanced Search drop down matches the list in the search results facet. I note, however,  that the facet modal is sorting things weird, but the sidebar facet appears to be correct. This does not change the QA pass and is detailed in #2219 

The top five on the search results page facet for language puts Abkhazian in the 5th spot. This is correct, with all the languages of which there is one instance being displayed alphabetically. Opening the modal, the alphabetical sort is not correct.
