### ISSUE TITLE
[MVP QA] Logging of Administrative metadata

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1709]
### Descriptive summary

Recording of user name and date/time information when object is created, as well as all modifications to both file and metatdata.

### Expected behavior

- [x] Create a new work
- [x] Confirm that the work show page lists the work as being deposited by you
- [x] Confirm that the work show page lists the correct file as being attached by you
- [ ] Replace the file with another version with the same name
- [ ] Confirm that Versioning is happening
- [x] Edit a metadata field
- [x] Confirm that work show page records that you have made an update
- [ ] Edit the permissions on the file
- [ ] Confirm that permissions changed and that the work show page records that you made an update
- [ ] Attach a new child to the work
- [ ] Confirm that the work show page records that you made an update

Bonus points:
- [ ] Confirm the new child's existence is indicated on the original work show page
- [ ] Confirm that the parent's existence is indicated on the child work show page

### Related work

#39, #45, #60, #1334, #1655

**Comment by sseymore** [comment]
![Screen Shot 2021-06-29 at 11 25 17 AM](https://user-images.githubusercontent.com/7328774/123848574-be25ac00-d8cc-11eb-9f3d-840f0b04c55b.png)

QA Fail. Could not replace file with new version.

**Comment by sseymore** [comment]
QA fail. I have 2 images attached to this work, but neither are appearing in the dashboard to go through the QA steps for this ticket. 

https://staging.oregondigital.org/concern/images/pk02c9792?locale=en#content

![Screen Shot 2022-08-18 at 8 42 09 AM](https://user-images.githubusercontent.com/7328774/185437444-d8d10a71-11eb-4e97-971d-04793a561a76.png)

**Comment by sseymore** [comment]
Tried again with a new work, just in case. Same issue. 

https://staging.oregondigital.org/concern/images/3n203z12q?locale=en#content

![Screen Shot 2022-08-18 at 8 50 46 AM](https://user-images.githubusercontent.com/7328774/185439074-a4da173d-abd3-4896-a6f1-c0773ee0a647.png)

**Comment by sseymore** [comment]
QA Fail --  Replace the file with another version with the same name

![Screen Shot 2022-10-04 at 11 47 18 AM](https://user-images.githubusercontent.com/7328774/193901119-990018f0-5ca6-4171-92c5-76a924fb9818.png)

**Comment by CGillen** [comment]
@sseymore I can't reproduce this. I even used the same work as you

**Comment by sseymore** [comment]
@CGillen I can't access staging Dashboard right now but will look into it this week.

**Comment by sseymore** [comment]
It worked! I am going through the rest of the QA checklist. 
![Screen Shot 2022-10-17 at 2 34 00 PM](https://user-images.githubusercontent.com/7328774/196288076-749c18b9-00f7-43ba-92b6-e53cf26e9499.png)

**Comment by sseymore** [comment]
QA Pass!!!
