### ISSUE TITLE
[MVP QA] Separate some out into Technical and/or Admin metadata

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1710]
### Descriptive summary

Allows for some technical and administrative metadata to be automatically recorded/extracted on ingest. Some technical and administrative metadata displays as part of the descriptive metadata and could be hidden from public view.

### Expected behavior

See ticket #1709 for QA review criteria

**Comment by CGillen** [comment]
- [ ] Upload a new file to a work
- [ ] Confirm that the fileset page has metadata
- [ ] Confirm the fileset metadata is accurate to the file uploaded
- [ ] Compare the fileset metadata with the file's metadata and the MAP. There isn't more metadata in the file than on the fileset page

**Comment by sseymore** [comment]
QA pass but to note the Metadata team does want to split up the contents in Characterization to match the MAP. This is a goal for WC18 and will be ticketed in the future.
