### ISSUE TITLE
Update metadata for worktypes

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1714]
### Descriptive summary

Add a metadata field to Generic. 

### Expected behavior

Add View to Generic. See MAP. 

### Related work

https://github.com/OregonDigital/OD2/issues/1307

### Accessibility Concerns

N/A

**Comment by straleyb** [comment]
Move View from image to generic

**Comment by sseymore** [comment]
@straleyb I am trying to create a new Generic work on staging but not seeing View in the form.

**Comment by jsimic** [comment]
QA pass.
