### ISSUE TITLE
Configurable facets on staging not working

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1715]
### Descriptive summary

Facets other than core facets do not appear on collection landing pages after selecting them in the dashboard. 

See Gifford:
https://staging.oregondigital.org/collections/gifford?locale=en
https://staging.oregondigital.org/dashboard/collections/gifford/edit?locale=en#configurable_facets 

### Expected behavior

Selected facets should appear on the collection landing page.

### Accessibility Concerns

N/A

**Comment by sseymore** [comment]
This needs to work for the trial migration workflow.

**Comment by straleyb** [comment]
Ive done some digging on this. It looks like the only facets we have configured are as follows: 
COPYRIGHT
FORMAT
MEDIA
TOPIC
CREATOR
DATE
DECADE
LOCATION
WORK TYPE
LANGUAGE
COLLECTION
INSTITUTION

These do show up when a work has the data in those fields and is attached to the collection. Do we want more for the configured facets? If this is the case, then we need to detach the configured facets in collections from the configured facets for the search.

**Comment by jsimic** [comment]
@straleyb  #1371

**Comment by sseymore** [comment]
QA fail. I'm not sure if this was ready but some facets are still not appearing on the landing page:

Photographer
Topic/Subject
Owner
Location
License
Local Collection Name
Series Name

I am seeing these fields in public/deposited works, so I think this should work.

**Comment by lsat12357** [comment]
I'm looking at the Gifford landing page, and most of these are either present, or don't actually have values for this little chunk of assets (like owner)
I think only one which seems not to be showing but which should be is location

**Comment by sseymore** [comment]
Oh cool, yeah there are more showing now. Maybe a delay? 

Do we close this ticket due to the geonames issue or keep open until that is resolved?

**Comment by sseymore** [comment]
Checked on this-- some facets still aren't working like Owner on Gifford: https://staging.oregondigital.org/collections/gifford?locale=en

**Comment by CGillen** [comment]
@sseymore to QA

**Comment by sseymore** [comment]
I saw the comment from before that Linda left about Owner not appearing in Gifford because it's only a portion of the collection... sorry. I selected and de-selected facets and it appears to be working. QA pass.
