### ISSUE TITLE
Add Copy to Clipboard buttons to Work page Citations entries

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1718]
### Descriptive summary

On a work show page, under the How To Cite section, add a Copy to Clipboard button next to each citation entry. This will ensure a clean text selection each time for the user.

### Expected behavior

Each citation entry has a Copy to Clipboard button next to the title.

### Related work

Related to #1551 

### Accessibility Concerns

Button title should include which citation the button is for.

**Comment by azle** [comment]
@CGillen  For the how to cite section, please add a  [Copy] button to the right of the labels. In the tradition blue square style of the other OD buttons.

For example:
https://oregondigital.org/concern/images/df709p869#citations

APA, MLA, Chicago and WIKI should have a blue copy button on the right.

**Comment by shieldsb** [comment]
Buttons are there and functional.  @azle could you look at sizing and placement?

**Comment by azle** [comment]
@CGillen Good morning Corey, could we layout the copy button like this see mockup below.

<img width="1489" alt="Screenshot 2023-08-14 at 9 49 45 AM" src="https://github.com/OregonDigital/OD2/assets/8353860/75ec0997-c3a4-49bd-8d27-d78a4e78a605">

**Comment by shieldsb** [comment]
QA pass.
