### ISSUE TITLE
Add 'Edit' button to Collection show page

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1719]
### Descriptive summary

A Collection show page needs an 'Edit' button, for those with access, similar to how Works have one. Currently you have to go through the Dashboard.

### Expected behavior

Collection show page has an 'Edit' button, probably to the right of 'View All' link.

**Comment by lamtu1** [comment]
@wickr I have a PR up for this and wanting to clarify. Do we only allow people who are admin access the `Edit` collection page or people who created their own collection can have that button `edit` show up too?

**Comment by wickr** [comment]
@lamtu1 yes people who created their own collection should have this too, along with admins. 

This isn't changing the access levels at all, just making a button available if they do have access.

**Comment by CGillen** [comment]
QA: Deployable.
Adding an edit button for User Collections is slightly more difficult since it requires a different functionality on the button. Users have access to the My Collections interface which has the edit button, I vote we leave it at that for non-privileged users.

**Comment by shieldsb** [comment]
QA pass.
