### ISSUE TITLE
[SEE #155] Devise Authentication Preservation

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#172]
### Descriptive summary

We need to preserve a way for users to login to the system through the application. This is separate from CAS and UO login. This is for anonymous users who wish to share public works through the system.

**Comment by straleyb** [comment]
Waiting on Saml cert and UO IS team to make us a truster authority

**Comment by vantuyls** [comment]
@straleyb right now if i try to recover the password, i get redirected to a localhost via the link sent in the email. is that because of your comment above or is there something else going on?

**Comment by vantuyls** [comment]
QA PASS
