### ISSUE TITLE
Homepage Featured Collections titles should be links.

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1720]
### Descriptive summary

On the homepage, the list of Featured Collections titles aren't links, the only active link is 'View All'. 

### Expected behavior

Collections listed under Featured Collections have the titles as active links.

### Related

This is mentioned in #1147

**Comment by shieldsb** [comment]
I think the underlining might need some styling work 
![image](https://github.com/OregonDigital/OD2/assets/53542788/0d48be7a-0ace-451f-8749-a8378b6cf7a3)

**Comment by shieldsb** [comment]
QA pass.
