### ISSUE TITLE
Accessing IIIF Manifest for unreviewed work gives ACK (HTTP 500) message, needs different error status/message

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1721]
### Descriptive summary

When trying to view the IIIF Manifest directly of an unreviewed or restricted work that one doesn't have access to, OD2 gives the ACK error message, not something clearer about access being denied.

Example (currently unreviewed): https://staging.oregondigital.org/concern/images/df66x013g/manifest

### Expected behavior

Accessing a IIIF manifest that one doesn't have access to should state that in the error message, not look like OD2 is broken.

**Comment by mellinma** [comment]
Right now it says OOPS! LOOKS LIKE WE CAN'T FIND THE PAGE YOU ASKED FOR. HEAD [BACK HOME](https://staging.oregondigital.org/) AND SEARCH AGAIN!

**Comment by CGillen** [comment]
`/manifest` gives 500. `/manifest.json` gives 404

**Comment by CGillen** [comment]
`/manifest.json` gives 403 on authenticated but not authorized and 401 on unauthenticated and unauthorized users
`/manifest` gives 403 and displays the dashboard on authenticated but not authorized and is a redirect to the homepage for unauthenticated and unauthorized users

Work left on the ticket: remove any visibility of the dashboard to users with less permissions than depositor/collection curator

**Comment by CGillen** [comment]
QA:
Access `/manifest` and `/manifest.json` on works in as many cases as you can. Public/Private/UO/OSU, (un)authenticated/(un)authorized, etc

**Comment by shieldsb** [comment]
Not sure how these should look, but assume they should be consistent @straleyb @CGillen 

Message for /manifest.json when not logged in:
![image](https://user-images.githubusercontent.com/53542788/194972579-4da979cc-b628-4109-af75-afcf92306524.png)

Message for /manifest when not logged in: 
![image](https://user-images.githubusercontent.com/53542788/194972634-59cb8839-d46f-49c7-b0e4-71cbf0ce2912.png)

Message for /manifest.json when logged in but no access to work: 
![image](https://user-images.githubusercontent.com/53542788/194972902-815db4ac-da15-45dc-8177-c7541f65615a.png)

Message for /manifest when logged in but no access to work: 
![image](https://user-images.githubusercontent.com/53542788/194972867-e93783bc-9412-404f-94ce-218d811ed548.png)

**Comment by CGillen** [comment]
Consistent json responses is what we should be looking for. Not the response code pages from #2223

**Comment by jsimic** [comment]
QA pass. Getting 401 as unauthenticated user, manifest when logged in as admin.
![Screen Shot 2022-10-31 at 10 46 10 AM](https://user-images.githubusercontent.com/6344086/199075982-366030f2-5cca-4de4-99af-d143aeb7d24f.png)
![Screen Shot 2022-10-31 at 10 52 24 AM](https://user-images.githubusercontent.com/6344086/199076019-abc13fdd-a6c8-4c24-88c4-d518a96e0225.png)
