### ISSUE TITLE
Accessing IIIF manifest for some Private works when not logged in is successful

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#1723]
### Descriptive summary

The IIIF Manifest of at least one Private work can still be accessed when not logged in. This can be used in our viewer or another one to view the restricted work.

Example IIIF Manifest of work marked Private: http://universalviewer.io/uv.html?manifest=https://staging.oregondigital.org/concern/generics/v979v313f/manifest#?c=0&m=0&s=0&cv=0&xywh=-92%2C1%2C433%2C200

However, trying several other Private works and manifests asked for a login as expected.

### Expected behavior

Private work IIIF Manifests should have same access conditions as the work and not be viewable unless logged in and with the appropriate permissions.

### Related work

#1721

**Comment by CGillen** [comment]
This is replicable by creating a private work, turning it into a public work, then returning it to private

**Comment by shieldsb** [comment]
QA pass.  Created a private work, turned it into a public work, then returned it to private and the private versions were not accessible when not logged in.
