### ISSUE TITLE
Deleted Account Confirmation

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1731]
### Descriptive summary

Institutional and non-institutional users may elect to delete their OD2 account. At that time they should get confirmation that the account has been deleted and we should solicit feedback as to their reason for account deletion.

### Expected behavior

When a user deletes their account, they should see a message within OD2 and receive an email confirming the action and asking for feedback

### Related work

Link to related tickets or prior related work here.

#1540, #848, #276, #275, #230

### Accessibility Concerns

In-system message should be accessible

**Comment by jsimic** [comment]
POSM discussed 20211116. Will need to decide what exactly can/should get deleted and make sure it is consistent with the Privacy Policy. Will wordsmith the messaging too.

**Comment by jsimic** [comment]
What happens when an account is "deleted", i.e. disabled. See also #1170:  

- Patron access to My Collections is blocked
- Usage history, activity logs stay in the system
- Passwords are not saved

Privacy Policy is now consistent with this.

**Comment by mellinma** [comment]
POSM reviewed again 03/22/2022.  We just need e-mail content that tells the user what happens next.

**Comment by jsimic** [comment]
Subj: Oregon Digital account removal confirmation

We’re sorry to see you go!

Thank you for your interest in Oregon Digital. All personally identifying information will be removed from our system. Aggregate data such as usage history and activity logs are kept for 50 months to help improve website performance.

If you have any questions, please contact us.

The Oregon Digital Team

**Comment by shieldsb** [comment]
QA fail.  Tried to delete an account and received an ack message. Also, see comments about wireframe for the delete account page in #365 

![image](https://user-images.githubusercontent.com/53542788/191874496-13f606fd-4fce-4891-9699-0f297b351d7d.png)

**Comment by shieldsb** [comment]
QA fail. Still receiving an ack message when I try to delete an account.

**Comment by shieldsb** [comment]
QA fail.  Received the message in OD, but did not receive an email.  I checked all folders.

**Comment by shieldsb** [comment]
QA pass.
