### ISSUE TITLE
oEmbed error email notifications

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#174]
### Descriptive summary

On new oEmbed error, an email should be sent to the initial depositor of the work.

### Expected behavior

- New oEmbed errors generate an email to the work depositor
- Email should include the error, the oEmbed URL, and dashboard/resolution link.
- Repeat errors should not trigger spam messaging.

### Related work

Resolves checkbox for #77

**Comment by vantuyls** [comment]
QA should wait until mailer is set up. Notification error appears in Hyrax notification page

**Comment by CGillen** [comment]
As Steve said, QA needs to wait until mailer is setup. Should be complete if we decide all Hyrax notifications should send emails. Otherwise we need to nail down #230 and figure out how to send emails for specific notificatioins

**Comment by revgum** [comment]
blocked by #297

**Comment by revgum** [comment]
Verified that the oEmbed error is sent successfully when a work is updated with an invalid oEmbed error.
