### ISSUE TITLE
[A11y] General - Link purpose - twitter link accessible name

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1802]
### Operating System

Windows

### Browser

Edge

### Affected page

Homepage

### Admin user?

Yes

### Issue Description

There's a link that's just "@oregondigcol" - there's no context to make it clear this is a link to the Oregon Digital twitter feed

### Suggested Fix

Probably best to make "@oregondigcol" into something like "OD on Twitter" to help all users. Most people will recognize the twitter symbol, but cognitively impaired people may not, people who haven't used twitter much may not, and blind people obviously need something more than a decorative image.

**Comment by jechols** [comment]
QA steps depend on remediation.  If the visible text is changed, QA will be easy, but if it's just screen reader text that changes, it will require dev tools to inspect the element and/or use of a screen reader.

**Comment by CGillen** [comment]
Fixed by #1862
