### ISSUE TITLE
[A11y] Advanced Search - Title

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1806]
### Operating System

Windows

### Browser

Edge

### Affected page

Advanced Search

### Admin user?

Yes

### Issue Description

The title of the page is "Index Advanced // Oregon Digital (Development)".  This title doesn't describe the page function, which is to do a search.  An advanced search, sure, but even just having the word "search" in the title would be wonderful.

### Suggested Fix

Change the page title prefix to "Search" or "Advanced Search".

**Comment by jechols** [comment]
The "//" is gone, but the rest of the title is the same - "Index Advanced" being the key part that doesn't make sense.

**Comment by straleyb** [comment]
This is fixed on staging it says advanced search.
