### ISSUE TITLE
[A11y] Desktop/Mobile Homepage: View All Collections Button

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#1812]
### Operating System

MacOS

### Browser

Chrome

### Affected page

Homepage

### Admin user?

No

### Issue Description

Homepage: https://staging.oregondigital.org/?locale=en

I was able to tab through the links and go to the specified pages except for the "View All Collections" button. I was able to tab to it but it didn't take me to the view all collections page.

### Suggested Fix

Double check it has a url to link to.

**Comment by CGillen** [comment]
@thornka Turn this into a link to `/explore_collections/all`

**Comment by azle** [comment]
The View All link is fixed. However, when I tab through starting from "Featured Collections" title. It skips the collection title and the screen reader just reads "View All" for each tab within the featured collection list.

Can the view all arial label include the collection title something like "View All My Little Pony", "View All African Political Ephemera and Realia Project" and etc.

**Comment by azle** [comment]
I was validating this page and found the following error:

Code:
<img width="1222" alt="Screen Shot 2021-12-06 at 2 20 17 PM" src="https://user-images.githubusercontent.com/8353860/144932040-745e0d32-2b74-402d-bb45-07a945681360.png">

Error and Fix:
<img width="352" alt="Screen Shot 2021-12-06 at 2 21 06 PM" src="https://user-images.githubusercontent.com/8353860/144932140-b9420c9a-3ddb-4b5a-a597-e6f12a97b6ba.png">

**Comment by azle** [comment]
@straleyb Could you take a look at the two contrast errors. Can you adjust them so they are the same text color as in the facets. See ticket #1836

See image, the red icon represents which text labels have low contrast errors.

<img width="1125" alt="Screen Shot 2021-12-13 at 9 22 27 AM" src="https://user-images.githubusercontent.com/8353860/145858952-8ec202a3-0b8c-4752-a674-7abd437aa7f4.png">
