### ISSUE TITLE
[A11y] Desktop/Mobile Search Results - Grid: Filter > Date > Limit Button 

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#1819]
### Operating System

MacOS

### Browser

Chrome

### Affected page

Search

### Admin user?

No

### Issue Description

Desktop/Mobile Search Results - Grid:https://staging.oregondigital.org/catalog?locale=en&q%5B%5D=test&search_field=all_fields&utf8=%E2%9C%93&view=gallery

When I tab to use the filter panel and go to date and enter a date range and click the limit button. I expect to be able to continue tab down the rest of the filters options from where I left off. Just like the other filters.

However, when I tab and hit the limit button it takes me back to the top starting at the skip nav.

### Suggested Fix

Be able to enter the date range and hit the limit button and it allows me to continue tabbing to the next section which is "Decade".

**Comment by CGillen** [comment]
Behavior can not be replicated. Selecting any facet takes me to the top of the page, which should happen on a page load.
