### ISSUE TITLE
[A11y] Collection Landing - Native Widget - "any/all" select

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1822]
### Operating System

Windows

### Browser

Edge

### Affected page

Collection Show

### Admin user?

Yes

### Issue Description

Similar to the advanced search, the any/all dropdown isn't useful.  In this page, it's set up differently, and leads to an entirely new confusion: the label is "Find items that match of", because the label wraps the whole heading, which includes the select.  That isn't a viable approach even though it might seem like it is, because labels never include the control's text.

### Suggested Fix

Similar to advanced search, this needs to be re-thought-out.  We could have instructions above the form or consider a better way to word it.  The issue of mid-sentence inputs is a very difficult one.

If it's not horrible, we could go with duplication of text.  The entire "Find items that match any/all of" could be a dropdown field with a label of something like "Scope"...?  I don't honestly know if this is a better approach, though.

**Comment by jechols** [comment]
See #1789 - the solution there is likely the same here.  Though in this case, there is at least a label already.

Note that on *Edge*, the label is "Find items that match of", but in Firefox with NVDA it's actually not awful considering our options.  If a good solution can be done for #1789, repeating it here makes sense.  If not, what's here might be "good enough".

QA: probably needs expertise to check how the label is working.

**Comment by CGillen** [comment]
First fix: #1878 
Second fix: #1911
