### ISSUE TITLE
[A11y] Collection Landing - Parsing - invalid nesting of headings

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1824]
### Operating System

Windows

### Browser

Edge

### Affected page

Collection Show

### Admin user?

Yes

### Issue Description

In addition to the report already filed about a level 1 heading (`<h1>`) being nested under a span, the collection landing page also has a level two heading nested in a span:

```html
    <span class="text-center"><h2 class="collection-search-header">OR, SEARCH THIS COLLECTION</h2></span>↩
```

### Suggested Fix

Change the span to a div

**Comment by CGillen** [comment]
Fixed by #1915
