### ISSUE TITLE
[A11y] Desktop/Mobile Search Results - Grid: Select All

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#1829]
### Operating System

MacOS

### Browser

Chrome

### Affected page

Search

### Admin user?

No

### Issue Description

Search Results Grid: https://staging.oregondigital.org/catalog?locale=en&q%5B%5D=test&search_field=all_fields&utf8=%E2%9C%93&view=gallery

As a user, I am not logged in. When I tab to the Select All and hit enter it does nothing. When I continue to tab and hit the "Save Selected To" button which has a pop up that prompts to "Save this item, please login to access your collection".

Should the save selected option and checkbox only be visible to a logged in user? Also if this is available at all times. Should the prompt include the ability to login from the prompt box that I mentioned above?

### Suggested Fix

Remove the checkboxes and the select all function for the user that is not logged in.

OR

Include the login within the prompt box and also be able to check the checkboxes as any user.

**Comment by CGillen** [comment]
@thornka Verify what Azle said is true on major browsers (FF, Chrome, Edge, Safari), and lets change the modal text to:
```
Please login or create an account to save this work to a collection
Log in
Sign up
```
Where `log in` is a button that swaps the modal to the log in modal (There is an example of this in the same modal while logged in when you select `create a new collection`)
and `Sign up` is a link to `/users/sign_up`

Service managers will probably change this wording at some point, but this will at least show them what's possible and they may end up liking it enough to keep it.
