### ISSUE TITLE
[A11y] Collection Landing - Text Spacing

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1838]
### Operating System

Windows

### Browser

Edge

### Affected page

Collection Show

### Admin user?

Yes

### Issue Description

User styles don't work on the collection page everywhere.  In particular:

- The text for the OSULP logo obviously doesn't get restyled since it's just an image of text
- The "VIEW ALL" and "SEARCH" buttons don't seem to accept user styling
- "OR, SEARCH THIS COLLECTION" doesn't seem to accept user styles 

Before styling:

![image](https://user-images.githubusercontent.com/2157974/128764038-5615efca-f0f8-4351-9283-2e5571cdf93f.png)

After styling:

![image](https://user-images.githubusercontent.com/2157974/128764077-3c20d9f4-ba21-4abe-9331-0e61ffcd74fa.png)

### Suggested Fix

I'm not sure we can fix this.  I checked the CSS and I don't see anything overriding the Accessibility Insights styles; the CSS is simply not applying properly.  I think this is an AI bug, not ours.

**Comment by jechols** [comment]
As mentioned on #1813:

@CGillen: If this isn't trivially easy to fix, close it.  The more I've looked at things the more convinced I am that this is not even an accessibility insights problem, but a "Jeremy doesn't understand the requirement" problem.  I think the letter spacing is probably fine *by default* for some of the places where it isn't adopting the new styles.

**Comment by CGillen** [comment]
Turns out this isn't easily fixable. For some reason in chromium browsers injected CSS doesn't take precedent over (some?) author css, even with `!important`. It might have something to do with specificity of the selector, either way it's dumb
