### ISSUE TITLE
[SEE #155] When a user tries to sign in via devise with a UO or OSU email, redirect to proper login page

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#184]
### Descriptive summary

Since we dont need to sync accounts, we need to make sure that when someone tries to login through devise, that we push them to the proper page. This means overriding the devise controllers and adding in a before filter to check the input information and redirect to the proper route.

**Comment by straleyb** [comment]
Waiting on Saml cert and UO IS team to make us a truster authority

**Comment by straleyb** [comment]
QA TESTING: Create an account in Devise and try and login and generate a work

**Comment by vantuyls** [comment]
QA: 

*Login via oregonstate.edu email account redirects as expected. (QA PASSED)
*Login via xxxx.oregonstate.edu email account (e.g. engr.oregonstate.edu) does not redirect as expected (QA FAILED)

@jsimic can you QA this on the UO side please (or find someone to do so)?

**Comment by straleyb** [comment]
👍 I didnt take that into account. I should get a list of all possible types of emails for UO and OSU.

**Comment by vantuyls** [comment]
@jsimic can you get a list of email suffixes for UO? that way @straleyb just needs to find the OSU ones.

**Comment by raybrarian** [comment]
UO is currently a blocker - I can't get a comprehensive list of suffixes from our folks, but probably need to reach someone in campus Identity Management to get that. I don't know who to contact there, and most folks I could ask are out today.

**Comment by vantuyls** [comment]
OSU IS indicates that we should be looking for:
*.oregonstate.edu
*.orst.edu

**Comment by straleyb** [comment]
It works for *.oregonstate.edu and *.orst.edu Still waiting on UO side

**Comment by CGillen** [comment]
@raybrarian Has identified *@uoregon.edu as the only email suffixes UO holds.
Still waiting on #173 to finish QA.
