### ISSUE TITLE
[A11y] Dashboard - Link Function

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1848]
### Operating System

Windows

### Browser

Edge

### Affected page

Backend

### Admin user?

Yes

### Issue Description

There's an empty `<a>` on the page.  I'm assuming this is for the skip-to-content button, much like in the non-dashboard views.

### Suggested Fix

Use an id, not an empty `<a>` element for the skip link's destination.

**Comment by jechols** [comment]
QA: inspect target of skip link to verify it's not an `<a>` tag

**Comment by CGillen** [comment]
Fixed by #2025
