### ISSUE TITLE
Plain-text passwords being leaked into request params

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#188]
### Descriptive summary

Request parameters for user logins from Devise are being submitted in plain-text in our Honeycomb events. 

![screen shot 2018-12-06 at 2 18 51 pm](https://user-images.githubusercontent.com/1882223/49617106-150eb300-f968-11e8-9cf4-3876367a16d8.png)

Honeycomb scrapes several objects within each request to build its events. this includes request.params, which is where user information is getting stored (request.params.user).

**Comment by straleyb** [comment]
closed by #189

**Comment by straleyb** [comment]
QA PROCESS: Login using devise and check the developers tools to see if there are still passwords in the POST. @decimalator

**Comment by vantuyls** [comment]
@decimalator would you mind running that QA test and confirming?

**Comment by decimalator** [comment]
Still looks like the plain-text password exists in params.user

![screen shot 2018-12-20 at 10 11 52 am](https://user-images.githubusercontent.com/1882223/50302846-2a8fdc80-0440-11e9-9853-af2ca1503213.png)

**Comment by revgum** [comment]
Remove: https://github.com/OregonDigital/OD2/blob/master/app/controllers/application_controller.rb#L20

Pin `gem rack-honeycomb, '~>0.5.0'` to get the fix they've put in place: https://github.com/honeycombio/rack-honeycomb/releases/tag/v0.5.0

**Comment by revgum** [comment]
Confirmed that `request.params.user` is no longer posting to Honeycomb
