### ISSUE TITLE
[A11y] Desktop/Mobile Collection Landing: Nu Checker

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#1881]
### Operating System

MacOS

### Browser

Chrome

### Affected page

Collection Show

### Admin user?

No

### Issue Description

Collection Landing: https://staging.oregondigital.org/collections/gwilliams?locale=en

Using the Nu Checker, attached is the following errors:
[Collection_Landing.zip](https://github.com/OregonDigital/OD2/files/6977127/Collection_Landing.zip)

### Can anybody QA or does this need an expert?

Needs expert

**Comment by thornka** [comment]
@CGillen I went through the errors and it seemed like all of the ones listed in the zip had been fixed. I also ran the Nu Checker on the page again and none of the same issues popped up. Is this ticket good or is there something that I missed?

**Comment by CGillen** [comment]
This one looks good to me 👍

**Comment by azle** [comment]
I rechecked the page and received the following errors see zip file:
[NU_CollectionLanding_Round2.zip](https://github.com/OregonDigital/OD2/files/7139180/NU_CollectionLanding_Round2.zip)

**Comment by azle** [comment]
@thornka  I revalidated the page and it contains two errors, see image below:

<img width="1262" alt="Screen Shot 2022-01-06 at 8 27 31 AM" src="https://user-images.githubusercontent.com/8353860/148415846-99b0bff7-0901-4d85-9a02-7004b52a72fd.png">

**Comment by azle** [comment]
@thornka I rechecked the page and it has only 2 errors, see below:

<img width="864" alt="Screen Shot 2022-01-11 at 6 34 58 AM" src="https://user-images.githubusercontent.com/8353860/148962486-c8a078fc-e897-4c2e-9b50-8708dd848682.png">

**Comment by azle** [comment]
@thornka , I revalidated and received the following three errors. See screen snap.

<img width="1078" alt="Screen Shot 2022-01-19 at 10 53 13 AM" src="https://user-images.githubusercontent.com/8353860/150195490-90e8cddc-1301-4fcc-9f5f-2ebfd7be0a89.png">
