### ISSUE TITLE
[A11y] Desktop/Mobile Explore Collection Grid: Error left of All tab

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#1892]
### Operating System

MacOS

### Browser

Chrome

### Affected page

Collection Show

### Admin user?

No

### Issue Description

Explore Collection Grid: https://staging.oregondigital.org/dashboard

There is a error located to the left of the "All" tab see screensnap, see red exclamation box:
<img width="1404" alt="Screen Shot 2021-08-12 at 12 21 29 PM" src="https://user-images.githubusercontent.com/8353860/129256522-230b6d7b-abe9-43d9-b49e-68552c3da6ad.png">

Accessability Insight Assessment for Link Function and Link Purpose is throwing the following error:
If an anchor element functions as a custom widget, it must have the appropriate ARIA widget role.
The purpose of a link must be described by its link text alone, or by the link text together with preceding page context.

Accessible name: (no value)
URL: (no value)
Role: (no value)
Tab Index: (no value)
Aria attributes: (no value)

### Suggested Fix

Needs accessible name

### Can anybody QA or does this need an expert?

A11y familiarity recommended

**Comment by CGillen** [comment]
This was the skip to anchor, fixed by #1867
