### ISSUE TITLE
Make list of supported oEmbed external sources

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#190]
### Descriptive summary

We should make a list of supported oEmbed sources that we can confirm will work in the system.

Include: OSU MediaSpace (Kaltura), YouTube, Vimeo, others?

### Related work

#75

**Comment by CGillen** [comment]
The ruby-oembed gem wins us these providers for free: https://github.com/ruby-oembed/ruby-oembed/blob/master/lib/oembed/providers.rb#L139-L359
Plus we can add oohEmbed, noEmbed, and Embedly aggregators.
After that, we need to follow the instructions for adding custom providers: https://github.com/ruby-oembed/ruby-oembed#custom-providers

**Comment by wickr** [comment]
Keep providers included by plugin, especially YouTube and Vimeo
Add OSU MediaSpace (Kaltura)

**Comment by vantuyls** [comment]
QA PASS - whitelisted (youtube) oembed works
QA PASS -  non-whitelisted (daily motion) oembed fails
