### ISSUE TITLE
[A11y] Explore Collections - Table - Page Title

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1901]
### Operating System

Windows

### Browser

Edge

### Affected page

Explore Collections

### Admin user?

Yes

### Issue Description

The page title for the grid view is the same as that for the table view.  Accessibility Insights says "For pages within a website, the page title must be unique."

W3C pages say this is not a requirement at all, but a "nice to have".  Consider this VERY low priority.

### Suggested Fix

If possible, the title should reflect the view a bit better.  For instance, "Explore Collections | Masonry", "Explore Collections | Search Results | Masonry", "Explore Collections | Page 3"...

It could become really unwieldy to try and make the page title perfect, however.

W3C even says that having it be unique within a site is "helpful", but it isn't required.  https://www.w3.org/WAI/WCAG21/Techniques/general/G88

If this isn't an easy win, just close this ticket.  The page title might need to be improved from "All Explore Collection", but it shouldn't be something we spend hours on to perfect.

### Can anybody QA or does this need an expert?

Anybody

### QA Steps

Make sure the page title reflects the page and fulfills the success criterion described at https://www.w3.org/WAI/WCAG21/Techniques/general/G88

**Comment by CGillen** [comment]
Fixed by #2117
