### ISSUE TITLE
[A11y] Explore Collections - Table - Reflow / Mobile

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1902]
### Operating System

Windows

### Browser

Edge

### Affected page

Explore Collections

### Admin user?

Yes

### Issue Description

While most of the table reflows well, the table headers themselves become difficult to read:

![image](https://user-images.githubusercontent.com/2157974/129588950-79b6bece-b547-4418-97f5-3be83d2f27d5.png)

The same is true on a mobile view:

![image](https://user-images.githubusercontent.com/2157974/129589001-c15fadb4-22fe-4ff8-beab-043d5b33dc8d.png)

### Suggested Fix

A bit more spacing between headings might help.  That would likely force the view to need more horizontal scrolling, but that's just how data tables are sometimes.

It might be good enough to fix the font and CSS.  By making the text all caps, it's very hard to tell where one header ends and the next begins.  Simply dropping the all-caps yields this:

![image](https://user-images.githubusercontent.com/2157974/129589331-c4513e11-d68f-481b-ad4c-65995a699d26.png)

If you also go with a serif font, it's even easier to read because the "I" doesn't look like an "l".  And if you're reading this on github, you'll see precisely the same problem in the quoted letters I just wrote, because github also uses a sans font....

![image](https://user-images.githubusercontent.com/2157974/129589541-8ab353e2-4abe-48f9-8132-dd7e51b32fab.png)

### Can anybody QA or does this need an expert?

Anybody

### QA Steps

Resize to 1280x1024, zoom to 400%, make sure table headers can be read

**Comment by CGillen** [comment]
Fixed by #2086
Fixed by previous work to complete mobile wireframe
