### ISSUE TITLE
[A11y] Homepage - Link Purpose

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1907]
### Operating System

Windows

### Browser

Edge

### Affected page

Homepage

### Admin user?

Yes

### Issue Description

Same issue as other pages have - this is probably a global issue - there's an anchor tag that's essentially empty, used as a target for the skip link.

### Suggested Fix

Remove this empty `<a>` and make the skip link go to wherever the `<main>` section is

### Can anybody QA or does this need an expert?

A11y familiarity recommended

### QA Steps

Testing this requires verifying that the empty `<a>` is not present, and then making sure the remediation is set up correctly for the skip link.

**Comment by straleyb** [comment]
QA: Skip link works and isn't empty.
