### ISSUE TITLE
oEmbed URLs are checked against a whitelist of sources/domains

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#191]
### Descriptive summary

We don't particularly want to support any available oEmbed source, but a few major ones. Plus a whitelist helps us confirm that they work as expected.

### Expected behavior

oEmbed URLs not recognized should be refused, with note to contact project team to look into including as an additional source.

Recognized oEmbed URLs should perform as expected.

### Related work
#75 
#190

**Comment by CGillen** [comment]
From the list we build in #190, we can pick which providers to whitelist. From that decision, we can then choose to not register all built in providers and selectively register our whitelist: https://github.com/ruby-oembed/ruby-oembed/blob/master/lib/oembed/providers.rb#L22
That way, if there's an attempt to retrieve an oEmbed URL from a provider we haven't whitelisted ruby-oembed will throw an error. We can then handle that error either in the oEmbed management dashboard or as part of the works submission validation.

**Comment by wickr** [comment]
List complete in #190.

**Comment by CGillen** [comment]
QA:
- [ ] Generate a work that embeds media from media.oregonstate.edu
