### ISSUE TITLE
[A11y] Search Results - Grid - Links - Pagination

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1924]
### Operating System

Windows

### Browser

Edge

### Affected page

Search

### Admin user?

Yes

### Issue Description

In the pagination:

- The "Prev" button is a link but it can't be activated
- The "1" element is not a link so screen reader users have a tough time finding their current page

### Suggested Fix

Make "prev" use `aria-disabled="true"`.  It could be turned into plain text, but there is value in making it clear that there is no previous page, so I'd advise simply making it disabled to assistive tech.

The number "1" should probably be turned into a link and use `aria-current="page"`

### Can anybody QA or does this need an expert?

Needs expert

### QA Steps

This is really best tested with NVDA or something in order to ensure the attributes are set properly.  Otherwise, somebody needs to very carefully verify this by checking the raw HTML, which can be error-prone.

**Comment by CGillen** [comment]
Fixed by #2131
