### ISSUE TITLE
[A11y] Search Results - Grid - facets (link purpose, link function, widgets, ...)

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1925]
### Operating System

Windows

### Browser

Edge

### Affected page

Search

### Admin user?

Yes

### Issue Description

This is a bit like #1834, but the "Filters" heading helps give the facet links context at least.

- The facet headings (e.g., "COPYRIGHT", "FORMAT", etc.) are coded as links even though they act like buttons
- The facet headings don't announce when they're activated that something occurred

### Suggested Fix

The facet headings (e.g., "COPYRIGHT", "FORMAT", etc.) should implement the disclosure or accordion pattern.  Accordions make more sense for the purpose of this type of widget.

https://www.w3.org/TR/wai-aria-practices-1.1/#accordion

### Can anybody QA or does this need an expert?

Needs expert

### QA Steps

Somebody needs to fully understand the accordion/disclosure requirements and verify they're fully implemented

**Comment by CGillen** [comment]
Fixed by #1899
Fixed by #2034
