### ISSUE TITLE
[UV] Zooms in to words

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1938]
### Descriptive summary
As a user, I would expect UniversViewer to not zoom in on the word. I want to the full view of the asset and I will determine when, if, and how far I want to zoom in.

### Expected behavior
After searching for a word or phrase, UV displays the whole asset and the results are tagged blue for the user to easily find with full context.

### Related work
#1645 

### Accessibility Concerns
Universal Viewer in general

**Comment by CGillen** [comment]
Fixed by #2228

**Comment by shieldsb** [comment]
QA fail. UV is not zooming in on the word, but it's also not tagging it in blue. Also unable to select the next or previous result buttons.

**Comment by CGillen** [comment]
Use this work for UV search testing: https://staging.oregondigital.org/concern/documents/gq67jr52k?locale=en#content
Most works were ingested before the worker that does the OCR & search indexing was updated. Only new works can use UV search and it takes a long while after the ingest to work properly (30mins+)

**Comment by jsimic** [comment]
QA pass. Term ("Christmas") is found and highlighted without zooming.

However, the pins above the bottom progress bar are too high and the Contents and More Information sidebars overlap and partially hide the pins. Previous/Next Result is working.

**Comment by shieldsb** [comment]
QA pass
