### ISSUE TITLE
Downloaded zip file is broken again

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1941]
### Descriptive summary
As a user, I would expect when I click download zip that my download starts immediately, even if I don't know how long it will take or how large the file will be.
I would also expect my downloaded file to open and contain the assets and metadata.

### Expected behavior
The user can stream the download as it's generated but does not need to know the final size (possible enhancement)
Once the download has finished, the zip is able to be opened and contains:

- For a regular work: The asset files and metadata
- For a compound work: The asset files of all children and metadata of all children (in one csv)

### Related work
#1449 QA for all of download
#1234 an additional version of download that needs to work
#1691 PR that broke this functionality

**Comment by shieldsb** [comment]
QA pass.
