### ISSUE TITLE
Remove all facet/filter/search metadata links from search results

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1943]
### Descriptive summary
As a user, I would like to not be shipped off to a new search while already in a search. This confuses me and makes it difficult to find my results

### Expected behavior
On search results, all links that bring the user off to a new search are removed and the text inside is preserved.

### Accessibility Concerns
I think this reduces A11y complexity.

**Comment by shieldsb** [comment]
QA pass.
