### ISSUE TITLE
Search institution field for display of institution image

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1947]
### Descriptive summary
In work show and collection show and explore collection we find the first institution label to determine some display elements (logos, institution text label). It's possible the first institution is not one of `OSU` or `UO`. We should iterate the institution field and match on the first in our list of institutions.

### Expected behavior
The edge case where the first institution is not OSU/UO does not cause a non-match if our institutions are in the metadata field.

### Accessibility Concerns
Images maintain their alt text

**Comment by straleyb** [comment]
Generate a work with an institution field where OSU or UO isnt the first. Make it work for first found.

**Comment by straleyb** [comment]
https://staging.oregondigital.org/concern/generics/ww72bb51z?locale=en First in the list is non-osu non-uo institution, it shows the first one found on the logo which is UO

https://staging.oregondigital.org/collections/gt54kn03w?locale=en Same for this collection

https://staging.oregondigital.org/collections/all?locale=en&page=18 Explore collections shows UO which is the correct institution that isn't first

QA: Verify work show page is displaying logo correctly

**Comment by shieldsb** [comment]
QA pass.
