### ISSUE TITLE
[A11y] Desktop/Mobile Work Show Page-CPD Child: Content Tabs

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#1955]
### Operating System

MacOS

### Browser

Chrome

### Affected page

Work Show

### Admin user?

No

### Issue Description

Work Show Page-CPD Child: https://staging.oregondigital.org/concern/documents/df727057n

The "How to Cite" and "Contact Us" tabs don't work. I am able to tab to them. However, when I try to enter to choose one of them they both take me to "Is Part of" below the page.

If I don't tab and use the mouse to click on the tabs it goes to the appropriate pages. Its only happening if I specifically using the tab to navigate the page.

### Suggested Fix

How to Cite  and Contact Us needs to go to their appropriate tab content.

### Can anybody QA or does this need an expert?

Anybody

**Comment by azle** [comment]
Also happening on the following page:
Work Show Page-CPD Parent: https://staging.oregondigital.org/concern/generics/df727084j?locale=en

**Comment by azle** [comment]
@CGillen Works fantastic in Safari. However for some reason in Chrome (Version 97.0.4692.71 (Official Build) (x86_64)) and in Firefox (96.0.1 (64-bit)) on a Mac its not working. When I tab through its still doing the same thing as what's mentioned in the ticket. I also refreshed and emptied cache.

Chrome > I tab to the button "copy" it tabs to "details" and the rest of the tabs. But if I select "how to cite" and click enter it takes me to "is part of" title label.

Firefox > I tab to the button "copy" but instead of taking me to the tabs when I tab it takes me to the first checkbox/thumbnail of the "is part of" section and not the title label like chrome.

**Comment by azle** [comment]
@CGillen Another page validated with one error

<img width="816" alt="Screen Shot 2022-02-02 at 1 35 26 PM" src="https://user-images.githubusercontent.com/8353860/152241201-d48dcba7-51e3-42e5-a755-91174a3eef6f.png">

**Comment by CGillen** [comment]
Above issue is related to an UV issue we currently can not fix. Please disregard until we can edit the UV iframe (if we decide to)
