### ISSUE TITLE
[A11y] Desktop/Mobile Work Show Page-CPD Child: NU Checker

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#1994]
### Operating System

MacOS

### Browser

Chrome

### Affected page

Work Show

### Admin user?

No

### Issue Description

Work Show Page-CPD Child: https://staging.oregondigital.org/concern/documents/df727057n?locale=en

NU Html Checker list of errors, see attached zip file.
[Work Show Page-CPD Child.zip](https://github.com/OregonDigital/OD2/files/7049837/Work.Show.Page-CPD.Child.zip)

### Can anybody QA or does this need an expert?

Needs expert

**Comment by straleyb** [comment]
None of these issues are present on the page anymore. 

QA: Rerun this page on Nu checker to see if any new errors exist.

**Comment by azle** [comment]
@straleyb , I ran it through the NU Checker and got the following errors see zip file attached to this comment.

[Work Show Page-CPD Child.zip](https://github.com/OregonDigital/OD2/files/7973095/Work.Show.Page-CPD.Child.zip)

**Comment by azle** [comment]
@straleyb, I re validated the page and found 1 error:

<img width="1123" alt="Screen Shot 2022-02-07 at 9 28 36 AM" src="https://user-images.githubusercontent.com/8353860/152840377-8015e71c-ba44-4881-8394-4ad76e3ed750.png">
