### ISSUE TITLE
[A11y] Desktop/Mobile Work Show Page-CPD Parent: NU Checker

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#1995]
### Operating System

MacOS

### Browser

Chrome

### Affected page

Work Show

### Admin user?

No

### Issue Description

Work Show Page-CPD Parent: https://staging.oregondigital.org/concern/generics/df727084j?locale=en

NU Html Checker list of errors, see attached zip file.
[Work Show Page-CPD Parent.zip](https://github.com/OregonDigital/OD2/files/7049850/Work.Show.Page-CPD.Parent.zip)

### Can anybody QA or does this need an expert?

Needs expert

**Comment by straleyb** [comment]
None of these issues are present on the page anymore.

QA: Rerun this page on Nu checker to see if any new errors exist.

**Comment by azle** [comment]
@straleyb , I rechecked the page on NU Checker and found the following errors. See attached zip file in this comment.

[Work Show Page-CPD Parent.zip](https://github.com/OregonDigital/OD2/files/7973129/Work.Show.Page-CPD.Parent.zip)
