### ISSUE TITLE
[A11y] Desktop Work Show Page-CPD Parent: CheckBox and Save

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#2001]
### Operating System

MacOS

### Browser

Chrome

### Affected page

Work Show

### Admin user?

No

### Issue Description

Work Show Page-CPD Parent: https://staging.oregondigital.org/concern/generics/df727084j

I am a non logged in user and on this page I see there is checkboxes and a save button for images. Should I be seeing this as a non logged in user?

When I check an image and click save. A popup appears and tells me the following:

SAVE THIS ITEM
Please login to access your collection.

Is that how it works?

### Can anybody QA or does this need an expert?

Anybody

**Comment by straleyb** [comment]
This is a non-issue and is functioning as expected.
