### ISSUE TITLE
Solve problem of search results by name as metadata (Kringle, Kris) vs. name as OCRed text (Kris Kringle).

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#202]
### Descriptive summary

As a user, I'd like to get results of name searches in a clear way whether I type in "Kris Kringle" or "Kringle, Kris" (understanding not results may be identical, of course) in both system and PDF viewer.

### Expected behavior

Solution may rest in the results at PDF viewer level... but not sure. NEEDS DISCUSSIONS.

### Related work

Karl Onthank is a good example for experiments and discussion. Top result in OD1 for either search format is a photo (which likely has the most metadata.) Seventh result has the most Onthank returns (eleven) once you are in the viewer.... but presents as "No returns" there because the OCRed text recognizes "Karl W. Onthank" or just "Onthank" but not "Karl Onthank" or "Onthank, Karl"   

Somewhat related to #1110

**Comment by wickr** [comment]
Check results again after Search is added to Universal Viewer. In OD1 search is a different system, but if in OD2 it's using the same Solr that backs the main search, we may not have this name problem anymore.

**Comment by wickr** [comment]
Related: https://github.com/OregonDigital/OD2/issues/1698
