### ISSUE TITLE
Add Landscape Architect property to works

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2021]
### Descriptive summary

Landscape Architect is an additional Creator type to be added to works. The new row is filled out on the MAP: https://docs.google.com/spreadsheets/d/1ien3djlZxcctuAE99XweyuNdMiN5YsrKoYBJcK3DjLQ/edit#gid=2011906483&range=25:25

It has already been added to OD1 and has some content using it, example: https://oregondigital.org/catalog?f%5Bdesc_metadata__landscapeArchitect_label_sim%5D%5B%5D=Corry%2C+Chester+E.%2C+1906-1989%24http%3A%2F%2Fid.loc.gov%2Fauthorities%2Fnames%2Fno2021077230

### Expected behavior

Landscape Architect is an available metadata property and displays appropriately.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

N/A

**Comment by jsimic** [comment]
Noted also in #1368

**Comment by lsat12357** [comment]
QA I successfully migrated a work which uses landscape_architect on staging
https://staging.oregondigital.org/concern/images/2f75r8366
