### ISSUE TITLE
[A11y] Work Show Page-CPD Child - "Action" button

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#2023]
### Operating System

Windows

### Browser

Edge

### Affected page

Work Show

### Admin user?

Yes

### Issue Description

https://staging.oregondigital.org/concern/documents/df727057n

The "SELECT AN ACTION" button has the accessible text "Press to Select an action". This is bad for screen-reader users as well as users of speech-to-text software.

This button also seems to be trying to implement a menu, but it isn't done correctly.

### Suggested Fix

Keep the button's accessible name the same as its visible name. There's no need to tell people to press or activate a button, and doing so is very problematic for users of dictation software.

Either implement the menu widget properly or implement this as a disclosure. A disclosure is perfectly reasonable here since it's not part of a complex application menu, and has fewer required keyboard controls.

### Can anybody QA or does this need an expert?

Needs expert

### QA Steps

Verify the accessible name of the action button matches the visible label. Verify the menu/disclosure is implemented according to the relevant pattern on https://www.w3.org/TR/wai-aria-practices-1.1/ including *all* required behaviors (keyboard in particular), roles, aria attributes, etc.

**Comment by straleyb** [comment]
Fixed already by #2073 . Closing
