### ISSUE TITLE
Add text about what user gets for signing up

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2049]
### Descriptive summary
Add a short blurb about what the user gets for signing up @kmthorn @petersec for text.
Add right below `Sign Up` bold text.

### Expected behavior
Short paragraph below sign up text

**Comment by kmthorn** [comment]
Add the following text to the right of the sign up form.

# Looking to Sign Up for an Oregon Digital Account?

## I am affiliated with UO or OSU.

- Great! You do not need to sign up for an account. UO and OSU affiliates can just login with your university credentials.
- Once done, you will have access to all of the material that your university offers through Oregon Digital, as well as the ability to select, organize, and share Oregon Digital materials with others.

## I am not affiliated with UO or OSU.

- If you are not affiliated then you need to sign up for an account
- Once done, you will have the ability to select, organize, and share Oregon Digital materials with others.

**Comment by straleyb** [comment]
To right of sign up.

**Comment by straleyb** [comment]
QA: This will show up next to the sign up form on the sign up page. An unregistered user visits the site, clicks sign up, to the right of the sign up form shows the information displayed above.

**Comment by straleyb** [comment]
This is ready for QA. Its related to #2049 and has been looked at by chris and azle.

**Comment by petersec** [comment]
QA Pass (ref #2609 )
