### ISSUE TITLE
Change placehold for "search within results" search box

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2050]
### Descriptive summary
The search box placeholder inside the search results is too long to see on ipad/mobile.

Change the text to `Search within` leave the sr-label as `search within results`
Expand the width of the search box to the size of facets

### Expected behavior
Search placeholder is visible in mobile/ipad size & the search box is full width.

### Accessibility Concerns
there is a label above the search box that needs to still be linked to the search box

**Comment by shieldsb** [comment]
QA pass.
