### ISSUE TITLE
Explore collections copy action shouldn't say copy until copied

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2051]
### Descriptive summary
The copy button in explore collections pops up `copied` when hovered. It should say `copy link` or something similar. Then when clicked it can say `copied`

### Expected behavior
Copy button only shows `copied` when text is coped

**Comment by CGillen** [comment]
Check if this is still issue before work

**Comment by shieldsb** [comment]
Now says "Copy link to clipboard" when you hover on it. However, when you click it still says "Copied" and doesn't change to "Copied"  - it does highlight the link though.

**Comment by lamtu1** [comment]
@CGillen Just double check on this. When going to the`Explore Collection`, and I clicked on the `copy` button, as Beth mention above, the copy button will display "Copy link to clipboard" when hover and clicked on it, it will say "Copied" for one second before revert back to the "Copy link to clipboard" message.

Was wondering if this will be good as it is or we need to change it up to say 'Copied' indefinitely when clicked until somebody refresh the page for the old message to reappear or extend the message to display longer before switching back?

**Comment by CGillen** [comment]
That should be ok. If there's a way to make the popup stay and say copied until the user leaves hover that's probably best, but not necessary. Go ahead and close & send to QA if you don't want to try the above or it's just not working out. don't spend too much time on it

**Comment by lamtu1** [comment]
`NOTE:` After trying the code out, it is best to leave it as where it is currently at the state based on feedback.
