### ISSUE TITLE
Advanced search configuring what type of input is required for each field

### ISSUE THREAD

**Issue by kmthorn** [OregonDigital/OD2#2065]
### Descriptive summary

As a user I want to be able to interact with the advanced search in the following ways:

- free text
- type ahead
- date range

### Expected behavior
 
- All fields, Free-text. Search like the global basic search
- Title (combined), Free-text
- Collections, Type-ahead, multi-value select
- Copyright (combined), Type-ahead, multi-value select, controlled vocab for rights statements/creative commons
- Creator (combined), free text
- Description (combined), free text
- Date (combined), Date start and end. [Model after University of Houston.](https://digital.lib.uh.edu/) 
- Institution, Type-ahead, multi-value select
- Language, Type-ahead, multi-value select
- Subject (combined), Free-text

### Related work

#2064 

### Accessibility Concerns

Check type ahead against [https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html)

**Comment by straleyb** [comment]
QA:
The advanced search page should properly display the free text fields and facets as type ahead. Date is a type ahead as well and an enhancement is to make it a date slider.

**Comment by shieldsb** [comment]
QA pass.  Date range still needs to be added.
