### ISSUE TITLE
Bulk review of works

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2067]
### Descriptive summary
The review page allows for a single item to automatically advance in the review workflow. Metadata would also like it if there could be checkboxes for multiple works to be advance as well. This can look exactly like the `save selected to` functionality.

The review queue can be trimmed down to only the list view, so the grid view doesn't need to be taken into account. This was already the mindset for the single approve button work.

This is not part of the Notch8 bulk ingest work.

### Expected behavior
Multiple works can be selected from the review queue UI and moved to the next review step when submitted.
Note: As of now, we only have one review step. Is it possible/trivial to make work advancement workflow agnostic?

### Related work
Required by #1654

### Accessibility Concerns
Compare functionality with current search results page issues

**Comment by straleyb** [comment]
QA:
When on the review page, you should be able to click check boxes on works that need to be reviewed and click the Review works button at the top of the review queue. This should review the works without redirecting. When the works are reviewed, they should not show up in the review queue.

**Comment by jsimic** [comment]
Tried to review 4 Dan Powell photos in review queue and got confirmation toast stating it would take a few minutes. 2.5 hours later they do not appear to have be reviewed or removed from the review queue

**Comment by sseymore** [comment]
This worked for me. Bulk reviewed and they disappeared from the Review queue. QA pass.
