### ISSUE TITLE
Work Show Page has 'Contact Us' appended at the end of Page Title

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2068]
### Descriptive summary

With the Contact Us tab added to the work show page, 'Contact Us' is now appended to the end of the page title.

Example:
https://staging.oregondigital.org/concern/images/zs25x8763?locale=en
Page Title: `OSU Wins National Baseball Championship | Oregon Digital (Development)Contact Us`

### Expected behavior

Page Title: `OSU Wins National Baseball Championship | Oregon Digital (Development)`

### Related work

https://github.com/OregonDigital/OD2/issues/1550 - Add Contact Us tab to work show page

**Comment by CGillen** [comment]
It's worse than this now. The whole title is duplicated many times

**Comment by straleyb** [comment]
Browser tab title is spooky.

**Comment by shieldsb** [comment]
QA pass.
