### ISSUE TITLE
Explore Collections page has singular 'Collection' in Page Title

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2069]
### Descriptive summary

The Page Title for the Explore Collections page is 'Explore Collection'

### Expected behavior

Page Title matches link and other references as 'Explore Collections'

### Related work

N/A

### Accessibility Concerns

N/A

**Comment by CGillen** [comment]
Generally improve title

**Comment by CGillen** [comment]
Fixed by #2493

**Comment by shieldsb** [comment]
QA pass.
