### ISSUE TITLE
[2] When oEmbed media is present, player should replace Universal Viewer box

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#207]
### Descriptive summary

When oEmbed media is present, it should be the only viewer/player shown, and should replace the Universal Viewer box in the same location. End users should not have to care whether media is from an oEmbed endpoint or not, and should not get a substantially different experience.

Added 10/8/2019: oEmbed association with work should be done at the FileSet level, not metadata. A work should accept oEmbed URL in place of image uploads.

### Expected behavior

When oEmbed media is present, it should be the only viewer in the same place as Universal Viewer.
oEmbed should not display as a field along with other descriptive metadata.

### Related work

#208

**Comment by vantuyls** [comment]
if i add oembed metadata and then go to add a file, what is the behavior?

if i add a file, then later add oembed metadata, what is the behavior?

**Comment by CGillen** [comment]
#208 dictates files or oEmbed, but not both. Adding files after oEmbed and adding oEmbed after files should result in failures/errors.
If #208 works correctly, it should be safe to assume display of one or the other, based on the presence of oEmbed metadata.

**Comment by mccallum** [comment]
oEmbed should function at the fileset level and not at the work level

investigate - oEmbed in place of UViewer at that fileset level

**Comment by CGillen** [comment]
#1345 moved oEmbed to the fileset level and replaces UV when an oEmbed fileset is present
