### ISSUE TITLE
External link icons/functionality next to specific metadata fields

### ISSUE THREAD

**Issue by kmthorn** [OregonDigital/OD2#2078]
### Descriptive summary
As a user I want to be taken to external resources with deeper descriptions of specific metadata fields. The existence of these resources is indicated by external link arrow icons that are placed next to select metadata fields. 

### Expected behavior
- Rights external link to the associated linked data source
- License external link to the associated linked data source
- Finding Aid external link to the associated linked data source
- Local Collection external link to the associated linked data source
- Open in a new tab

### Related work
- Link to related tickets or prior related work here.
- [Work show page wireframes](https://drive.google.com/drive/u/0/folders/1gFBKTkc2Gcgyz-0ZJVdhrkXsYiaiqXfK)
#2075 

### Accessibility Concerns
- The link should open in a new tab
- Link needs a label

**Comment by wickr** [comment]
Considered complete with the shift to 'footnote' style links to references with the full URI.
