### ISSUE TITLE
Collection metadata field is displaying collection identifier instead of collection name

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2080]
### Descriptive summary
While browsing work metadata, the collection field shows a link to the collection, but the text for the link is the collection identifier. This is useless information for users, they care about the name of the collection.

### Expected behavior
The work show page shows the title of the collection and links to the collection in the collection metadata field

### Accessibility Concerns
Accessible link text should improve with the collection title

**Comment by jsimic** [comment]
#1384
