### ISSUE TITLE
Cookie Consent Form

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2094]
### Descriptive summary
We need to implement a cookie consent form for GDPR and ePrivacy Directive compliance. This looks like a resource we can use: https://www.freeprivacypolicy.com/free-cookie-consent/

We need to review our use of cookies outside of session and GA. Do we use any others?

### Expected behavior
Use is made aware of cookies usage and can easily opt-out

### Accessibility Concerns
The pop-up/banner should be audited

**Comment by CGillen** [comment]
Hyrax with a cookie consent form:
https://github.com/gwu-libraries/scholarspace-hyrax/issues/259

**Comment by shieldsb** [comment]
QA fail.  The "Got it!" button is not working, so there is no way to clear the cookie banner display.

**Comment by shieldsb** [comment]
QA pass.
