### ISSUE TITLE
Duplicate email registration causes ack

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2095]
### Descriptive summary
When a user tries to register with an already registered email, they get Ack. An error message should flash instead telling the user that email is already in use.

### Expected behavior
Duplicate email registrations doesn't Ack and user is made aware of the problem.
"This email is already in use. Please use the forgot my password link below to set a new password"

**Comment by shieldsb** [comment]
Message doesn't match expected behavior text listed in ticket 

![image](https://user-images.githubusercontent.com/53542788/182893855-286ae7b2-8008-4a56-8ed8-a66f998418a2.png)

**Comment by shieldsb** [comment]
QA fail.  Text is correct, though there are accent marks before and after forgot my password.  However, there is no actual link for forgot my password on the page. 
![image](https://user-images.githubusercontent.com/53542788/184199885-553b7b9d-44d6-4f75-815a-2b15cbcefb1c.png)

**Comment by shieldsb** [comment]
QA pass.  Minor thing, but we might want to flip "send me reset password instructions" to "send me password reset instructions" @CGillen
