### ISSUE TITLE
'Geographics' link in TOC doesn't work, doesn't match edit form heading 'Locations'

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2098]
### Descriptive summary

On the edit form, the heading 'Locations' doesn't match the Table of Content's 'Geographics'. Clicking the 'Geographics' heading doesn't go anywhere on the edit form: https://staging.oregondigital.org/concern/images/df718441m/edit?locale=en#Geographics

### Expected behavior

Clicking 'Geographics' in the edit form TOC jumps user to correct spot

### Related work

#1201 
#1202 

### Accessibility Concerns

Nothing new, just making links and headings match

**Comment by straleyb** [comment]
Just messed up for image and video. Update the rendered TOC heading

**Comment by shieldsb** [comment]
QA pass.
