### ISSUE TITLE
Model metadata and predicate changes after MAP updates

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#210]
### Descriptive summary

The Metadata Application Profile wasn't super clear if there was a predicate change for OD2. I've tried to emphasize that more, and the OD2 Column now comes first.

After QA on #129, here's a list of things that need updating:

- [x] oembed doesn't need :stored_searchable, just need to store it not search tokenized fields
- [x] Remove caption_title
- [x] Biographical Information: new predicate
- [x] Description of Manifestation: new predicate
- [x] Form of Work: new predicate
- [x] Mode of Issuance: new predicate
- [x] Cultural Context: new predicate
- [x] Style or Period: new predicate
- [x] TGN: new predicate
- [x] Material: new predicate
- [x] Technique: new predicate
- [x] Place of Production: new predicate

### Related work

#129

**Comment by vantuyls** [comment]
i see this is closed/merged. did QA happen? @straleyb @revgum

**Comment by straleyb** [comment]
im pretty sure @wickr Did it.

**Comment by wickr** [comment]
QA OK.
