### ISSUE TITLE
Create About Pages

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#2101]
### Descriptive summary

A series of pages containing information about Oregon Digital 2 need to be created and made public

### Expected behavior

Clicking on links contained in the site footer or on the home page should send the user to one of the informational pages. On any given page, a sidebar will ease navigation to other informational pages. There are a series of [wireframes](https://drive.google.com/drive/folders/1Yb1fUvcP2ap5TNo7F006ZiamXixwEJWb?usp=sharing) detailing the style and layout of each page:

- [x] Mission and Vision ([wireframe](https://drive.google.com/drive/u/2/folders/1mqIWCppDRLbrIiBd6lWr1SLVvM3qAyVC), [content](https://docs.google.com/document/d/1lixkmKiHSgqvmM8zfLYF_WLAOXpM-Zb516YYkRPpIJA/edit#))
- [x] About ([wireframe](https://drive.google.com/drive/folders/13qng4UmQLgPBgqPM25G0BCRTerLmqj_J?usp=sharing), [content](https://docs.google.com/document/d/1xcNuUjDyAarMaps5FuXXwoWVPS3DGszsYhtmpCEEMHs/edit))
- [ ] How to Use This Website  ([wireframe](https://drive.google.com/drive/u/2/folders/1jNoGNoMWagolnaZFq6jzRrFHeEUUVim9), content TBD)
- [x] Privacy Policy ([wireframe](https://drive.google.com/drive/u/2/folders/1E3w4RiYD8-jHeKYltSsqIDSGoARP6RXo), [content](https://docs.google.com/document/d/1NiBt64ZlTxeiC94xpCys-_XwqZGRRZ6YTpweCnPx4w8/edit))
- [x] Terms of Use ([wireframe](https://drive.google.com/drive/folders/1Q55-xsF2Mfwm2zf8LQR51X1Z7XqcYSDb?usp=sharing), [content](https://docs.google.com/document/d/1CGHaZ3mDRMPorGDZfJSp9sv_JWliEZ9lgoTW8Iob4AI/edit))
- [x] Copyright and Usage Requests ([wireframe](https://drive.google.com/file/d/1c6WCbYUocU4wh8ujC_xFjkjmSe0LrPP6/view?usp=sharing), ([content](https://docs.google.com/document/d/1HC_YBgFUIgv5TPUcLrSTL9N4kLEs9tjRAMBneChhSK8/edit))
- [x] Harmful Content Statement ([wireframe](https://drive.google.com/drive/folders/1fjqJmblzX7ApNVYNLWva1AFuCtGNGDHf?usp=sharing), [content](https://docs.google.com/document/d/1PWhAR7HS0jGdgMiO55SXOqcCJxSUmqKJfJ3fLz0ibRo/edit?usp=sharing))
- [x] Take-Down Policy ([wireframe](https://drive.google.com/drive/folders/1ETHb3jgDHND8OfQzcWdIsmXj9yaO_VLC?usp=sharing), [content](https://docs.google.com/document/d/1CGHaZ3mDRMPorGDZfJSp9sv_JWliEZ9lgoTW8Iob4AI/edit))
- [x] Collection Development Policy (UO) ([OD2 wiki link](https://github.com/OregonDigital/OD2/wiki/Collection-Development-Policy-(University-of-Oregon)))
- [x] Collection Development Policy (OSU) ([OD2 wiki link](https://github.com/OregonDigital/OD2/wiki/Collection-Development-Policy-(OSU)))

### Related work

#1339, #1147, #597

### Accessibility Concerns

Pages and navigation should meet accessibility standards for site

**Comment by jsimic** [comment]
@kmthorn I've also left comments on your comments

**Comment by kmthorn** [comment]
@petersec and @kmthorn will revisit the content for these pages with an eye towards use in instruction and public services. They will do this beginning in 2022.

**Comment by azle** [comment]
@jsimic I created temporary templates for pages awaiting content and I doubled checked the templates that have content ready and replaced as needed. They are all in the final folder and updated links in the ticket.

**Comment by azle** [comment]
@jsimic I created the mock up page for the mission and vision statement. I just need to know what the proper title should be. Here is the link to the mockup: https://drive.google.com/drive/u/2/folders/1mqIWCppDRLbrIiBd6lWr1SLVvM3qAyVC

**Comment by CGillen** [comment]
QA for check marked pages. @jsimic @mellinma we need content for 

- [ ] How to Use
- [ ] Copyright
- [ ] Collection development policies

**Comment by petersec** [comment]
I've drafted Copyright language and sent it to @jsimic for her review. We'll update this ticket once it's finalized.

The OSU collection development policy published on the OD2 wiki has been finalized. (not sure if UO is finalized or not)

I'd be happy to work with @jsimic and @mellinma on the How to Use text.

**Comment by jsimic** [comment]
@CGillen The final version of UO's collection development policy is also on the wiki and can be a direct link.

**Comment by petersec** [comment]
@CGillen The copyright text is now finalized. I've updated the ticket description to include the link to our Google Doc. In addition to the text, I'm recommending that a few screenshots be included as well for illustration purposes.

**Comment by petersec** [comment]
QA notes for the About pages:

- About Oregon Digital - pass

- Mission and 'Vission' Statement - fail (Vision is misspelled in the sidebar link and page header)

- How to Use This Website - fail (page content hasn't been created yet - @kmthorn  and I will be working on this starting in October)

- Privacy Policy - pass

- Terms of Use - pass

- Copyright and Usage Requests - fail (@CGillen - I'm getting the Ack message when trying to access)

- Harmful Language Statement - fail (page title, 'Harmful Content Statement,' does not match link title. @jsimic do you have any preferences about which one we use? I'm inclined toward Harmful Content Statement, since there is plenty of imagery that could prove harmful.)

- Take-Down Policy - pass

- Collection Development Policy - UO & OSU (not sure - the content is fine, but it lives in GitHub. @jsimic Do we want to link out of Oregon Digital to the GitHub wiki pages? Or add this content into Oregon Digital as with all the other About pages? My preference would be to add them into Oregon Digital, so that the user isn't shipped off to another location.)

**Comment by jsimic** [comment]
It should be Harmful Content Statement.

Linking out to the wiki versions of the CD policies means we only have to update them in one place if/when they change.

**Comment by carakey** [comment]
I noticed some formatting problems in the Harmful Content Statement page at https://prod.oregondigital.org/harmful?locale=en. The block of text at the bottom of the page is meant to be three more sections with headers, bulleted lists, and links.

**Comment by shieldsb** [comment]
@CGillen Here are links to the videos from Chris and Kate for the How to Use This Site section.

Tutorial 1 of 2 on running searches in Oregon Digital. This video was created by Kate Thornhill and Chris Petersen, Service Managers for the Oregon Digital 2 development initiative: https://media.oregonstate.edu/media/t/1_744k8lby 

Tutorial 2 of 2 on running searches in Oregon Digital. This video was created by Kate Thornhill and Chris Petersen, Service Managers for the Oregon Digital 2 development initiative: https://media.oregonstate.edu/media/t/1_89kpwqgm

**Comment by petersec** [comment]
@CGillen Here are three more How-To videos that are ready:

**Browsing and Searching from the Collections Index Page (three-part tutorial)**
- [The Collections Index Page](https://media.oregonstate.edu/media/t/1_cn56ox03/2947392)
- [Overview of a Collection Landing Page](https://media.oregonstate.edu/media/t/1_aj3jcw6r/2947392)
- [Searching from a Collection Landing Page](https://media.oregonstate.edu/media/t/1_850ipgcw/2947392)

Scripts for three more videos focusing on item show pages (image, text, complex object) have been written and will be created the week of March 6.

**Comment by petersec** [comment]
Three more How-To videos are ready to be added to to Oregon Digital:

- [Item Pages for Photographs](https://media.oregonstate.edu/media/t/1_czheb1lp/2947392)
- [Item Pages for Text Objects](https://media.oregonstate.edu/media/t/1_z72dvgvb/2947392)
- [Item Pages for Complex Objects](https://media.oregonstate.edu/media/t/1_2oxdlp0v/2947392)

Also, we have put together some ideas for additional How-To page content and organization -- see this [Google Doc](https://docs.google.com/document/d/17xaOFMCH-_5s-txlTIzroFF3369Q-chAm-EGau5Oay8/edit#heading=h.byqkkjiuntp6).

**Comment by petersec** [comment]
This is basically QA pass, though I found a grammatical error (introduced by Kate and I in our original document) in one of the video titles on the [How to Use Oregon Digital](https://staging.oregondigital.org/use?locale=en) page. 

The title `3.3 - What is and How to Use Complex Objects: Print Examples as well as Audio and Video Object Examples` should read `3.3 - What are and How to Use Complex Objects: Print Examples as well as Audio and Video Object Examples ` 

@lamtu1 - can we make this small change?

**Comment by lamtu1** [comment]
@petersec I can make that changes to the title of that section really quick and push up a small PR up for it.
