### ISSUE TITLE
Remove Hyrax Core Metadata fields from GenericMetadata model

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#211]
### Descriptive summary

The Hyrax Core Metadata fields were added to GenericMetadata but they don't need to be there, they're still included. There are errors for the same predicates being defined for multiple instances of those properties.

### Expected behavior

We can rely on the Hyrax Core metadata fields being in place and don't need to specify them in GenericMetadata.

### Related work

#129

**Comment by straleyb** [comment]
QA TESTING: This can be checked by cross referencing the code changes to the MAP. This was mostly a change to remove a lot of duplicate predicates which is fixed in #219

**Comment by wickr** [comment]
Moving to In Progress since this is fixed by #219 which isn't yet merged.

**Comment by wickr** [comment]
QA OK.
