### ISSUE TITLE
[SEE #155] Setup change password for user

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#212]
### Descriptive summary

A logged in user should be able to change their password.

**Comment by vantuyls** [comment]
QA - logged in using devise; changed password; logged in using new password (QA PASS)

Additional QA - tried combinations of wrong, not matching, etc. passwords on the password recovery form and was not allowed to modify password without 1) using the proper current password or 2) providing matching new passwords (QA PASS)
