### ISSUE TITLE
Setup smtp for OD2

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#213]
### Descriptive summary

Since OD2 will be sending out emails to people, it will need its own email set up. This means that a unique email username and password will be needed and will be the email username that sends out emails to people in situations like a user needed to request their email address from OD2 because it was forgotten. 

This means we need:
Email Username
Email Password 
Configuration in OD2

**Comment by decimalator** [comment]
#215 is a blocker for this

**Comment by straleyb** [comment]
QA: Emails are being sent out on the staging server.

**Comment by straleyb** [comment]
Waiting for verification that its working properly on staging server. After this is working, the tickets below it in the project can be QA'd

**Comment by straleyb** [comment]
@revgum @decimalator

**Comment by revgum** [comment]
Confirmed email flows from Rails => Amazon SES => Email Address... SMTP at the infrastructure level is functional.
