### ISSUE TITLE
Work count on collection landing page includes unreviewed works

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2144]
### Descriptive summary
https://staging.oregondigital.org/collections/fairbanks?locale=en @jechols first recognized this issue while QA'ing this page. The total work count was listed at 20, but if you hit 'View all items' no works were found. Same with the dashboard. It would say 20 items total, 0 works in the collection. I think that is possibly valid for the dashboard, because we might not want to get confused why there's works in the dashboard but not the front end.

### Expected behavior
Total work count on collection landing and explore collections does not reflect unreviewed works.

**Comment by straleyb** [comment]
Filter items out when displaying amount that are not reviewed/private

**Comment by shieldsb** [comment]
QA fail.  When I select view all on any collections landing page, it takes me to the same search results for works in all collections. Same happens when I'm logged in and logged out.  
![image](https://user-images.githubusercontent.com/53542788/193169642-cb435909-8922-4904-8b77-e9ec49afe9d8.png)

**Comment by shieldsb** [comment]
This works for a majority of collections, but there are still some that show no results.  Could this be based on when the collections were added, or for some other reason @straleyb @CGillen

**Comment by shieldsb** [comment]
QA pass.
