### ISSUE TITLE
Collection Search and Advanced Search

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2149]
### Descriptive summary
We chose to make the collection landing search fields/facet mirror the advanced search fields/facets. We will keep this going but need to improve styling + verbiage. We also should explore the possibility of reordering facet values alphabetically, rather than most values.

### Expected behavior

Look for @azle's wireframe for improved advance/collection search facets
Explore possibility of reordering facet value order (alpha if possible)
Change placeholder & `.sr-only` help text to say "Start typing or choose from list"

### Related work
https://drive.google.com/drive/u/1/folders/12mphWVRe01oO5bffK7RhLUGyJ201drlI

### Accessibility Concerns
Placeholder text is not read be screen readers, make sure there's a hidden help text associated with the facets section (or individual facets)

**Comment by jsimic** [comment]
@CGillen Styling is updated for wireframes in [Advanced Search wireframes folder](https://drive.google.com/drive/u/0/folders/1bF30M2ftI50Syhhg7hL4MIOtn9DmZFEj)

**Comment by straleyb** [comment]
Wireframes

**Comment by azle** [comment]
@CGillan, can we remove the following Search Tips:

Select "match all" to require all fields.
Select "match any" to find at least one field.
Combine keywords and attributes to find specific items.

Talking with Julia and we would like to move the Search Tips below the "Search" Button. Potentially in the future we would like to move Search Tips above the form fields and have the word "Search Tips" be expandable when clicked to reveal the search tips. Just like "read more" on collection landing pages.
