### ISSUE TITLE
Setup DNS records for AWS Simple Email Service (SES)

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#215]
To use AWS Simple Email Service (SES) we need to setup a few DNS records in the oregondigital.org domain. The necessary records are below. If possible, it would be great to get University of Oregon IS to delegate the oregondigital.org domain so we can manage it within AWS Route53.

TXT record (for domain verification)
_amazonses.oregondigital.org  -->  ijkrG1GAuiLtNvQL64z1RTDN0fpLCMUZNYW+ZpvbEPg=

DKIM records (tell spam filters who we are, to avoid spam classification)
ti6gtbd5kklonhgd7z67u4gxjytipv6q._domainkey.oregondigital.org --> ti6gtbd5kklonhgd7z67u4gxjytipv6q.dkim.amazonses.com (CNAME)
pulp7qjsqhdbso37ilwga3oqdtijlixr._domainkey.oregondigital.org -->
pulp7qjsqhdbso37ilwga3oqdtijlixr.dkim.amazonses.com (CNAME)
vtlb7vjp6beuml7w2oxu4h7zsvbruq2r._domainkey.oregondigital.org -->
vtlb7vjp6beuml7w2oxu4h7zsvbruq2r.dkim.amazonses.com (CNAME)

**Comment by revgum** [comment]
@decimalator I'm pretty sure this was completed in the last sprint in cycle 2, feel free to close this out if you confirm.

**Comment by revgum** [comment]
Verified
