### ISSUE TITLE
ubio fetch failure throws error

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2153]
### Descriptive summary

Attempting to retrieve a label from ubio resulted in
ERROR -- : Failed to open TCP connection to ubio.org:80 (Connection refused - connect(2) for "ubio.org" port 80)
(btw, is there is a limit on how many requests we can make?)

### Expected behavior
Fetching a label from ubio should fail gracefully allowing caller to continue

Traceback:
ERROR -- : Failed to open TCP connection to ubio.org:80 (Connection refused - connect(2) for "ubio.org" port 80)
Traceback (most recent call last):
       16: from (irb):5:in `process_pids'
       15: from (irb):5:in `each'
       14: from (irb):10:in `block in process_pids'
       13: from (irb):57:in `fix_visibility'
       12: from app/actors/oregon_digital/actors/create_with_oembed_url_actor.rb:19:in `update'
       11: from app/indexers/image_indexer.rb:6:in `generate_solr_document'
       10: from app/indexers/generic_indexer.rb:15:in `generate_solr_document'
        9: from app/indexers/concerns/oregon_digital/indexing_dates_behavior.rb:9:in `generate_solr_document'
        8: from app/indexers/oregon_digital/deep_indexing_service.rb:19:in `fetch_external'
        7: from app/indexers/oregon_digital/deep_indexing_service.rb:19:in `each'
        6: from app/indexers/oregon_digital/deep_indexing_service.rb:20:in `block in fetch_external'
        5: from app/indexers/oregon_digital/deep_indexing_service.rb:27:in `block (2 levels) in fetch_external'
        4: from lib/oregon_digital/controlled_vocabularies/scientific.rb:22:in `fetch'
        3: from lib/oregon_digital/controlled_vocabularies/vocabularies/ubio.rb:20:in `fetch'
        2: from app/services/oregon_digital/xml_parse_service.rb:7:in `xml'
        1: from app/services/oregon_digital/xml_parse_service.rb:11:in `query_xml'
Faraday::ConnectionFailed (Failed to open TCP connection to ubio.org:80 (Connection refused - connect(2) for "ubio.org" port 80))

**Comment by lsat12357** [comment]
I tried looking up a ubio term on Blazegraph, and was able to get a label, however this is from the logs:
7qr6k:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)        
7qr6k:I, [2021-12-29T10:12:48.242383 #40]  INFO -- : [ActiveJob] [Hyrax::Migrator::Jobs::MigrateWorkJob] [b78d0a92-c48e-4967-8770-cdb906de6176] Fetching http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:835129
3 from the authorative source. (this is slow)
dzcgp:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)        
dzcgp:I, [2021-12-28T15:05:51.343146 #40]  INFO -- : [ActiveJob] [CreateDerivativesJob] [c1d0525a-bbc1-480b-8c04-569c9f496719] Fetching http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293 from the author
ative source. (this is slow)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
fk7tq:I, [2021-12-28T15:00:03.328669 #40]  INFO -- : [ActiveJob] [AttachFilesToWorkJob] [b7acab95-bc25-411f-a693-b776a8a42bc6] Fetching http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293 from the author
ative source. (this is slow)
fk7tq:I, [2021-12-28T15:00:18.485455 #40]  INFO -- : [ActiveJob] [AttachFilesToWorkJob] [b7acab95-bc25-411f-a693-b776a8a42bc6] Fetching http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293 from the author
ative source. (this is slow)
fk7tq:I, [2021-12-28T15:00:52.207059 #40]  INFO -- : [ActiveJob] [AttachFilesToWorkJob] [b7acab95-bc25-411f-a693-b776a8a42bc6] Fetching http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293 from the author
ative source. (this is slow)
fk7tq:I, [2021-12-28T15:01:10.084611 #40]  INFO -- : [ActiveJob] [AttachFilesToWorkJob] [b7acab95-bc25-411f-a693-b776a8a42bc6] Fetching http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:8351293 from the author
ative source. (this is slow)

**Comment by lsat12357** [comment]
another connection error for ubio

E, [2022-02-07T11:46:10.635004 #40] ERROR -- : [ActiveJob] [AttachFilesToWorkJob] [d1d5ee06-4c4b-4e56-b8ff-69c53b77095d] Error performing AttachFilesToWorkJob (Job ID: d1d5ee06-4c4b-4e56-b8ff-69c53b77095d) from Sidekiq(default) in 157182.19ms: Faraday::TimeoutError (Net::ReadTimeout with #<TCPSocket:(closed)>):
/usr/local/lib/ruby/2.7.0/net/protocol.rb:217:in `rbuf_fill'
/usr/local/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
/usr/local/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
/usr/local/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
/usr/local/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
/usr/local/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
/usr/local/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
/usr/local/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
/usr/local/lib/ruby/2.7.0/net/http.rb:1492:in `request'
/usr/local/lib/ruby/2.7.0/net/http.rb:1485:in `block in request'
/usr/local/lib/ruby/2.7.0/net/http.rb:933:in `start'
/usr/local/lib/ruby/2.7.0/net/http.rb:1483:in `request'
/usr/local/lib/ruby/2.7.0/net/http.rb:1241:in `get'
/usr/local/bundle/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:86:in `perform_request'
/usr/local/bundle/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:44:in `block in call'
/usr/local/bundle/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:93:in `with_net_http_connection'
/usr/local/bundle/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:39:in `call'
/usr/local/bundle/gems/honeycomb-beeline-2.4.0/lib/honeycomb/integrations/faraday.rb:29:in `block in call'
/usr/local/bundle/gems/honeycomb-beeline-2.4.0/lib/honeycomb/client.rb:70:in `start_span'
/usr/local/bundle/gems/honeycomb-beeline-2.4.0/lib/honeycomb/integrations/faraday.rb:16:in `call'
/usr/local/bundle/gems/faraday-0.17.4/lib/faraday/request/url_encoded.rb:15:in `call'
/usr/local/bundle/gems/faraday-0.17.4/lib/faraday/rack_builder.rb:143:in `build_response'
/usr/local/bundle/gems/faraday-0.17.4/lib/faraday/connection.rb:387:in `run_request'
/usr/local/bundle/gems/faraday-0.17.4/lib/faraday/connection.rb:138:in `get'
/usr/local/bundle/gems/faraday-0.17.4/lib/faraday.rb:102:in `method_missing'
/data/app/services/oregon_digital/xml_parse_service.rb:11:in `query_xml'
/data/app/services/oregon_digital/xml_parse_service.rb:7:in `xml'
/data/lib/oregon_digital/controlled_vocabularies/vocabularies/ubio.rb:20:in `fetch'
/data/lib/oregon_digital/controlled_vocabularies/scientific.rb:22:in `fetch'
/usr/local/bundle/gems/hyrax-3.0.1/app/indexers/hyrax/deep_indexing_service.rb:52:in `fetch_value'
/usr/local/bundle/gems/hyrax-3.0.1/app/indexers/hyrax/deep_indexing_service.rb:45:in `fetch_with_persistence'
/data/app/indexers/oregon_digital/deep_indexing_service.rb:27:in `block (2 levels) in fetch_external'
/usr/local/bundle/gems/active-triples-1.1.0/lib/active_triples/relation.rb:323:in `block in each'

**Comment by lsat12357** [comment]
this seems to be unrelated to this problem https://github.com/OregonDigital/OD2/issues/1628
which I don't think came up on the last round of testing

**Comment by lsat12357** [comment]
ugh, the namespace on the error is wrong.

**Comment by lsat12357** [comment]
QA
At the moment, ubio is timing out, so this is testable
uri = 'http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:3921915'
s = OregonDigital::ControlledVocabularies::Scientific.new(uri)
s.fetch
##should get the ControlledVocabularies::ControlledVocabularyFetchError from ubio.rb and reraise

**Comment by wickr** [comment]
QA pass
Used different identifier in URI since the first one was fetched ok. Got the CV fetch error.

```
irb(main):016:0> uri = 'http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:3921914'
=> "http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:3921914"
irb(main):017:0> s = OregonDigital::ControlledVocabularies::Scientific.new(uri)
=> #<OregonDigital::ControlledVocabularies::Scientific:0x7d514 ID:<http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:3921914>>
irb(main):018:0> s.fetch
[INFO] fetch_cached_graph(http://ubio.org/authority/metadata.php?lsid=urn:lsid:ubio.org:namebank:3921914) not found in triplestore cache (http://blazegraph.od2-test.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
Traceback (most recent call last):
        3: from (irb):18
        2: from lib/oregon_digital/controlled_vocabularies/scientific.rb:19:in `fetch'
        1: from lib/oregon_digital/controlled_vocabularies/scientific.rb:29:in `rescue in fetch'
OregonDigital::ControlledVocabularies::ControlledVocabularyFetchError (OregonDigital::ControlledVocabularies::ControlledVocabularyFetchError)
```
