### ISSUE TITLE
[1] Build and ingest workflows

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#22]
### Descriptive summary

Each `worktype` will have its own workflow based on specific needs of either an institution or process needed to accept a type of work in the application. These workflows are expressed in a configuration file found here. https://github.com/osulp/Scholars-Archive/tree/master/config/workflows or in `/config/workflows/*.json`. These workflows will be generated based on a state machine type flow. For information about state machines see here. https://en.wikipedia.org/wiki/Finite-state_machine#Classification. There is also a wiki that has been written about hyrax workflows found https://github.com/osulp/Scholars-Archive/wiki/Workflows and https://github.com/samvera/hyrax/wiki/Defining-a-Workflow . The workflows will then need to be heavily tested as their layout, states, to and from actions, can tend to get quite complicated. 

The workflows are built using a system called Sipity. This library can be found here: https://github.com/ndlib/sipity

This is a library that can arbitrarily build a set of rules based on a state machine. These rules define the state machine. How to get from one state to the next, what are any processes that need to be ran when you transition to a certain state, and many other different things. These workflows will have to be verified heavily, but progress needs to be made on them over time. @vantuyls Is the one who worked heavily on the workflows in ScholarsArchive, and would be a good consultant for this work. 

These will be committed to the repository, but make sure that when these PRs are being pushed up, to add a GIF of it working. We use LICEcap as our capture software, but any file in gif format should work.

https://licecap.en.softonic.com/ 

Checking and setting a workflow looks like this: 

![workflow](https://user-images.githubusercontent.com/6424683/46487364-a9b43380-c7b4-11e8-9450-08f6e6277bbe.gif)

Using a workflow is found in this dropdown:

![workflow2](https://user-images.githubusercontent.com/6424683/46487384-b9cc1300-c7b4-11e8-9055-51de19117c3d.gif)

### Expected behavior
After a workflow is created per the layout expressed in the previous links, and put in the proper place in the application, a rake task will need to be ran in order to generate the necessary workflow within the application. The system will express that an error exists in the workflow json file and fail to ingest, if it does not work. If it does, no error will be reported out. You can then check that the workflows exist in the dashboard > collections (under the all collections tab). When you edit a collection, you can express what workflows each work within that collection gets. Each `work type` will have its own admin set or collection.

### Related work

The related work associated with this ticket is the Completion of the MAP. The map will have to be completed to know what types of workflows are associated with each `work type`

### Related Tickets

**Comment by vantuyls** [comment]
Decision made at OD meeting on Nov 8 (https://docs.google.com/document/d/1VvzpvCVtWBujNqc03PcsiT5z3s4Rs0BUYWXWZ0iiq3s/edit)
- apply one step workflow to every worktype

**Comment by vantuyls** [comment]
@wickr @jsimic @petersec do we have a common email address that notifications should go to? i understand that @jsimic is currently triaging email but if we want to change that, now is the time.

**Comment by jsimic** [comment]
oregondigitalref@uoregon.edu is the email for the OD contact form. Right now I monitor it. Would it be possible for emails to be directed according to the person's registered email? i.e., a person with a uoregon email would have mail sent to the uoregon account. Better yet, for the collection/item from which the Contact link was clicked?

**Comment by petersec** [comment]
I'd definitely advocate for the latter, if it's possible. Most of the remote reference that we receive is from off-campus users. The relevant email address from the OSU side would be scarc@oregonstate.edu

We would also need to think about OD collections that are not directly associated with either OSU or UO; e.g., Lincoln County Historical Society, Siuslaw National Forest, etc. A quick glance indicates that the Institution field usually (always?) contains either OSU or UO, so perhaps that is where the system would look to figure out where to send a given patron request. Not sure if there are instances where UO and OSU both appear for a given item.

**Comment by mccallum** [comment]
I'd love to see some way of logging the OD correspondence emails for any or all on the insightful OD team to analyze at their leisure (very post-triage or even just once a year). That communication log could inform development beyond MVP, marketing efforts ("could we quote you on that?"), user experience, collection development, and other ways I can't think of, no doubt. Just my two cents. @jsimic @vantuyls

**Comment by vantuyls** [comment]
ok, for now, lets set this up for oregondigitalref@uoregon.edu. i'll create some additional issue(s) for an enhancement to route emails based on user domain.

**Comment by vantuyls** [comment]
closing in deference to more granular issues #334 and #333
