### ISSUE TITLE
Purge the IIIF cache of images when assets change or are removed

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#220]
#### Background

This involves our IIIF server's cache, so warrants a bit of explanation here:

We store our JP2s in S3, so when the IIIF server needs to serve up tiles for one of them, it has to cache the file locally.

RAIS has an [S3 plugin](https://github.com/uoregon-libraries/rais-image-server/wiki/S3-Images-Plugin) for serving images from S3, and part of that plugin handles caching files locally.

Via an [undocumented feature](https://github.com/uoregon-libraries/rais-image-server/blob/develop/src/plugins/s3-images/main.go#L73-L81) (which I plan to document once we kick the tires a bit more), we can configure this cache to live for a certain amount of time.  But however long it lives, whether we configure it for 5 minutes, 5 days, or just let it live indefinitely, we need to be able to purge anything cached if the asset's content changes in Oregon Digital.

#### What's needed

RAIS provides an [endpoint for purging cached data](https://github.com/uoregon-libraries/rais-image-server/wiki/Administration#purging-caches) which we can leverage to automate removal of cached items per asset's S3 id.  We will need to be able to translate from a Fedora pid to the asset's S3 id (but we'll need this anyway in order to display images in the first place).

We'll need to call this endpoint any time an asset is removed or its has a modified datastream.

### Expected behavior

When...

- ...an image is deleted
  - Ingest an image
  - View it with RAIS (i.e., verify that it's been processed for universal viewer)
  - Delete the image in OD
  - Verify that RAIS purged the image from its cache - this may require a low-level filesystem check
- ...an image is modified
  - Ingest an image
  - View it with RAIS (i.e., verify that it's been processed for universal viewer)
  - Modify the image in OD
  - Verify that RAIS purged the image from its cache - this may require a low-level filesystem check
  - Verify that viewing the new asset in universal viewer doesn't have remnants of the old image
- ...a PDF is deleted
  - Ingest a PDF
  - View **all pages** with RAIS
  - Delete the PDF in OD
  - Verify that RAIS purged **all pages' images** from its cache - this may require a low-level filesystem check
- ...a PDF is modified
  - Ingest a PDF
  - View **all pages** with RAIS
  - Update the PDF in OD
  - Verify that RAIS purged **all pages' images** from its cache - this may require a low-level filesystem check
  - Verify that all pages are for the new PDF; no remnants of the old cache show up
- ...an asset's metadata is changed, but the image or pdf don't change
  - Ingest an asset (image or PDF)
  - View it with RAIS
  - Update the asset's metadata without changing its image
  - Verify RAIS still has the image cached
  - This scenario may not be a huge priority; worst-case scenario is purging more from our cache than we technically need to

### Related work

Semi-related to #84

**Comment by jechols** [comment]
From @revgum:

> so when a fileset changes or updates, there should be a job that fires off in the actor stack to tell RAIS to clear its cache

**Comment by raybrarian** [comment]
@jechols - is this still valid due to S3 changes?

**Comment by jechols** [comment]
Hmm, good question.  It may be worth keeping around just because there are other bits of data RAIS can cache even when not using S3.  But if it's too much work, it's probably not worth it (but the risks should be known: for instance if we replace an image but we have enabled the in-memory tile caching, for a short while some tiles could be totally wrong)

**Comment by raybrarian** [comment]
Hey @jechols - is this issue still relevant? We *think* so (in a ticket review) but would like your input on this one. Thanks!

**Comment by jechols** [comment]
I think it is.  It may not be a high-priority item, I don't know, but it is an issue that exists.  Most systems do *not* purge IIIF caching when images change, because caches self-expire and massive change is rare, but it may be something we want.

This ticket was built more for the cloud-world we envisioned last year, though.  In a local setup, where we're not trying to cache everything under the sun (to avoid things like huge S3 pulls), it may not be important.

**Comment by jechols** [comment]
Given how unlikely this is to occur in the real world with RAIS, which only caches tiles in memory and very few of them, we decided to close this rather than try to spend a ton of time sending purge requests to RAIS.
