### ISSUE TITLE
controlled vocab repository does not include LocOrgs

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2200]
A number of assets failed on the megatest due to use of uris like http://id.loc.gov/vocabulary/organizations/oreuurm for repository. Use is valid on OD1 but perhaps it needs to be replaced prior to migration? or LocOrgs needs to be added to repository on OD2?

**Comment by sseymore** [comment]
@lsat12357 can we get a scrape of these assets to remediate?

**Comment by wickr** [comment]
We believe it was an intentional decision to not have this vocab on the Repository CV in OD2, so it doesn't need to be added to OD2.

**Comment by lsat12357** [comment]
see wickr's comment, this is being resolved with remediation on od1
