### ISSUE TITLE
/search

### ISSUE THREAD

**Issue by Lucifer2442** [OregonDigital/OD2#2202]
### Descriptive summary

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticomwk j

 w. Woq IKQEMPX

**Comment by CGillen** [comment]
Spam
