### ISSUE TITLE
Fix explore collections masonry view

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2215]
### Descriptive summary
Reimplement wireframe with a11y improvements

### Expected behavior
Wireframe

### Accessibility Concerns
All the a11y tickets

**Comment by azle** [comment]
@CGillen QA the following link: https://staging.oregondigital.org/explore_collections/all#content, the page is valid except for 1 mismatch error. See screensnap below:

FastPass: passed
NuChecker: passed, no errors or warnings to show 

Here is the label content mismatch error:
<img width="1050" alt="Screen Shot 2022-08-01 at 1 33 03 PM" src="https://user-images.githubusercontent.com/8353860/182242696-724ccf47-c1e5-4822-85aa-8664cbe7506d.png">

**Comment by azle** [comment]
Good to go, no errors.

<img width="1320" alt="Screen Shot 2022-11-21 at 10 32 18 AM" src="https://user-images.githubusercontent.com/8353860/203132883-0455d907-8da7-4ce5-96c3-88b17f11bc88.png">
