### ISSUE TITLE
Dashboard > Collections > All Collections results table headers don't match columns

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2216]
### Descriptive summary

On the Collections page in the Dashboard, the results table listing Collections, the table header does not match the columns, it's off-by-1. Title header is over collection type badges, etc.

https://staging.oregondigital.org/dashboard/collections?locale=en#content

![image](https://user-images.githubusercontent.com/2293544/155813205-6d33865c-ef60-41b6-93f5-7dee7de2c406.png)

At least for the All Collections tab, may apply to My Collections as well.

### Expected behavior

Collections page in Dashboards has table with header aligned with the correct columns.

### Related work

https://github.com/OregonDigital/OD2/issues/2210

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by straleyb** [comment]
JQuery table issue. Needs an extra TD possibly

**Comment by jsimic** [comment]
QA pass.
