### ISSUE TITLE
A11y Regression - More Facets modal

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2219]
### Descriptive summary
After a search, opening a facet and clicking `More >>` opens the more facets pop-over modal. This modal now displays a copy of the search page. It should display more facet values

### Expected behavior
More Facets modal displays more facets

### Accessibility Concerns
Maintain A11y work

**Comment by shieldsb** [comment]
QA fail.  
![image](https://user-images.githubusercontent.com/53542788/159594734-f34d2613-f0c4-4567-9e2b-b12a87a660a2.png)

**Comment by jsimic** [comment]
Blocked from QA until facets are showing on search results page.

**Comment by jsimic** [comment]
QA fail.  Testing on Work Type from [this search](https://staging.oregondigital.org/catalog?locale=en&q%5B%5D=oregon&search_field=all_fields&utf8=%E2%9C%93&view=gallery#content).

Clicked on More > button and modal appeared

Numeric sort is in reverse order with the least number of items first
Switching to A-Z sort, the results are still listed in numeric order

Clicking back to Numeric, the list is now with the most number of items first
Clicking back to A-Z, the list is now in the most number of items first
It continues to switch back and forth when clicking between the two
The two lists do not appear to be identical between Numeric and A-Z. See below

Clicking Next > pops you out of the modal and into a new page with the list and you no longer see the search results
It is possible that the sorting is happening at the group level, where the first group is sorted, but when you move to the next group, it re-sorts. That may be why the Numeric and A-Z lists appear to differ. I can't tell.

Regardless, the modal is not working after clicking the Next > button, the sorting is not working as expected, and using the Next > and < Previous buttons are affected by the weirdness in the sorting.

**Comment by shieldsb** [comment]
QA fail.  The next button in the modal isn't functional, though it looks like it should be. Can't text the previous button until it will allow advancement to the next page.

**Comment by jsimic** [comment]
QA pass. I am able to open the modal, use the next and back buttons, resort and get to the appropriate sub-group of works.
