### ISSUE TITLE
Write eight end user tasks.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#224]
### Descriptive summary

In the user center design process approved by our stakeholders, we'll want to determine eight end user tasks to test against.

### Expected behavior

Eight tasks should be enough to cover the success metrics we've determined: https://drive.google.com/file/d/11jK9G_HjiHtcHuRKwQFscnnmwDbUS5yh/view?usp=sharing

### Related work

Link to related tickets or prior related work here.

**Comment by raybrarian** [comment]
POSM review - closed
