### ISSUE TITLE
"and others" in Creator display in search results

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#2252]
### Descriptive summary

Currently, "and others" appears after every Creator in the search results records, even if there is only one creator on the work. The metadata team would like the results to display a maximum of 3 creators, and then only add "and others" if there are 4+ creators.

### Expected behavior

"and others" will only appear on works in the search results with 4+ creators.

**Comment by straleyb** [comment]
This is not an issue anymore. Took out Creator from Search Results.

**Comment by shieldsb** [comment]
QA pass.
