### ISSUE TITLE
Write invitation to logo design charratte. 

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#227]
### Descriptive summary

For promotional and project "shorthand" purposes, an Oregon Digital logo beyond the existing text one could go far.

### Expected behavior

A small critique group with Dave as the designer could pull together a handsome logo that would compliment UO and OSU identities. 

### Related work

Link to related tickets or prior related work here.

**Comment by raybrarian** [comment]
POSM review - closed
