### ISSUE TITLE
My Collection search has no results

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2274]
### Descriptive summary
Performing a collection search on a user collection (collection landing page => view all items) returns 0 results. The search searches on `non_user_collections_ssim`. for a user collection that's not going to work

### Expected behavior
My Collection searches return results

**Comment by shieldsb** [comment]
QA fail. 
![image](https://user-images.githubusercontent.com/53542788/164130730-0d08c0cc-0a55-4e3e-b358-7c29a8d2bc27.png)
![image](https://user-images.githubusercontent.com/53542788/164130773-2f7cd3b2-638d-4e28-987f-6fdf69d9ff4c.png)

**Comment by shieldsb** [comment]
Still happening with new user/my shelf collection. Created a new digital collection and also received the no results found for your search message.

**Comment by shieldsb** [comment]
QA fail. Still showing 0 results.
