### ISSUE TITLE
No representative images when collection is first created

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2275]
### Descriptive summary
My shelf collections and other collections do not set representative images when first created. This prevents images from showing on my shelf and diminishes the user experience. 4 representative images should be picked as works are added if no representative are set.
Also, if a work is removed a new representative image should be selected to take its place.

### Expected behavior
Representative images pre-populate and stay populated for collections.

### Related work
#2255

**Comment by shieldsb** [comment]
QA fail.  Created two collections, one with 4 images (user collection) and another (digital collection) with one image.  Neither were populated with representative images.

**Comment by shieldsb** [comment]
Created a user/my shelf collection with an unaffiliated account and it has four images - not sure when they appeared since I created it for a different ticket.  Created a new digital collection with my OSU account and so far no representative images for the collection - and the fuchsia box still appears. 
![image](https://user-images.githubusercontent.com/53542788/168691203-7c50f0ae-1b94-43d3-b794-a611093a2ac0.png)

**Comment by shieldsb** [comment]
QA fail.

**Comment by shieldsb** [comment]
QA fail. 
![image](https://user-images.githubusercontent.com/53542788/175133320-cc821558-5581-4b45-b70a-7bc34517d112.png)

**Comment by shieldsb** [comment]
QA fail.  Created a my shelf collection with 5 photos and no representative images appeared. 
![image](https://user-images.githubusercontent.com/53542788/192405792-384b2689-7002-40b4-b43a-c00804e2795d.png)

**Comment by CGillen** [comment]
@shieldsb Try again? I just looked at your test collection and there's repr images:
https://staging.oregondigital.org/collections/br86b362v?locale=en

I'm not sure what would be causing the images to not show up or be delayed

**Comment by shieldsb** [comment]
QA pass. Took about 10 minutes for the representative images to appear on the collection page.
