### ISSUE TITLE
My shelf edit form has too many fields

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2276]
### Descriptive summary
My shelf collections should only present editable fields for title and description. The form should also not allow multiple values.

### Expected behavior
My shelf collection form only allows user to edit title and description

**Comment by shieldsb** [comment]
I receive the ack message when I try to edit those fields.

**Comment by shieldsb** [comment]
Still receiving the ack message when I try to edit the my collection/shelf description

**Comment by shieldsb** [comment]
Can now edit the title and description fields.  But it will also allow me to add a second collection title and second collection description, which the ticket says it should not allow.

**Comment by shieldsb** [comment]
QA pass.
