### ISSUE TITLE
Verification of Features Already in Hyrax/OD

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#23]
### Descriptive summary

This ticket represents the need to go through hyrax and verify that some of the features assumed to be working in hyrax, are actually working as expected. This ticket can be updated overtime when we discover that hyrax has a feature that we need and we need to verify that they are working. Some different features that exist that need to be verified are as follows.

### Expected behavior
* Verify that User editing works. 
      * Updating user info
      * Is the user info correct?
      * Can you delete and create other users in the UI?

A user can update their own information which includes ORCID, facebook, twitter, G+. 
A user can update their password if logged in.
An admin cannot remove users from the application.
An admin cannot update information about a user.
An admin cannot create other users unless through the devise interface or using their university credentials.
A user cannot delete their account.

* Verify that the review queue is sufficient
      * Can you review a work from the UI
      * Can you see all works under review
      * Can you filter out works to see your works that you want to review?

A work can be reviewed from two places. The review queue located at `/admin/workflows`
An admin can see all the works under review at `/admin/workflows`
Under review works can be sorted via the columns at `/admin/workflows`. They can also be searched for. No other methods of filtering are available at this time. 

* Verify the Parent Child relationship information is displayed properly on the show page
      * Is this how we want it?
      * Does it need to be moved anywhere?

Currently, the parent child info is shown quite far down on the page. Its not readily visible when a user first visits the show page. Do we want to move it up? @mccallum Might have some good ideas.

* Verify Zoomable image viewer is working properly
      * Is it working as expected?
      * Does it cover all our needs for different image types?

Images: The viewer works well for images. They can pan, zoom, rotate, display information about the item. 

Audio: Not working

Video: Not working

PDF: Available for downloading. No viewer used

Document: Gets loaded into the system and is downloadable. No viewer used.

* Verify PDF viewer fulfills all requirements
      * OCR reading for searching
      * Next/Previous page
      * Table of Contents
      * Zoomable

PDF VIEWER NOT FUNCTIONAL

* Versioning

Versioning not working. Says it uploads a new file, but dont have access to file and doesnt replace old file.

**Comment by jsimic** [comment]
PSOM reviewed. Closed.
