### ISSUE TITLE
Figure out notification and email policy

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#230]
### Descriptive summary

Hyrax, by default, does not send emails to users. Instead, they use the [mailboxer gem](https://github.com/mailboxer/mailboxer) to send in-app notifications. ScholarsArchive configured mailboxer to send emails to users when they receive a notification: https://github.com/osulp/Scholars-Archive/blob/master/config/initializers/mailboxer.rb

### Expected behavior

Decisions made on:
- [ ] Should we do the same for OD2?
- [ ] Can we configure mailboxer to only send emails on certain notifications?
- [ ] Who should be emailed under what conditions? (workflow change, oEmbed errors, new user, etc) 

### Related work

Simplifies #77 
Discussion and discovery on PR #221 
Relevant work on SA: https://github.com/osulp/Scholars-Archive/search?q=mailboxer&unscoped_q=mailboxer
Hyrax documentation about notifications/emails: https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#notifications - should be noted, the only mention of ActionMailer in code is for the contact form

**Comment by vantuyls** [comment]
@petersec @jsimic @wickr can you put heads together to sort out an initial set of use cases for email notifications in OD2 and drop them into this issue?

**Comment by CGillen** [comment]
Relates to #276

**Comment by jsimic** [comment]
For us:
- User error notifications, i.e. if a patron is getting an error it would be nice for us to know about it right away so we can investigate it rather than relying on the patron to report it.
- Bulk task errors
- Analytics--could we bake in a monthly/quarterly/yearly summary report for admins?


For patrons:
- Service disruptions/long maintenance
- UX surveys (optional?)
- New functionality announcements (optional?)
- New collection announcements (optional?)
- Password resets
- Copy of Contact Form submission
- Account maintenance/deletion

**Comment by mccallum** [comment]
After discussion -

For us: 
Explore possibilities of "something went wrong" errors
Bulk task errors, yes (might need beyond what Hyrax offers)
- needs broken down
Analytics notification probably not MVP (and could be part of grant?)
Derivatives
Workflow notifications [in app]

For patrons:
Improved 404/etc type error messages for end users
Service disruptions/long maintenance [in page]
UX surveys (optional?) [probably just email on our own - no automation]
New functionality announcements (optional?) [probably just email on our own - no automation]
New collection announcements (optional?) [probably just email on our own - no automation]
Password resets [exists]
Copy of Contact Form submission [needed]
Account maintenance/deletion [needed, user data discussion - GDPR, etc.]

**Comment by CGillen** [comment]
POSM has identified the following types of system generated announcements:
- Error Notification
  - These will be generated by Honeycomb and sent out through its integrations (slack and email)
  - These notifications should go to a developer focused slack channel and emailed in certain situations to devs and infrastructure
  - The types of errors are routing (4xx and 5xx responses), unhandled exceptions, system instability/crashes/resource use
- Oembed Errors
  - An email should be sent to the depositor of the work and the curator of the collection the work is being deposited into.
  - Emails should come in batches at the beginning or end of the day
- Failed Fetch Jobs
  - An email should be sent to the depositor of the work
  - Explore the option of digesting all of these to the head of metadeities
  - Emails should come in batches at the beginning or end of the day
- Derivative Failed Jobs
  - An email should be sent to the depositor of the work and the curator of the collection the work is being deposited into
  - Emails should come in batches at the beginning or end of the day to the depositor and collection curator
  - Devs and infrastructure may want slack notifications when this happens
- Something went wrong page
  - Reword for clarification that users don't need to do anything.
  - A certain threshold of these should trigger in Honeycomb to email or slack devs & infra

**Comment by CGillen** [comment]
- Review queue messages
  - These should be digested for the user daily, especially during bulk tasks

**Comment by CGillen** [comment]
Decision is above and tickets created
