### ISSUE TITLE
Research and determine three complimentary fonts for OD (serif, sans-serif, mono) with support for full Latin encoding as well as macrons for Pinyin. 

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#231]
### Descriptive summary

Across a wide variety of collections (including some presenting characters in languages other than english), a versatile set of fonts will be needed. 

### Expected behavior

Our font requirements include a sans-serif, serif (for body text) and monospaced for code and all complimenting each other. Stakeholders emphasized a modern tone as well. 

### Related work

Link to related tickets or prior related work here.

**Comment by mellinma** [comment]
Fonts defined in MAC OD2 Identity Guide: https://drive.google.com/open?id=1Bk7WG9Y5n0joSlZ_5DFYv1B9fLI0IBzj

**Comment by shieldsb** [comment]
See MAC design
