### ISSUE TITLE
Work child pagination pushes to the side on mobile

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2331]
### Descriptive summary
![image](https://user-images.githubusercontent.com/11052958/173387296-92039c4a-e076-4b97-bd93-881c835fa33e.png)
Pagination should be below the associated works (check child, parent, sibling).

This also causes thumbnails to not be hoverable near the pagination. Make sure that is solved with moving the pagination back.

### Expected behavior
Pagination is below related works section

### Accessibility Concerns
Keep `<nav>` element, make sure not to change any other properties

**Comment by shieldsb** [comment]
QA pass.
