### ISSUE TITLE
topic_combined_label is annoyingly empty

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2333]
### Descriptive summary

as advertised, topic combined label is empty, but creator combined label is working as expected.  
my suspicion is that the indexing behavior in the generic indexer is clobbering the indexing when the labels are fetched.
### Expected behavior
topic combined label should have all the subject labels

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
QA
pid = 
sd = SolrDocument.find(pid)
sd['topic_combined_label_sim'] #will equal nil
item = ActiveFedora::Base.find(pid)
item.update_index
sd = SolrDocument.find(pid)
sd['topic_combined_label_sim'] #should now have subject labels

**Comment by wickr** [comment]
QA pass
Opened work on staging, checked topic_combined_label_sim from index and it was empty. Updated index on work, and then the field was correctly populated.

```ruby
irb(main):007:0> w = Image.find('hx11xf95h')
D, [2022-06-16T10:47:08.789921 #66640] DEBUG -- :   Load LDP (40.3ms) http://fcrepo.od2-test.svc.cluster.local:8080/fcrepo/rest/prod/hx/11/xf/95/hx11xf95h Service: 513020
=> #<Image id: "hx11xf95h", head: [#<ActiveTriples::Resource:0x7dd0c ID:<http://fcrepo.od2-test.svc.cluster.local:8080/fcrepo/rest/prod/hx/11/xf/95/hx11xf9...
irb(main):010:0> sd = SolrDocument.find('hx11xf95h')
D, [2022-06-16T10:47:30.073983 #66640] DEBUG -- : Solr query: get select {:qt=>"document", :id=>"hx11xf95h"}
D, [2022-06-16T10:47:30.074179 #66640] DEBUG -- : Solr fetch (51.8ms)
=> #<SolrDocument:0x00007fd6461bad90 @_source={"system_create_dtsi"=>"2022-06-10T18:22:22Z", "system_modified_dtsi"=>"2022-06-10T18:35:40Z", "has_model_ssi...
irb(main):011:0> sd['topic_combined_label_sim']
=> nil
irb(main):012:0> w.update_index
...

irb(main):013:0> sd = SolrDocument.find('hx11xf95h')
D, [2022-06-16T10:48:21.033479 #66640] DEBUG -- : Solr query: get select {:qt=>"document", :id=>"hx11xf95h"}
D, [2022-06-16T10:48:21.033757 #66640] DEBUG -- : Solr fetch (7.5ms)
=> #<SolrDocument:0x00007fd6474ebc48 @_source={"system_create_dtsi"=>"2022-06-10T18:22:22Z", "system_modified_dtsi"=>"2022-06-10T18:35:40Z", "has_model_ssi...
irb(main):014:0> sd['topic_combined_label_sim']
=> ["Boys", "Coaster cars", "outdoor candid portraits"]
```
