### ISSUE TITLE
Collection facet showing collection ids and not labels

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#2346]
### Descriptive summary

The labels for Collection facet are displaying the collection id, not the collection name. 

<img width="280" alt="Screen Shot 2022-06-23 at 1 44 04 PM" src="https://user-images.githubusercontent.com/7328774/175396227-d0849b8d-98d7-49ac-94a9-fb1423dc858e.png">

### Expected behavior

The labels for collection should be the full collection name. 

### Related work

N/A

### Accessibility Concerns

N/A

**Comment by jsimic** [comment]
Working!
