### ISSUE TITLE
Edit Form Full Size Download Allowed field has capitalized value in form code

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2347]
### Descriptive summary

Values for Full Size Download Allowed are correctly set in the migrator, but when editing a newly migrated work, the form doesn't recognize 'false' and shows empty.
Example: https://prod.oregondigital.org/concern/images/df66zj20c/edit?locale=en#Administratives

The HTML in the form select has 'False' capitalized so it's not matching the metadata.

```html
<select class="form-control select optional form-control" name="image[full_size_download_allowed]" id="image_full_size_download_allowed" aria-describedby="image_full_size_download_allowed_help"><option selected="selected" value=""></option>
<option value="true">True</option>
<option value="False">False</option></select>
```

It appears that the DownloadService is giving back differently capitalized values, despite the authority values being lowercase:

```ruby
irb(main):013:0> ds = OregonDigital::DownloadService.new
=> #<OregonDigital::DownloadService:0x00007f8ce600f648 @authority=#<Qa::Authorities::Local::FileBasedAuthority:0x00007f8ce600f4e0 @subauthority="download">>
irb(main):014:0> ds.select_sorted_all_options
=> [["", ""], ["False", "False"], ["True", true]]
```

### Expected behavior

Form should show the value if it is set on the work.

### Related work

#2320 

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by jsimic** [comment]
QA pass
