### ISSUE TITLE
Pass through search query from results page to work show page, highlight search terms in UV

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2355]
### Descriptive summary
When a show page is reached through a search, search terms used to reach page should automatically be searched through UV

### Expected behavior
A search for `oregon` should highlight every instance of `oregon` in UV.

### Related work
#1450

**Comment by wickr** [comment]
Found this ticket, though no noticeable resolution yet: https://github.com/UniversalViewer/universalviewer/issues/367

**Comment by shieldsb** [comment]
QA fail.

**Comment by CGillen** [comment]
@shieldsb Can you QA again? I'm not sure what's failing?

**Comment by shieldsb** [comment]
This is the message I receive on both staging and production 
![image](https://github.com/OregonDigital/OD2/assets/53542788/3532d378-91af-49ae-a35d-231c5bc41d78)
