### ISSUE TITLE
Add LCSH to Scientific controlled vocabulary

### ISSUE THREAD

**Issue by carakey** [OregonDigital/OD2#2360]
### Descriptive summary

Part of the task to replace Ubio.org URIs, specifically for Common Name field. Ubio had separate entities for common names, but ITIS does not. Wikidata occasionally has common name labels but having LCSH as an available option would improve our coverage for replacing Ubio terms. 

Needs to be completed to remediate Ubio; needs to be done to migrate several priority level 2 collections.

### Expected behavior

LCSH URIs will be accepted in the Scientific Names group of metadata fields (but will only be used in Common Name). 

### Related work

https://github.com/OregonDigital/oregondigital/issues/1553 
https://github.com/OregonDigital/oregondigital/issues/1561 (same as this ticket but for OD1)

**Comment by jsimic** [comment]
Working. Can add LCSH to any scientifics field.
