### ISSUE TITLE
Geonames fields must accept URIs in webform

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#2363]
### Descriptive summary

Currently in the webform locations fields (Location, Ranger District, Water Basin, Place of Production, Publication Place) one must type all or part of the label to search Geonames and return a list of matches. The field needs to also accept URIs since the returns are not in useful order and will slow down cataloging.

### Expected behavior

Entering a URI in a field on the webform that requires Geonames should call up a single, accurate return for use.

**Comment by lamtu1** [comment]
Hi @jsimic, I was wondering for the URI, would the user be able to input:
The entire URI: `https://www.geonames.org/9431267/monet-s-water-lilly-pond.html`
or
The ID: `9431267`

or both to search for specific location area?

**Comment by jsimic** [comment]
QA pass on staging!

**Comment by KevinJonesMeta** [comment]
Full URI accepted in form on production
