### ISSUE TITLE
[Remediation] Post OD2 Migration: clean up metadata entry errors in Grayson Mathews collection

### ISSUE THREAD

**Issue by lharka** [OregonDigital/OD2#2366]
### Descriptive summary
Grayson Mathews is listed in 3 facets: Creator, Photographer, and Subjects. Each facet has a different spelling/format for Grayson Mathews' name (i.e., the wrong Grayson Mathews LCNAF/controlled vocab entry may have been used and needs to be remediated). Variations of the name used include:
Creator: Mathews, Grayson Lane
Photographer: Mathews, Grayson Layne
Subject: Mathews, Grayson

### Expected behavior
Remediate collection using correct Grayson Mathews controlled vocab. Remove Creator entry, only use Photographer field (i.e., Grayon's role as a creator is photographer, so using both fields is redundant). 

If still including Grayson Mathews in Subject Heading, make sure it is the same controlled vocab URI used in the Photographer field. If removing, enhance Subject Heading field by adding new relevant subjects (3-5 SHs total per item, as needed).

**Comment by sarahfish07** [comment]
Errors above fixed. Grayson Matthews is now listed with LOC URI under photographer and subject only.
Closing this ticket.
