### ISSUE TITLE
Email should appear under My Account for logged in users

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#2373]
### Descriptive summary

There is nothing in the current interface to indicate a user is logged into their own account or someone else's.

### Expected behavior

Once a user is logged in using either an institutional or public account, their email should appear in the My Collections menu. This tracks with the original MAC wireframe's use of "Profile"

<img width="639" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/6344086/176796156-7ceb31d8-b99d-4ff1-94fe-ccbff0f5a5d9.png">

**Comment by shieldsb** [comment]
@CGillen This ticket passes QA as it stands.  I did ask Julia and Azle about the display, so there is a minor udpate. I'll add it here, I can make a separate ticket if you would prefer. 

For a user that also has a dashboard, the email displays second on the list, but the email should move to the top for all user types. View from admin user: 
![image](https://user-images.githubusercontent.com/53542788/191824478-6afa6bcb-7d5b-4ec1-b24e-4ba5e0d5f3e3.png)

View of non-admin user: 
![image](https://user-images.githubusercontent.com/53542788/191825190-d92dca9c-0af3-4c23-a3d6-205dc8c17b70.png)

**Comment by shieldsb** [comment]
QA pass.
