### ISSUE TITLE
[Remediation] Wrong "Painting" URI in gbwarner collections

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#2391]
### Descriptive summary

Delete wrong "Painting" URI in gbwarner collections. 

[http://id.loc.gov/authorities/subjects/sh00006877](https://www.google.com/url?q=http://id.loc.gov/authorities/subjects/sh00006877&sa=D&source=docs&ust=1657129081305112&usg=AOvVaw1E885gdM59YuEv4A2zM8ok) and [http://id.loc.gov/authorities/subjects/sh85096661](https://www.google.com/url?q=http://id.loc.gov/authorities/subjects/sh85096661&sa=D&source=docs&ust=1657129081305200&usg=AOvVaw09i8LWn1Evcis380q8qkqu) are not the same

Should be using [http://id.loc.gov/authorities/subjects/sh85096661](https://www.google.com/url?q=http://id.loc.gov/authorities/subjects/sh85096661&sa=D&source=docs&ust=1657129081305244&usg=AOvVaw2Uuoi8QrrzVQL9MBrrYxEb) for all

### Expected behavior

One URI for one label.

### Related work

https://github.com/OregonDigital/OD2-migration/issues/61

### Accessibility Concerns

N/A

**Comment by sarahfish07** [comment]
gb-warner includes multiple collections:
Checked gb-warner-photos. The URIs listed above are not used in this collection.

**Comment by sarahfish07** [comment]
Checked schnitzer-nitrate. The URIs listed above are not used in this gb-warner collection.

**Comment by sarahfish07** [comment]
Checked gbwarnerpapers. The URIs listed above are not used in this gb-warner collection.

**Comment by sarahfish07** [comment]
last one- checked gb-warner-papers-nosatsu. Fixed painting URIs.
No other collections to check. Closing this ticket.
