### ISSUE TITLE
HTML markup on collection landing pages

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#2393]
### Descriptive summary

There is HTML markup appearing in the descriptions in the collection landing pages. See:

https://prod.oregondigital.org/collections/walter-bowman#content
https://prod.oregondigital.org/collections/grayson-mathews#content
https://prod.oregondigital.org/collections/florence-hartshorn#content
https://prod.oregondigital.org/collections/joel-palmer#content
https://prod.oregondigital.org/collections/gb-warner-papers-ua022#content
https://prod.oregondigital.org/collections/mountaingrove#content
https://prod.oregondigital.org/collections/coll560#content
https://prod.oregondigital.org/collections/gb-warner#content
https://prod.oregondigital.org/collections/gbwarnerpapers#content
https://prod.oregondigital.org/collections/dissociation#content

### Expected behavior

This should not be there.

**Comment by jsimic** [comment]
Removed all the html

**Comment by lharka** [comment]
Reviewed a new collection that is showing HTML mark-up. I will continue to track for each collection and note here. @jsimic, should we move back to QA?

**Comment by lharka** [comment]
Html error in public view. Showing html markup < p >< /p > in collection description. Check here:
https://prod.oregondigital.org/collections/colver-family#content

**Comment by jsimic** [comment]
@lharka  I think we're going to have look at all the collection descriptions and edit these manually. I'm putting it back to In Progress until all of them are checked.

**Comment by jsimic** [comment]
All existing collection descriptions checked. Two exceptions: Picturing the Cayuse, Walla Walla, and Umatilla Tribes (UO) does not exist; Chuck Williams Photographs (OSU) does not exist

**Comment by azle** [comment]
I have checked the following links, and the html markup has been removed.

https://prod.oregondigital.org/collections/walter-bowman#content
https://prod.oregondigital.org/collections/grayson-mathews#content
https://prod.oregondigital.org/collections/florence-hartshorn#content
https://prod.oregondigital.org/collections/joel-palmer#content
https://prod.oregondigital.org/collections/gb-warner-papers-ua022#content
https://prod.oregondigital.org/collections/mountaingrove#content
https://prod.oregondigital.org/collections/coll560#content
https://prod.oregondigital.org/collections/gb-warner#content
https://prod.oregondigital.org/collections/gbwarnerpapers#content
https://prod.oregondigital.org/collections/dissociation#content
