### ISSUE TITLE
languages to be added to authorities file

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2398]
### Descriptive summary

we have just a couple of assets each that use the following languages on OD1:
http://id.loc.gov/vocabulary/iso639-2/hin
http://id.loc.gov/vocabulary/iso639-2/swa
will need to add them prior to ingest.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by wickr** [comment]
QA: languages are available in Language field dropdown menu

**Comment by jsimic** [comment]
QA pass
