### ISSUE TITLE
Collection landing page advanced search Collection facet showing collection ids, not titles

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2404]
### Descriptive summary

On a Collection landing page, the advanced search style Collection facet is showing the collection ids instead of the collection titles

![image](https://user-images.githubusercontent.com/2293544/179633361-0761fdc0-5ca3-4ac9-a472-2ffe6b5926c1.png)

https://prod.oregondigital.org/collections/orange-owl?locale=en#content
Click Collection facet

### Expected behavior

Collection facet displays collection title

### Related work

#2346 

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by shieldsb** [comment]
QA pass.
