### ISSUE TITLE
Search from collection landing page returns inaccurate results

### ISSUE THREAD

**Issue by carakey** [OregonDigital/OD2#2405]
### Descriptive summary

On the collection landing page in "Search this collection," searching using any of the free text fields (All Fields, Title, Creator, Description, Subject) returns all items in the collection no matter the search term used. This is true whether the search string actually occurs in all records, some records, or no records. 

### Expected behavior

Searching in a field from the collection landing page returns works in that collection that contain the specified search string in the specified field.

**Comment by sseymore** [comment]
QA pass on staging. Searching GB Warner and OSU Lichens collection.
