### ISSUE TITLE
folder_number and has_number properties have the same predicate assigned

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2411]
### Descriptive summary

Per @KevinJonesMeta migration QA: https://github.com/OregonDigital/OD2-migration/issues/169#issuecomment-1191936577

`folder_number` (Generic) and `has_number` (Document) both have the same predicate assigned (`ons:folderNumber`) after a code change last year. This means that any value assigned to one of those properties also gets shown in the other. 
`folder_number`'s predicate is correct, so any value there should stop showing in Number when this is fixed, and not need further work.
Any value that should be in `has_number` will have to be moved (at least works in oregon-state-yank and oregons-agricultural-progress).

Examples: 
has Number but should not have Archival Folder Number
https://prod.oregondigital.org/concern/documents/fx71c7617#content
has Archival Folder Number but should not have Number
https://prod.oregondigital.org/concern/documents/df70j985z?locale=en#content

### Expected behavior

`folder_number` and `has_number` are separate properties with different predicates.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by sseymore** [comment]
I used the examples @CGillen linked above, but I am still seeing the data errors:

https://prod.oregondigital.org/concern/documents/fx71c7617#content -- Has number and archival folder number, not like asset in OD1: https://oregondigital.org/catalog/oregondigital:fx71c7617#page/1/mode/1up

https://prod.oregondigital.org/concern/documents/df70j985z?locale=en#content-- also has both fields, not like asset in OD1: https://oregondigital.org/catalog/oregondigital:df70j985z#page/1/mode/1up

Does this need to be re-indexed to correct the works on staging?

**Comment by sseymore** [comment]
@wickr @KevinJonesMeta I am not seeing this corrected in the links attached to the tickets and staging is not accessible at all for me right now. Can you take a look at this?

![Screen Shot 2022-08-17 at 8 45 42 AM](https://user-images.githubusercontent.com/7328774/185183921-ab175a3c-386d-4478-81d8-0e845b829609.png)

**Comment by sseymore** [comment]
I think a QA pass? This appears to be correct on staging using the form and looking at a UO work, but I can't QA the OSU collections mentioned above because there are no works from those collections on staging. 

https://staging.oregondigital.org/concern/documents/df70ks47m#content
https://staging.oregondigital.org/concern/generics/x920fw88h?locale=en#content
https://staging.oregondigital.org/concern/documents/js956f80d?locale=en#content

**Comment by wickr** [comment]
QA pass. Combined with Sarah Beth's QA I can confirm this is working well for Oregon's Agricultural Progress works. I ran a cleanup script to move the values and they're only in the correct field. Joel Palmer works either need similar cleanup or at least a reindex. But the fields are acting separately and correctly.
