### ISSUE TITLE
Worktype labels fetched from Getty are not all saved/indexed in English

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2429]
### Descriptive summary

Worktype labels from Getty are being indexed with non-English labels.

![image](https://user-images.githubusercontent.com/2293544/182898200-c4da7acb-2633-45c2-8cbf-80a5ea73d08f.png)

Current worktype facet browse link: https://prod.oregondigital.org/catalog/facet/workType_label_sim?facet.page=4&locale=en&q%5B%5D=&search_field=all_fields&utf8=%E2%9C%93#content

### Expected behavior

Indexed labels are in English. Labels are consistent and contribute to clean and usable facet values.

### Related work

#578

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by sseymore** [comment]
@wickr I am still seeing a Spanish label being pulled here. Can you confirm?

**Comment by sseymore** [comment]
QA fail. 

On staging, I am seeing one weird label, but the rest look good. http://vocab.getty.edu/aat/300046065
![Screen Shot 2022-08-18 at 7 46 56 AM](https://user-images.githubusercontent.com/7328774/185424551-0d0ed314-1243-4794-8f10-c51ad45e4da9.png)

**Comment by carakey** [comment]
Noticed this is still not working correctly when QA'ing a work migrated September 16 (after issue was closed), which had fetched a non-English Getty AAT label. 
Work: https://prod.oregondigital.org/concern/images/df716w07h
URI: http://vocab.getty.edu/aat/300403916 -- in Work Type -- should have the English label "fob chains" as in [OD1](https://www.oregondigital.org/catalog/oregondigital:df716w07h) but instead has "sierkettingen". 

Looking at the Work Type facet for all works in OD2 prod, there are several other labels that appear to be non-English including [amphithéâtre](https://prod.oregondigital.org/concern/images/df694559k), [cǎi sè zhào piàn](https://prod.oregondigital.org/concern/images/rj430454t), [fotografías en color (obra visual)](https://prod.oregondigital.org/concern/images/9w0323039), and others. 

Notes: 

This specific work was reviewed as part of migration QA, and I did not notice the non-English label until after it was reviewed. I did not see any other non-English labels in the Work Type or Topic facets in unreviewed works in this collection (or at least none that differed from OD1 labels, as some non-Western garments are present in the collection). 

The problematic labels are showing as non-English on the work show page and the search results facets. Many of the ones that I've sampled do have the English label on the "Data Sources" tab, and are missing the supertext #data_sources reference number on the work page. The first work mentioned, with fob chains/sierkettingen, is an exception to that pattern.

**Comment by wickr** [comment]
For the specific work that Cara linked, there is only one `skos:prefLabel` and it's not in English. 
http://vocab.getty.edu/aat/300403916?inference=implicit&role=all
But there's many more English labels so it should continue on until one of those.

For the last note, I'm also seeing the mismatch between label values shown on Details vs. Data Sources tab, and no reference, but those do appear to be going away with an update on the work's indexing.

**Comment by jsimic** [comment]
@CGillen Here's a list of the labels, URIs, and items with mis-fetched labels. 
[badLabels_worktype.xlsx](https://github.com/OregonDigital/OD2/files/10015639/badLabels_worktype.xlsx)

**Comment by sseymore** [comment]
@CGillen Do we QC this on staging or prod?

**Comment by sseymore** [comment]
![Screen Shot 2022-12-05 at 12 21 22 PM](https://user-images.githubusercontent.com/7328774/205735382-e04e183d-3f09-477c-88b4-3fa9ba1c9a74.png)
![Screen Shot 2022-12-05 at 12 21 17 PM](https://user-images.githubusercontent.com/7328774/205735385-035ed9f2-0bb4-4ae0-9d82-ba216d72f448.png)
![Screen Shot 2022-12-05 at 12 21 00 PM](https://user-images.githubusercontent.com/7328774/205735389-fc337518-3e0b-433d-8296-c2d6ad0dcc26.png)

**Comment by CGillen** [comment]
Staging for now. There might be some left with bad labels. Let me run a reindex and ping again in this ticket

**Comment by jsimic** [comment]
QA fail. Still showing the Greek version of pumps as per Sarah Beth's image. http://vocab.getty.edu/aat/300210043

**Comment by sseymore** [comment]
@CGillen This item is still erroring in the details tab (https://staging.oregondigital.org/concern/images/df713553r#metadata) but looks correct in data sources tab. Do you know what's going on?

![Screen Shot 2023-01-03 at 11 06 58 AM](https://user-images.githubusercontent.com/7328774/210424552-df5775de-3376-44c7-974b-16340ae0cf3e.png)

![Screen Shot 2023-01-03 at 11 06 51 AM](https://user-images.githubusercontent.com/7328774/210424557-e988ae3c-d902-4f68-b6de-b35a7ac1e944.png)

**Comment by CGillen** [comment]
Frick. I didn't check the modified time before I re-saved the work, but this was another indexing issue. The `Data Sources` tab actually re-fetches the label, where the `Details` uses what's in Solr. That alone seems like a problem, but that explains the difference.

I re-saved, kicked off a reindex, and all looks good now

**Comment by sseymore** [comment]
QA Pass!
