### ISSUE TITLE
prevent unfetched uri from displaying

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2460]
### Descriptive summary
When the fetch graph was moved into the deep indexer, I blocked terms that had no label from getting indexed which is the wrong strategy. We should index them, but prevent them from displaying. I have removed the block in #2458, but now we'll need something in the view that skips any term that doesn't have a label (i.e., has the uri string as a label).

### Expected behavior
On the asset show page, do not display uris where there should be a fetched label.
Do display non-controlled fields that have uris as their value.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by KevinJonesMeta** [comment]
Current behavior: URIs with no label do not display on work show page; are listed in data sources with no label; are indexed; URIs display in facet results. We want this behavior to continue to facilitate remediation.
