### ISSUE TITLE
[WIREFRAMES] HOMEPAGE, NOT LOGGED IN

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#2465]
====================
Issue #1 Homepage Banner, the spacing in the banner needs to be tightened up. The tagline should also read "Unique Cultural Heritage Collection" and not University Library Archives. There was also a decision to make the tagline mixed caps.

Screen snap of current state: 
<img width="1291" alt="Screen Shot 2022-09-06 at 3 25 13 PM" src="https://user-images.githubusercontent.com/8353860/188751164-4e16d815-e90e-4ee7-b4bc-f71a917fdcf1.png">

Screen snap of what it should look like:
<img width="1395" alt="Screen Shot 2022-09-06 at 3 21 01 PM" src="https://user-images.githubusercontent.com/8353860/188750628-3edd7178-3867-45f5-b51b-898f60355787.png">

URL from MAC Agency: https://projects.invisionapp.com/share/47X400SV3BM#/screens

Logo plus Oregon Digital dimension: 209.44 by 45.32
Sub Header Text: Lato 11 Black #757575
Explore Collection text: Lato 13.5 Black #073C5C
Search box dimension: 266px by 42px
Advanced text: Lato 10 Black #073C5C
Login button dimensions: 108px by 37px ; text Lato 12 Black #073C5C
Sign Up button dimensions: 94px by 37px ; text Lato 12 Black #FFFFFF

Also have the button and the search box be the same height.

====================
Issue #2 Image and line/drop shadow. The gray line/dropshadow should appear over the image aligned to the top.

screen snap of current state, see the faint gray line with drop shadow:
<img width="1411" alt="Screen Shot 2022-09-06 at 3 39 33 PM" src="https://user-images.githubusercontent.com/8353860/188752774-cccfb9b4-9452-49f1-8639-7ccc5880eed7.png">

screen snap of what it should look like:
<img width="1438" alt="Screen Shot 2022-09-06 at 3 41 45 PM" src="https://user-images.githubusercontent.com/8353860/188753001-8b8e45ec-260f-419b-b514-336cc65a1621.png">

====================
Issue #3 Unknown Decision: Did we decide to remove the slider and caption from the main search image?

In our current homepage wireframe we still have the caption and slider. At some point I do remember there was a decision to make the image static. But did we decide to use the same image or does it change at every visit and what was the decision on the captions and slider?

Screen snap of final wireframe:
<img width="256" alt="Screen Shot 2022-09-06 at 3 49 18 PM" src="https://user-images.githubusercontent.com/8353860/188753783-d4692aab-3829-4e3f-bd58-0312c1fa9076.png">

Current view on production: https://prod.oregondigital.org/#content

====================
Issue #4 Unknown Decision: For featured collection production shows some with 2 or 0 thumbnails. Is there a rule for what is displayed in the featured collection area for the number of thumbnails. Currently the wireframes shows that all features have 3 thumbnails.

The issue would be when they show 2 or 0 thumbnails what is the expected behavior for it to display.

On production with two missing images thumbnails and one with 0 thumbnails.
<img width="568" alt="Screen Shot 2022-09-06 at 4 42 20 PM" src="https://user-images.githubusercontent.com/8353860/188758706-6dd61075-29ff-49d1-9c34-9422ecdddb68.png">

Wireframe has 3 thumbnails showing:
<img width="282" alt="Screen Shot 2022-09-06 at 4 41 36 PM" src="https://user-images.githubusercontent.com/8353860/188758642-b61784b2-9e66-4895-a757-5ea04de731c6.png">

====================
Issue #5 Featured Collection thumbnails show a variety of sizes but in the wireframe the thumbnail should be a consistent square the size should be 90 by 90 pixels.

What it should look like:
<img width="269" alt="Screen Shot 2022-09-06 at 4 47 05 PM" src="https://user-images.githubusercontent.com/8353860/188759089-9203f7bb-8c58-4123-b56d-d03aaa2907de.png">

====================
Issue #6 About Oregon Digital column is missing the Read More and the following categories First time here? and Dig Deeper.

See screen snap:
<img width="247" alt="Screen Shot 2022-09-06 at 4 53 57 PM" src="https://user-images.githubusercontent.com/8353860/188759633-66da646c-8fe9-45ee-beff-b0c379766e33.png">

====================
Issue #7 Footer is not layed out correctly, needs to look like the wireframe.

Correct layout for the footer:
<img width="797" alt="Screen Shot 2022-09-06 at 4 55 59 PM" src="https://user-images.githubusercontent.com/8353860/188759842-d44f71b3-4d6f-4396-bfcc-11460e79de19.png">

background color for footer: #757575

====================
Issue #8 POSM decision to use mixed caps:

Following items should be changed to mixed caps:

- header tagline
- Explore Collection
- Advanced (in header, and in search box in blue image area)
- Login
- Sign Up
- View All Collections 

====================
Issue #9 Homepage is missing "First time here" and "Dig deeper" which appears after the about text.

Should look like this:
<img width="221" alt="Screen Shot 2022-09-15 at 1 57 13 PM" src="https://user-images.githubusercontent.com/8353860/190507328-131b63e0-32d2-411c-b898-7576da0cb388.png">

**Comment by azle** [comment]
@CGillen, Issue #2 is still missing the line/drop shadow and #7 the footer text looks good in all browsers except for safari. The footer text is aligned to the left and needs more spacing on the left hand side. Safari displays the gold line right next to the browser window.

What it looks like in safari:
<img width="314" alt="Screen Shot 2023-01-03 at 2 36 32 PM" src="https://user-images.githubusercontent.com/8353860/210452770-20b1a67f-9137-4ba6-9c6e-bbf18de12210.png">

**Comment by azle** [comment]
@cgillen and @straleyb this looks good across all browsers except for safari. Issue #7, the footer looks good except in safari. Safari is missing the left side padding.

**Comment by CGillen** [comment]
@straleyb This one is for you, my safari renders correctly:
smallest desktop
![image](https://user-images.githubusercontent.com/11052958/212950378-d1ad4136-8a47-4481-b051-c144235f1353.png)

Largest desktop
![image](https://user-images.githubusercontent.com/11052958/212950551-6e6ea982-c758-4d47-8a6e-6affe8143a94.png)

**Comment by straleyb** [comment]
@azle I think the safari issue is with the version of safari you have. We've been noticing that some stuff hasn't been working right unless on a newer version of safari. Can you check to see whether or not if you update safari it works or what safari version you are on?

**Comment by azle** [comment]
@straleyb correct, I checked another version of safari and it is working. Doesn't work in safari version 13.1.3
