### ISSUE TITLE
[WIREFRAME] EXPLORE COLLECTION GRID, NOT LOGGED IN

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#2466]
====================
Issue #1 Blurred line at the bottom of banner, need to be y axis 5 px and 5 px blur

What it currently looks like:
<img width="389" alt="Screen Shot 2022-09-06 at 6 18 39 PM" src="https://user-images.githubusercontent.com/8353860/188767614-fdb074ab-4814-416f-b5f5-42a9a083be77.png">

What it should look like, y axis 5px and blur of 5 px: 
<img width="364" alt="Screen Shot 2022-09-06 at 6 18 05 PM" src="https://user-images.githubusercontent.com/8353860/188767567-805febf1-6664-4439-a229-6b1c4be90e62.png">

====================
Issue #2 Masonary view thumbnail has incorrect icon color. Background is correct. But the icon color should not be blue and should be white #ffffff. However, with that said. Was there a POSM decision on making the white text color on orange background to blue due to accessiblity? The orange and white text fails for color contrast.

Correct look:
<img width="70" alt="Screen Shot 2022-09-06 at 6 25 33 PM" src="https://user-images.githubusercontent.com/8353860/188768333-f2dca210-d044-49b9-9523-ca88d0ebd3cf.png">

====================
Issue #3 Gray bar before results, should be 12 px tall. The full dimensions in Mac mockup is 1137 by 12 px.

Should look like this:
<img width="1083" alt="Screen Shot 2022-09-06 at 6 29 19 PM" src="https://user-images.githubusercontent.com/8353860/188768764-cfa209f4-64a1-43f5-b1a9-c9ccb2c64837.png">

====================
Issue #4 Gray line above the thumbnails. Height should be 2px. MAC dimensions are border size 2, 165px wide.

Should look like this:
<img width="144" alt="Screen Shot 2022-09-06 at 6 37 04 PM" src="https://user-images.githubusercontent.com/8353860/188769554-9dbc5dab-a1c6-4150-88f4-33566f127756.png">

====================
Issue #5 Pagination, Prev should be spelled out like wireframes to Previous. 

====================
Issue #5 The image thumbnails start to wrap. They need to be aligned to the left side. Currently they are wrapping on second line but aligned right.

Current look:
<img width="1205" alt="Screen Shot 2022-09-13 at 12 06 39 PM" src="https://user-images.githubusercontent.com/8353860/189988564-9598968e-b884-4a08-b865-0fd62ddadd66.png">

What it should look like
<img width="652" alt="Screen Shot 2022-09-13 at 12 09 01 PM" src="https://user-images.githubusercontent.com/8353860/189988952-4351e7cf-2049-474c-88a8-eea88917867c.png">

**Comment by CGillen** [comment]
#2, it was more of an executive decision. The blue was our best color that had contrast with the orange
#4 the border is already 2px. Width will depend on the viewport
Others are fixed in #2629

**Comment by azle** [comment]
@CGillen Question: Was there a decision for the orange icons to be orange and navy, the mockups have them as orange and white. See #2 and #3 above.

Also for #5, with the images not aligning correctly. It is getting closer not sure why this one is aligned left but then you have a space before the last box. See screen snap.

<img width="1282" alt="Screen Shot 2022-12-08 at 9 14 31 AM" src="https://user-images.githubusercontent.com/8353860/206519140-106f9453-6c33-461c-b9da-4b5c19d765e8.png">

**Comment by CGillen** [comment]
#2 & #3 Are as I stated above and you mentioned. White on orange does not meet contrast requirements, nor does black on orange. Blue/Orange is our best color combo that meets contrast requirements. If you want to look through our color swatches and give me a different set I can change them.

#5 is a more difficult issue. Our masonry library wants to fill vertical space before horizontal. So it'll scan left-to-right looking for the highest point and putting a card under the spot it finds. Before the left aligned setting, that was the last two as you pictured. After left-align it forces the next item after the end to be touching the left (left-aligned) then does the same thing, scan for the highest point to put the next card. I can't really do anything about it.
In fact, looking over the documentation, the last left align fix might not have actually done anything and you're just looking at the difference of staging vs prod

**Comment by CGillen** [comment]
@azle, Yeah our left-align option doesn't actually do anything it was just the difference between staging/prod.
So yeah, #5 can't really be resolved without reworking the page entirely. We decided on a masonry a long time ago. I can increase the count of collections that are displayed by default and that'll probably smooth out the look. It'll be more helpful for users anyways

**Comment by azle** [comment]
@CGillen, I am moving the ticket over to the DONE pile. I also realized that the issue with the layout #5 is also a safari issue. Looks right in Chrome and Firefox. It also looks like we are locked into the blue and orange schematic since it also is in the graphics. Maybe we can look into this as an enhancement later on.

We should probably have some verbiage on the site for best viewing to use Firefox and Chrome.
