### ISSUE TITLE
[WIREFRAME] ITEM WORK PAGE (Single ; Parent w/Children ; Child w/Parent and Siblings), NOT LOGGED IN

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#2470]
====================
Issue #1 Collection Title, Item # and View all is missing from the top of the page that would appear opposite of the UO or OSU logo. Not sure if this was a POSM decision but the label helps to identify the collection its is part of.

Should look like this:
<img width="655" alt="Screen Shot 2022-09-08 at 12 15 06 PM" src="https://user-images.githubusercontent.com/8353860/189207018-a5261004-566e-412b-a4aa-5cb83b61b6a7.png">

====================
Issue #2 The download button is missing the white arrow icon.

Should look like this:
<img width="95" alt="Screen Shot 2022-09-08 at 12 16 36 PM" src="https://user-images.githubusercontent.com/8353860/189207264-9d572d5e-bd9e-4c9d-b50b-56caede98959.png">

====================
Issue #3 Not sure if this was a POSM decision if not the "Save to..." button should be "Add to...".

====================
Issue #4 Browser issue in Safari. The columns are mushed together fits fine in 13" screen but the columns are not liquid and get mushed together when you make the browser smaller.

Full screen on 13" screen
<img width="1440" alt="Screen Shot 2022-09-08 at 12 27 52 PM" src="https://user-images.githubusercontent.com/8353860/189209235-df5e257c-4a28-42da-8858-8cbfeaa97f46.png">

When window is smaller
<img width="768" alt="Screen Shot 2022-09-08 at 12 28 52 PM" src="https://user-images.githubusercontent.com/8353860/189209391-7efe122e-7608-4f73-8d49-1f3806f31ff3.png">

====================
Issue #5 Contact Us tab, the contact form needs to be styled. Can we also move the reCAPTCHA and send button so it is aligned right?

Fields should be styled like below:
<img width="426" alt="Screen Shot 2022-09-08 at 12 33 05 PM" src="https://user-images.githubusercontent.com/8353860/189210158-9f7221fd-7f31-4dc4-80f2-40b1d33b62a6.png">

====================
Issues #6 Text is being cut off from details tab first column at the bottom and second column top.

See link for error: 
https://prod.oregondigital.org/concern/generics/zp38x1335#metadata

Screen snap bottom left:
<img width="615" alt="Screen Shot 2022-09-08 at 4 34 33 PM" src="https://user-images.githubusercontent.com/8353860/189243542-0d7c90ff-4df4-4305-9533-f26094d86e55.png">

Screen snap top right:
<img width="784" alt="Screen Shot 2022-09-08 at 5 10 37 PM" src="https://user-images.githubusercontent.com/8353860/189246734-39f666e6-e78b-4103-8926-1c3c7b200cde.png">

====================
Issue #7 Rollover for images need styled, see ticket #2469 Issue #8

====================
Issue #8 Can we add some extra spacing above "contained in this object" and below the tab content container. Same amount of spacing when it is "Is part of" is at the top instead of "contained in this object".

What it currently looks like
<img width="420" alt="Screen Shot 2022-09-13 at 8 52 02 AM" src="https://user-images.githubusercontent.com/8353860/189948390-974ff566-c2d9-4eea-874a-42ccfaf3cb96.png">

What it should look like
<img width="295" alt="Screen Shot 2022-09-13 at 8 55 04 AM" src="https://user-images.githubusercontent.com/8353860/189949148-fcaeb763-b3bd-4a52-9256-46f18e98f366.png">

====================
Issue #9 The "Is part of" section, should include the following after description item # and copyright info.

Current look:
<img width="301" alt="Screen Shot 2022-09-13 at 9 52 58 AM" src="https://user-images.githubusercontent.com/8353860/189960941-27c20acc-b471-4b97-b4b0-a20e30d19d60.png">

What it should look like:
<img width="274" alt="Screen Shot 2022-09-13 at 9 53 21 AM" src="https://user-images.githubusercontent.com/8353860/189961017-1620cb26-22da-4229-8804-75465feea9e5.png">

====================
Issue #10 In the section "Related Items", should include the following after description include date, is part of, copyright and image icon or type.

Current look:
<img width="402" alt="Screen Shot 2022-09-13 at 9 55 56 AM" src="https://user-images.githubusercontent.com/8353860/189961523-463ae165-342d-445c-b77c-a41d5d0ff6b7.png">

What it should look like:
<img width="352" alt="Screen Shot 2022-09-13 at 9 56 28 AM" src="https://user-images.githubusercontent.com/8353860/189961626-2809a31d-5a28-42d4-aec7-3452503f0f2f.png">

====================
Issue #11 The section "contained in this object" should include the following after description date, is part of, copyright, image or type icon.

current look:
<img width="412" alt="Screen Shot 2022-09-13 at 9 59 53 AM" src="https://user-images.githubusercontent.com/8353860/189962306-ebcc3de3-3b97-43e5-b41c-c4797be9fb77.png">

What it should look like:
<img width="338" alt="Screen Shot 2022-09-13 at 10 00 14 AM" src="https://user-images.githubusercontent.com/8353860/189962382-57f9b0bc-0cb3-44f4-9a9e-402c0af0713c.png">

**Comment by azle** [comment]
Pages used to QA layout:

Single Item Page
https://prod.oregondigital.org/concern/images/fx719n57s?locale=en#content

Parent with Children
https://prod.oregondigital.org/concern/generics/zp38x1335#content

Child with Parent and Siblings
https://prod.oregondigital.org/concern/images/zp38wn251?locale=en#content

**Comment by CGillen** [comment]
As far as I'm aware, #9,10,11 are outdated according to POSM. The search results grid view uses the current tiles, these changes would be inconsistent with that.

@jsimic Preference?

**Comment by jsimic** [comment]
@CGillen  is correct, we want parity with the search results grid view.

**Comment by azle** [comment]
@CGillen, Issue #5 still needs the look and feel to the contact form elements.
