### ISSUE TITLE
[1] Configure proper URL to be sent out when user tries to recover password

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#248]
### Descriptive summary

Currently, when a user requests to recover their password, the email that gets sent out includes a url that links to `localhost`. This is because it is not configured to use the actual url the application is at. This means on staging it should route to `od2-staging.library.oregonstate.edu`. Once this is configured, this should allow users to request their password on staging. 

### Current functionality

When a user requests their password, the link that is sent out goes to `localhost`

### Expected functionality

When a user requests their password, the link that is sent out goes to `od2-staging.library.oregonstate.edu`

**Comment by revgum** [comment]
Address in https://github.com/osulp/OD2-infra configurations

**Comment by vantuyls** [comment]
@revgum so no QA needed here?

**Comment by vantuyls** [comment]
so, @straleyb, this shouldn't be closed?

**Comment by straleyb** [comment]
QA: On the staging server, before you login, click the password reset link at the top. You should receive an email which will have a link that will take you to the password change page. Change your password and save.

**Comment by revgum** [comment]
This has been fixed and validated to be sending proper links.

**Comment by straleyb** [comment]
This issue popped up because the environment variable didn't get moved over to staging. Once we are able to get the environment variable back into staging as `staging.oregondigital.org` then the password reset url should route to the right spot. The environment variable is being pulled from here
```
config.action_mailer.default_url_options = {
    host: ENV.fetch('DEFAULT_URL_OPTION', 'localhost:3000'),
    protocol: ENV.fetch('DEFAULT_URL_OPTION_PROTOCOL', 'http')
  }
  ```
  
  The DEFAULT_URL_OPTION should be `staging.oregondigital.org`

**Comment by straleyb** [comment]
This is not a problem anymore. Closing.

**Comment by shieldsb** [comment]
QA pass.
