### ISSUE TITLE
[WIREFRAME] SIGN UP, NOT LOGGED IN

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#2481]
REFERENCE LINK
https://prod.oregondigital.org/users/sign_up?locale=en#content

====================
Issue #1 Sign Up needs styled. Has no wireframe for look and feel.

Current look:
<img width="478" alt="Screen Shot 2022-09-15 at 3 10 36 PM" src="https://user-images.githubusercontent.com/8353860/190517622-af9bd89a-a6c0-4def-96d2-5fdceaf59b2b.png">

- text and input forms should be centered to the content page
- button should be background ##073C5C with text color #FFFFFF
- text Lato 16 Regular
- text links should be Lato 16 Regular #073C5C underline color #E28A25

Here is what it should look like
<img width="513" alt="Screen Shot 2022-09-20 at 10 42 31 AM" src="https://user-images.githubusercontent.com/8353860/191327392-941ca81f-9ae7-47eb-ac8c-7f34cbec44b3.png">

**Comment by azle** [comment]
@CGillen, can we format the top of the sign up screen to also include the institution and other affiliates just to keep it consistent with the other login screens.

Since the text underneath the yellow bar is lengthy. Can we have the input boxes and submit button appear below the yellow line and above the following text: 

Already have an account? [Log in]
Already a part of OSU/UO? 
[Sign in with Oregon State University]
[Sign in with University of Oregon]
[Didn't receive confirmation instructions?]
[Privacy Policy]

**Comment by azle** [comment]
Reference link: https://staging.oregondigital.org/users/sign_up

@CGillen, can we move the following text (6 character minimum) below the word Password and please include 2 lines spaces after the (6 character minimum) text and the signup button.

**Comment by azle** [comment]
@CGillen, everything looks great! Just one thing from the following link:

https://staging.oregondigital.org/users/sign_up

Can we move the following text:  (6 characters minimum) so that appears like below:

                    PASSWORD 
(6 characters minimum)

Can we also add some additional spacing between the ()'s and the sign up button. Other then that it looks great!

**Comment by azle** [comment]
@CGillen, to fix the issue with the sign up button on the following page: https://staging.oregondigital.org/users/sign_up

 Can we shorten Password Confirmation to Confirm Password? I am hoping to avoid having the word touch the button.

**Comment by CGillen** [comment]
@azle Can you take a screenshot and tell me what browser/OS you're using? I don't have the `Password Confirmation` text touching the button on FF, Chrome, and Safari on MacOS 13.0
<img width="763" alt="image" src="https://user-images.githubusercontent.com/11052958/203403108-f2d68bcd-e70a-496a-b7e0-9b9dd32a73c8.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/11052958/203403183-75e16be7-2c2c-44a6-aa31-9920934fcfbd.png">

**Comment by azle** [comment]
@CGillen, I was on safari. The left aligned fixed it! For some reason it is displaying the button on different lines across browsers.
