### ISSUE TITLE
Images in UV are very dark

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#2489]
### Descriptive summary

In QA'ing uo-athletics I've noticed that the images displayed in UV are significantly darker than the attached file. Example: [https://prod.oregondigital.org/concern/images/df739m78m](https://prod.oregondigital.org/concern/images/df739m78m). Downloaded images are fine.

### Expected behavior

The brightness, contrast, hue, and saturation of the derivatives displayed in UV and the fileset images should match.

**Comment by jsimic** [comment]
@shieldsb Putting this in the workcycle so it doesn't get lost. We're getting complaints from collection curators.

**Comment by shieldsb** [comment]
Still seeing the same issue: https://prod.oregondigital.org/concern/images/df736d74r?locale=en

**Comment by wickr** [comment]
@megwalt are you still working on this? @shieldsb 

I redid derivatives for 2 works on prod just now and your change seems to have fixed it. Your browser may cache the images, so I had to load the works in an incognito browser to check.

https://oregondigital.org/concern/images/df736d74r?locale=en
old:
![image](https://github.com/OregonDigital/OD2/assets/2293544/76e02c04-1aaa-4bc4-88d0-862b7ef45f3e)

new:
![image](https://github.com/OregonDigital/OD2/assets/2293544/7c63ca21-6d62-42d4-8884-b157bbff3c75)


https://oregondigital.org/concern/images/df71vw11c
old:
![image](https://github.com/OregonDigital/OD2/assets/2293544/a728664d-dbc3-438d-8baa-f8668bdf26ce)

new:
![image](https://github.com/OregonDigital/OD2/assets/2293544/ce83eedb-5a2f-4585-a6e9-9175a278735d)

**Comment by shieldsb** [comment]
Can add this to the ready for production column
