### ISSUE TITLE
Configure users with proper roles within admin sets

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#25]
### Descriptive summary

This will be a bunch of busy work that requires someone to go in and setup workflow roles for specific users. You can add users to workflow roles from the workflow roles tab.

Dependent on #24

Based on what was said in ticket 24, the base could work with the possible addition of a 4th, which is called "Curating" A discussion about this role will be found here "INSERT LINK HERE!!!!!!!!!!!!!!!!!". 

Configuring a new role can be quite an extensive process, and should be discussed amongst the developers. Some key files however, are as follows. 
https://github.com/samvera/hyrax/blob/5a9d1be16ee1a9150646384471992b03aab527a5/lib/hyrax/role_registry.rb

It may be as simple as adding the role to this file to register it, but some more work may be involved. We have not added extra roles to SA so we are unfamiliar with this process for the most part.

**Comment by vantuyls** [comment]
can be done manually via dashboard - probably a good starting point is to get this set up on staging. this is probably a good training opportunity for POs and SMs (cc: @jsimic @petersec @simholt)

**Comment by jsimic** [comment]
PSOM reviewed. Closed.
