### ISSUE TITLE
Failed blazegraph fetches can cause puma to crash and cause 502 errors

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#2546]
### Descriptive summary

@wickr tracked down the source of the 502 errors for prod.oregondigital.org

It's unclear yet whether this bug gets triggered every time a specific graph is called, but when fetching and caching some graphs from Blazegraph, failure can trigger an exception like below. 

```
I, [2022-10-13T13:48:34.508966 #1]  INFO -- : [c9fc44e017d15de72b3ac0eec0151593] Attempting to fetch http://opaquenamespace.org/ns/subject/summer from local graph cache.
[INFO] fetch_cached_graph(http://opaquenamespace.org/ns/subject/summer) not found in triplestore cache (http://blazegraph.od2-prod.svc.cluster.local/.:8080/bigdata/namespace/kb/sparql)
I, [2022-10-13T13:48:34.510298 #1]  INFO -- : [c9fc44e017d15de72b3ac0eec0151593] Fetching http://opaquenamespace.org/ns/subject/summer from the authorative source. (this is slow)
[INFO] fetch_cached_graph(http://opaquenamespace.org/ns/subject/summer) not found in triplestore cache (http://blazegraph.od2-prod.svc.cluster.local/.:8080/bigdata/namespace/kb/sparql)
I, [2022-10-13T13:48:34.625552 #1]  INFO -- : [c9fc44e017d15de72b3ac0eec0151593] Completed 500 Internal Server Error in 1706ms (ActiveRecord: 82.5ms)
#<Thread:0x00007fd140246828 /usr/local/bundle/gems/actionpack-5.2.5/lib/action_controller/metal/live.rb:288 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/bundler/gems/triplestore-adapter-30081b1ff8be/lib/triplestore_adapter/triplestore.rb:116:in `rescue in fetch_and_cache_graph': fetch_and_cache_graph(http://opaquenamespace.org/ns/subject/summer) failed to load the graph with exception: <http://opaquenamespace.org/ns/subject/summer>: Not Found(404) (TriplestoreAdapter::TriplestoreException)
	from /usr/local/bundle/bundler/gems/triplestore-adapter-30081b1ff8be/lib/triplestore_adapter/triplestore.rb:107:in `fetch_and_cache_graph'
	from /usr/local/bundle/bundler/gems/triplestore-adapter-30081b1ff8be/lib/triplestore_adapter/triplestore.rb:27:in `fetch'
```

This can cause `puma` to try to restart but fail.
```
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
2022-10-13 13:48:34 -0700: Read error: #<IOError: closed stream>
/usr/local/bundle/gems/puma-4.3.12/lib/puma/reactor.rb:377:in `write'
/usr/local/bundle/gems/puma-4.3.12/lib/puma/reactor.rb:377:in `<<'
/usr/local/bundle/gems/puma-4.3.12/lib/puma/reactor.rb:377:in `block in add'
/usr/local/bundle/gems/puma-4.3.12/lib/puma/reactor.rb:375:in `synchronize'
/usr/local/bundle/gems/puma-4.3.12/lib/puma/reactor.rb:375:in `add'
/usr/local/bundle/gems/puma-4.3.12/lib/puma/server.rb:508:in `process_client'
/usr/local/bundle/gems/puma-4.3.12/lib/puma/server.rb:332:in `block in run'
/usr/local/bundle/gems/puma-4.3.12/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

While `puma` can't restart itself, it also doesn't fully exit. As far as Kubernetes is concerned, `puma` is still running. At that point that replica becomes unresponsive and will be removed from requests to the `od2-prod/web` Service that incoming web requests are delivered to. Only functional replicas will continue to receive requests. Once there aren't any functional replicas, requests will all get a 502 response from the `od2-prod/web` service.

To work around this issue I've re-enabled `livenessProbe` probes for `od2-prod/web` and `od2-prod/web-admin`. When `puma` becomes unavailable, Kubernetes should Terminate the unhealthy Pods and create a new one to replace it. As long as both replicas don't crash within 4-5 minutes of each other we shouldn't lose availability, but requests might get slower with only one replica handling the load while the other restarts.

### Expected behavior

Graph fetches should always fail gracefully and exceptions should get handled.

**Comment by decimalator** [comment]
Here is a Loki query that captures all of the failed graphs with exceptions for the past 30 days. 

https://grafana.library.oregonstate.edu/explore?orgId=1&left=%5B%22now-30d%22,%22now%22,%22Loki%22,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bjob%3D%5C%22od2-prod%2Fweb%5C%22,namespace%3D%5C%22od2-prod%5C%22%7D%20%7C%3D%20%5C%22failed%20to%20load%20the%20graph%20with%20exception%5C%22%22%7D%5D

The LogQL query itself:
```
{job="od2-prod/web",namespace="od2-prod"} |= "failed to load the graph with exception"
```

The following graph endpoints have been triggering the issue:

- http://opaquenamespace.org/ns/subject/summer
- http://id.loc.gov/authorities/subjects/sh8511893
- http://opaquenamespace.org/ns/creator/FinchOtisJ
- http://opaquenamespace.org/ns/repository/FrancoVannottiCollectionSwitzerlandowner

All of the exceptions in the past 30 days have been from 404 responses

**Comment by wickr** [comment]
QA pass.
It's tough to add a non-functional URI to a test record, since the save is rejected, but some migrated works have URIs like the ones listed above that causing issues. I got a pid from Linda and confirmed it's loading fine in the viewer and edit form despite having no label, and Corey's updated log message is showing up in the logs when these URIs are tried.
