### ISSUE TITLE
Cannot create a My Shelf collection

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2568]
### Descriptive summary
As a non-admin user I can not create a myshelf collection. I can check box works, open the create collection modal, enter collection information, and submit form. I will receive the JS alert box asking to wait for collection to create, but collection never creates.

Collection never appears in admin dashboard

### Expected behavior
Collection is created for user

**Comment by jsimic** [comment]
Related #1407

**Comment by shieldsb** [comment]
The collection can be created now but no items are added to the collection.  Still can not add items to existing myshelf collections either.  When I selected a newly created collection that was showing zero items (though it was created with two items) this is what I saw: 
![image](https://user-images.githubusercontent.com/53542788/202790002-81ad8eef-69e3-49cf-8561-fdb813f908c2.png)

**Comment by shieldsb** [comment]
QA pass.
