### ISSUE TITLE
5xx server message pages

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2579]
### Descriptive summary
We have specific displays for 500 and 503 error codes that need copied to the BRPX for display when OD2 is broken or down for maintenance.

Ideally these are copied from `public/5xx.html` to BRPX automatically or are volume mounted back, but this can come much later as long as we can copy these over on request.

### Expected behavior
BRPX will serve our custom 501 & 503 error pages

### Related work
#2577 contains those `public/5xx.html`

**Comment by CGillen** [comment]
https://github.com/OregonDigital/OD2/blob/master/public/500.html

https://github.com/OregonDigital/OD2/blob/master/public/503.html

**Comment by decimalator** [comment]
this is ready for testing on staging.oregondigital.org

I've started a filesystem tree for custom error pages in `/cache/nginx/html`. 

- `od2-test`: `/cache/nginx/html/od2-test`
- `od2-prod`: `/cache/nginx/html/od2-prod`


```
server {
   include listeners-https.conf;
   server_name staging.oregondigital.org iiif-test.oregondigital.org;
   include proxy_defaults.conf;
   include ssl_defaults.conf;
   error_page 500 /500.html;
   error_page 503 /503.html;
   ssl_certificate /etc/nginx/ssl/oregondigital-org.crt;
   ssl_certificate_key /etc/nginx/ssl/oregondigital-org.key;
   location / {
      proxy_intercept_errors on;
      proxy_pass https://b8s_upstream_secure;
   }
   location /500.html {
      root /cache/nginx/html/od2-test/;
   }
   location /503.html {
      root /cache/nginx/html/od2-test/;
   }
}
```

**Comment by shieldsb** [comment]
QA pass.
