### ISSUE TITLE
Pare down dashboard for "Shelf" or bookmarking functionality for Researcher role.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#258]
### Descriptive summary

As a researcher, I want to bookmark and share collections, items, and searches that I've gathered.

### Expected behavior

For the "authenticated_user" but not Submitter/Editor/Administrator (dubbed "Researcher"), the dashboard menu to the left will need to be pared down. Whether this is a role "below" Submitter or some anti-role as defined above might still be a decision. Regardless, that "Researcher" should _not_ be presented with some dashboard menu items:

under Activity/Your Activity, do _**not**_ show

- Transfers
- Manage Proxies

The dashboard menu will include a Searches menu item below Collections and Works.

### Related work

Related mockup: https://sketch.cloud/s/bAlA0/zxQPErr

**Comment by raybrarian** [comment]
POSM review - closed

**Comment by CGillen** [comment]
Finishing closing out from above POSM review. Hyrax dashboard will not be used, building a new dashboard.
