### ISSUE TITLE
UO Login link on login page is mislabelled

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#259]
### Descriptive summary

on the login page (see screencap) the UO login link is labelled as OSU.

### Expected behavior
UO Login link labelled as UO

**Comment by mccallum** [comment]
Revised med-fi mockup: https://sketch.cloud/s/bAlA0/jgM09ez

**Comment by straleyb** [comment]
QA: Go to devise login page and links for UO and OSU should be labeled correctly.

**Comment by raybrarian** [comment]
@straleyb - can you @ who you want to QA this? FYI, if I go here: [http://od2-staging.library.oregonstate.edu/users/sign_in?locale=en] I get this for a UO login:
![image](https://user-images.githubusercontent.com/4460510/51262150-9e050b00-1966-11e9-8372-125eed1cf788.png)

**Comment by raybrarian** [comment]
QA: devise page properly labeled - I'll move this to done and open a new issue if I need to on the UO issue.
