### ISSUE TITLE
What is MVP for user groups and grouping in OD2?

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#26]
### Descriptive summary

Groupify found here: https://github.com/dwbutler/groupify

The groupify gem would be used in place of the abilities in hyrax. This would replace the abilities that are in hyrax. You can express relationships between rails models. There is some research that we would have to do to see if this meets our needs and there would have to be some discussion about how we want to configure this gem to work differently for each user. This is also dependent on whether or not the roles currently in hyrax get the job done or not. This would be based on ticket #24.

**Comment by vantuyls** [comment]
@revgum ping - any additional thoughts?

Note: hyrax roadmap currently has enhancements to permissions and roles, including better UI for such.

**Comment by revgum** [comment]
Good question.. A long while back we had a discussion and I think we punted because we were hoping/expecting the community to have a solution. I’d ask @vantuyls of the status of that, and then this is an open question on whether or not we roll this out instead.. I do think we have groups but maybe more `Role` beyond admin is enough.

**Comment by revgum** [comment]
IMO, we should try and just make the most of `cancan` and `Role` in the system to group people into different roles with specifically named `abilities`

**Comment by straleyb** [comment]
I agree with @revgum. We hsould try and stick as closely to hyrax as possible (as a theme for this project) and try to utilize things that already exist, up until we realize it doesnt cover our needs well enough. cancan, Role, and abilities has a lot of power and wiggle room to configure and customize quite a lot.

**Comment by shieldsb** [comment]
Permission matrix is being used by Features Team.
