### ISSUE TITLE
Reduce control of collections for Researcher role.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#260]
### Descriptive summary

As a researcher, I want to bookmark and share collections that I've gathered. I will not need to brand my collections and my collections will be private and not for discovery in the larger system. Sharing will consist of downloading and passing that along.

### Expected behavior

When in the Researcher role described in #258 --
Clickable lo-fi wireframe at: https://sketch.cloud/s/bAlA0/bgbe0W0/play

Under New Collection BUTTON, restrict the researcher to only the collection visibility of Private. (Description tab (including Title and Description) are the only options for researchers to edit collections.)

Under Description tab of New User Collection, eliminate the Additional fields BUTTON.

Under Collections > Actions dropdown, eliminate "Edit Collection." (Researchers will only be allowed to add or delete collections.... if they have some typo in the title they can delete and try again. Also, for those in the Researcher role, "Edit collection" and "Add to collection" could be confusing options.)

Under Collections > Actions dropdown, add "Download Collection" with one of three system responses (Dave can break these into other issues if needed): 

- Grayed out, with tooltip of "with tooltip of "Rights or your computer's network prohibits download"  (We'll want to include this instead of just not presenting the option so that users can learn why one collection has the download option and another might not.)
- Go, with a caveat - "Some items in this collection are unavailable to download due to rights or your network. A Zip file of the allowed items is being prepared and will download soon." (Zip might include a text manifest listing those not downloaded, why, who to contact for more information.)
- Go - "A Zip file of your collection is being prepared and will download soon."

This is **open to discussion** but those are the scenarios that Dave sees for Researcher Collections as a start before user testing. Other system restraints might impact the UX.

### Related work

One of a few related to #258 

(Future options might include transfer to cloud spaces like Google Drive or Dropbox instead of just Download.)

**Comment by raybrarian** [comment]
POSM review - closed
