### ISSUE TITLE
Change dashboard Works functions available to Researcher role.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#261]
### Descriptive summary

As a researcher, I will want to bookmark items that I discover. Those bookmarks might be moved into collection(s) of my creation, stay in a bookmarked items list, or both.

### Expected behavior

Related to the Researcher role described in #258 -- 
Clickable lo-fi wireframe at: https://sketch.cloud/s/bAlA0/WKg5RLK/play

Under Repository Contents/Works (or whatever labels these end up as), do _**not**_ show

- Create batch of works BUTTON
- Add new work BUTTON

Change (or eliminate) phrase "X works you own in the repository" to "x works you have marked in the repository"

Under Works > Actions > Select dropdown, eliminate Edit Work and Transfer Ownership of Work

Under Works > Actions > Select dropdown, add Download Work with one of two states

- Grayed Out - with tooltip of "Rights or your computer's network prohibits download"

- Good - "The work has been transferred to your download folder." is the response.

When "Select" checkbox checked is true, eliminate Edit Selected BUTTON

[Ideally, item/works references that mention "Delete" will be changed to "Remove" or "Clear" for this Researcher role. Remove and Delete are defined quite similarly, but the main difference between them is that delete means erase (i.e. rendered nonexistent or nonrecoverable), while remove denotes take away and set aside (but kept in existence). While Researchers will know on a moment's thought that they of course wouldn't be allowed to erase an item, it will build their confidence in the system to not have to give that moment's thought.]

### Related work

One of a few related to #258 

(Future options might include transfer to cloud spaces like Google Drive or Dropbox instead of just Download.)

**Comment by raybrarian** [comment]
POSM review - closed
