### ISSUE TITLE
[MVP] Large Compound Objects fail to load in UV

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#2616]
### Descriptive summary

Manifest loading is timing out for large compound objects, resulting in nothing showing up in the UV. This was first noticed by Sarah in QAing the gb-warner-nosatsu collection. See ticket below.

Linda poked at this a bit and Ryan W. suggests a possible way to address this is to increase the load time and cache on a cpd's first load. It does not make sense to cache everything, just the big cpds. 

### Expected behavior

UV will display a cpd regardless of size.

### Related work

[https://github.com/OregonDigital/OD2-migration/issues/123](https://github.com/OregonDigital/OD2-migration/issues/123) 

### Accessibility Concerns

n/a

**Comment by CGillen** [comment]
It's not quite blazing fast, but we're down from 60+sec to <15sec for this work with 94 attached children:
https://prod.oregondigital.org/concern/generics/df719w666?locale=en

**Comment by CGillen** [comment]
Ok, I'm not sure this is much faster.
This is the largest work linked in the other ticket: https://prod.oregondigital.org/concern/generics/df72s906s/manifest.json

I thought it was loading the manifest in 1:30 and the new version 0:45, but now I'm not sure anymore. The page I kept open from the old version says 0:40

Anyway check if this is fast enough

**Comment by jsimic** [comment]
@CGillen  Still slow enough that a user will assume there's a problem. It still only loads the first thumbnail, which is also a problem. And if I click on the next item in the Index tab, it appears to try and reload the whole manifest (or at least it takes that long for the next thumbnail/image to load.)

**Comment by CGillen** [comment]
To QA, load a large manifest once & check the time it takes to load. Load it AGAIN and you should see a large drop.
`https://prod.oregondigital.org/concern/generics/df72s906s/manifest.json` went from 40s to 500ms

**Comment by shieldsb** [comment]
This compound object has 538 items and took 40 seconds to load in UV: https://oregondigital.org/concern/generics/df736b80g
After 3.5 minutes this one was still not loading in UV: https://oregondigital.org/concern/generics/df735k498

**Comment by shieldsb** [comment]
QA fail. 
287 items took 45 seconds: https://oregondigital.org/concern/generics/bv73c806d
157 items took 20 seconds: https://oregondigital.org/concern/generics/df739z64b
377 items took 1 minute, 22 seconds: https://oregondigital.org/concern/generics/kp78hq99c

**Comment by CGillen** [comment]
QA:
- [ ] On staging, when I load the large manifest work, it does not take such a long time that I think UV is broken.
- [ ] UV isn't broken

Large manifest work to come, I will update the ticket when It's done ingesting.

**Comment by CGillen** [comment]
@shieldsb here's a large staging work https://staging.oregondigital.org/concern/generics/kp78hq99c
looks like it has 376 children

**Comment by shieldsb** [comment]
@CGillen The first time I tried to load it took nearly a minute, then 35 seconds the second time, and 25 seconds the third time. That was in Chrome.  When I tested in Firefox it loaded in about 5 seconds.

**Comment by CGillen** [comment]
35sec is probably as good as we're going to get, and caching gets us faster and faster until the work is updated or 30day passes (or maybe a reboot? idk). Let's call it and if it's still a problem open a new ticket
