### ISSUE TITLE
Add search bookmarking for Research role.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#262]
### Descriptive summary

As a researcher, I want to save and share the searches that I've made that yield results that further my research or teaching goals.

### Expected behavior

As the new Researcher role described in #258 --

Add a third menu item below Collections and Works of "Searches." A low-fidelity mockup is available: https://sketch.cloud/s/bAlA0/3Ol35jo/play

Similar to Collections and Works, users are presented with a table of saved searches.

Under Searches > Actions > Select, add just two options - Remove Search and Share Search. See #xx for functionality of Share Search option.

### Related work

This is new functionality outside Hyrax for the Researcher role but carries on from some of broken OD1 functionality of "Bookmarks" that users found confusing alongside "Search History." An automatic Search History (a la Amazon or much shopping) is going away in favor of deliberate bookmarking and easy sharing of that search. This is MVP owing to OD1 functionality.

This is open for discussion but users did find the crossed terms of Saved Searches and Bookmarks confusing.

Among a few related to #258

**Comment by raybrarian** [comment]
Functionality deprecated in Blacklight - closing after POSM review
