### ISSUE TITLE
OAI Sets are set to Private and should not show to public

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2631]
### Descriptive summary

The OAI Set Collection Type sets all collections to Private, and they shouldn't show to the public. Right now this collection type is included in the Collection metadata field display, even when not logged in.

![image](https://user-images.githubusercontent.com/2293544/206375261-1602deb6-cf4d-4b77-97cd-352e675d7d8e.png)
from https://staging.oregondigital.org/concern/documents/df71cw11z?locale=en with Incognito window

### Expected behavior

OAI Sets (or any future collection types marked Private) don't show to the public, on work show pages.
OAI Sets are viewable by admins.

### Related work

I don't think this is directly related to any of the OAI work, I think this issue would apply to any new Collection Type that is set to Private. #38 

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by sseymore** [comment]
QA fail. Looking at the record above in a private browser, not logged in and it's still visible. 

![Screen Shot 2023-01-03 at 11 10 18 AM](https://user-images.githubusercontent.com/7328774/210424928-d36c2bc6-98fa-4dfe-9f44-d50d47d9ee06.png)

**Comment by CGillen** [comment]
Just needed an index update.
Admin: 
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/11052958/210447412-219f38c8-24b4-4489-aeb9-67c0f2e905c0.png">


Private:
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/11052958/210447487-1dce2b11-2eb0-41d9-879a-5c43428cb31d.png">

**Comment by wickr** [comment]
QA Fail.
The OAI Set metadata field is no longer showing, as expected.
However, I am seeing the OAI Set name in the top header bar above the work, so OAI Sets need to be excluded from that title display as well. I wouldn't expect those collection titles to be up there even if a user could see the OAI Set.

![image](https://user-images.githubusercontent.com/2293544/211616726-c00a7b9c-9a2e-476c-8cd0-5e48a24fbd5a.png)
Private browser.

**Comment by wickr** [comment]
QA Pass.
The header on the Century Farm doc didn't show the OAI Set any longer. I removed both other collections just to double check.
Also checked a different work, which needed a reindex but was fine after that.
