### ISSUE TITLE
Write privacy statement for signup (and other?) page.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#264]
### Descriptive summary

As a user of Oregon Digital logged in with my UO or OSU ID or my personal email, I'll want to be informed of how my use of the system is to become part of any record or not.

### Expected behavior

While both OSU and UO libraries have privacy statements on their library sites, OD will want to adapt one of them or create some hybrid for the collaboration site Oregon Digital. This could be very near a boiler plate privacy statement but will serve a few purposes, among them to increase trust in the system for users of all types.

This will need to be approved by all the parties at either institution that need to approve such materials.

### Related work

Link to related tickets or prior related work here.

**Comment by jsimic** [comment]
Dependent on #1731

**Comment by jsimic** [comment]
https://docs.google.com/document/d/1NiBt64ZlTxeiC94xpCys-_XwqZGRRZ6YTpweCnPx4w8/edit
