### ISSUE TITLE
rdf_label method erroring on language

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2646]
### Descriptive summary
in OregonDigital::ControlledVocabularies::Resource, this line:
values = values.select { |val| val.language.in? %i[en en-us] } if values[0].is_a?(RDF::Literal)
is causing this error:
NoMethodError (undefined method `language' for "Arettino, Giorgio":String)
when trying to process the resource for this URI:
http://vocab.getty.edu/ulan/500017608
in this asset df71tt17f and others

I think these are the values being iterated over, a mix of RDF::Literal and strings
=> [#<RDF::Literal:0x83cd4("וסאסרי, ג'ורג'יו"@he)>, #<RDF::Literal:0x83ce8("Vasari, Giorgio (II)"@nl)>, #<RDF::Literal:0x83cfc("Vasari, Giorgio"@en)>, "Arettino, Giorgio", "George Vasari", "Giogio Vasari", "Giorgio Vassalii", "Giorge Vasari", "Vassari", "laretino", "Vasari, Giorgio II", "Arettino", "Aretino, Giorgio", "Vasari, Georges", #<RDF::Literal:0x83d10("וסאסרי, ג'ורג'יו"@he)>, "Giorgio Vassari", "Вазари, Джорджо", "Giorgio Vasarri", "Giorg. Vasari", #<RDF::Literal:0x83d24("Vasari, Giorgio (II)"@nl)>, #<RDF::Literal:0x83d38("Vasari, Giorgio"@en)>, "Giorgio Vasaro", "Georgio Vasari", "Giorgio Vasari II", "Giorgio Vassara", "Giorgino di Rezzo", "Aretino", "Giorgio Vasari", "Giorgio Vassaro", "Giorgio Vattani", "Laretino, Giorgio", "Georgi Vassari", "Giorgio Vaccari", "le Vasari", "Georges Vasari", "Vazari, Dzhordzho", "Giorgio Vasaio", "Vasari, Giorgio, II", "vasari, g.", "Giorgione d'Arezzo", "Giorgino", "G. Vasari", "Vazari", "Vasari", "Vasari, Georgio", "Giorgio d'Arezzo", "Arettino, Giorgio", "George Vasari", "Giogio Vasari", "Giorgio Vassalii", "Giorge Vasari", "Vassari", "laretino", "Vasari, Giorgio II", "Arettino", "Aretino, Giorgio", "Vasari, Georges", "Giorgio Vasaio", "Giorgio Vassari", "Вазари, Джорджо", "Giorgio Vasarri", "Giorg. Vasari", "G. Vasari", "Giorgio Vasaro", "Georgio Vasari", "Giorgio Vasari II", "Giorgio Vassara", "Giorgino di Rezzo", "Aretino", "Giorgio Vasari", "Giorgio Vassaro", "Giorgio Vattani", "Laretino, Giorgio", "Georgi Vassari", "Giorgio Vaccari", "le Vasari", "Georges Vasari", "Vazari, Dzhordzho", "Vasari, Giorgio, II", "vasari, g.", "Giorgione d'Arezzo", "Giorgino", "Vazari", "Vasari", "Vasari, Georgio", "Giorgio d'Arezzo"]

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by wickr** [comment]
I've also started seeing this.

glass plate negatives
http://vocab.getty.edu/aat/300393160
rdfs:label has no language

Frank, Joseph
http://vocab.getty.edu/ulan/500011201
rdfs:label has no language

**Comment by wickr** [comment]
QA Pass.
https://prod.oregondigital.org/concern/images/df71tt17f#data_sources  label is working well, no errors.
I was unable to locate any other works that has this type of error on a label.
