### ISSUE TITLE
Add privacy statement to signup page (at least).

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#265]
### Descriptive summary

As a user of Oregon Digital logged in with my UO or OSU ID or my personal email, I'll want to be informed of how my use of the system is to become part of any record or not.

### Expected behavior

Signup page (others?) should include at least a link to the privacy statement.

### Related work

Implementation of #264

**Comment by vantuyls** [comment]
@mccallum is there currently a privacy statement or terms of use for OD? if not, please generate a tix to create that text.

**Comment by mccallum** [comment]
Composing the statement is #264   OSU and UO have privacy statements in the footer of their set pages on OD1. (Links to each libraries' website privacy statement.) I'm not a lawyer but OD will want to either adopt one of those two that we can agree on, or create some hybrid, or get some other.

**Comment by straleyb** [comment]
Add link to sign_up page to the privacy policy

**Comment by shieldsb** [comment]
QA pass.
