### ISSUE TITLE
Dashboard Collection view, Works section, hovering over thumbnail blanks image

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2659]
### Descriptive summary

In the Dashboard Collection view, in the Works section, when hovering over a thumbnail, there's some kind of overlay but it ends up blanking the whole image.

https://prod.oregondigital.org/dashboard/collections/chuck-williams?locale=en

Regular display:
![image](https://user-images.githubusercontent.com/2293544/209217406-2e490f4b-e489-4c2b-804e-a29b4e18906d.png)

Hover over third thumbnail:
![image](https://user-images.githubusercontent.com/2293544/209217607-a025efdf-88ef-4af1-ad03-c9bcfbc07f3b.png)

### Expected behavior

Thumbnail isn't blanked out in view even with hover overlay.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by shieldsb** [comment]
QA pass.
