### ISSUE TITLE
Dashboard Collection edit form, add link in Breadcrumbs to Collection show page

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2660]
### Descriptive summary

A work's edit form has a link in the Breadcrumbs to the show page, and I think this would be useful for Collections as well. Back on the main Collection dashboard page there is a 'Public view of Collection' link but not one on the edit form.

Current view of Collection edit form with Breadcrumbs but no title link:
![image](https://user-images.githubusercontent.com/2293544/209218949-eaf31746-0de7-428a-8e66-5ab1a8386d9d.png)

Work edit form with link of partial title in Breadcrumbs before Edit link:
![image](https://user-images.githubusercontent.com/2293544/209218831-f8aa344a-e7dc-428a-8304-11ec7f8f9cd1.png)

### Expected behavior

Collection edit form has a link to the Collection show page, so it's easy to open if not already.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by shieldsb** [comment]
QA pass.
