### ISSUE TITLE
[2] Enable fields based on MAP to accept URIs as linked data fields

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#267]
### Descriptive summary

We have some base work set up that allows for the connection between OD and blazegraph. This means you can insert a URI into a form field that has been decided as linked data, and it will hit that endpoint, return the data and display the proper label linking to the proper place. 

Currently we have a lot of work put into place to enable this, but we have to configure the fields to be triple powered. This is done here: https://github.com/OregonDigital/OD2/blob/master/lib/oregon_digital/triple_powered_properties/work_behavior.rb#L21 If we add the fields to this list, then they will be viewed as controlled and expect URIs

### Expected behavior

Put a URI into the controlled fields, and it displays a linkable lable to the user on the show page

### NOTE

We need to know which fields are controlled so check the MAP

### Sub-tickets
- [x] #400 
- [x] #378 
- [x] #379 
- [x] #380
- [x] #381 
- [x] #382 
- [x] #383 
- [x] #384 
- [x] #385 
- [x] #386
- [x] #421 
- [x] #429

**Comment by straleyb** [comment]
Fields need to behave nicely with QA whether or not a URI or a string is input

**Comment by straleyb** [comment]
Ready for QA

**Comment by raybrarian** [comment]
POSM review - closed
