### ISSUE TITLE
[5] Enable Typeahead for controlled fields

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#268]
### Descriptive summary

Some fields will be designed to hit a specific endpoint such as Based_near which hits the geonames endpoint. If you fill out the location field, it does a search and hits an endpoint and displays it to the user to choose from. We need to enable typeahead for all controlled fields. This means, finding out which fields are controlled, and building a QA object that the app knows about and enable it to hit its endpoint. This means knowing which end point to hit for something like subject. 

We need to look at the MAP and find out which fields need which endpoints. Then we need to implement a QA object for each field that will hit a specific endpoint. This should enable typeahead. More configuration may be needed to parse out the label and display it as a choice in the typeahead.

### Expected behavior

Typing in a controlled field, displays a typeahead with results from a specific endpoint.

**Comment by vantuyls** [comment]
@jsimic @wickr how important is typeahead for OD2? I don't recall it being an MVP

**Comment by straleyb** [comment]
Relates #313
