### ISSUE TITLE
Create A - Z and numerical sort dropdowns on Explore Collections index pages

### ISSUE THREAD

**Issue by petersec** [OregonDigital/OD2#2682]
### Descriptive summary

On the Explore Collections pages, we want to provide the ability for users to sort collections alphabetically and by number of items contained in the collection. Doing so will improve efficiency of use for Explore Collections pages, while also providing feature parity with OD1.

### Expected behavior

For all Explore Collections pages - 'All'; 'Oregon State University'; 'University of Oregon'; and 'My Collections' - users will see a Sort dropdown option similar to what appears on search results pages. The Sort options made available for Explore Collections will be 'Title A-Z'; 'Title Z-A'; and 'Numerical Sort', with the most heavily populated collections appearing at top.

**Comment by shieldsb** [comment]
QA fail.  Sort options now available, but the collections are not sorting appropriately.

**Comment by jsimic** [comment]
QA pass. Things are sorting, though it is not clear when using the date sorts what date is being used. Not a deal breaker.

@CGillen Can we omit title initial articles, i.e The, from the alphabetical sorts?

**Comment by shieldsb** [comment]
QA fail.  sort sorting with initial article "The." @jsimic Is that MVP or an enhancement?

**Comment by jsimic** [comment]
@shieldsb It can be an enhancement if its sucking up too much time.

**Comment by shieldsb** [comment]
QA fail. Putting this in the backlog for after launch.

**Comment by shieldsb** [comment]
QA pass
