### ISSUE TITLE
Change the Sort dropdown list's default number from 8 to 20

### ISSUE THREAD

**Issue by kmthorn** [OregonDigital/OD2#2683]
### Descriptive summary

On all item search pages, users should have the ability to click on the sort dropdown and have their first option be 20. Currently the default option is 8.

### Expected behavior

For all item search pages, when a user clicks on Sort's dropdown option 20 should be the first number that they can select.

### Related work
No

### Accessibility Concerns

No

**Comment by shieldsb** [comment]
QA pass.
