### ISSUE TITLE
In Universal Viewer, index tab should appear as the default Contents menu option for complex objects

### ISSUE THREAD

**Issue by petersec** [OregonDigital/OD2#2684]
### Descriptive summary

When first accessing a complex object within Universal Viewer on an item show page, the user should see the Index tab under 'Contents' on the left hand side of the viewer, rather than the Thumbnails tab. Currently the Thumbnails tab displays by default. Because of this, it is not immediately clear to the user that more than one item is accessible within the viewer. Switching the default tab to Index will give a better sense to the user of the full scope of content available to them as they work with the given complex object. Should they wish to work more specifically with the first child item in the viewer, it will be a more intuitive process for them to do so by clicking on the Thumbnails tab.

### Expected behavior

When the user arrives at the item show page for a Complex Object, upon scrolling down to Universal Viewer they should see 'Index' displayed as the default tab on the left hand side under 'Contents.'

**Comment by shieldsb** [comment]
QA pass

**Comment by teamestreet** [comment]
Thumbnail tab is the default view in UV for complex objects. 

Example: https://oregondigital.org/concern/generics/1j92gp11d
Example: https://oregondigital.org/concern/generics/df729170r
