### ISSUE TITLE
Add space between subject metadata found at bottom of collection landing pages

### ISSUE THREAD

**Issue by kmthorn** [OregonDigital/OD2#2685]
### Descriptive summary

On all collection landing pages, users need the ability to read subject metadata. The terms do not have spaces between them. Spaces need to be added to improve readability.
![od-collsubheadings](https://user-images.githubusercontent.com/36867009/212167952-5c2a484a-e242-4ead-923d-afb247550d11.jpg)

### Expected behavior
At the bottom of all collection landing pages, subject metadata should have space between them.

### Related work
No

### Accessibility Concerns

No

**Comment by shieldsb** [comment]
QA pass
