### ISSUE TITLE
Change global header logo to say "Unique Cultural Heritage Collections"

### ISSUE THREAD

**Issue by kmthorn** [OregonDigital/OD2#2686]
### Descriptive summary
When a user comes to Oregon Digital the logo should read "Unique Cultural Heritage Collections" not "Unique Cultural Heritage Collection". This should be applied to all pages

![od-logoname](https://user-images.githubusercontent.com/36867009/212170216-f2d8891e-277b-4daa-b861-127c12fdf3a9.jpg)

### Expected behavior
In the global header, the logo should read "Unique Cultural Heritage Collections" not "Unique Cultural Heritage Collection".

### Related work

None

### Accessibility Concerns

None

**Comment by shieldsb** [comment]
QA pass
