### ISSUE TITLE
[3] Configure showpage to display different types of linked fields

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#269]
### Descriptive summary

There are multiple types of ways we want to display linked data on the show page. We may want the label to link to a search. We may want the label to link to a search with an external link to the endpoint. We may need to display multiple labels each with its own link. We may just want to display the link. 

We need to decide how we want to display each field on the show page that is linked and configure the system to be able to handle that. This means building a renderer that can be used to configure the system to extract data and build html to allow for the display to work properly. This has been done in SA and can be ported over for ease of use. 

### Expected behavior

The displayed controlled field on the show page renders properly.

**Comment by wickr** [comment]
Some relation to #45
