### ISSUE TITLE
Configure metadata based on worktypes

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#27]
### Descriptive summary

This work will be to configure the metadata for each worktype in the system. Each work type will have its own metadata which will be laid out im the MAP by the metadata group. >>>>>>>>>>>>>>> INSERT LINK TO MAP HERE >>>>>>>>>>>> After the metadata is laid out in the map, it will need to be translated over to each work type based on work done here. https://github.com/osulp/Scholars-Archive/tree/master/app/models/concerns/scholars_archive. Each model has *_metadata.rb where * is the work type name in the system. (I.E article_metadata default_metadata etc.) Each piece of metadata will have to be taken care, to make sure the controlled vocabulary fields are configured as controlled vocabulary metadata fields and ordered fields are configured as ordered fields with the proper predicates. 

This work will have to be translated over to make sure that the forms all have the proper metadata as well as well as having the metadata in the proper order. Alpha sort the fields in the metadata files.

Here are a few examples of configured metadata and supporting configurations in the metadata file that are needed.

```
property :abstract, predicate: ::RDF::Vocab::DC.abstract do |index|
    index.as :stored_searchable
end
```

The property command comes from a supporting library already in hyrax. Followed is the name of the field to be configured. The next is the definition of the predicate which should come from the map. Next comes the description of how the field will be indexed in solr. The main configurations are `:stored_searchable` and `:facetable`. This will allow the metadata in the field to be searched and used as a facet.

Another potential configuration will be for linked data. 

```
property :based_near, predicate: ::RDF::Vocab::DC.spatial, class_name: Hyrax::ControlledVocabularies::Location do |index|
    index.as :stored_searchable, :facetable
end
```

The only difference to note in this one is the defined class name. This class is a linked data class and will be discussed later. If research would like to be done now, check this file. 
https://github.com/samvera/hyrax/blob/5a9d1be16ee1a9150646384471992b03aab527a5/lib/hyrax/controlled_vocabularies.rb

and

https://github.com/samvera/hyrax/blob/5a9d1be16ee1a9150646384471992b03aab527a5/lib/hyrax/controlled_vocabularies/location.rb

Keep in mind the bottom of the metadata file
```
accepts_nested_attributes_for :based_near, :allow_destroy => true, :reject_if => proc { |a| a[:id].blank? }
```
This configures the models to accept nested attributes for an object. Since there are extra fields associated with controlled vocabularies, this is what helps with that.

Lastly there is this configuration

```
property :nested_ordered_abstract, predicate: ::RDF::Vocab::BIBO.abstract, :class_name => NestedOrderedAbstract do |index|
    index.as :stored_searchable
end
```
This looks similar to the controlled vocabulary but is denoted as an ordered field. This will come into play later.

We may be able to skip over these configurations early on and configure them simply, until we focus more on metadata logic. 

### Expected behavior

This should configure the work types in the system to have the proper metadata fields in the system with the proper predicates.

### Actual behavior

No change may actually be seen however, it can be tested by inspecting the objects in the console on creation.

### Requirements/ToDo
- [x] create separate ticket for metadata fields for each work type
~~create ticket for Configure Ordered Metadata~~

### Related work

#21

**Comment by vantuyls** [comment]
MAP should convey all of this information:
https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0

@wickr @jsimic

**Comment by wickr** [comment]
QA: work types are set up with the current type-specific metadata fields added, more to come later. Controlled vocabularies definitions and any specific ordering/nesting implementations are also coming later.
