### ISSUE TITLE
Library images on the home page are skewed at smaller screen sizes

### ISSUE THREAD

**Issue by mellinma** [OregonDigital/OD2#2705]
### Descriptive summary

This is not impeding functionality, but the images of the Valley Library and the Knight Library appear stretched at smaller screen  sizes.  See screen shot

### Expected behavior
Images would be more responsive to the screen size so that they keep the correct aspect ratio

### Related work

none

### Accessibility Concerns

no known accessibility concerns

![Screen Shot 2023-01-20 at 9 44 26 AM](https://user-images.githubusercontent.com/11778515/214107633-a8dfb6d1-742c-4465-90b0-02972301c28d.png)

**Comment by mellinma** [comment]
![Screen Shot 2023-01-23 at 9 30 47 AM](https://user-images.githubusercontent.com/11778515/214108694-d1a6abc4-ec88-4656-b9ff-bcf3bb7fc0ec.png)

**Comment by mellinma** [comment]
The second screen shot is tablet sized - horizontal stretching

**Comment by azle** [comment]
Needs a solution.

**Comment by jsimic** [comment]
@shieldsb If we can possibly get this worked out before launch, please get it done. It's a bit embarrassing.

**Comment by shieldsb** [comment]
QA pass per Margaret
