### ISSUE TITLE
[2] Display labels instead of URIs in faceting 

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#271]
### Descriptive summary

We need to change the system to look at the label of a field, rather than its uri, to display properly. The link should use the label to search instead of the URI as well. 

### Expected behavior

Facet is displayed using the label of a controlled field, and clicking it searches for the label. 

### Related work

Link to related tickets or prior related work here.

**Comment by CGillen** [comment]
QA:
- [ ] Properties from the MAP that indicate they are facetable create facets when attached to works
- [ ] Facets properly limit searches
- [ ] Facets Display for controlled vocab field labels, not their URIs

**Comment by vantuyls** [comment]
QA Failed - facets showing URIs, not labels.

**Comment by vantuyls** [comment]
QA Failed - facets showing URIs, not labels.

**Comment by vantuyls** [comment]
<img width="1196" alt="Screen Shot 2019-04-11 at 1 18 29 PM" src="https://user-images.githubusercontent.com/9534576/55990412-7a4b1b80-5c5c-11e9-90bc-3905ffe18e0c.png">

**Comment by vantuyls** [comment]
QA Failed - Location still shows URI instead of label

**Comment by CGillen** [comment]
New QA:
- [ ] Location facet only appears once
- [ ] Location facet only displays labels

**Comment by vantuyls** [comment]
QA pass.
