### ISSUE TITLE
Dashboard oEmbed specific status page gives wrong message

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2727]
### Descriptive summary

From the Manage oEmbeds page in the Dashboard, clicking through to one that is working and shows 'Good' on that page, the specific oEmbed page says the URL is broken.

![image](https://user-images.githubusercontent.com/2293544/216681825-fd7d6697-1dec-4350-b907-619f3359224f.png)

It would also be good to make the form box holding the URL maybe 3 times wider than it is.

### Expected behavior

oEmbed status page shows correct message.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by shieldsb** [comment]
QA pass
