### ISSUE TITLE
[1] Create and implement contact page and email text

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#273]
### Descriptive summary

Work can be done on the contact form to make sure the wording is correct on it, it provides the proper information and links, and tells people the proper person to contact if they need further assistance. 

Service managers also need to determine the workflow for these notifications.

### Expected Behavior

Contact form emails are sent properly and look correct.

**Comment by kmthorn** [comment]
Kate and Chris will be writing the content for the email text during their Service Manager Retreat in February.

**Comment by CGillen** [comment]
@petersec Was this content written? Can we get a link in this ticket

**Comment by petersec** [comment]
I don't think anything was ever written. 

I think we can reuse the text that appears on the OD1 'Contact Us' page and include the same form that we're using on the item show pages. The text is:

> Oregon Digital is a joint collaboration between the [University of Oregon Libraries](http://library.uoregon.edu/) and [Oregon State University Libraries & Press](http://osulibrary.oregonstate.edu/). Oregon Digital hosts materials from both institutions, as well as collaborating partners.

> Please use the following form to send us feedback:

(and then add the same Contact Us form that appears on the item show pages)

**Comment by shieldsb** [comment]
QA fail. Chris' text above doesn't appear on the contact us page or the email that is received after sending a message.  @azle @jsimic Is there a wireframe for this?

**Comment by shieldsb** [comment]
On the Contact Us page, UO and OSU are not linked.  Also @azle @jsimic, should the blue text box be on this page too? 
![image](https://user-images.githubusercontent.com/53542788/193013625-d6c276df-cdc6-4775-9556-4b0b3b85f179.png)

Form the work page Contact Us tab, the links to UO and OSU give an oops 404 page when selected: 
![image](https://user-images.githubusercontent.com/53542788/193013940-ae4632e2-5171-4403-a2f1-8c4f00476d2b.png)

**Comment by azle** [comment]
@shieldsb @jsimic, I think we can combine the text and remove the blue box. I was looking over the mockups and I don't see anywhere that we are using alert boxes in this manner.

**Comment by shieldsb** [comment]
QA pass.
