### ISSUE TITLE
[1] Verify notifications are all correct. 

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#274]
### Descriptive summary

We need to make sure that our notifications are going to be helpful. One of the most important notifications that I can think of is a review on your work occurred. Changes on your work need to be done. A work is now in the review queue. 

If we can make sure those are all working correctly and are helpful, that would be good. 

### Expected behavior

A user receives notifications for when a work is now in the review queue, when your work has been reviewed, etc.

### Related work

Link to related tickets or prior related work here.

**Comment by raybrarian** [comment]
POSM review - closed

**Comment by raybrarian** [comment]
Handled in #230
