### ISSUE TITLE
[1] Verify emails for password recovery are correct.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#275]
### Descriptive summary

Verify that all the information provided in the password recovery are correct. This email needs to be useful enough to allow a person to reset their password easily.

### Expected behavior

Emails for password reset are functional and looking correct.

**Comment by revgum** [comment]
These emails could use some improvement, at minimum with the subject line to mention Oregon Digital. Here's a screenshot of a password reset email for reference and to gather feedback from @vantuyls @raybrarian @mccallum etc.

![screen shot 2019-01-18 at 9 53 05 am](https://user-images.githubusercontent.com/32885/51404042-1aceeb00-1b07-11e9-9d52-d1ccae7c6505.png)

**Comment by mccallum** [comment]
Link in staging.oregondigital.org reset email goes od2-staging.library for the reset there. Change Password there requires user to know old password. :( Are there plans to just send the old as a reminder or do we want to get rid of the requirement to know your old password in order to change it?

**Comment by vantuyls** [comment]
@straleyb is there any reason to have concern about the URL issue @mccallum mentions above?

**Comment by vantuyls** [comment]
@revgum your comments are reflected in a new issue: https://github.com/OregonDigital/OD2/issues/365

**Comment by straleyb** [comment]
Yes, since both domains work, but it only has one configured uri to return, so eventhough the other uri would work, it wouldnt return them to the same url they came from.

**Comment by vantuyls** [comment]
@straleyb is this the expected behavior?

**Comment by straleyb** [comment]
Thats a good question. If we dont care as long as they are getting to the app, then thats fine, but if we want to return them to the same url then we will have to configure a second email, that gets sent out depending on what url they came from.

**Comment by revgum** [comment]
The problem `od2-staging.l.o.e` is related to the deployment configuration setting `DEFAULT_URL_OPTION` improperly. `od2-staging.l.o.e` is invalid any longer.. I've updated the configuration and it will be reflected in the next deploy.

**Comment by vantuyls** [comment]
QA conducted by resetting password and working through the reset password. QA pass.
