### ISSUE TITLE
Updates to Footer

### ISSUE THREAD

**Issue by shieldsb** [OregonDigital/OD2#2754]
### Descriptive summary

Activate links for Explorer Collections and Advanced Search in the footer.  Hide "My Collections" and "Oregon Digital WC3-0.0.1-" in the footer. 

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by jsimic** [comment]
QA pass
