### ISSUE TITLE
Recommended Browser Notice

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#2771]
The homepage, needs text dealing with the recommend best viewed browsers for the entire to be viewed on for MAC and PC.

**Comment by lamtu1** [comment]
Hi @azle, I was wondering how would you want this message to be on the homepage? Would it be like the `announcement banner` or something else in a different area on the homepage?

And also what kind of recommendation message do you wanted to be display?

**Comment by azle** [comment]
The layout looks good. I had a question about the wording for POSM are we going to fully exclude Safari? There is a related ticket #2986.

**Comment by azle** [comment]
@lamtu1 @jsimic Julia is verifying with POSM

**Comment by lamtu1** [comment]
Hi @jsimic, I just want to check to see if `POSM` has finish verifying it. Thank you

**Comment by lamtu1** [comment]
> @lamtu1 Thanks for the reminder. Yes, the consensus is the placement is good. The wording needs to be reconciled with the wording in the footer: "Trouble Viewing Oregon Digital?", i.e. the shorter phrase with the question mark at the end.

@jsimic Would this then wording `Trouble Viewing Oregon Digital?` be change to `Trouble Viewing` or `View Experience` or `OD Viewing Experience`?

**Comment by jsimic** [comment]
@lamtu1 Just use "Trouble Viewing Oregon Digital?"on the both the sidebar and the footer

**Comment by shieldsb** [comment]
QA pass.
