### ISSUE TITLE
Resize analytics button on work show page

### ISSUE THREAD

**Issue by shieldsb** [OregonDigital/OD2#2779]
### Descriptive summary

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

Resize analytics button on work show page so that it aligns with the "print" "add to" and "download" buttons. 

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by shieldsb** [comment]
![image](https://user-images.githubusercontent.com/53542788/218811191-e38a07f3-78c9-4af2-98a0-0dd0b30b276c.png)

**Comment by wickr** [comment]
This might be browser specific, I'm not seeing the issue with Chrome on Linux.

**Comment by shieldsb** [comment]
Issue resolved.
