### ISSUE TITLE
Ordering of child/sibling items in complex objects

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#2786]
### Descriptive summary

There appears to be no order to the child or related items when viewing complex objects. This makes flipping through the paged thumbnails below the metadata challenging.

### Expected behavior

Child works and sibling works should be displayed ordered A-Z by title.

### Related work

#1354 #47 #44

**Comment by lsat12357** [comment]
discussed this asset with jsimic: https://oregondigital.org/concern/generics/wm117t01t?locale=en
and we agreed that the order that is returned by item.ordered_member_ids is the order that should be used when displaying child objects. My hypothesis is that when the manifest is created, the order is potentially jumbled at the point in which solr is queried with a list of the children.
It occurred to me however that it is possible that there is some kind of wonky indexing behind the problem?

**Comment by KevinJonesMeta** [comment]
QA pass. https://staging.oregondigital.org/concern/generics/kp78hq99c correctly A-Z sorts as expected.
