### ISSUE TITLE
MyShelf: Searching for an existing collection is not working as expected

### ISSUE THREAD

**Issue by kmthorn** [OregonDigital/OD2#2795]
### Descriptive summary
If I am any Oregon Digital user who has an existing MyShelf collection then I want to be able to search for that collection when adding new items to it. In the 'Add this Item' screen, when I search for an existing collection, the system tells me to type in 2 letters and my existing collection will appear. On staging, this is not happening as expected. Our testing indicates that the system provides the expected behavior when you truncate a word by using an asterisk. 

For example: In a collection titled "Test", the system will find the existing collection if I search for the entire word 'Test' or if I type in "t*". It does not find it if I type in "t", "te", "tes".

### Expected behavior
On the 'Add this Item' screen, the system is prompting me to type in 2 letters to find the existing collection. As a user, I expect that typing in the first two letters of any word in the existing collection's title will find that existing collection.

### Related work

#1407 screenshots can be found in this ticket. See comment [from Feb 9th 2023](https://github.com/OregonDigital/OD2/issues/1407#issuecomment-1424866835)

### Accessibility Concerns

There might be something related to the add this item screen, but this would need to be verified by a developer.

**Comment by shieldsb** [comment]
QA pass.
