### ISSUE TITLE
MyShelf: Sharing collections not working as expected

### ISSUE THREAD

**Issue by kmthorn** [OregonDigital/OD2#2796]
### Descriptive summary
Our testing indicates that sharing only works if the user 'enables' the share by clicking the Share link next to the collection's title on the My Collections index page. If the user does not do this and then attempts to share the collection by copying and passing along the link next to the 'Share This:' prompt on a personal collection's landing page, that link will not open for the user to whom it has been shared.

### Expected behavior
As any Oregon Digital user who makes a personal collection, I should be able to copy the Share link next to the collection's title on the personal collection's landing page, share the link with another person, and expect them to be able to open the collection that has been shared.

### Related work

Initially notes in #1407. See https://github.com/OregonDigital/OD2/issues/1407#issuecomment-1399088961

### Accessibility Concerns
None.

**Comment by jsimic** [comment]
You are not supposed to even see the link until you have Shared the collection, as per wireframe. If you are seeing this, that is a wireframe issue. [https://drive.google.com/file/d/1mwcIqLWdMdjJArp23u05sZq58hvWT7Qz/view?usp=share_link](https://drive.google.com/file/d/1mwcIqLWdMdjJArp23u05sZq58hvWT7Qz/view?usp=share_link)

**Comment by petersec** [comment]
The 'Share This:' link shown below is what we're referring to. This is what is displaying for a personal collection on staging that has not had 'Share' enabled from the My Collections index page. 

![sharing-link](https://user-images.githubusercontent.com/8129900/220185162-8d1fa03b-b4dc-4b0a-a8fa-e0fc61b93a1b.png)

**Comment by petersec** [comment]
Confirming QA pass on Staging, per #2811
