### ISSUE TITLE
Sorting issues with search results 

### ISSUE THREAD

**Issue by shieldsb** [OregonDigital/OD2#2802]
### Descriptive summary

Reported issues with sorting search results in ascending and descending order: 

I've received a report of buggy search results sorting from a SCARC colleague. In working with a patron, they searched for "athletic training", faceted on institution (OSU), decade (1970s) and then sorted by Date Ascending. [Their results](https://oregondigital.org/catalog?f%5Bdate_combined_decade_label_ssim%5D%5B%5D=1970-1979&f%5Binstitution_label_sim%5D%5B%5D=Oregon+State+University&locale=en&per_page=60&q%5B%5D=%22athletic+training%22&search_field=all_fields&sort=date_dtsi+asc) (44 items) sort the Barometer newspapers in correct order at the top of the search results page, but other publications (beginning with item 18) are not intermingled with the newspaper results and are also not sorted by Date Ascending among themselves. I can create a ticket describing this specific issue, if that's helpful.

In main search results, the Sort: Date Descending, and Sort: Date Ascending aren’t clearly sorting based on Date field. I’m not sure what they are using but works aren’t in date order. Also, if I try to sort Date Descending multiple times for the same results, I get a different order most of the time. I compared modified and submission dates on several works and didn’t see a pattern connected to sort order for Date Descending.

Also, after viewing a work and using the breadcrumb to go back to the results the order of results will be different though the sort type displayed does not change.

A search for “Hamm” limited to OSU in the Oregon State University General Catalogs, 1985-2000 using the slider for the date range. After sorting for Descending order the top three results have “/” in the date field which is EDTF compliant but maybe a factor? 

 

 

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by KevinJonesMeta** [comment]
QA Fail.

I tested "athletic training" on staging without facets and got 4 results. Order of results did not change between Date Ascending and Date Descending. Order was different from Relevance.

**Comment by KevinJonesMeta** [comment]
QA Fail.

Tested again with "athletic training" on staging and got 4 results. Date Ascending order same as Date Descending, and was not accurate. Sort order not stable when changing back and forth between sort options. Tested with search "Geese" (3 results) and had same sort outcomes.

Initial Sort Order of Results (first > last):

Relevance: 2015-06-05; 1986; 1979;1988.
Date Ascending: 2015-06-05; 1979; 1988; 1986.
Date Descending: 2015-06-05; 1979; 1988; 1986.
