### ISSUE TITLE
Next/Previous page counts out of sync

### ISSUE THREAD

**Issue by shieldsb** [OregonDigital/OD2#2803]
### Descriptive summary

Example complex object: [https://oregondigital.org/concern/images/fx71d5432?child_page=5&locale=en&page=4](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Foregondigital.org%2Fconcern%2Fimages%2Ffx71d5432%3Fchild_page%3D5%26locale%3Den%26page%3D4&data=05%7C01%7CBeth.Shields%40oregonstate.edu%7Cb2da8bc002c34f7dad0f08db150a2e77%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C638126905684778730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hFsGrXbgYkLaLEZMCLO47nVd0dyc7KlJpj8%2BZHFiQms%3D&reserved=0)

When I use the child object navigation at the top or bottom of the Works and Files section, it doesn’t stay in sync with the same navigation at the other end of the list. Clicking on specific sheet pages on one end doesn’t change on the other. When I clicked next instead of a sheet page, they actually flipped the highlighted sheet page numbers which made knowing where I was in the list confusing.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by CGillen** [comment]
This is intended behavior.

- The top navigator is for the `contained in this object` section (notice `&child_page=5` in the url)
- The bottom navigator is for the `works and files` section (`&page=4`)

**Comment by CGillen** [comment]
QA: Ask initial founder of issue if above comment resolves their issue/understanding

**Comment by KevinJonesMeta** [comment]
Ah, thank you. That covers it.
