### ISSUE TITLE
OAI colls

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2812]
### Descriptive summary

I'm planning to create the oai colls based on a list similar to the collections.yml that we used for initially populating OD2 with collections.
The new list would not include aa-images, or any other coll that is entirely uo or osu only.
I think the only question is whether or not to use the description field, and what value to use.
On OD1 OAI we create the description on the fly, from the institution and title, so we could potentially do something similar here.
wickr suggested however that we consider populating the description field, and possibly come up with a short blurb to use.

It looks like with reindex_extent set to 'limited' we could add the boilerplate description (i.e. title and institution) now, and update later without launching a massive reindex of all the member assets.
(We will also need to configure? OAI to actually provide the description)

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by sseymore** [comment]
@lsat12357 @wickr @jsimic to discuss at next metadata team meeting

**Comment by sseymore** [comment]
https://od1.oregondigital.org/oai?verb=ListSets

The team just talked about this. Please use the description from the collection-level metadata record and append institution at the end.

**Comment by wickr** [comment]
In our meeting today I think we've settled on using OAI Set's Description field for setDescription. This will continue to be separate from Digital Collection Description field (future rich text formatting would not work in the OAI Set field). The same text can exist in both but will need to be copied manually.
Institution value should continue to be appended at the end automatically by the system.

If, when re-creating existing OAI sets from OD1, UO wants to automatically pull in existing collection description data that should be doable.

**Comment by lsat12357** [comment]
I've gone through and verified counts, in some cases pids, between colls and their oai coll.
