### ISSUE TITLE
PDF Image trim is too aggressive. Mostly blank pages get reduced too far and cause errors

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2817]
### Descriptive summary

The trim command is too aggressive for most PDF documents in general, often removing all page margins. 

![image](https://user-images.githubusercontent.com/2293544/222297703-7db2dffc-15f3-4482-825c-d6071da20c3b.png)

Further, mostly blank pages, such as those with just a page number, get trimmed down so far that they cause a FloatDomainError with the jp2 processor, halting derivatives.

PDF document with error (only 12 pages derived instead of full 130):
https://prod.oregondigital.org/concern/documents/gb19fq534#data_sources

Page with just a page number in corner, Page 13 of PDF (shown on OD1):
![image](https://user-images.githubusercontent.com/2293544/222296950-e5b64bd5-9580-4900-b3b7-e1b2edb52a40.png)
OD1 link: https://od1.oregondigital.org/catalog/oregondigital:gb19fq534#page/12/mode/2up

I don't have the exact value for this page's trimmed result, but this equation uses the longest dimension of a page to calculate levels and any value less than 96 throws a FloatDomainError.
https://github.com/OregonDigital/OD2/blob/master/lib/oregon_digital/derivatives/image/jp2_processor.rb#L39

tested in console:
```ruby
irb(main):375:0> long_dim = 96
=> 96
irb(main):376:0> 1 + Math.log2(long_dim / 96).floor
=> 1
irb(main):377:0> long_dim = 95
=> 95
irb(main):378:0> 1 + Math.log2(long_dim / 96).floor
Traceback (most recent call last):
        2: from (irb):378
        1: from (irb):378:in `floor'
FloatDomainError (-Infinity)
```

The latest version of the jp2 processor in hydra-derivatives seems to have a guard against this:
https://github.com/samvera/hydra-derivatives/blob/main/lib/hydra/derivatives/processors/jpeg2k_image.rb#L53
which might be the easiest thing to update.

### Expected behavior

PDF derivatives succeed even for small/trimmed page images.

### Related work

[Link to related tickets or prior related work here.](https://github.com/OregonDigital/OD2/pull/2715)

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by CGillen** [comment]
QA requires an ingest of new PDFs. Use one from here and one from https://github.com/OregonDigital/OD2/issues/1425

**Comment by wickr** [comment]
QA Pass.
I didn't ingest a new one but I did redo derivatives on the original one here:
![image](https://user-images.githubusercontent.com/2293544/223336604-6082a9de-0993-4e20-ba81-1eb49b8e271e.png)

And from the other ticket, the Beaver yearbook and the sports media guide PDF are looking good on production: 
https://oregondigital.org/concern/documents/12579s71x?locale=en
https://oregondigital.org/concern/documents/fx71c840p?locale=en
