### ISSUE TITLE
include work Identifier in Contact Us form emails

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#2819]
### Descriptive summary

Emails from the Contact Us form include the work title in the subject line, which can be insufficient to identify a work.

### Expected behavior

Emails should continue to have the work title in the subject line, and include the Identifier in the body of the message if the user is utilizing the Contact Us tab on a work show page.

### Related work

#137, #230, #273, #278, #286, #315, #442, #1550, #1608, #1649, #2053

**Comment by shieldsb** [comment]
QA fail.  No identifier in body of the email.

**Comment by straleyb** [comment]
@jsimic Since we have the title of the work in the email subject, is it fine if we put the id right next to the title in the subject too or do we need it in the body of the email?

**Comment by jsimic** [comment]
@straleyb That will work. As long as it's somewhere. Probably better if it comes before the title, since long titles appear to get cut off.

**Comment by straleyb** [comment]
Ill update it and push this back to QA when its done.

**Comment by lamtu1** [comment]
@jsimic I would love to help out on this ticket. Would it be okay if you have a copy or a demo of the email that you get so I can get an understanding what it say?

**Comment by jsimic** [comment]
@lamtu1 This has been working for a while now. The work id is appended to the email subject as such: Oregon Digital Contact Request -  PH036_5042 Lee Moorhouse photographs (df713p013). I think this ticket can be closed.
