### ISSUE TITLE
Revise search results tally language for searches that return fewer than 20 results

### ISSUE THREAD

**Issue by petersec** [OregonDigital/OD2#2822]
### Descriptive summary

Currently, the search results tally language for searches that return fewer than twenty results is confusing. [This search](https://oregondigital.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q%5B%5D=%22Rachel+Lilley%22#content), for instance, returns six results, and the tally language at the top of the search results page reads "Showing 1 to 20 of 6 item(s)."

![results-tally](https://user-images.githubusercontent.com/8129900/222585035-d41e81f4-9212-4c2e-ba45-45838f7af3ab.png)

### Expected behavior
For searches that return fewer than twenty results, change tally language to "Showing 1 to [x] of [x] items."

**Comment by shieldsb** [comment]
QA pass.
