### ISSUE TITLE
[Remediation] Tee Corinne reprocessed, update metadata

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#2849]
### Descriptive summary

This collection was reprocessed after digitization. The existing metadata online is now incorrect and there is metadata in patron scans orders that needs to be corrected before upload. 

https://oregondigital.org/collections/tee-a-corinne-coll263?locale=en

### Expected behavior

Metadata aligns with finding aid data.

**Comment by sarahfish07** [comment]
UO has decided to pull this collection off OD due to the many metadata errors. Aligning finding aid data with OD is proving difficult. Closing ticket.
