### ISSUE TITLE
[Remediation] Joanna Russ papers, 1968-1989 metadata incorrect

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#2850]
### Descriptive summary

The metadata in this collection doesn't match the finding aid. The titles don't match box and folder numbers. 

https://oregondigital.org/concern/generics/df724k40g?locale=en

### Expected behavior

Metadata aligns with finding aid data.

**Comment by sarahfish07** [comment]
Fixed finding aid, folder name, description, title, original identifier.
Metadata now matches finding aid. Titles now match box and folder numbers.
QA'ed. No other errors found. 
Closing this ticket.
