### ISSUE TITLE
[Remediation] Really bad subjects/keywords in Marketing Communications Photo Archive

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#2851]
### Descriptive summary

Clean up non-subject data in keyword in this collection. There is data about format, dates, and other non-compliant or useful data in this field. 

https://oregondigital.org/collections/marketing-photos?locale=en

### Expected behavior

Keywords don't include this useless and messy data. Do not import this data into OD moving forward.

**Comment by jsimic** [comment]
The keywords are supplied by them, not us, and are their standard. We will continue to import their data as they supply it.
