### ISSUE TITLE
Inability to remove first Subject term

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#2860]
### Descriptive summary

The first term under Subject does not have the option to remove it. This only happens if there are multiple headings.
![Screenshot 2023-05-05 at 8 10 28 AM](https://user-images.githubusercontent.com/6344086/236508125-94a2b8de-b06c-4932-a7db-264cec4d2add.png)

### Expected behavior

Users should be able to delete any Subject

**Comment by shieldsb** [comment]
QA pass
