### ISSUE TITLE
Remove Hyrax default hard-coded Description on work show page

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#287]
### Descriptive summary

Hyrax ships with a hard-coded Description field on a work show page, included below the viewer. See http://od2-staging.library.oregonstate.edu/concern/generics/w3763676r?locale=en#?c=0&m=0&s=0&cv=0&xywh=-675%2C-1%2C2549%2C877  
"So much stuff 1" is the Description, and also shows up again with the rest of the metadata fields. While it will be moved in the future, we don't need it appearing twice.

### Expected behavior

Description content only appears once.

### Related work

#99 - potential new view for show page

**Comment by CGillen** [comment]
Fixed by @straleyb in #292
I QA'd locally by creating work w/ description set. Description only appeared in hard-coded area. This is likely preferential until we have final wire frames to work towards.
