### ISSUE TITLE
Remove block to delay external fetching

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2870]
### Descriptive summary

see https://github.com/OregonDigital/OD2/issues/2352, https://github.com/OregonDigital/OD2/issues/2287.
This block was a hacky way of speeding up the migration workflow, but is no longer needed, and preventing assets that do not have children or filesets from having complete solr docs.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
for QA: create a generic item with some controlled fields, eg subject or creator, but without adding any children. The labels should fetch/display on the item show page.

**Comment by wickr** [comment]
QA Pass.
Made a generic work on staging, via the console, with no file added and no children. Labels fetch as expected.

https://staging.oregondigital.org/concern/generics/2z10wq25s?locale=en

Screenshot:
![image](https://github.com/OregonDigital/OD2/assets/2293544/2e51157c-0e5e-49a2-a6f8-bd995156beab)
