### ISSUE TITLE
Change Character Length of Title For Child Works in Viewer

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/OD2#2879]
### Descriptive summary

Change length of displayed title on child works from 7 characters to 50 characters in contents list in viewer to allow user to see full titles of child works when viewing parent work of compound objects.

### Expected behavior

50 characters of title of a child work display in contents list in viewer for compound objects.

### Related work

https://github.com/OregonDigital/OD2/issues/2880

**Comment by lamtu1** [comment]
@KevinJonesMeta would you like the Child Works in Viewer to display the entire title or would you have set limit if a title is too long, then having a `50 characters limit` and hide the rest of the title where you have to hover over it to see the rest of the name?

**Comment by KevinJonesMeta** [comment]
@lamtu1 having a 50 character limit and hiding the rest is great. if we discover with this change that we would like to increase the character limit will that be significant work to change? We don't want them to be really long but we do want users to see enough of the title on child works to tell which is which.

**Comment by KevinJonesMeta** [comment]
QA pass. Expected character count is displayed on child works on staging.
