### ISSUE TITLE
Change Displayed Title on Child Works In Viewer to Match Title Value On Child Work

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/OD2#2880]
### Descriptive summary

Displayed title on child work in contents list in viewer is fileset title based on pid and is meaningless to users. Would like displayed title for child work in contents list in viewer to match Title value from child work.

### Expected behavior

Displayed title for child works in contents lists of viewer matches/resembles Title value on child work.

### Related work

(https://github.com/OregonDigital/OD2/issues/2879)

**Comment by lamtu1** [comment]
@KevinJonesMeta would you able to screenshot and display where is this is occurring? I would love to see the problem area and tackle on it.

**Comment by KevinJonesMeta** [comment]
![image](https://github.com/OregonDigital/OD2/assets/57114731/61d0e62c-5b8d-434c-824d-15a78337dbc7)

This is https://oregondigital.org/concern/images/fx71d542s

**Comment by lamtu1** [comment]
Got it, thank you! So from what I understand from the ticket, we wanted to instead having the `child work` in the `content` display area to display the `pid` number, we wanted to display the name of the actual file or the name of the `child work` in this example you shown me as `Benton County Aerial Mosaic Map`.

**Comment by KevinJonesMeta** [comment]
"Benton County Aerial Map, 1936" is actually the title of the parent. A child work title example is "Benton County Aerial 0711 [711], 1936" found here https://oregondigital.org/concern/images/pv63g3217.

**Comment by KevinJonesMeta** [comment]
QA pass. Child works on staging display work title, not pid content filename.
