### ISSUE TITLE
bulkrax exporter can't use importer as source

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2896]
### Descriptive summary
Created an importer to import 9 images, then tried to export them using the importer as the source. This process failed two attempts, the first time it remained stuck in pending and reported not finding any entries. The second time it reached status failed, and reported an error in the code.

### Expected behavior
User should be able to export based on a prior importer.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
QA create an exporter using a (valid) importer as the source. Export should succeed.

**Comment by wickr** [comment]
QA Pass.
Created Exporter on staging with Importer as source. Did both Exporter without files and 1 with.
On the second one, got 11 files and 11 rows in CSV exported.
