### ISSUE TITLE
IIIF Configuration/Linking for Thumbnails

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#29]
### Descriptive summary

Each work within OD should have a supporting image or `FileSet` associated with it. This image will be stored elsewhere and will need to be linked into Hyrax from where it is stored. One of the ways it will be linked in is on the search results page. If a work shows up in the search results and has an accompanying image, it will need to be displayed as a thumbnail here. It needs to be formatted to a specific size based on derivatives being generated.

This work is highly dependent on what the Systems Team decides to do for creating derivatives. It will also need to be decided what we want to display if the accompanying FileSet is an audio or video file. Do we want to display a specific frame in the video file? Do we want a default images? 

RIIIF Will have to be configured. This will allow the image viewer work, This is a part of IIIF within OD2 and can be found here:

https://github.com/curationexperts/riiif

RIIIF can be a little confusing, but is useful when working with other forms of viewers within hyrax. 

### Expected behavior

Thumbnails show up in places around the system Featured Works, Search Results, etc.

### Related work

This work is heavily dictated by whether or not the systems team has the derivative generation infrastructure into place and derivatives are being generated properly.

#54

**Comment by vantuyls** [comment]
Blocked by #30

**Comment by revgum** [comment]
See also #145

**Comment by raybrarian** [comment]
We are generating static thumbnails and expect the viewer is getting what it needs. Closing.
