### ISSUE TITLE
bulkrax not reporting child works in export

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2902]
### Descriptive summary
Bulkrax is finding the filesets, but in the case of a cpd, not putting any child works in the children column.

### Expected behavior
pids of child works should be listed with separators in the children column of an export for a given cpd work

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
QA Create an export on staging of a coll that contains at least one cpd (eg mss-rb). Row for a cpd parent should have the child pids in the children column (will also have file set ids if there are any attached to the cpd parent)

**Comment by wickr** [comment]
QA Pass.
Created new Exporter of `mss-rb`, got 411 works, found a Parent work that included children work pids in the children column.
https://staging.oregondigital.org/exporters/21?locale=en

<img width="1259" alt="image" src="https://github.com/OregonDigital/OD2/assets/2293544/23ae0a7d-4c4a-42a5-96e0-d87b57a88c32">
