### ISSUE TITLE
WorkType column is not importing data

### ISSUE THREAD

**Issue by sarahfish07** [OregonDigital/OD2#2904]
### Descriptive summary

My Bulkrax testing is done, importing metadata for a test collection, and then exporting out and QA'ing.
Upon QA, I noticed that workType column on spreadsheet is not generating metadata on OD. Facet is missing. Looked under data sources, does not show "no label found"- worktype does not appear anywhere.
One fix I tried that was not successful: Using "work_type" instead of "workType"

### Expected behavior

workType should import label from Getty Vocab.

### Related work

Pids from my test collection:
cz30ps71s
sx61dm37v
s4655g70t
rx913q00j
hh63sv99c
b5644r60j
cz30ps722

**Comment by sarahfish07** [comment]
Upon looking at my spreadsheet, I am missing www for worktype... this might be the issue. Trying this fix.

**Comment by wickr** [comment]
The column name should be `workType` and the Getty entity URIs don't have `www`, this one is valid:
`http://vocab.getty.edu/aat/300134977`

This is one of the few property names that doesn't use a `_`. 

This column in the MAP is a good place to double check URI syntax and should be fully correct:
https://docs.google.com/spreadsheets/d/1ien3djlZxcctuAE99XweyuNdMiN5YsrKoYBJcK3DjLQ/edit#gid=1266119486&range=D:D

If you have a lot of further testing, you should be able to re-use Importers (can click Edit and give a new file to upload), or you can also create them on the staging site.

**Comment by wickr** [comment]
@sarahfish07 Linda and I are still looking at some of your CSVs, and we're double checking things, you may have found a bug.

**Comment by wickr** [comment]
QA Pass.
Did a new CSV with 2 works, seeing workType values included.
https://staging.oregondigital.org/concern/images/4m90dv511?locale=en has 'color photographs'
https://staging.oregondigital.org/concern/images/d504rk38j?locale=en has 'yearbooks'

Also seeing workType value in Parsed Metadata section:
https://staging.oregondigital.org/importers/63/entries/1317?locale=en
