### ISSUE TITLE
Logging in under community option with non-registered user causes app error

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2906]
### Descriptive summary

When selecting Other Affiliation to log in, and then trying to use a non-registered account, an error occurs because the user is not found and the `.deactivated?` checks need to check for nil. Staging and prod show "Something went wrong..." but it's 

```ruby
NoMethodError in Users::SessionsController#create
undefined method `deactivated?' for nil:NilClass
```
`app/controllers/users/sessions_controller.rb:11:in `create'`

### Expected behavior

Trying an email under Other Affiliation that is not yet registered should give the appropriate message.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by shieldsb** [comment]
QA pass
