### ISSUE TITLE
[A11y] Remove italics from the description text

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#2913]
### Operating System

MacOS

### Browser

Safari

### Affected page

Collection Show

### Admin user?

No

### Issue Description

In one of Jeremys accessibility tickets we needed to remove the italics from the header and description of the collection landing page. It is currently still showing italics.

### Suggested Fix

If we can remove the font style italic or change the css to normal:

.collection-header .hyc-desc {
font-weight: lighter;
font-style: italic;

### Can anybody QA or does this need an expert?

Anybody

### QA Steps

Check to see if the italics has been removed.

**Comment by shieldsb** [comment]
QA pass
