### ISSUE TITLE
Update Footer

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#2928]
### Descriptive summary

The OD footer needs to be updated to reflect the UO re-organization.

### Expected behavior

The ownership statement on the right side of the footer should read:
Oregon Digital is collaboratively managed by the [University of Oregon Libraries](https://library.uoregon.edu/) and by [Oregon State University Libraries](https://osulibrary.oregonstate.edu/).

**Comment by shieldsb** [comment]
QA pass
