### ISSUE TITLE
Add Download button for uploaded CSV or zip of bulkrax Importer

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2937]
### Descriptive summary

Bulkrax importers show the file path of the uploaded CSV or zip, but no easy way to then download the file. It would be helpful to have a Download button next to the file path. 
This would be useful for debugging and solving metadata issues, and be more direct than showing a Google Sheet or Excel file since it's exactly what the server is trying to parse. 

![image](https://github.com/OregonDigital/OD2/assets/2293544/a8aa6ffd-907b-4d57-9366-e1eea26e03b8)

### Expected behavior

Download button in Importers for original, uploaded files.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by KevinJonesMeta** [comment]
QA Pass. Download button appears in expanded Parser Fields box on staging.

![image](https://github.com/OregonDigital/OD2/assets/57114731/d5b601ef-dd16-4284-8f00-ce755e9b4e4e)
