### ISSUE TITLE
add local collection as a query in bulkrax exporter

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2938]
### Descriptive summary
OSU makes a lot of use of local collection, and enabling this feature will make it possible to have smaller exports.

### Expected behavior
User will be able to input a local collection as the source for an export. 

### Related work

Making this change will be simplified by waiting for the upgrade to 5.2.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
tested this myself and it's not working. also a label in the form is missing. also failing to display field in the exporter's show page.

**Comment by lsat12357** [comment]
updated QA instructions
this requires the uri from opaquenamespace
eg http://opaquenamespace.org/ns/localCollectionName/yadda

**Comment by wickr** [comment]
QA Pass.
Exported from LCN of Barometer on staging. 51 Works, with 51 FileSets.
Only Barometer works were in CSV as expected.
Exporter view shows local_collection as source.
![image](https://github.com/OregonDigital/OD2/assets/2293544/9e54e214-8712-4d27-ad45-372177ad82f4)
