### ISSUE TITLE
Index View Not Appearing in Viewer on Work Show Page

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/OD2#2942]
### Descriptive summary

Index view does not appear on this [complex object](https://oregondigital.org/concern/documents/ng451h73h).  Complex object was created with single file attached to parent through work form. Child works were added manually using 'Attach Child' button on work show page while parent object was in review queue. Child works appear in viewer contents list, are listed in file manager, and thumbnails appear in viewer and at bottom of show page. All works are now reviewed and public. Ryan Wick reindexed works following review.

### Expected behavior

Index view appears on left side of viewer on complex object with title list of children files viewable as attached to parent work.
### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by CGillen** [comment]
This is caused by the parent object having attached filesets.
Part of the requirements for OD2 was that no complex object would have filesets, only child works. Does that need to change or do we need to support depositing fileset-less parent objects through the form?

**Comment by KevinJonesMeta** [comment]
Supporting fileset-less parent objects through the form would be great. We don't need to change the requirements.

**Comment by CGillen** [comment]
QA: This will not fix previously deposited Generic/Complex Objects that started with a fileset. For Generic/Complex Objects to display the `index` in UV, they must have their fileset removed

**Comment by KevinJonesMeta** [comment]
QA pass. Generic complex object was created through the form without file attached.
