### ISSUE TITLE
bulkrax is changing visibility on restricted works

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2947]
### Descriptive summary

It looks like if bulkrax does not have a value for visibility during an import job, it will default to "open."
I haven't tested this yet, but I'm guessing visibility does not get exported because it is not in the list of mapped fields. So by running an importer from an export, any restricted items will get flipped from "uo" to "open."
A quick solution would be to add visibility to the list of fields, but this would be the exception to the logic that works for all the other fields, which is if there is no value, don't change it.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
For QA on staging
Part 1.
create an import csv for a new asset, without visibility in the header
expected outcome: asset completes, visibility is set to public
Part 2
add the new asset's id to the csv, run importer 3 more times to update:
  First: change visibility by putting "visibility" in the header and either of values "uo" or "osu"
    expected outcome: visibility is changed to new value
  Second: remove visibility from the csv, edit some other field.
    expected outcome: visibility does not change.
  Third: set visibility back to public using the importer web form; edit some other field in csv.
    expected outcome: visibility changes to public.
Part 3
create an export
  expected outcome: visibility column present in the output.

**Comment by KevinJonesMeta** [comment]
@lsat12357 I followed the steps I think  and all of the expected outcomes took place but I don't see a visibility column in the final export. We'll talk about it today at Metadeities to make sure I did it correctly before I mark it QA fail.

**Comment by KevinJonesMeta** [comment]
@lsat12357 QA fail:

Part 1-2: Visibility is stable on import, edit and reimport of metadata through csv and in importer web form.
Par 3: Visibility column is not present in export output.

**Comment by lsat12357** [comment]
Retry QA on export.

**Comment by wickr** [comment]
QA Pass.

Did a new export, visibility column is present in CSV:

![image](https://github.com/OregonDigital/OD2/assets/2293544/5641848f-a88f-496b-aedf-d585d4b057a6)
