### ISSUE TITLE
Add new properties for additional Siuslaw content

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2959]
### Descriptive summary

Public Land Survey System (plss) - http://opaquenamespace.org/ns/plss
Geographics section
New predicate made for https://en.wikipedia.org/wiki/Public_Land_Survey_System data.
Text field, not URIs.
Not faceted.
Format like "Section ##, Township ##S, Range ##W, Willamette Principal Meridian"

Applicant - http://id.loc.gov/vocabulary/relators/app
Creators section
Most appropriate creator/relator for Homestead applications.
Controlled, URIs expected.
Facetable but would need to be turned on at collection level.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by KevinJonesMeta** [comment]
These predicates look good.

**Comment by KevinJonesMeta** [comment]
I see Applicant and PLSS in work form in appropriate sections on staging.
