### ISSUE TITLE
BrowseEverything fails unexpectedly for S3

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#298]
### Descriptive summary

S3 bucket has an image file in it, and the UI shows and allows to pick the image, but when it is tried to be imported by a background job it fails. Testing the S3 URL directly successfully fetched the image from S3.. so I'm not sure why "Error: Expired URL" is happening. Are these urls only single use?

See ticket #297 for the error that was attempting to be emailed (but email failed to send too).

**Comment by revgum** [comment]
https://github.com/samvera/hyrax/blob/58c667cca0a09e0a7d16a854c99190394c0d3b93/app/jobs/import_url_job.rb#L27-L30

**Comment by luisgreg99** [comment]
@revgum I wonder if setting `:s3_uri` instead of `:signed_url` in `:response_type` https://github.com/OregonDigital/OD2/blob/master/config/browse_everything_providers.yml#L22 would make a difference.
