### ISSUE TITLE
add archival_object_id

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2989]
### Descriptive summary
this was added to the OD2 metadata map but not yet implemented.
predicate: http://opaquenamespace.org/ns/archival_object_id
add to Generic
not faceted
searchable
not visible on showpage
visible on form
add to crosswalk_metadata to enable on bulkrax
### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
QA 
open an asset in edit view, find Archival Object ID text box and add a value.
save
field should not appear in show page, but should be present in console view of asset, solr doc, bulkrax export, and metadata download.

**Comment by wickr** [comment]
QA Pass.
Made a new Image and added a value in the new ID field.
Value was not on show page.
Searching for ID of `aid12345` returned only the work, also confirmed solr field value.
Console view looked good. 
Value included in bulkrax export, as well as metadata download.
