### ISSUE TITLE
Remove unneeded text from Edit Form Visiblity box

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#3011]
### Descriptive summary

On the Edit Form, in the Visibility selection box, remove the display of text under the 'Public' option, starting with `Please note, making`

![image](https://github.com/OregonDigital/OD2/assets/2293544/68177be0-9bd9-4bb7-84be-8a1865aa2c59)

This isn't relevant for Oregon Digital, and removing it will free up vertical space in the right sidebar.

### Expected behavior

In the Visibility box, the text under 'Public' option only needs to read 'Make available to all.'

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by shieldsb** [comment]
QA pass
