### ISSUE TITLE
Use single solr field to store URI and label

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#3013]
### Descriptive summary
SA@OSU uses `$` as a delimiter between the URI and Label on controlled vocab values.
This is a parsing service that explains the idea: https://github.com/osulp/Scholars-Archive/blob/main/app/services/scholars_archive/label_parser_service.rb

Essentially index the uri & label as `<value>_tesim: <label>$<uri>` and `<value>_ssim: <label>$<uri>` then anytime you want to retrieve the URI or Label you go through this service (or similar, whatever we build) to read either value

### Expected behavior
URI and Label for CV values are index in one solr field for consistent and quicker retrieval 

### Related work
https://github.com/osulp/Scholars-Archive/blob/main/app/services/scholars_archive/label_parser_service.rb

**Comment by lamtu1** [comment]
@CGillen I was wondering if this ticket is done since we merge that PR for `label$uri` and wondering if the reindex for that PR merge was done to mark this complete
