### ISSUE TITLE
A to Z faceted search error

### ISSUE THREAD

**Issue by sarahfish07** [OregonDigital/OD2#3023]
### Descriptive summary
When faceting within a collection, the A-Z menu options generate ALL labels found in OD.

Screenshot of topics faceted A-Z, before clicking a letter in the menu.
![image](https://github.com/OregonDigital/OD2/assets/114957715/f1b5eef3-0107-4d48-bd89-268610a1d363)
Screenshot of topics faceted A-Z, after clicking the letter "A".
![image](https://github.com/OregonDigital/OD2/assets/114957715/75a0a5a1-0c9c-4238-8680-539a53aafdba)
Collection used in example: https://oregondigital.org/catalog?locale=en&f[non_user_collections_ssim][]=alice-b-sheldon

### Expected behavior
When faceting within a collection, the A-Z menu options generate labels for only that collection.

**Comment by shieldsb** [comment]
QA pass
