### ISSUE TITLE
Add Local Contexts Labels Controlled Field And Display Labels on Work Show Page

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/OD2#3029]
### Descriptive summary

https://localcontexts.org/
Local Contexts labels allow OD institutions to identify works that contain biocultural heritage and/or traditional knowledge of indigenous communities and communicate to those communities opportunities for collaboration regarding those works. These labels contain both an image icon and brief text outlining the meaning of a label.

### Expected behavior
TK labels and BC labels from Local Contexts display in the metadata and designated locations on work show page; fields allow multiple labels and icons to display in relevant locations; labels are indexed and searchable; in ingest form label values are available in a dropdown list similar to creative commons license values; use label page URLs for field values (URIs don't exist as of 2/2/24); webpage with explanation of use of labels and source of labels exists in About/Dig Deeper section of Oregon Digital.

Known Collections That Will Use TK/BC Labels:

(UO) [The Healers Project Collection](https://oregondigital.org/collections/the-healers-project?locale=en)

Known Task List:

- [ ] Create metadata field for TK and BC labels, using https://opaquenamespace.org/ns/localContexts
- [ ] Create facet for Local Contexts field available for collections - defaults to off
- [ ] Create value list for ingest form and add field(s) to ingest form
- [ ] Display TK and BC label icons in upper section with viewer on work show page
- [ ] Display TK and BC label label title in metadata on work show page
- [ ] Explanatory webpage for Local Contexts labels (TK/BC labels) exists in Oregon Digital and linked as appropriate from collection pages
- [x] Add metadata fields to MAP (Metadata Team)

Local Contexts Label titles and URLs sheet: https://docs.google.com/spreadsheets/d/1_jJ22sTw5ys_prLOr0KF_6A-bMtOzqBkNWWuRlgfGUE/edit#gid=0
Style Guide: https://localcontexts.org/wp-content/uploads/2023/08/TK-and-BC-Labels-Usage-and-Style-Guide.pdf
About Page text: https://docs.google.com/document/d/1BniBKhXFGybxpDAJoaGm7-eZe2v9lO07/edit

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by wickr** [comment]
[local_contexts_icons.zip](https://github.com/OregonDigital/OD2/files/14300752/local_contexts_icons.zip)
Here are the icon files. I downloaded them directly from the LC website (thanks Web Developer Tools), renamed them as needed, but otherwise didn't edit them. They are different dimensions and varying transparency but should work for the size(s) we need.

**Comment by lamtu1** [comment]
Hi @KevinJonesMeta I have some questions was hoping if you can clarify for me in regards of this ticket:

1.  When you mention, `Create facet for Local Contexts field available for collections - defaults to off`, does this mean that the `local context` search filter only appear in the collection show page or will it also be filterable on the main search for everything on OD2?

2. For this one, `Explanatory webpage for Local Contexts labels (TK/BC labels) exists in Oregon Digital` Is it something we need to create for the explanatory page or it already exist in OD2 already? And when you said `linked as appropriate from collection pages` meaning this link will appear to user who wants to learn ore about it only appear if the work in the collection has `local context` correct?

**Comment by KevinJonesMeta** [comment]
Hi @lamtu1 Regarding your questions:

1. It means it will be available on collection show pages _and_ main search filters but collection creators will need to add it to the list of visible filters on collection show pages.

2. We are working on the text for this page now but it will need to be added as a subpage of the About page. For the link I like what you are describing if that is feasible. We anticipated adding the subpage as a link on collection show pages in the description field value but that would be handled by collection creators. Your solution sounds more elegant but if it is a lot of work we can remove that from the ticket and collection creators can handle it in the description field manually.

**Comment by lamtu1** [comment]
@KevinJonesMeta As the implementation happen, and once we have the explanatory page setup. I will definitely try to find a way to implement it with that idea in mind. But if anything comes up, I will reach out to you again to discuss and see if we want to go down the other routes as well.

**Comment by lamtu1** [comment]
Hi @KevinJonesMeta I have a discussion with Corey and going through to see if the plan is feasible if we were to implement one of the way I suggested. And we came up that it is not feasible to implement and sticking with the `anticipated adding the subpage as a link on collection show pages in the description field value` would be suitable right now. If anything down the road we see that could change this, we will let you know.

**Comment by KevinJonesMeta** [comment]
Hi @lamtu1. metadata team will fill out `MAP`. This a link to the About page text we would like to use. It includes all of the label icons with the explanatory text from Local Contexts and an introductory statement about the project https://docs.google.com/document/d/1BniBKhXFGybxpDAJoaGm7-eZe2v9lO07/edit.

**Comment by lamtu1** [comment]
Hi @KevinJonesMeta I notice that in the document you linked above, I saw we have a section called `Local Contexts Notices` I was wondering are these icon will be available in the `selection when creating/editing work` and `display on the work show page` or it will not be use in that way at all?

And I was wondering if the display in the work show page like this below would be good or need to change it?
<img width="1255" alt="Screenshot 2024-03-08 at 11 14 01 AM" src="https://github.com/OregonDigital/OD2/assets/111306182/d1f92c46-fbed-4263-99ff-e4d8df2dbfa5">

**Comment by KevinJonesMeta** [comment]
Hi @lamtu1 . The wireframe Azle worked up for display I believe is viewable here https://drive.google.com/file/d/11jUVzeDICc6j8N4fetryfipQ6nUnJaFl/view . The Local Contexts Notices would be used and displayed in the same way as the other Local Contexts labels.

**Comment by jsimic** [comment]
@lamtu1  There is also a style guide matching the wireframe here: [https://drive.google.com/file/d/1QJumj8m8I6OOTnAJ3wnvA6QTMJs9kA-P/view?usp=drive_link](https://drive.google.com/file/d/1QJumj8m8I6OOTnAJ3wnvA6QTMJs9kA-P/view?usp=drive_link)

**Comment by lamtu1** [comment]
Hi @KevinJonesMeta @azle @jsimic, as I work on and following the wireframe for the display of the local contexts, I ran into this situation. Based on the `Google Drive WireFrame`, the image suppose to match the dimension around `150x116` but there are the `notice icons` which are `150x150`. I was wondering if this is okay to display even though they are not the same size or are we forcing them to fit into that size in the wireframe?

<img width="1227" alt="Screenshot 2024-04-15 at 9 12 29 AM" src="https://github.com/OregonDigital/OD2/assets/111306182/8aa812db-b12c-4ace-b6da-89750edcccbd">

Another question I have is, in the ticket, it mention `linked as appropriate from collection pages`. I saw in the wireframe on where we need to linked it in the `show page of a work`, but was wondering do we have a wireframe for the `collection show page if the work in the collection has local contexts, where would we have a place to redirect user to learn more about it?` or `we are not to include it in collection but only in work show page for now`? Thank you!

**Comment by KevinJonesMeta** [comment]
@lamtu1 sorry this took so long to respond. For size, I think it's okay to display the different sizes. We don't want to distort the icons per the use instructions. For linking on Collection pages, we intended for curators/collection creators/metadata editors to provide a link within the text description field.

**Comment by KevinJonesMeta** [comment]
@lamtu1 Metadeities will discuss collection pages today regarding icons on collection page and talk to Azle about wireframes after we confirm we need more than a link in the description.

**Comment by KevinJonesMeta** [comment]
@lamtu1 in Metadeities we just discussed that we have a concern about accessibility with the slider. Can overflow kick down to the next 'line' and just push the metadata down in the event there is overflow?

**Comment by lamtu1** [comment]
Hi @KevinJonesMeta, that something I will have to look into and get back to you on it to see if there is an overflow, that the whole `metadata` section will be push down so it doesn't block it

**Comment by KevinJonesMeta** [comment]
@lamtu1 Regarding LC icons on Collection pages:

1. We will ask Azle for a wireframe and get that into the folder when it is ready
2. We would like icons on Collection pages right under 'Explore More About the Collection'
3. We would like a link to the About LC page to the right of the icons in a similar manner to the workshow pages since the icons will be there.
4. We only anticipate using notice icons and LC labels that apply to the entire collection so overflow is low risk, but being consistent by displaying all icons at once even if in multiple rows is preferred. I can ping you once the wireframe is in the folder.

**Comment by KevinJonesMeta** [comment]
@lamtu1 Azle completed the wireframe for Collection pages and it is in the LC wireframe folder in G-Drive.

**Comment by lamtu1** [comment]
> @lamtu1 Azle completed the wireframe for Collection pages and it is in the LC wireframe folder in G-Drive.
> 
> Also, the text displayed with the the icons only needs to be the label as seen with [wireframe version 4](https://drive.google.com/file/d/1eWB0Ndnhp1Bq3iq2vnwh-_CSMBKI9RwD/view?usp=sharing) so pushing the metadata down won't be a problem for workshow or collection pages. Because the full descriptions are so long we're relying on the link out to the about page for full explanations.

Hi @KevinJonesMeta, thank you for letting me know in regards of the wireframe on the collection page and thank you the team again for updating me on the layout. I will get to work with it once I am back from my conference trip.

**Comment by KevinJonesMeta** [comment]
QA fail. Local Contexts field does not appear in form for works on staging. Collection edit function errors so cannot confirm if Local Contexts field is in form for collections. @lamtu1 I'm writing up an bulkrax ingest sheet to test display that way. Does it show up for you in the form?

**Comment by lamtu1** [comment]
@KevinJonesMeta I am testing out staging, on the `Generic` under >> `subject (the very last area before moving into the scientific area)` is showing up for me. And for the `collection form`, it is showing up for me in the `create`.

**Comment by KevinJonesMeta** [comment]
@lamtu1 Ah, I see it on Generic for new works. We understood generic to mean available for all types of works in the MAP, so it makes sense I don't see it on the form for existing works on staging. Yes, please make it available for all types of works.

I used bulkrax for two images that had LC field values and they ingested successfully but don't display the labels (which makes sense). It's nice that it didn't error on ingest even if the metadata has values that aren't set to display for that work model.

**Comment by lamtu1** [comment]
@KevinJonesMeta I will get onto it and get other types of work to show up with the LC, let me know if there's anything that comes up.

**Comment by KevinJonesMeta** [comment]
QA Pass. multiple LC label icons appear in 1+ rows under UV, labels appear in metadata and URIs are linked in Data Sources. Labels can be added in form to all work types. Metadeities will work with Migration to test bulk ingest of works with LC label metadata.
