### ISSUE TITLE
reuse base verification classes from hyrax migrator

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#3030]
### Descriptive summary
Bring over the verification classes used in migration. Not all of the classes will be needed, and modifications needed (for example, classes assume the existence of a migrator_work, migration profiles)
Likely includes: VerifyWorkJob, VerifyWorkService, VerifyService, BatchVerificationService

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
for QA, see #3032

**Comment by wickr** [comment]
QA Pass. See https://github.com/OregonDigital/OD2/issues/3032#issuecomment-2059418296
