### ISSUE TITLE
File upload buttons are inaccessible

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#304]
### Descriptive summary

Some style change (probably Hyrax base theming, but I'm not sure) hides the file upload button elements off-screen.  This means keyboard users can't see the focus indicator around the button, and assistive tech for sighted people (vimium, for instance) can't enumerate the button.

### Expected behavior

I should see the button on screen, and be able to find it with the keyboard as well as enumerate it with vimium.

**Comment by vantuyls** [comment]
@jechols is this our theming or Hyrax theming?

**Comment by jechols** [comment]
@vantuyls Good point - that is probably the base hyrax theme, but I'm not certain.  I'll adjust the description.

**Comment by raybrarian** [comment]
Hey @jechols - is this still happening?

**Comment by jechols** [comment]
Last I checked it was - that may have been a month or two ago, though, and I'm not sure if anybody has addressed it since then

**Comment by straleyb** [comment]
Closing until we find this issue again if it is still happening.

**Comment by jechols** [comment]
@straleyb I think we need to leave this open and test it, not simply close it hoping it's fixed.

**Comment by jechols** [comment]
Finally did an actual test of this and it does appear it was fixed by somebody at some point.  Woohoo!
