### ISSUE TITLE
IIIF v2 manifest links return error page

### ISSUE THREAD

**Issue by megwalt** [OregonDigital/OD2#3040]
### Descriptive summary

Screenshot of error thrown going to https://oregondigital.org/iiif_manifest_v2/dr26xx94g:
![Screenshot 2024-02-07 at 16 23 34](https://github.com/OregonDigital/OD2/assets/54194852/020ea1fd-15d1-4d82-a5bc-5a5fd506b374)

This means that users are unable to import resources through IIIF from OD.

### Expected behavior
The URL returns the IIIF v2 manifest.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by KevinJonesMeta** [comment]
(Document Work) https://staging.oregondigital.org/iiif_manifest_v2/rf55z773n yields "manifest not supported for rf55z773n"
![image](https://github.com/OregonDigital/OD2/assets/57114731/c83c78a3-2cd1-49b7-918c-f7122aee9624)

 (Image Work) https://staging.oregondigital.org/iiif_manifest_v2/np193919g yields a manifest
![image](https://github.com/OregonDigital/OD2/assets/57114731/819e21db-a9cf-49aa-b016-f23d70d15cac)

(Video Work) https://staging.oregondigital.org/iiif_manifest_v2/xd07gs724 yields "manifest not supported for xd07gs724"
![image](https://github.com/OregonDigital/OD2/assets/57114731/7cfae78d-019f-4478-8d23-81b0cc2548f2)

(Audio Work) https://staging.oregondigital.org/iiif_manifest_v2/0z708w42x yields "manifest not supported for 0z708w42x"
![image](https://github.com/OregonDigital/OD2/assets/57114731/a2ffe2b0-4092-416b-9d03-8339b79c9e36)

@megwalt Should this work for non-images? if not, QA pass.

**Comment by megwalt** [comment]
@KevinJonesMeta Non-images are not supported.

**Comment by KevinJonesMeta** [comment]
Great. I'll move it to done.
