### ISSUE TITLE
Add job to grant edit access to work and filesets to user groups

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#3052]
### Descriptive summary

We didn't get user groups set up and configured before migration, so any migrated works or since-created works won't have permissions set even if they are added to an Admin Set now. User groups make it easy to add edit permissions to works instead of for multiple people, but there are only pre-existing jobs for users. A job would help scale up the bulk assignment to handle tens of thousands of works. 

### Expected behavior

Bulk assignment of edit permissions to a user group on a work and fileset(s).

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by wickr** [comment]
QA steps:
Create new user group / role - either (as admin) at https://staging.oregondigital.org/roles?locale=en or via console
Find a work, get the pid
From console, launch job: `OregonDigital::GrantEditGroupJob.perform_now(pid, group)`
Check work, edit form, Sharing tab

**Comment by lsat12357** [comment]
r = Role.create(name: 'yodeler')
pid = 'gm80hv387'
OregonDigital::GrantEditGroupJob.perform_now(pid, r.name)
item = Image.find(pid)
item.edit_groups
  => ["yodeler", "admin", "collection_curator"]
QA pass
