### ISSUE TITLE
adding errors to works

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#3053]
### Descriptive summary
Using ActiveModel::Errors is not working as expected. After discussing with gillenc, implementing a small error class that uses redis to stash errors for a given work. 

### Expected behavior
Class will support adding errors associated with a keyword to a given work, displaying all errors for a given work, and removing errors with a keyword for a given work.
### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
for QA see #3032

**Comment by wickr** [comment]
QA Pass. See https://github.com/OregonDigital/OD2/issues/3032#issuecomment-2059418296
