### ISSUE TITLE
Content Warnings on Collection and Work Showpages

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/OD2#3078]
### Descriptive summary

Oregon Digital needs content warnings on potentially harmful content to inform users before they view works or collections.

### Expected behavior

- [x] Identify predicates for new metadata fields (Metadeities)

- [x] Two metadata fields are added to MAP in Descriptions Section (MetaDeities)
1. Mask Content (MAP row 50): Multivalued field to identify when to blur thumbnail image in search results and display banner warning over UV on showpage
  a. potential values: 'thumbnail', 'viewer'
2.  Content Alert (MAP row 34): text field to hold content warning text. Default value listed in map. Would like option to customize value as presented in wireframe if default value is not selected.

-Tab with Content Warning fields is available in form for Collections and Works (see wireframes)
-Content Warning metadata can be ingested through bulkrax on Collections and Works
-Default content warning text on warning banner is selectable in absence of content warning field text value

-Thumbnails on identified works are blurred in search results list. 
-Content in universal viewer is not visible to user until they click 'I agree' button on warning banner covering UV on workshow page for relevant works and collections (see wireframes)
-Content Warning text displays in warning banner above 'I Agree' button on workshow pages (see wireframes)

### Related work

[Link to Content Warnings Wireframes](https://drive.google.com/drive/folders/1kSKBHwgK04QG7Yh4txMmagbhlFsmuY1z)

#3094 
#3095 
#3096 
#3097 
#3098 
#3099 

### Accessibility Concerns

Content warning text will need to be recognizable for screen readers

**Comment by KevinJonesMeta** [comment]
Metadeities found/created and added predicates to MAP. Can meet with Features if/when needed to address any questions.

**Comment by KevinJonesMeta** [comment]
@straleyb two questions: In the form, can the warning text radio button start in the default text position? It would reduce the number of conscious decisions users need to make in the form to setup image blur on the showpage.

2nd question: when doing bulk ingest is there a value that will trigger the default text or do we need to populate the value with the entire default text?

**Comment by straleyb** [comment]
I can look into the first one for this.

For the second question: The Bulk ingest would be two values. For the mask_content: "Item Show Page" and "Search Results Page" are the values you would need to use. content_alert can be populated with text, so I would assume using the default text provided to me would be the text you would use on ingest.

**Comment by KevinJonesMeta** [comment]
QA Pass.

@straleyb Great. If it can be done that would be helpful on our end. Do you want me to leave the ticket open?

**Comment by KevinJonesMeta** [comment]
Added mask_content values to MAP example values column.
