### ISSUE TITLE
Homepage Featured Collections thumbnails use non-default thumbnails when available

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#3089]
### Descriptive summary

On the homepage, the Featured Collections thumbnails sometimes include the default thumbnails, where either it's a compound object with no thumbnail specified, or derivatives failed.

Current prod homepage when logged out includes:
![image](https://github.com/OregonDigital/OD2/assets/2293544/4ed56d24-cc33-40eb-b86e-b4ea7117ea22)

We can change the solr query to exclude the default thumbnails. I also think there's some streamlining of the solr queries that can be done.

### Expected behavior

Homepage Featured Collections all have graphical thumbnails where possible.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by shieldsb** [comment]
QA pass
