### ISSUE TITLE
add sidekiq status to importer show page

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#3114]
### Descriptive summary

After the user has launched the verification job for an importer, they can immediately click the show results button and get results that will show no errors found, bc at that point, the jobs probably haven't had a chance to record any errors yet.
wickr suggested that a low-cost solution could be to simply report how many jobs are currently enqueued on Sidekiq.

**Comment by wickr** [comment]
QA Pass

![image](https://github.com/OregonDigital/OD2/assets/2293544/cbcefce4-c532-44de-a961-1ba6ed08beb3)
