### ISSUE TITLE
limit number of importers loaded for index page

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#3119]
### Descriptive summary

Importer page is failing; gillenc notes that the page is timing out while loading Bulkrax::Status and Bulkrax::ImporterRun objects. Potential solution is to cap the number of importers displayed, but we still want to be able to get to older importers.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by wickr** [comment]
QA Pass.
Staging importers loads 50 max. There's currently 66.

![image](https://github.com/OregonDigital/OD2/assets/2293544/ad6d4674-6bd2-420e-b437-02a70b3de855)
