### ISSUE TITLE
Create job that reruns a "fetch label" if a fetch label fails

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#312]
### Descriptive summary

Per discussions on Thursday, when someone creates a work, and adds linked data to that work, there is a possibility that fetching the label for that url could fail. When that job fails we want to automagically fire off a new job to attempt to refetch that label. We want to continue to do this until the fetch works and the label is successfully pulled from the endpoint. 

After the job fails, we would like to send off a notification to that user notifying them that their data hasn't been fully saved (or better verbiage than that) so they know that their work doesn't have all the data that it would otherwise due to an endpoint being down. Once the job fetches properly, we should send off another notification telling them their work has been updated successfully. 

### Expected behavior

When a work has a uri in its form and is saved, it should go out and try to fetch the labels from the data source. If the fetch returns a failed code, it should enqueue a job to continue to fetch that label and notify the user that everything isnt updated in the work quite yet. With nice verbiage of course. When it is successful it should notify the user it was successfully updated. It should continuously run the job until it fetches successfully. 

- [x] User can save a work and have it fetch a label from an endpoint
- [x] Upon failure of fetching the label it should notify the user
- [x] Upon failure of fetching the label it should enqueue a job to refetch the label
- [x] It should continuously fire off jobs until the fetch is successful
- [x] It should notify the user and update the work upon successful fetching

**Comment by petersec** [comment]
Here's a first attempt: 'The metadata vocabulary resource referred to in this field is not currently responding to your request. We will continue to query the resource and will notify you when the field has been successfully updated.'

**Comment by jsimic** [comment]
It would be nice if, when batching, the batch and/or items were identified.

**Comment by wickr** [comment]
@vantuyls @straleyb immediately and continuously firing off retry fetch jobs is not advised. I'm not familiar with Sidekiq's retry options, but Resque had an add-on we used in OD1 that did delay and exponential backoff: https://github.com/lantins/resque-retry

Actually if it can just retry the failed Fetch Job that may be simpler than creating a new Job each time.

For the email text, Chris' is a good start but maybe:
"The label and related information for the resource you requested at [URI] is not currently available. Oregon Digital will retry the source endpoint and will notify you when the data has been retrieved and the field has been successfully updated."

**Comment by CGillen** [comment]
QA:
- [ ] Save a work with a URI that doesn't presently work. Can be done from CLI or this form bypass:
![image](https://user-images.githubusercontent.com/11052958/55500427-28bbe480-55fd-11e9-969d-870ae2069b64.png)
- [ ] Receive an in-app notification of failure and will attempt to retry
- [ ] Recieve an email of failure and will attempt to retry
- [ ] Check Sidekiq for queued job
- Unsure of integration test for getting URI to successfully fetch
- [ ] (optional) Wait 2 days and receive in-app and email notification of retry exhaustion

**Comment by CGillen** [comment]
#488 Caused a regression in this functionality.
Actions like this need to be taken on #prefetch_graph: https://github.com/OregonDigital/OD2/issues/392#issuecomment-480442594

From my memory, just moving #prefetch_graph to after_save caused some weirdness to happen with multiple enqueues/emails. More digging needs to go on to figure out why and how to stop it.
