### ISSUE TITLE
Add Identifier as Search Field and for Advanced Search

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#3123]
### Descriptive summary

Direct searching for exact matches by Identifier (metadata field, not work id) is not currently possible since there's only `identifier_tesim` populated in Solr.
It is included in the 'all fields' search but other unrelated matches, especially for numeric things, will also be included.

As part of linking to the Freshwater Treaties works from another system, a query using the 'Identifier' value (here, a numeric treaty number) needs an exact match.

Example of search query with identifier (480) in all_fields and collection specified:
https://oregondigital.org/catalog.json?commit=Search&f%5Bmember_of_collection_ids_ssim%5D%5B%5D=freshwater-treaties&all_fields=%22480%22&op=AND&search_field=advanced&sort=score+desc&utf8=%E2%9C%93

### Expected behavior

A web/advanced search or JSON catalog query for a value in the 'Identifier' field (probably `identifier_ssim`), alone or with other filters (such as collection) needs to provide an exact match.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by wickr** [comment]
(staging reindex needed before QA of known identifier lookup)
QA:
Try Identifier search field on Advanced Search. This is the tokenized field, so you may get extra results or partial matches.
For known identifier lookup, edit this style of URL to provide a value direct to `identifier_sim` https://staging.oregondigital.org/catalog?f%5Bidentifier_sim%5D%5B%5D=siletz-news-october-2023&locale=en

**Comment by KevinJonesMeta** [comment]
QA Pass.
Basic search for identifier `polk-county-DFP-2LL-123-N-3-1970` provides single exact match in results.

Advanced search in Identifier field for `polk-county-DFP-2LL-123-N-3-1970` returns 29 results with exact match at top of list.

Tested in Chrome and Edge logged in and logged out.
