### ISSUE TITLE
Collection search results (mss-rb) redirect to OD homepage.

### ISSUE THREAD

**Issue by sarahfish07** [OregonDigital/OD2#3127]
### Descriptive summary

When navigating through the search result pages for the collection mss-rb, clicking on page 7 or later redirects to the OD homepage.

Page 1 of results (20 per page): https://oregondigital.org/catalog?locale=en&f[non_user_collections_ssim][]=mss-rb 
Page 7 of results (20 per page): https://oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=mss-rb&locale=en&page=7

Note: I switched from 20 works per page to 100 works per page. The bug now occurs on page 2 of search results.

Page 1 of results (100 per page):https://oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=mss-rb&locale=en&page=1&per_page=100
Page 2 of results (100 per page): https://oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=mss-rb&locale=en&page=2&per_page=100

### Expected behavior
Clicking through search results pages should continue browsing through the works in the collection.

### Related work
I have not found this bug on any other collection.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by KevinJonesMeta** [comment]
Tested several OSU collections and haven't found the bug so far in those collections.

**Comment by shieldsb** [comment]
Tested several collections on prod and could not duplicate the issue.

**Comment by wickr** [comment]
This hasn't actually deployed to production yet, it's an older ticket but the merge was just a few days ago. So QA still needed after the deploy.
I confirmed that at least the 2nd link above is still a problem on production.

**Comment by shieldsb** [comment]
QA pass.
