### ISSUE TITLE
Autocomplete for single endpoint controlled vocabulary fields

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#313]
### Descriptive summary

Autocomplete should work for a form field that only has one endpoint. We need to signify that a certain field is linked data and should accept a uri. Of these fields, the ones that only look to use one endpoint instead of multiple endpoints, should have autocomplete enabled. This means, when a user types into this field, it will search the endpoint for the corresponding label. It should present a dropdown with properly formatted data that when the choice is clicked, it will save the proper uri and label into the proper fields when saved. 

### Expected behavior

A user should go to a form and find a field with a single endpoint. If the user types a valid string that corresponds to a label from that endpoint, it should find that label and display it in a dropdown with other matches. The user should be able to make a choice and have the data be stored in the proper place and when the form is saved, it should save the label and uri properly.

### Child issues

- [x] #302  
- [x] #316 
- [x] #317
- [x] #318 
- [x] #335
- [x] #324

**Comment by vantuyls** [comment]
controlled vocabulary fields are indicated in the MAP - https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0

**Comment by straleyb** [comment]
This now exists on one field and for each field thats single endpoint we can do it like in #311 following the QA work and field overrides found in this PR.

**Comment by CGillen** [comment]
QA:
- [ ] Child issues QA'd
- [ ] Typical user creates work with a controlled field, using typical workflow, sees expected results.

**Comment by straleyb** [comment]
Fixed by #337
