### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/OD2#314]
### Descriptive summary
Rails 5.2 now includes support for ActiveStorage. This integration would be nice for https://github.com/OregonDigital/hyrax-migrator/issues/26

### Expected behavior
With Rails 5.2 installed, we can follow the guide to setup ActiveStorage (one of the new features) at https://guides.rubyonrails.org/active_storage_overview.html

### Related work

- So far, I have a branch https://github.com/OregonDigital/OD2/compare/rails-5.2-support and attempted to upgrade Rails to 5.2.2 with:
```
bundle exec rake app:update
bundle update rails
```
But, I got
```
hyrax was resolved to 2.4.0, which depends on
      hydra-works (< 2.0, >= 0.16) was resolved to 1.0.0, which depends on
        hydra-pcdm (>= 0.9) was resolved to 1.0.0, which depends on
          activesupport (< 5.2)

    rails (~> 5.2.2) was resolved to 5.2.2, which depends on
      activesupport (= 5.2.2)
```
It looks like at this point, one of the dependencies (hydra-pcdm) doesn't support Rails 5.2, and there is a related open ticket at https://github.com/samvera/hydra-pcdm/issues/264
- Rails diff between Rails 5.1.6 (current recommended version in Hyrax) and 5.2.0:
http://railsdiff.org/5.1.6/5.2.0

**Comment by shieldsb** [comment]
Part of Hyrax 3.0
