### ISSUE TITLE
Explore Collections: fix OSU and UO capitalization in page title, match breadcrumbs

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#3142]
### Descriptive summary

On the Explore Collections 'tab' pages for OSU and UO, the page title changes to include 'Osu' and 'Uo'.

Example: https://oregondigital.org/collections/osu?locale=en&view=table
![image](https://github.com/OregonDigital/OD2/assets/2293544/3f937892-0a3b-4e94-ab59-06f0f0df263f)

Further, the breadcrumb title is different, but they should be unified.

The breadcrumbs text pulls from the locale files, which is good, but spaces need to be around the / since it's a separator.

### Expected behavior

Page titles have correct capitalization, and match titles in breadcrumbs.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lamtu1** [comment]
Hi @wickr I wanted to help get this ticket fix real quickly and wanted to double check with you on the clarification on the ticket. When you said you want to add space and lowercase the abbreviation, do you mean to change it to something like this `Explore Collections / Osu`?

**Comment by wickr** [comment]
Hi @lamtu1 no, not lowercase it, any instance of `Osu` or `Uo` is wrong.

To simplify, do this first:

Breadcrumb Titles, add spaces: like `Explore Collections / OSU`

then change Page Title (in very top of screenshot, in `<title>` tag)
Make this use the same values in the locale file as above.

**Comment by wickr** [comment]
Closed by #3158

**Comment by shieldsb** [comment]
QA pass.
