### ISSUE TITLE
Dashboard > Manage oEmbeds page times out on production

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#3153]
### Descriptive summary

The Manage oEmbeds page at 
https://oregondigital.org/oembeds?locale=en
now times out on production. This worked ok with about 5 oEmbeds, now there's over 250. Need to optimize the loading and possibly add pagination.

### Expected behavior

Manage oEmbeds page loads and is usable to view all oEmbeds in system.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
QA: confirmed that the page now loads quickly, links work as expected.
