### ISSUE TITLE
Make Ethnographic Term a Controlled Vocabulary field

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#316]
### Descriptive summary

This work should follow the work done in #311 This lays out the ground work for adding a controlled vocabulary to hyrax utilizing the work done in hyrax. 

### Expected behavior

When a uri is punched into the form field, it should fetch labels and uris and index them properly.

**Comment by CGillen** [comment]
QA:
- [ ] Ethnographic Term accepts a URI from afs_ethn controlled vocab
- [ ]  Work show page shows ethnographic term field as uri and ethnographic term label as label of term

**Comment by vantuyls** [comment]
QA Failed:
Entering search terms does not result in response
Entering URI with .html suffix indicates Load Failed
Entering URI without html suffix loads label

**Comment by straleyb** [comment]
I think as of right now, we want these to only accept uris. @wickr Can you confirm? I dont believe any of these actually have a search endpoint.

**Comment by straleyb** [comment]
This is good to go
