### ISSUE TITLE
oembed actor fixes

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#3161]
### Descriptive summary

some typos requiring fixes discovered while testing oembed
eg F, [2024-10-01T13:21:41.671470 #44] FATAL -- : [1a55bd00fddcb6704130168ed30374b3] NameError (undefined local variable or me
thod `curation_concern' for #<OregonDigital::Actors::CreateWithOembedUrlActor:0x00007f4a34a3d790>):
### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
QA: create a new video, on files tab use the oembed option and supply a URL from media.oregonstate, eg   `https://media.oregonstate.edu/id/0_zx4a0y4p?width=400&height=285&playerId=22119142`
complete the form and save, video should load. 
Note that RyanW has been trying to fix problems with different viewers, the above link is currently working.

**Comment by wickr** [comment]
QA Pass.
New work created, oEmbed URL added. Work saved ok and player loads.
https://staging.oregondigital.org/concern/videos/9g54xh72b?locale=en
