### ISSUE TITLE
Fix broken link on OD2 HARMFUL CONTENT STATEMENT page

### ISSUE THREAD

**Issue by briesenberg07** [OregonDigital/OD2#3163]
### Descriptive summary

Broken 🔗 link for "UO Libraries’ Statement On Racism and Systemic Inequalities" under section **How are librarians and archivists working to address this problem and help users better understand such content?**. 

### Expected behavior

Link should work. Link `href` should be:  
https://library.uoregon.edu/administration/uo-libraries-statement-racism-and-systemic-inequalities

### Related work

n/a

### Accessibility Concerns

not aware of any a11y concerns

**Comment by wickr** [comment]
Discovered the link is also on the Takedown page: https://github.com/OregonDigital/OD2/blob/master/app/views/oregon_digital/about/takedown.html.erb
@lamtu1 can you do another quick PR changing that file?

**Comment by shieldsb** [comment]
QA pass.
