### ISSUE TITLE
Add National Library of Spain (BNE) Authority File to Subject CV

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/OD2#3164]
### Descriptive summary

A Spanish language subject cv will support Spanish language search in Oregon Digital once cv is applied in parallel with English language subject vocabularies.
[Authority File](https://bnelab.bne.es/en/dataset/authorities/) page
[Sparql endpoint](https://datos.gob.es/es/sparql)
Subject+subheading csv file downloaded 10/2/2024
[materiaysubenc-UTF8.zip](https://github.com/user-attachments/files/17235076/materiaysubenc-UTF8.zip)

### Expected behavior

BNE authority URIs are saved through UI form and Bulkrax; label is fetched from BNE authorities and displayed in UI form lookup, on workshow page and faceted with other subject terms. Searches for these terms successfully return matching results. 

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lamtu1** [comment]
Hi @KevinJonesMeta, as I am going through this `cv` for `BNE`, I was wondering if you could provide some example URL that the user would be using when paste in the `subject area` to search for `BNE` so I can get a sense what content we can fetch out of that URL?

Currently as I am going through the `API for BNE` there is couple different layout that they are using and just want to double check to see which one (URL) we would be using the most. Thank you

**Comment by KevinJonesMeta** [comment]
Hi @lamtu1 , I don't know what URI it should be, but this is an example of what I see in the BNE records: http://datos.bne.es/resource/XX533518. The public view URL for this record is https://datos.bne.es/tema/XX533518.html. The first one looks more useable/reusable and consistent with the LCSH URIs than the second one.

**Comment by lamtu1** [comment]
Thank you for the reply @KevinJonesMeta, and when looking at the `jsonld` data, I do see that the `id` is given as `http://datos.bne.es/resource/XX533518.` so we can easily store that to fit in and be consistent to the LCSH URIs. Another question I have is what `label` is best to display when fetching from the URL?

1. Would you like `english label [espanol label] (id)` or would you like `espanol label (id)` or `eng label (id)`?

**Comment by KevinJonesMeta** [comment]
`espanol label (id)` would be better for this purpose.

For the base, is that easier than using the same base for search and storage?

**Comment by lamtu1** [comment]
> For the base, is that easier than using the same base for search and storage?

I just double check on some searching with the link you provide, I do see we have other bases as well base on the picture below: 'we have tema, libro, obra, etc...' so we will use the original URL with those attachment to search and all of their `.jsonld` format do return us the `resource` type that needed to be store which is easy implementation so far but if anything changes down the road, I will update you on it

<img width="1205" alt="Screenshot 2024-10-15 at 12 57 54 PM" src="https://github.com/user-attachments/assets/eec5d16b-cd2e-49c6-bd4e-26e04747afa9">

**Comment by KevinJonesMeta** [comment]
@lamtu1 QA fail: Bulkrax ingest errored on BNE subject in various combinations using `http`, `https`, `tema`, `resource`, with and without `html` in URI. See [BNESubjectTest1](https://staging.oregondigital.org/importers/118),[BNESubjectTest2](https://staging.oregondigital.org/importers/119), [BNESubjectTest3](https://staging.oregondigital.org/importers/120), and [BNESubjectTest4](https://staging.oregondigital.org/importers/121) for example errors.

- [ ] successfully looked up BNE subject in UI form using `tema` base and `resource` base with and without `html` at end of URI.
- [ ] Successfully saved BNE subject in UI form using above bases and end of URI
- [ ] Successfully searched BNE subjects in search box; BNE subjects display in `Subject `facet.

**Comment by lamtu1** [comment]
@KevinJonesMeta Left a comment on ticket #3165 about new QA test

**Comment by KevinJonesMeta** [comment]
@lamtu1 @straleyb QA fail: Bulkrax errored on URIs ending in 'html' (this is acceptable behavior) [BNESubjectTest1](https://staging.oregondigital.org/importers/118),[BNESubjectTest2](https://staging.oregondigital.org/importers/119), [BNESubjectTest3](https://staging.oregondigital.org/importers/120), and [BNESubjectTest4](https://staging.oregondigital.org/importers/121) on attempt 2.

[BNESubjectTest5](https://staging.oregondigital.org/concern/documents/kk91fk56f) processed through bulkrax but no label was found for BNE subject using 'http' and 'https' without 'html'. Worktype is also still displaying Spanish label.

**Comment by KevinJonesMeta** [comment]
thanks @lamtu1 . I updated [BNESubjectTest5](https://staging.oregondigital.org/concern/documents/kk91fk56f) and the workType label displays in English now but the BNE labels aren't fetching and/or displaying. I'll try a new work before moving this back to ready.

**Comment by KevinJonesMeta** [comment]
@lamtu1 QA fail. [BNE SubjectTest6](https://staging.oregondigital.org/importers/123) displayed correct workType label but BNE labels are not found.

**Comment by lamtu1** [comment]
@KevinJonesMeta currently there's something being down/outage for fetching `.jsonld` for BNE as I just check their website as fetching for other formats is giving `404 error`. I'm just gonna put it in ready, and wait a day or so to see if they are doing maintenance or something with their server until that fix is up.

**Comment by KevinJonesMeta** [comment]
@lamtu1 QA fail. I replaced subjects and edited [BNE SubjectTest6](https://staging.oregondigital.org/importers/123). I accidently included `http://datos.bne.es/resource/XX4343841` instead of http://datos.bne.es/tema/XX4343841. No labels were found. Also, the following were kept on the record that were not included in the revised metadata spreadsheet: `http://datos.bne.es/entidad/XX85148` and `https://datos.bne.es/tema/XX786913` which were present on the original importer file.

New importer [BNESubjectTest7](https://staging.oregondigital.org/importers/127) completed but no label found on two BNE subjects using 'tema'. No additional values were added.

**Comment by KevinJonesMeta** [comment]
Retested BNE value through UI form on existing subject and label was fetched and displayed on staging. https://staging.oregondigital.org/concern/documents/fx71cv58n
