### ISSUE TITLE
Add Homosaurus CV to Subject CV

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/OD2#3165]
### Descriptive summary

Homosaurus contains current, updated, and more appropriate terms for LGBTQ-related terminology. This CV will make reparative description of relevant works easier, reflect more nuance in the works described, and be more complete than using currently available terms in other CVs.
[Homosaurus](https://homosaurus.org/)
### Expected behavior
Homosaurus URIs are saved in UI form and Bulkrax; label is fetched in UI form lookup, displays on workshow page and is faceted with other subjects. Searches for these terms return matching results.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by KevinJonesMeta** [comment]
@lamtu1 QA fail: Bulkrax ingest errors on `https` and `http` homosaurus URIs. See [HomosaurusTest3](https://staging.oregondigital.org/importers/116) and [HomosaurusTest5](https://staging.oregondigital.org/importers/117) for error examples.

- [ ] UI form accepts `https` homosaurus URIs
- [ ] UI form accepts `http` homosaurus URIs
- [ ] homosaurus labels display and are indexed/searchable after being saved in UI form

**Comment by lamtu1** [comment]
Hi @KevinJonesMeta I was wondering if you could give `QA` to `Bulkrax` another try? I was given guidance by Linda that the `Bulkrax` got handle ingested by the `workers` on Rancher and I manually updated the image to latest PR pull so was wondering if this will QA fine when you get the chance? Thank you!

**Comment by KevinJonesMeta** [comment]
@lamtu1 QA Pass with an question: Bulkrax accepted homosaurus terms, terms were saved and displayed in review submissions queue.

Question: workType value is now displaying a Spanish language label value on test object. I assume this is not intended. https://staging.oregondigital.org/concern/documents/rn301140q

**Comment by lamtu1** [comment]
Hi @KevinJonesMeta, yeah I need to refine the code for `spanish` language to only affect the `BNE Authority File` that another thing I need to look into that will not affect the others. And yeah this was not intended.

**Comment by KevinJonesMeta** [comment]
@lamtu1 Great. I'll move to Ready for Production then?

**Comment by lamtu1** [comment]
@KevinJonesMeta Yes you can move this ticket to `ready for prod` and I will move the other tickets back to `in-progress`
