### ISSUE TITLE
Make TGN a controlled field

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#317]
### Descriptive summary

Follow the work done in #311 to make tgn work as a controlled field

**Comment by CGillen** [comment]
QA:
- [ ] Historic Place accepts a URI from TGN controlled vocab
- [ ]  Work show page shows historic place field as uri and historic place label as label of term

**Comment by vantuyls** [comment]
QA Failed:
entering URI from TGN does not result in label - URI appears to be unrecognized (e.g. http://vocab.getty.edu/page/tgn/7016143)

entering search term in field does not return results

**Comment by jsimic** [comment]
I believe the resolvable URI's are like http://vocab.getty.edu/tgn/7016143

**Comment by straleyb** [comment]
@jsimic Is correct. http://vocab.getty.edu/tgn/7003714 goes to west-berlin and indexes the label properly. QA should be a pass on this.

**Comment by straleyb** [comment]
<img width="1046" alt="screen shot 2019-02-20 at 12 39 33 pm" src="https://user-images.githubusercontent.com/6424683/53122903-a70c6d80-350c-11e9-969c-31499d247992.png">

**Comment by vantuyls** [comment]
@straleyb does that mean QA passes?

**Comment by straleyb** [comment]
@vantuyls Yes. I suggest it does
