### ISSUE TITLE
Allow edit of oEmbed URL on FileSet

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#3177]
### Descriptive summary

After creating a work with an oEmbed URL added, a FileSet is made with the oEmbed URL. However, there's no way to edit the oEmbed URL, as there's no exposed field on FileSet edit view. Example: https://staging.oregondigital.org/concern/file_sets/np193921h/edit?locale=en#descriptions_display

### Expected behavior

A FileSet with an oEmbed URL value should make that editable.
Can add oEmbed URL on 'Descriptions' pane, under Title.
Should only be available when a value exists, not allow new URLs to be created, since we limit to either oEmbed URL or content media.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by wickr** [comment]
@megwalt FYI, I had forgotten about this (partly because the oembed dashboard on staging wasn't working) but there is an 'Edit oEmbed' page linked from Manage oEmbeds. https://staging.oregondigital.org/oembeds/8049g5150/edit?locale=en

I don't know what that means for this ticket? Could just link from the FileSet edit page to this page. Or if you're far enough along and want to continue, I don't think it'd be a bad thing to have FileSet form have it too.

**Comment by megwalt** [comment]
@wickr I think that I'll still look into getting the field onto the FileSet, but if it ends up being more complicated than expected, I will pivot to a link.

**Comment by KevinJonesMeta** [comment]
QA pass. Value was changed, saved, and retained after leaving the FileSet oembed edit form and returning to page.
