### ISSUE TITLE
Make Local Collection Name a controlled field

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#318]
### Descriptive summary

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Related work

Link to related tickets or prior related work here.

**Comment by CGillen** [comment]
QA:
[ ] Local Collection Name accepts a URI from ON Local Collection Name controlled vocab
[ ] Work show page shows local collection name field as uri and local collection name label as label of term
