### ISSUE TITLE
Explore Collections views, Institution column only showing 'Multiple' values. OSU and UO tabs show no results

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#3191]
### Descriptive summary

On staging, somehow the Explore Collections views, for Institution, all show 'Multiple'. Then if you try the OSU and UO tabs, there are no results.
https://staging.oregondigital.org/collections/all?locale=en

![image](https://github.com/user-attachments/assets/a0b54d91-11a7-4496-aff3-9a51de0ae947)

![image](https://github.com/user-attachments/assets/47ba6a2c-0e6e-4b1e-999d-47f0a7d87048)

The collection landing pages seem to accurately show the correct Institution and logo.

### Expected behavior

Explore Collections All shows the Institution values correctly, and the OSU and UO tabs show the correct collections.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by KevinJonesMeta** [comment]
QA Pass. Each tab displaying relevant list of collections when logged in and logged out.
