### ISSUE TITLE
Rights based restrictions

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#32]
### Descriptive summary

There are some works that should respect the copyrights of a work. For instance. If a work has copyrights that imply that a user should not have the full resolution image, then we shouldnt allow users to download the full resolution image. If there is a work and it is older than a specific day, then we should allow for folks to have access to all the information and full rez image due to it being in public domain. 

EDIT: As noted below, there are some extra concepts that need to be looked at based on licensing even though they are public domain works. Or works that are shared with an institution that need to allow full rez downloads but are restricted via IP. 

We should lay out all possible permutations we can think of, so that we dont implement this feature inappropriately. We we want to layout these permutations in a spreadsheet here is fine. 

Labeled this as a question now as well, to further emphasize an not entirely fleshed out concept. 

### Expected behavior

When you visit a work, and its copyrights suggest folks shouldn't have the full resolution images, then it shouldn't provide a link to download that image. Instead it should provide a link to download the proper image based on the rights.

If a work is public domain or just became a public domain work, we should allow full unaltered access to that work. 

### Related work

Some related work may include metadata logic work surrounding mechanisms that check a works age and makes decisions based on that age.

**Comment by jsimic** [comment]
There are a number of complications for using rights status to decide anything. We have a number of works that are legally in the public domain, acquired through licensing, for instance. There are also works licensed to UO where I'd like to see full res download access, but restricted by IP.

**Comment by jsimic** [comment]
POSM reviewed. Closed.
