### ISSUE TITLE
Make sure redirects are followed when hitting a controlled vocabulary endpoint

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#320]
### Descriptive summary

Currently there is a possibility that an endpoint will redirect. For instance, https://w3id.org/spar/mediatype/text/tab-separated-values redirects to http://www.sparontologies.net/mediatype/text/tab-separated-values. We need to make sure situations like this, where there is an internal server redirect that the application follows the redirect and grabs the data from the new uri endpoint. If a user plugs in either of those endpoints, both should work. 

There was work done previously to manage this, bu substituting for the redirect uri before the fetch. https://github.com/OregonDigital/oregondigital/blob/master/lib/oregon_digital/controlled_vocabularies/format.rb#L11-L17 But we could possibly handle it another way, or this way may be most effecting. So some exploration will have to be done for that. 

### Expected functionality

When you plug in a uri into a controlled field and that uri redirects to a new endpoint, it should still work.

**Comment by wickr** [comment]
I believe this is handled with the newer versions of the gems we're using, where the redirect is being followed, but the result URI is having issues. Definitely worth confirming for the mediatype URIs.
I've sent an email to the SPAR Ontologies address.

**Comment by CGillen** [comment]
Whoops, didn't realize an issue was open for this.
Fixed in this commit: https://github.com/OregonDigital/OD2/pull/311/commits/38bee99c9f2af957171dc9d1fd1ff863e7f73c4c
