### ISSUE TITLE
Showpage Next/Previous item links needed (a la OD1) whether coming from search results or collection.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#328]
### Descriptive summary

As a researcher, on viewing an item on the showpage, I'll want to go to the _next_ or _previous_ of whatever grouping I've arrived there from - whether search result or collection. (Or latest items, even.)

### Expected behavior

On the showpage, a _next_ and _previous_ (alongside a "3 of 7"-type ticker) would take the user to the next in their grouping (@mccallum made up this "grouping" term so feel free to change) - whether it is a grouping from a search, a collection (warning: Items may exist in more than one collection, of course), a latest items, or other. (Can we imagine other showpage uses?)  

### Related work

Might come with Blacklight in ways that aren't showing in Nurax vanilla. From @wickr, perhaps "Blacklight 'natively' and are part of search results I think. Hyrax may be able to use that, or build in different ones via the updated PCDM/member stuff."

#99

**Comment by jsimic** [comment]
@petersec @kmthorn Is this still functionality we want? If yes, need to update wireframes

**Comment by petersec** [comment]
This is probably an expected feature by most users, so is likely a piece of functionality that we would want to retain.

**Comment by kmthorn** [comment]
POSM revisit when seed data is added to staging. This is possibly not MVP.

**Comment by shieldsb** [comment]
See MAC design
