### ISSUE TITLE
Sparontologies controlled vocabulary is throwing errors

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#330]
### Descriptive summary

If you hit a Sparontology term (https://w3id.org/spar/mediatype/image/tiff) it eventually redirects to a 500 page. This is potentially throwing off indexing of our Media Type (Format) term.

@wickr Has sent an email to the Sparontology folk to see if they know about the issue and have plans to fix it.

This ticket is to document the issue, we can explore solutions if we don't think Sparontologies will respond or can QA when they do.

### Expected behavior

https://w3id.org/spar/mediatype/image/tiff -> http://www.sparontologies.net/mediatype/image/tiff.html doesn't give a 500 error

### Related work

#311 implemented Media Type and this was a known issue on merge.

**Comment by straleyb** [comment]
Fixed. Follow the links stated above
