### ISSUE TITLE
Set contact email for single step workflow

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#334]
### Descriptive summary

as a starting point, the email address: [oregondigitalref@uoregon.edu](mailto:oregondigitalref@uoregon.edu) should be set as the notification email for the single step workflow.

**Comment by vantuyls** [comment]
Deposit Message:
<Title> (<ID as link>) was deposited by <Depositor email> and is awaiting approval

Reviewed Message:
<Title>(<ID as link>) has been reviewed by <reviewer ID> and is now live in Oregon Digital.

**Comment by straleyb** [comment]
Confusing. Moving to a new issue
