### ISSUE TITLE
Setup URI validation for Controlled Vocabularies

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#335]
### Descriptive summary

For each controlled vocabulary, there needs to be both a front end and back end validation on uris that are used for controlled vocabulary endpoints. This means, when someone puts the wrong uri into the form, it kicks them back to the edit page or displays a JavaScript popup that tells the user that is an improper uri. 

Also on the back end, when creating a work, even through the console, it should not save the work if an improper uri is used in a controlled vocabulary field. 

This would have to work for multiple endpoints. For each controlled vocabulary, it should validate against all proper uri endpoints for that field. 

### Expected behavior

When an improper endpoint is used on the form, it rejects it and displays an error

When a work is created, it rejects and doesnt save the work if an improper uri is used.

**Comment by CGillen** [comment]
Front end validation should be handled with autocomplete or drop downs on the form.
Autocomplete will happen in QA Authorities, such as: https://github.com/OregonDigital/OD2/blob/master/app/authorities/qa/authorities/format.rb
Somewhere, there should be a validation check, probably around build_query_uri, making sure the query string matches a URI in the vocab.

Back end validation should be handled at the ActiveTriples::Resource level, here: https://github.com/OregonDigital/OD2/blob/master/lib/oregon_digital/controlled_vocabularies/media_type.rb
A validation check should be applied that `id` matches the same validation checks in the front end.

**Comment by CGillen** [comment]
Front end validation should be spun into a separate ticket if we end up needing to do more work on it. Otherwise, each new controlled field should be setup similar to this:
https://github.com/OregonDigital/OD2/pull/336/files#diff-aab7d3469545c3c95d225fa67a77c977R15
