### ISSUE TITLE
URIs show up next to labels

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#34]
### Descriptive summary

After we have the triplestore and all supporting libraries, we should be able to input a uri in the form field of a triple powered property, and have it go to that uri, pull down the labels, and cache the label and uri both in the triplestore as well as index it in solr. when looking at the form during the editing of a work, you should be able to see the label next to the uri. In the show page, maybe we can link out to the uri as well as supply the label for searching in hyrax. 

### Expected behavior

A user who is ingesting a work that has triple powered fields, can input a uri and have it cache the label and uri. When viewing this on the show page, you should be able to see the label and possibly link out to the uri. When editing that work, you should be able to see the uri next to the label, with the uri only being editable. 

### Related work

This work has already been done in Scholars Archive, and will most likely be based on the "Related URI" Field in SA. This already provides the functionality of accepting a uri and a label and displaying it to the user. We would just have to hit the URI and grab the label and cache it which should already work based on the setting up of the triplestore and making active triples work in OD.

**Comment by luisgreg99** [comment]
Related work in ScholarsArchive: 

- https://github.com/osulp/Scholars-Archive/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+triple+powered+
- https://github.com/osulp/Scholars-Archive/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+blazegraph

**Comment by jsimic** [comment]
I vote we use an external-link icon/button on the show pages. Visual clutter...

**Comment by jsimic** [comment]
I'd also like extern-link icons for predicates. But maybe not MVP.

**Comment by wickr** [comment]
I'm not sure how this is substantially different than #45. This could potentially be a ticket underneath that epic and not it's own epic.
Also there are references to a fetched label in some spots and a user-submitted label in others (the reference to the ScholarsArchive 'Related URI' where the form has the label and a URL).

**Comment by straleyb** [comment]
You have a point. This is basically metadata viewing, however, I think metadata viewing was more focused on the show pages and this is a ticket that refers more to the form. I dont think I did a good enough job laying that out in the ticket description and will be fixing that.

**Comment by straleyb** [comment]
Same as #269
