### ISSUE TITLE
Minimize spider traffic

### ISSUE THREAD

**Issue by duncanbarth** [OregonDigital/OD2#343]
~Now that we're in the cloud and there are costs, we need to pay more attention to network transit~
_We still want to make sure traffic is not disruptive to the application. Instead of taking immediate action, Infrastructure should take a look at the available features and hints for spiders and verify they will minimize abuse from well-behaved spiders._

One thing that could cost us a lot is if we aren't providing spiders hints about what content hasn't changed. We don't want them constantly pulling unchanging content. This is especially true when it involves images or other bitstreams.

Some possible controls we have include:

- setting lastmod and changefreq fields in sitemaps
- serving up appropriate last-modified response headers in the replies
- properly handling if-modified-since headers in requests

I'm sure there are others.

It's also quite possible that different spiders (google, bing, baidu, etc.) are using slightly different methods to determine when to redownload content.

**Comment by wickr** [comment]
https://github.com/cdmo/blacklight-sitemaps might be worth looking at.
We've also done work with sitemaps in Scholar's Archive.

**Comment by decimalator** [comment]
Unless we plan to somehow generate sitemaps outside of the application, this is probably not an Infrastructure issue

**Comment by straleyb** [comment]
Need to figure out what pages we want to block with robots.txt. This might be a posm thing. Can generate a site map too.

**Comment by CGillen** [comment]
- Look for example hyrax robots.txt/sitemap.xml
- Explore blacklight-sitemaps
- Mostly consider blocking search results
https://github.com/gwu-libraries/scholarspace-hyrax/issues/224

**Comment by CGillen** [comment]
@decimalator How does our bot traffic look? Do we need to make this more aggressive somehow?

**Comment by decimalator** [comment]
no, this was a theoretical ticket for a theoretical problem from pre-development

**Comment by decimalator** [comment]
- last 24h: 58%
  - bot requests: 1606
  - total requests: 2735
- 24h last week: 89%
  - bot requests: 3092
  - total requests: 3484

<img width="1781" alt="Screenshot 2023-07-21 at 10 19 35 AM" src="https://github.com/OregonDigital/OD2/assets/1882223/3cd7d2c4-c0d4-41ad-961e-3adfb68e5669">
<img width="1781" alt="Screenshot 2023-07-21 at 10 43 00 AM" src="https://github.com/OregonDigital/OD2/assets/1882223/256a90f7-60d0-4c55-83c2-02b9c7e6678c">

Sounds like an improvement to me!
