### ISSUE TITLE
Preserve Solr index (and Fedora index / other stuff?) across container refreshes

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#344]
### Descriptive summary

When I'm having odd behaviors in dev, I tend to do a quick (okay, quick for Rails) `docker-compose down && docker-compose up server`.  This seems to cause my data to have really odd behaviors.  When I ingest something, I can find it with `Image.all`.  After a container refresh, I cannot, but I *can* find it via `Image.find`.  However, the show view won't find it.  I haven't fully investigated exactly what might be going wrong, but my suspicion is that the solr index is getting broken in some way, likely due to us not having a persistent volume somewhere (or maybe multiple somewheres).

I ran `ActiveFedora::Base.reindex_everything`.  This found a bunch of old assets I'd previously lost.  `Image.all` now has these orphaned assets, but **not** the one I lost most recently.  No idea why.

Even stranger: though the `.reindex_everything` operation didn't find the asset, `Image.find("rb68xb84x").update_index` fixes the entire problem.  I have no idea why `.reindex_everything` failed to find it.

### Expected behavior

`docker-compose down && docker-compose up server` should not alter the data in any way.

**Comment by revgum** [comment]
This may be a byproduct of the change to a single SOLR volume away from solr-cloud.. bottom line, this should be working after an initial rebuild and app setup (making admin sets, collections, admin user, etc) https://github.com/OregonDigital/OD2/pull/331

**Comment by jechols** [comment]
After much mucking about, we've solved this one.  PR incoming!
