### ISSUE TITLE
:owner in GenericMetadata improperly configured

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#348]
### Descriptive summary

The Metadata Application Profile indicates that this property should be a multi-valued field, but it is configured as singular. 

Can we validate that the multi-valuedness of the configured metadata is matching the spec in the MAP?

https://github.com/OregonDigital/OD2/blob/master/app/models/concerns/oregon_digital/generic_metadata.rb#L100-L102

**Comment by wickr** [comment]
Yes, confirmed with Metadata Team, `:owner` should be multi-valued.
