### ISSUE TITLE
Results have changed from Google - perhaps nothing can be done?

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#358]
### Descriptive summary

In reviewing our old usability tasks from five years ago (where some image searches began from the  Google search box), some images that once appeared in Google image results do not appear at all in 2019.

A 2014 usability task was "Find a photograph of the 1926 OSU baseball team. Do you have the right to reprint the image?"

Most users searched for "1926 OSU baseball" from Google, flipped to Google's Image results and then located this image in the second or third "page" of results (after passing over a bunch of Ohio State stuff): https://oregondigital.org/catalog/oregondigital:0r967408h or other similar team images. And then completed the task.

For some reason, in 2019, those images do not appear at all from Google. Of the eighteen OD results that do appear for "1926 OSU baseball," most carry an "Untitled" or "1 =tFi I lpi" title in Google images and do not allow any click-through to OD.

I understand OD has very little control over Google search results but thought I'd mention the change in case others had some insight. Dunno.

### Related work

Link to related tickets or prior related work here.

**Comment by wickr** [comment]
It's likely a combination of more content indexed by Google now, and that not being a great search phrase for the image you linked. Especially with the OSU/OAC difference. "1926 oac baseball" gets the image first, though it's also from a SCARC Omeka exhibit. 

Variations on regular/Images search results and different phrases get closer, though you still have to scroll: https://www.google.com/search?client=ubuntu&hs=wKi&biw=1879&bih=982&tbm=isch&sa=1&ei=UmxkXOOoD5i50PEP1PyzwAw&q=1926+%22oac+baseball%22+site%3Aoregondigital.org&oq=1926+%22oac+baseball%22+site%3Aoregondigital.org&gs_l=img.3...15983.18089..18260...0.0..0.56.110.2......0....1..gws-wiz-img.Lp1xQnrhg6A

Also, Google Images seems to be pulling images out of our PDFs (especially the Sports Media Guides). So the OD results with weird text are from the PDFs, and unfortunately does link only to the direct PDF download. (Also the PDF parser seems to be 'whiting out' the words on those pages and isolating only the images, which looks weird). It's the first time I've seen this, so this may be a somewhat recent feature addition.

We could maybe do more to improve how our Images are indexed and presented. Also some Search Results (facet results) are indexed, which can be good and bad.

**Comment by raybrarian** [comment]
POSM review  - closed
