### ISSUE TITLE
Fix behavior of "enter" on ingest form

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#359]
### Descriptive summary

Typically the "enter" key submits a form.  In our form, it appears as if it does nothing **unless** you've uploaded a file... in which case it deletes the upload.

### Expected behavior

"Enter" should attempt to submit the form.  If that's not possible for some reason, we need clear instructions above the form that tell users what to expect.  It should *never* delete files unless you hit "enter" while your focus is on the delete button.

The form may be significantly more accessible if it didn't have so many different pieces.  A more DSpace-style form would be a lot more user-friendly.  Enter basic metadata, submit form, now you have an "upload files" page.  Upload files, submit form, now you have a relationships form (or whatever workflow makes sense).  With a clear indication of what step you're on and what steps are left, this can be significantly easier for keyboard-only users (sighted or not).

**Comment by jechols** [comment]
Note that I refer to pressing "enter" while in a data field, such as a dropdown, radio, or simple text field.  In text areas, "enter" should add a line break.  On any button or link, enter should activate said button or link.

**Comment by raybrarian** [comment]
Have there been any changes to Hyrax that address this issue?

**Comment by jechols** [comment]
I'd have to look.  Maybe slate this to look at for WC12?  I could spin it up "real quick" but that might waste an hour or something.  It's also worth considering Hyrax 3's state since we're migrating there semi-soon I think.

**Comment by straleyb** [comment]
This is still an issue. Accessibility needed.
