### ISSUE TITLE
Consider mirroring authorities to facilitate typeahead

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#36]
### Descriptive summary

We ought to consider mirroring LC, Getty, and other authorities locally to facilitate typeahead and other functionality.

**Comment by luisgreg99** [comment]
I think Josh mentioned something along the lines of implementing an API endpoint in which we can service multiple external authorities like LC and Geonames and manage caching there. @revgum I'm not sure if this is what you were thinking.

**Comment by wickr** [comment]
This presentation covers what Linked Data for Libraries Labs (LD4L-Labs) and Linked Data for Libraries Production (LD4P) projects built: https://swib.org/swib17/slides/khan_linking-the-data.pdf
including server architecture and system size.

https://github.com/LD4P/qa_server
https://github.com/LD4P/linked_data_authorities

**Comment by straleyb** [comment]
Non-issue Mirroring will be an enhancement for later.
