### ISSUE TITLE
View n-triples for single items (MVP)

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#360]
### Descriptive summary

Viewing n-triples for an individual records is part of the quality assurance workflow and a way to verify predicates and URIs not dependent on labels. Currently in OD1 we are able to download a text file with the descriptive metadata in n-triple format by adding .nt to the URL in the web interface. We would at least like to replicate this functionality, or create a way to look at the data within the web interface. It would also be useful for any raw statements to be displayed with the mapped metadata (see related iceboxed issue below.)

### Expected behavior

When requested, a user can view and/or download the descriptive metadata for a single record.

### Related work

OD1 issue #802 refers to the raw statement problem: https://github.com/OregonDigital/oregondigital/issues/802

**Comment by straleyb** [comment]
QA: Adding .nt to the end of the url for a work show page, should trigger a download for the ntriples.

**Comment by KevinJonesMeta** [comment]
QA Pass.
