### ISSUE TITLE
Look into session cookie security concerns

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#362]
### Descriptive summary

Multiple developers are seeing their session persisted even after taking the entire stack down, deleted the local mounted `tmp` directory, and restarting the application.  This suggests the session cookie may contain a user's password rather than just a session id or something similar.

### Expected behavior

The user session should be in a cookie, not their credentials.  Cookie hijacking should, in a worst-case event, allow an attacker to get into OD as a given user (which we can potentially protect against with other mechanisms).  It should never expose their password, because once that's compromised it's much more difficult to prevent the attacker from malicious behavior.

**Comment by jechols** [comment]
Per @revgum : server-side sessions should be pretty easy to implement

**Comment by straleyb** [comment]
Session cookie should not be able to be copied over to new browser and work as being logged in.

**Comment by CGillen** [comment]
Apparently this is normal for session cookies. I can copy cookies for `google.com` and `amazon.com` into postman (and probably other browsers) and I can connect to my account just fine.

Apparently the standard practice for session cookie security is to enable `htmlOnly` and `secure` flags for the cookie. `htmlOnly` will prevent access from JS and `secure` will require cookies be sent over `https`.

Devise will set `htmlOnly` by default, but `secure` must be set through `config.rememberable_options = { secure: true }`

**Comment by CGillen** [comment]
QA:
- [ ] Can still log in
- [ ] Stays logged in on different pages
- [ ] Stays logged in through admin dashboards
- [ ] Remain un-signed in in other browsers / private browse

**Comment by shieldsb** [comment]
QA pass
