### ISSUE TITLE
Create the rest of the controlled vocabularies

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#364]
### Descriptive summary
These are the rest of the controlled vocabulary types, along with their endpoints that they work with. This can tie in nicely to the endpoint validation that is set up currently. 

- [x] OregonDigital::ControlledVocabularies::Creator | lcnames, uonames, creator, dummycreator, ulan,people, wikidata, osuacademicunits
- [x] OregonDigital::ControlledVocabularies::Subject | lcsh, lcnames, tgm, aat, subject, lc_orgs, creator,people, itis, ubio, osubuildings, wikidata, ulan,lcgenreforms, osuacademicunits
- [x] OregonDigital::ControlledVocabularies::StylePeriod | styleperiod, aat, lcsh
- [x] OregonDigital::ControlledVocabularies::WorkType | aat, worktype, lcsh, tgm
- [x] OregonDigital::ControlledVocabularies::RightsStatement | rights, cclicenses, ccpublic
- [x] OregonDigital::ControlledVocabularies::Language | iso_639_1, iso_639_2, marc_lang
- [x] OregonDigital::ControlledVocabularies::Repos | lc_orgs, repository, lcnames, ulan, lcsh
- [x] OregonDigital::ControlledVocabularies::Organization | oregon_universities, institutions, creator
- [x] OregonDigital::ControlledVocabularies::Scientific | sciphylum, sciclass, scigenus, scicommon, ubio, itis,wikidata
- [x] OregonDigital::ControlledVocabularies::Culture | culture, lcsh, lcnames, aat

**Comment by wickr** [comment]
This is mostly accurate but we've been changing some things, the correct list of controlled vocabularies will be in the MAP. It's mostly there but it should be finished later today.

**Comment by straleyb** [comment]
QA is needed before it is closed.

**Comment by straleyb** [comment]
Done
