### ISSUE TITLE
Make corrections and additions to content of password reset email (only for "forgot my password" selection)

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#365]
### Descriptive summary
Current password reset email text for community users (non-university-affiliated) is probably insufficient (see below). Make changes and update email notification text. 

Subject: Reset password instructions
Body: 
Hello <email address>!

Someone has requested a link to change your password. You can do this through the link below.

Change my password

If you didn't request this, please ignore this email.

Your password won't change until you access the link above and create a new one.

### Related work
#275 
Link to related tickets or prior related work here.

**Comment by kmthorn** [comment]
Kate and Chris will write content during their Service Manager Content Writing Retreat

**Comment by kmthorn** [comment]
Subject: Oregon Digital Password Reset Instructions

Body:
Hello [ add person’s name ] 

We received a request to reset the password for your Oregon Digital account: [ add email address associated with the user’s account ]. We are here to help! 

This link will help you reset your password. [ This text should be hyperlinked to the page where a password is reset.]
If you didn't request this, please ignore this email. Your password won't change until you access the link above and create a new one.

Thank you,
The Oregon Digital Team

**Comment by shieldsb** [comment]
QA fail.  I received the message in the original ticket description section, not the updated text in the comment above from 2/25/2021.

**Comment by straleyb** [comment]
Being worked on currently by @straleyb

**Comment by shieldsb** [comment]
Above is an email the user should receive when requesting to change their password.  However, the change your password screen now allows you to change your password on the site without an email link.  Also, the change your password page (which also allows you to delete an account) does not match the wireframe: https://drive.google.com/file/d/1rq4vCkiKX1OEqU4Nk6wE-aHIC5bgyLn7/view

**Comment by shieldsb** [comment]
Also @azle and @jsimic , the change password option appears to also allow me to change my user account info (email, password, delete collection).  When I click on my email which now displays at the top of the dropdown list, a message appears on the page that says "user does not exist" : 
![image](https://user-images.githubusercontent.com/53542788/191874156-a16c9bc2-0d41-4101-baa9-9b84d55e771e.png)

**Comment by jsimic** [comment]
@shieldsb The change password option, as on the wireframe, should not allow a user to change their email. It should allow password changes and deleting the account. Perhaps the confusion is the blank email field. Can that be autofilled if one is already logged into the site?

**Comment by shieldsb** [comment]
This is still the case: the change your password screen now allows you to change your password on the site without an email link.

**Comment by shieldsb** [comment]
QA fail.  Received an email, but the text didn't match Kate's text above from 2/25/2021 
![image](https://user-images.githubusercontent.com/53542788/193163067-5ba8ca77-f675-49bb-852a-7d8417456283.png)

**Comment by shieldsb** [comment]
QA fail. There are just a couple of places the email doesn't match.  The subject line should start be Oregon Digital Password Reset Instructions
The greeting is supposed to be: Hello [add the name of the user] - assuming this should pull from the user name 

We received a request to reset the password for your Oregon Digital account: **[ add email address associated with the user’s account ]**.  The bolded part is missing and instead there is the colon then a space and then the period. 

![image](https://user-images.githubusercontent.com/53542788/195222456-ee6efd4a-893a-43eb-857d-0244d047552d.png)

**Comment by shieldsb** [comment]
QA fail!  Just two minor things.  The subject line should be: Oregon Digital Password Reset Instructions 

There should be a comma after Hello   - this wasn't in the original request because it just lists the user name which I guess isn't available.

**Comment by shieldsb** [comment]
QA pass.
