### ISSUE TITLE
Remove properties from system

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#366]
### Descriptive summary

After further analysis by the Metadata Team, these properties are no longer needed and can be removed entirely. No records were found in OD1 that had any of these values.

- [ ] boxName
- [ ] hostItem
- [ ] canzonierePoems 
- [ ] higherClassification 
- [ ] scribe

### Expected behavior

Remove all occurrences from property definitions, forms, indexing, etc.

**Comment by CGillen** [comment]
QA:
- [ ] Metadata fields are gone

**Comment by vantuyls** [comment]
QA pass, fields are gone
