### ISSUE TITLE
resource_type and date_modified mismatch in MAP

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#373]
### Descriptive summary

`Type` (resource_type, line 157) should be multivalued in the MAP to match the multiplicity of this value in Hyrax, OD2 override this and make resource_type single valued?

~`Modified` (date_modified, line 183) should be singular value in the MAP to match the multiplicity of this value in Hyrax.~

**Comment by wickr** [comment]
Related to #462

**Comment by vantuyls** [comment]
qa pass - type is single value
