### ISSUE TITLE
Linked Data enabled fields using QA UI

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#377]
### Descriptive summary

Some fields, (ie. `format`) are configured to use the QA autocomplete UI but are currently expecting that a legitimate URL be pasted instead of search text (as is the typical QA use-case). The UI doesn't make any attempt to tell you that its expecting a URL for our application and defaults to "Search for a ****" instead. 

It seems worthwhile to make the help text for the QA UI state that it is expecting a full URL to a term in the cases that we have that are expecting that. 

See the screenshot for an example that would be more clear to state "Enter a URL for this controlled vocabulary" or something similar. 

![screen shot 2019-02-20 at 3 55 33 pm](https://user-images.githubusercontent.com/32885/53133456-193e7b80-3528-11e9-8c9e-90ff221989f5.png)

**Comment by CGillen** [comment]
I'm fine with "Enter a URL for this controlled vocabulary" for all of these autocomplete fields that expect a URI, and "Search for a _______" for any that actually searches by label.

@mccallum or @revgum Any thoughts on different terminology or I can just go ahead an implement above?

**Comment by straleyb** [comment]
This might be a bit more involved than previously expected. This text is managed in select2, and we would have to override hyrax's instantiation of select2 i order to change the text. We might be able to override the en files from select2 directly, but that might be a bust too. The only other idea of how we could fix this is to write very generic JS that says, after a click, check to see if a select2-no-results div is available, and change the text on the fly.

**Comment by CGillen** [comment]
It's not right here?
https://github.com/OregonDigital/OD2/blob/master/app/views/records/edit_fields/_format.html.erb#L3

**Comment by straleyb** [comment]
Oh we could do it there too, but this text in the drop down is not accurate either 
"Please enter 2 or more characters" implying searching works as a label search.

**Comment by CGillen** [comment]
I don't think it's too crazy to to leave "Please enter 2 or more characters" if the placeholder says "Enter a URI for ______ controlled vocabulary"
It still kind of acts like a search, if they get the URI right.

Regardless, you could override this file
https://github.com/samvera/hyrax/blob/master/app/assets/javascripts/hyrax/autocomplete/linked_data.es6
to apply the fix suggested in the comments of this issue
https://github.com/select2/select2/issues/2561

It might be a big tricky figuring out when to apply new text and when to choose the default.

**Comment by straleyb** [comment]
Yeah thats where this piece of the comment came from `We might be able to override the en files from select2 directly, but that might be a bust too.` Because we have tried to override stuff in the past and it gets messy fast. Possible, but didnt want to get my hopes up.

**Comment by straleyb** [comment]
Err I mean this file
https://github.com/select2/select2/blob/14a059d7eedfd97fc530ac63852c0ee22324df48/src/js/select2/i18n/en.js

**Comment by straleyb** [comment]
But yeah, we could override the LinkedData object, but thats kinda scary too lol.

**Comment by CGillen** [comment]
Either works and both kind of suck. I'd be fine with leaving the "2 or more" wording, but I guess it's a product owner (service manager?) call.

**Comment by straleyb** [comment]
@vantuyls ? Any input? I can easily change the "search for a ****" text but the "please enter 2 or more characters" is a little more difficult.

**Comment by vantuyls** [comment]
if the expected user behavior is to enter an entire URI, leaving text that says "enter 2 or more..." doesn't make any sense. I'd prefer @CGillen's original suggestion:
"Enter a URL for this controlled vocabulary"

**Comment by revgum** [comment]
Expanding on what @CGillen was suggesting with the fix at https://github.com/select2/select2/issues/2561 .. copying and overriding what Hyrax provides and adding the new `language` configuration should be added to this PR. 

Maybe just override this
https://github.com/samvera/hyrax/blob/master/app/assets/javascripts/hyrax/autocomplete/linked_data.es6#L31 
and add something along the lines of:

```
  language: {
  	inputTooShort: function() {
  		return 'Enter a URL';
  	}
  },
```

**Comment by vantuyls** [comment]
if this is ready for QA, please add QA test suggestions. @revgum @straleyb

**Comment by straleyb** [comment]
CV search box should suggest using a uri and the help text should suggest using a uri

**Comment by vantuyls** [comment]
QA Pass - CV search boxes ask for  URL.
