### ISSUE TITLE
Make creator a CV

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#378]
### Descriptive summary

Creator Controlled Vocab with multiple endpoint support

**Comment by CGillen** [comment]
QA
- Can insert valid URIs (see MAP) for creator controlled fields:
  - [ ] Arranger
  - [ ] Artist
  - [ ] Author
  - [ ] Cartographer
  - [ ] Collector
  - [ ] Composer
  - [ ] Creator
  - [ ] Contributor
  - [ ] Dedicatee
  - [ ] Donor
  - [ ] Editor
  - [ ] Illustrator
  - [ ] Interviewee
  - [ ] Interviewer
  - [ ] Lyricist
  - [ ] Owner
  - [ ] Patron
  - [ ] Photographer
  - [ ] Print Maker
  - [ ] Recipient
  - [ ] Scribe
  - [ ] Transcriber
  - [ ] Translator

**Comment by vantuyls** [comment]
creator CV functions as expected -  QA Pass

**Comment by vantuyls** [comment]
QA passes on all vocabs for all identified Creator fields.
