### ISSUE TITLE
Make subject CV

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#379]
### Descriptive summary

Subject CV with multiple endpoints

**Comment by CGillen** [comment]
QA
- [ ] Subject and Military Branch will accept valid URIs (check MAP)

**Comment by vantuyls** [comment]
QA using URI from LC does not return labels - http://id.loc.gov/authorities/subjects/sh2001006600

**Comment by CGillen** [comment]
Fixes added. Wait until deployed hash is changed from 45f7c5a

**Comment by vantuyls** [comment]
- [ ] Military Branch
- [ ] Subject

**Comment by vantuyls** [comment]
QA Pass for all relevant vocabs
