### ISSUE TITLE
Make Scientific CV

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#382]
### Descriptive summary

Scientific with multiple endpoints

**Comment by straleyb** [comment]
Fixed by #418

**Comment by vantuyls** [comment]
- [ ] Taxon Class
- [ ] Family
- [ ] Genus
- [ ] Order
- [ ] Species
- [ ] Phylum / Division
- [ ] Common Name

**Comment by vantuyls** [comment]
QA passed for all above fields for all vocabs
