### ISSUE TITLE
PREMIS Data indexed and accessible in exports and show pages

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#39]
### Descriptive summary

We need to begin logging PREMIS Data. PREMIS data is the "who" "what" "when" of changes being made to works in the system. If a user goes in and edits a work, we would like to know things like, what fields were changed, who changed them, when was the change made, what was it changed from? This are all important questions and can help with tracking within the system. We need to figure out which pieces of data are already being logged, what pieces of metadata need to be added to the work metadata to help with tracking, indexing this data, and being able to display this data to those who need it. We would also have to work on working this data into exports of data at some point down the road. 

### Expected behavior

When a work is created, edited, and possibly reviewed, it logs premis data that can be viewed by specific users on the show page of a work. 

### Related Work

The related work associated with this ticket includes the ability to create metadata for a default work, review being possible. We would have some logic behind the scenes that accumulates all the necessary PREMIS data and ties it to a work and indexes it and exposes it on the show page.

**Comment by vantuyls** [comment]
Considerations:
- what PREMIS events are being captured by Fedora out of the box in Hyrax?
- are there PREMIS events that are not being captured by Fedora that we want to capture?
- do we want to consider adding the ability to annotate an event (e.g. to explain why a change happened)?
- what happens to PREMIS tracking when we are no longer using Fedora?

**Comment by sseymore** [comment]
The metadata team does not any PREMIS metadata captured on work show pages. There are some PREMIS data in fileset metadata and we are fine with keeping it there.

**Comment by CGillen** [comment]
@sseymore This is a file that has been uploaded, renamed, replaced, and reverted. There's a double entry for rename made at the exact same time as the replace. I'm unsure why, but if I solve that mystery, is that enough logging of fileset changes?
https://staging.oregondigital.org/concern/file_sets/08612n644?locale=en

**Comment by sseymore** [comment]
@CGillen This looks great to me, but I want to check with the team.The Metadata team didn't get to review this due to C4L this week, but I will get back to you with a definitive answer next week.

**Comment by sseymore** [comment]
@CGillen looks good to us after discussion-- thanks!
