### ISSUE TITLE
Location controlled vocabulary failed

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#392]
### Descriptive summary

Testing QA on Location and it failed with 

```
I, [2019-02-22T19:39:34.299740 #22]  INFO -- : [80c454b0-0e63-45e2-adbb-20811fc57690] Completed 500 Internal Server Error in 545ms (ActiveRecord: 11.7ms)
F, [2019-02-22T19:39:34.301259 #22] FATAL -- : [80c454b0-0e63-45e2-adbb-20811fc57690]
F, [2019-02-22T19:39:34.301358 #22] FATAL -- : [80c454b0-0e63-45e2-adbb-20811fc57690] ArgumentError (wrong number of arguments (given 1, expected 0)):
F, [2019-02-22T19:39:34.301417 #22] FATAL -- : [80c454b0-0e63-45e2-adbb-20811fc57690]
F, [2019-02-22T19:39:34.301467 #22] FATAL -- : [80c454b0-0e63-45e2-adbb-20811fc57690] lib/hyrax/controlled_vocabularies/location.rb:36:in `fetch'
[80c454b0-0e63-45e2-adbb-20811fc57690] app/indexers/generic_indexer.rb:9:in `generate_solr_document'
[80c454b0-0e63-45e2-adbb-20811fc57690] app/indexers/image_indexer.rb:6:in `generate_solr_document'
```

**Comment by straleyb** [comment]
https://github.com/OregonDigital/OD2/issues/323

**Comment by CGillen** [comment]
QA
- [ ] Location search works
- [ ] Choosing a location does not cause a work to fail to save
- [ ] Location label is acceptable <- if failure, should be a new ticket

**Comment by vantuyls** [comment]
Save failed when location added. Thoughts? @CGillen

**Comment by CGillen** [comment]
Started because the fetch retry queue attempts to pre-fetch graphs here: https://github.com/OregonDigital/OD2/pull/438/files#diff-d4647144231ccfbf7837024f402add14R28

Hyrax/FCRepo expects the graphs to be empty before they object is saved to Fedora. Specifically, FCRepo doesn't want to save something if it contains subjects that don't match whatever's being saved.

My first suggestion would be to move `#prefetch_graphs` to `#enqueue_fetch_failures` and call it on `after_save`. It could probably save some cycles by not calling `indexer.add_assertions(nil)` anymore too.

**Comment by vantuyls** [comment]
QA Fail:
1) edit existing item
2) add new location in Location field
3) Save item errors with ACK! error

**Comment by vantuyls** [comment]
Still failing...

i’m entering an existing work, adding a location, and saving
on this work: http://staging.oregondigital.org/concern/images/9019s2443?locale=en
thoughts?
also: by failed i mean: i get the Ack! message
BUT when i go back to re-edit the item the URI for the new location appears in the metadata

**Comment by revgum** [comment]
Looks like we aren't loading a needed class;

```
F, [2019-04-12T17:48:17.536032 #24] FATAL -- : [f13f3296-cf3e-4c17-a665-0357f0356ba9] NameError (uninitialized constant OregonDigital::FeatureClassUriToLabel):
F, [2019-04-12T17:48:17.536060 #24] FATAL -- : [f13f3296-cf3e-4c17-a665-0357f0356ba9]
F, [2019-04-12T17:48:17.536088 #24] FATAL -- : [f13f3296-cf3e-4c17-a665-0357f0356ba9] lib/hyrax/controlled_vocabularies/location.rb:30:in `rdf_label'
[f13f3296-cf3e-4c17-a665-0357f0356ba9] lib/hyrax/controlled_vocabularies/location.rb:69:in `label_or_blank'
[f13f3296-cf3e-4c17-a665-0357f0356ba9] lib/hyrax/controlled_vocabularies/location.rb:27:in `rdf_label'
[f13f3296-cf3e-4c17-a665-0357f0356ba9] app/indexers/generic_indexer.rb:9:in `generate_solr_document'
[f13f3296-cf3e-4c17-a665-0357f0356ba9] app/indexers/image_indexer.rb:6:in `generate_solr_document'
```

**Comment by vantuyls** [comment]
QA Pass - location can be searched, added, and saved
