### ISSUE TITLE
Metadata not indexing as facetable in Solr

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#397]
### Descriptive summary

Non-core metadata is only being indexed as `<property>_tesim` which relates to `Solrizer.solr_name(<property>, :stored_searchable)`. `Solrizer.solr_name(<property>, :facetable)` outputs `<property>_sim` and these values aren't found in the schema or documents once a work is saved.

This seems to be causing facets to not appear for most metadata fields on the search page, though may not be the only factor

### Expected behavior

Metadata that specifies to be indexed as `:stored_searchable` and `:facetable` should be indexed into Solr as `<property>_tesim` and `<property>_sim`

### Related work
Blocks work on #271

**Comment by CGillen** [comment]
QA:
- [ ] Create new work with metadata that should and should not be faceted
- [ ] Check Solr document that fields align with reality
  - [ ] Facted fields are indexed as `*_sim`
  - [ ] Searchable fields are indexed as `*_tesim`. Faceted and searchable may be indexed as both
  - [ ] Non-faceted fields are not indexed as `*_sim`

**Comment by vantuyls** [comment]
QA Fail - see notes on #272

**Comment by wickr** [comment]
QA Fail - see faceting notes on #272

**Comment by raybrarian** [comment]
Metadata will QA.

**Comment by straleyb** [comment]
Related to #272

**Comment by sseymore** [comment]
Note: waiting for seed data ingest to QA

**Comment by sseymore** [comment]
Please see most recent QA on #272

**Comment by CGillen** [comment]
We're done here. This is basically a duplicate of #272 at this point and we're just going to keep refining metadata.
