### ISSUE TITLE
Create PWA manifest.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#398]
### Descriptive summary

As a user on smartphone or other non-desktop device, I want an experience that appears and performs well with respect to my device and any of its limitations.

### Expected behavior

Use a PWA manifest generator to create a good rounded experience for mobile users that save OD to their homescreen:
For example: https://tomitm.github.io/appmanifest/
More on manifests: https://developers.google.com/web/fundamentals/web-app-manifest/

### Related work

Link to related tickets or prior related work here.

**Comment by raybrarian** [comment]
POSM review.
