### ISSUE TITLE
Create favicon.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#403]
### Descriptive summary

As a regular user of Oregon Digital, I'd like to quickly find it among browser tabs, bookmarks, and browser homepage quick menus.

### Expected behavior

For easy identification in browser tabs and across browser homepage quick menus, Oregon Digital should carry a favicon of all the standard dimensions.

**Comment by mellinma** [comment]
Icon https://drive.google.com/open?id=1xhfw4bGc2s5S7gZBnrJRuYa7HntOtrI8

**Comment by CGillen** [comment]
Implement above linked favicon

**Comment by azle** [comment]
@CGillen  Here is the graphic for the favicon, let me know if the graphic looks good once uploaded.

[favicon_io.zip](https://github.com/OregonDigital/OD2/files/12243126/favicon_io.zip)

**Comment by lamtu1** [comment]
@CGillen Can I tackle this ticket once you approve the design?

**Comment by shieldsb** [comment]
QA pass.
