### ISSUE TITLE
Deployment improvements

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#413]
Implement CI/CD with automated deploys for staging and automated deploys with approval for production

**Comment by decimalator** [comment]
This is blocked and waiting on registration of a domain name for service discovery and ingress (ordig.io)

**Comment by decimalator** [comment]
Blocked by #415

**Comment by vantuyls** [comment]
@decimalator can you give a status update on this?

**Comment by vantuyls** [comment]
ping @decimalator

**Comment by decimalator** [comment]
Staging portion is done. We can save production deploys for when we have a production environment
