### ISSUE TITLE
Metadata Validations

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#42]
### Descriptive summary

This may not actually need an epic ticket, but this ticket describes the need to validate all metadata. We need to make sure that if we are expecting a string, that the form only accepts strings. If it is a controlled vocabulary field, that it accepts uris from specific endpoints. If we are expecting dates in a specific format, that we are getting those dates in those formats. 

We need to go through and make sure every piece of metadata is validated

### Expected behavior

The front end rejects a value if it isnt correct. The backend rejects a value if it isnt correct.

**Comment by jsimic** [comment]
In OD1 having a URL in a text field is problematic (such as has_findingAid URLs being treated at URIs), even when there is other text in the field, such as a paragraph with a link to an artist's personal site. This information, while not critical, is useful for the user.

**Comment by vantuyls** [comment]
@jsimic can you reflect the expected format for dates in the MAP? are there any  other format expectations beyond URI, text, and date?

**Comment by raybrarian** [comment]
Related to #40

**Comment by jsimic** [comment]
POSM reviewed. Closed.
