### ISSUE TITLE
Need to be able to highlight works in a collection for the collection landing page

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#425]
### Descriptive summary

Collection landing page should have a  space where collection manager can highlight works in the collection (and unhighlight them) to be featured on the landing page. 

Note: Hyrax's default banner and logo image functionality shouldn't be used (disable branding) because it diverges from the wireframes.

Please use MAC wireframes for this: https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938474

**Comment by CGillen** [comment]
Take note of `@member_docs` discussion in #1292.
Collections already have a `thumbnail_id` field for selecting the thumbnail image for a collection. If we make that multivalue and have `@member_docs` set itself to those values first, we can use `@member_docs` as an easy entrypoint to display "featured works followed by any number of 'random' works" in a collection.

**Comment by CGillen** [comment]
QA:
- [ ] Edit a collection with works (with thumbnails)
- [ ] Sharing tab
- [ ] See 4 representative image select boxes
- [ ] Open RI box & see type-ahead for file names
- [ ] Select 1-4 images & save
- [ ] Collection show page has selected images as thumbnails
- [ ] Thumbnails are in order to the select boxes (left-to-right)

**Comment by jsimic** [comment]
@CGillen  Thumbnail selection is under the Branding tab. I'm assuming that was just a mistake in the QA list, as it makes more sense for it to be under Branding.

The mechanism is working,  but there are some aesthetic issues:

Thumbnails appear stacked vertically, and should be horizontal (I'm on a 13" laptop display 2560×1600, there is plenty of room for the thumbs) and there are grey bars above and below. No bars should separate the images according to the wireframe.
Fileset name appears under thumbnail (i.e. "df661w63k_content.pdf"). There should be no text according to wireframe.

I edited the landing page for [Texts and Data](https://staging.oregondigital.org/collections/texts-data)

**Comment by CGillen** [comment]
Fixed by #2220
