### ISSUE TITLE
Need to allow collections to have additional supporting pages

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#427]
### Descriptive summary

Collection pages in OD2 need to allow for linking to additional supporting pages, as seen on OD1:
https://oregondigital.org/sets/herbarium/page/acknowledgements

need to have an interface to:
1) create these pages as subpages in a collection
2) allow a text editor for subpages (maybe similar to the content blocks in the admin dashboard)
3) place in the dashboard or on the collection homepage that indicates where/how to create these subpages

**Comment by raybrarian** [comment]
Do we still need this functionality? POSM will review and determine.

**Comment by mellinma** [comment]
We still want subpages, but they don't necessarily need to be in the system.  UO has a couple that link to a libguide. Use this for now.  Not MVP right now, but much desired feature.

**Comment by wickr** [comment]
Here is the current list of collections that have actual supporting pages beyond the collection homepage:

- Braceros (braceros)
  - Related Information
  - Technical Information
- Gifford (gifford)
  - About
  - Bio
- Herbarium (herbarium)
  - About
  - Additional Links
- Middle East Waters (middle-east-water)
  - Bio: Kolars
  - Bio: Laylin
  - Bio: Naff
- OSU Yearbooks (osu-yearbooks)
  - Covers
  - Hayseed/Orange/Beaver Article
- Percent For Art - percent-for-art
  - About

**Comment by wickr** [comment]
Current plan is utilize LibGuides or other external site, and eventually Spotlight, if more supporting pages are needed for a collection.
