### ISSUE TITLE
Configure Collection level metadata fields

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#437]
Metadata fields for use with collection records:

- [x] Title
- [x] Description 
- [x] Thumbnail choice
- [x] Creator
- [x] Contributor
- [x] License
- [x] Publisher
- [x] Date Created
- [x] Subject
- [x] Language
- [x] Identifier
- [x] Related URL
- [x] Resource Type (Type)
- [x] Institution
- [x] Date
- [x] Repository

**Comment by raybrarian** [comment]
Need to edit a collection to see thumbnail choice. QA: check for all listed fields above and no others

**Comment by vantuyls** [comment]
@jsimic if by Description we mean Abstract, then QA pass. Thoughts?

**Comment by jsimic** [comment]
@vantuyls Yes

**Comment by vantuyls** [comment]
@jsimic works for me. is there something that needs to happen for this particular issue to close or are we good to go with Abstract?

**Comment by straleyb** [comment]
@raybrarian This should be good to go.

**Comment by sseymore** [comment]
@raybrarian @straleyb We were discussing this at the check in yesterday. @wickr and I thinking more about Identifier and Related URL. We will discuss on Monday and update.

**Comment by wickr** [comment]
Metadata Team met today and discussed these. The current batch looks good and we say QA pass. 

I'll make a separate ticket to drop Identifier, as we don't have a solid use-case for that on Collections right now.
