### ISSUE TITLE
Checkbox or pulldown for public domain or Creative Commons works filtering

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#445]
As a way to highlight our open content, a checkbox or pull down menu would be added at or near the top of the home page, advanced search, and search results page in addition to the Rights facet. It would provide functionality like the OD1 relevancy pull-down. It would need to limit the items returned by public domain, any CC license, or both.

**Comment by CGillen** [comment]
QA:
- [ ] Works exist with and without Creative Commons and Public Domain licensing
- [ ] Facet for Open Access does NOT display on search page
- [ ] Homepage Free to Use tile links to search results for open access materials
- [ ] Search bar drop down Open Content Only filters for open access materials

**Comment by shieldsb** [comment]
QA pass
