### ISSUE TITLE
Metadata Viewing

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#45]
### Descriptive summary

This is a large ticket that encompasses many different pieces of functionality. As we are working on creating the logic behind the scenes that manages and formats the metadata, we will have to be conscious about how it is displayed to the users. There are a lot of different types of metadata views that we will have to be conscious of. 

Show Page: The show page is a where a majority of the metadata is displayed. There are many different types of metadata
     - Metadata Searchable Via Facets/Quick Link Searches
     - Basic non linked metadata
     - Metadata with supporting URIs
     - Metadata that is a URI and label
     - Text Fields
     - Date Fields
     - Ordered Fields
     - More

Each one of these will be displayed differently on the show page and we need to make sure that all of them work properly. Searchable, external links link out properly, popups look right, labels for the fields, Etc.

We need to also take care of what is displayed on the search results. What pieces of metadata do we want there? How big do we want the search results to be? Images. We need to make sure this all looks right.

There are also featured works that need to be formatted properly.

This is a ticket that outlines the need to break down all the places where the metadata is displayed and make sure it is all displayed properly.

**Comment by vantuyls** [comment]
@mccallum is mocking up showpage. Other elements of this issue should be broken down as additional epics:
- [ ] metadata form views and functionality
- [ ] showpage views
- [ ] search result views
- [ ] collection views

**Comment by jsimic** [comment]
POSM reviewed. Closed.
