### ISSUE TITLE
generic_metadata changes

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#452]
Came across the following possible changes while trying to migrate some assets:
according to the OD2 map, repository should be multiple: false
according to @wickr , set and primary_set should not be included here

**Comment by CGillen** [comment]
Opened #462 to explore and implement single-value controlled vocabulary fields
QA:
- [ ] Primary Set and Set metadata fields are gone

**Comment by vantuyls** [comment]
QA Fail: 
* Repository is still multiple:true

QA Pass:
* set has been removed
* primary_set has been removed

**Comment by vantuyls** [comment]
QA Fail:
- repository still allows multiple entries on the form

**Comment by CGillen** [comment]
Repository allowing multiple entries has been split off into #462 since it requires a more significant chunk of work. There are links both directions between that ticket and this one.

**Comment by CGillen** [comment]
All other QA has passed
