### ISSUE TITLE
Rake task to generate email that contains a list of all current works in a review queue

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#454]
### Descriptive summary

A rake task needs to be fired off at the end of each day which looks at all the works in a specific step of a workflow (like being reviewed) and sends an email out to the people who are assigned to that step of that workflow.

**Comment by straleyb** [comment]
@CGillen

**Comment by CGillen** [comment]
Looks like rake task exists: https://github.com/OregonDigital/OD2/blob/master/lib/tasks/oregon_digital/daily_email.rake

Slightly different in that it specifically looks for in-review and needs-change items, not arbitrary steps. Probably fine and intended.

**Comment by straleyb** [comment]
Can we close these? Or no. Id like to work toward closing these if possible

**Comment by CGillen** [comment]
I would say yes. We should double check them at the start of sprints and see if we need to open bugfixes, or ask PMOP/POSM about expected functionality. I suspect it has changed since these opened.
