### ISSUE TITLE
Implement single-value controlled vocabulary terms

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#462]
### Descriptive summary

`:license`, `:access_restrictions`, and `:repository` are supposed to be single-value fields. Controlled vocabulary fields do not support single-value entry on the add/edit work form.

### Expected behavior

Add/edit form respects single-value restriction for descriptive metadata

### Related work

#452 Exposed this issue.

**Comment by vantuyls** [comment]
QA Fail: License and Repository are still multi value. I can add new metadata elements for these fields on the upload and edit forms.

**Comment by vantuyls** [comment]
QA Fail: Repository isn't saving the entered URI
(tested with this one: http://opaquenamespace.org/ns/repository/ASoudavarCollection)

**Comment by vantuyls** [comment]
qa pass
