### ISSUE TITLE
Change Description of Manifestion property ID

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#469]
### Descriptive summary

An update was made to the MAP, need to update code to match.

Description of Manifestation property ID should be rdaw:P10271  ( `http://rdaregistry.info/Elements/w/P10271` )

**Comment by vantuyls** [comment]
@jsimic can someone on Metadata QA this please?

**Comment by wickr** [comment]
QA, made a work with text in this property on staging, and confirmed in JSON-LD output the correct property is used.
```"http://rdaregistry.info/Elements/w/P10271": "Text by Louis Asekof. Drawings by Erica Van Horn. This book has been produced by...```
