### ISSUE TITLE
[10] Alternative rendering of relationships on the show page

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#47]
### Descriptive summary

Currently, we are rendering a simple link on the show page to a parent or a child. This is rendered pretty far down on the page, and may not be as apparent to someone who is viewing the page right away. We need to work on making this more noticeable. Do we want to render the relationships higher on the page? Do we want to add a badge on the work if it is in a relationship? Another badge if it is in a collection? We need to figure out how to render these pieces of information on a work show page to better highlight the relationships of the work. This would allow users to have an easier time discovering other works within the system. 

Furthermore, This work may have siblings. Works that have the same parent. If this work is a sibling to another work, it would be great if a user could go to the previous or next work in the list. This builds off of the ordering of works within a collection, but can also stand alone based on the current order in a returns list of sibling IDs. Whichever it may be, being able to go sideways in the graph would also enhance discoverability in the system.

### Expected behavior

When a user views a work that is part of a collection or has a parent or child, it is easily noticeable and easy to see what collection or parents or children this work has. A user must be able to go to said collection, parent, or child for ease of discoverability. 

### Related work

This work may be done by another team at the time of arriving at this ticket. We may need to re-discuss this and figure out our needs at that time. 

Also discussed having some of this relationship info in the Universal Viewer.

**Comment by vantuyls** [comment]
@mccallum can you mock up some options for what better representation of complex works might look like on the showpage? happy to discuss further to help scope this issue.

**Comment by jsimic** [comment]
Drafts of compound objects in line with MAC wireframes: [compoundObjects_finalDrafts folder](https://drive.google.com/drive/u/1/folders/1c4mylcxJtsEODlcC1hCcDIeaWc3QNQB2)
Includes display of parent and child objects in list and grid view search results, and item view pages for parents and children.

**Comment by CGillen** [comment]
Closing, see #46 for implementing compound object wireframes
