### ISSUE TITLE
Dummy creator cleanup

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#471]
### Descriptive summary

- [x] Get rid of dummy creator functionality in web form. - done

- [ ] Clean up dummy creator "URIs" by remediating to ONS URIs. 

https://docs.google.com/spreadsheets/d/1d9-0_ayu7rjhWy0STkcXjrcl_AOX1MUBW6mGZIZAfyc/edit#gid=815152553

### OSU Cleanup
* [ ] Oregon Explorer / Gerald Williams - 157 unique values (some overlap with Columbia Gorge)
* [ ] Siuslaw - 105 unique values
* [ ] other SCARC collections - 48 unique values
* [ ] Fairbanks - 100 unique values
* [ ] Middle East Waters - 456 unique values

* [x] OSU Baseball Centennial - 21 unique values, 5 new URIs created
* [x] Columbia Gorge - 134 unique values. Found 57 URIs, created 48 in opaquenamespace.org
* [x] OSU Multicultural Archives - done. 21 new URIs created
* [x] OSU Media Guides - done
* [x] OHBA - done
* [x] Braceros - done

**Comment by sseymore** [comment]
[UO_dummy_cleanup.xlsx](https://github.com/OregonDigital/OD2/files/3307077/UO_dummy_cleanup.xlsx)

UO work done. Waiting to bulk create URIs via OPNS dashboard, then replace in OD.

**Comment by sseymore** [comment]
URIs created; mass replacement next.

**Comment by lsat12357** [comment]
Made the swaps on the UO spreadsheet.

**Comment by wickr** [comment]
Closing this because remaining work was split out into other tickets by collections: #1327 #1328 #1329 #1330 #1331
