### ISSUE TITLE
Single email on the day an item hits a step in the workflow

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#478]
### Descriptive summary

For each workflow step, we should send an email out when an item enters the step on that day. 

# EXAMPLE
This means, when a work is ingested, and not reviewed by the end of the day, the users who have the ability to review that work, will receive an email suggesting they have things to do with a link to the notifications page. 

After that first day, if the work is still in the review queue, we will not re-notify someone that they have something to do. 

However, if a new work ends up in the review queue and is not reviewed, it will send a new email out, suggesting they have something to do.

**Comment by straleyb** [comment]
@CGillen Is this working or nahh?

**Comment by CGillen** [comment]
A rake task exists (reply available in #454) for this functionality, but will require a cron job or similar.
