### ISSUE TITLE
Configurable Facets

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#49]
### Descriptive summary

We need to have a lot of work done around Configurable Facets. This is a multi-faceted (see what I did there?) bit of work that spans across many different pieces. We need to be able to configure facets per collection. Each collection will have different metadata that is important to that collection. We need to not only configure the facets per collection, but order them as well. Since different collections will highlight different pieces of metadata, we need to be able to push the most important metadata to the top. We need to be able to turn on and off, these facets per collection in a UI of some sort and that leads to the second point.

We need to have some sort of way to track whether or not to render a specific facet depending on what is being viewed. Therefore, we need a way to toggle facets on and off, or assign it to specific collections or both. This could be a drop down or check box either in the collections pages somewhere, or its own UI element. A admin user, need to be able to go in and add or remove facets per collection at any time. 

There will be a lot of different pieces in the code that surround this. Maybe we need more database driven configuration, maybe we can use flip flop. There will have to be a lot of discussion around this ticket, but the basics should be lain out here.

### Expected behavior

A user can go to a collection and see a specific set of configured facets, in a specific order, to further enhance the discoverability within that collection. 

An administrative user should be able to go in and turn on and off and reorder facet fields based on a collection or within the system as a whole. 

### Related work

Collections work will need to be extended and there will be a lot of work needed behind the scenes to make facets a much more useable piece of the system.

**Comment by wickr** [comment]
We should test if this makes sense with some existing collections. Possibly have the same order system wide but can still toggle facets on/off per Collection. That would have better consistency than different ordering for each collection.

**Comment by vantuyls** [comment]
Note: this requires implementation of faceting on the collection view. @mccallum can you mock up what this would look like?

**Comment by raybrarian** [comment]
Related: #549

**Comment by jsimic** [comment]
POSM reviewed. Closed.
