### ISSUE TITLE
Display labels instead of URIs in search results.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#490]
### Descriptive summary

Search results display uris for controlled vocab fields instead of labels

**Comment by raybrarian** [comment]
Hey @straleyb - where should we be seeing URIs? Are there examples in the current items, or is this something we need seed data to QA?

**Comment by straleyb** [comment]
If you search for a work, and the work has a creator in which a URI was used, it should show the label for that creator instead of the URI.

**Comment by shieldsb** [comment]
QA pass.
