### ISSUE TITLE
Show derivatives for PDFs in the "show" page

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#493]
### Descriptive summary

PDF derivatives can be generated without a lot of overrides, but getting them to actually display is proving troublesome, so this ticket is to track the work of getting those derivatives to show up.

Some background points:

- Hyrax *and* IIIFManifest both seem to be built with the very hard-coded assumption that any given fileset has exactly **one** derivative for a display format (e.g., one thumbnail and one zoomable image, but not multiples of either)
- Building the IIIF manifest by hand without relying on the existing support in Hyrax is going to be difficult
- Relying on Hyrax without some significant core hacks is going to be difficult if not impossible
- Overriding the "show" page in full won't even solve this because then we're still stuck coming up with a IIIF manifest
- Splitting a PDF into one fileset per page is extremely ineffective: a big PDF is unusably slow (one minute *after* the page has loaded to get the universal viewer to start displaying), updates are almost impossible (no way to associate the original PDF with its per-page filesets, so updating a PDF almost means deleting all the filesets manually), disk usage is effectively doubled, and it still requires some core hacks
- Hyrax's use of `file_set_presenters` is more widespread than just IIIF purposes, so we can't simply override this

### Expected behavior

This really comes down to one thing: for each JP2 derivative in a work, we want to see it in universal viewer.  That could mean a lot of things, and until we figure out what's possible / feasible, I don't want to try to elaborate much more.

### Related work

#374

**Comment by jechols** [comment]
How to QA:

- Ingest a multi-page PDF
- Wait for derivative job to complete
- Verify all the PDF's pages are shown in universal viewer on the asset's show page
- Ingest images to verify existing image-viewer functionality hasn't changed

**Comment by jechols** [comment]
@straleyb @petersec @kmthorn - We think this QA job belongs to one of you since it's validating UX, so... ping!

**Comment by vantuyls** [comment]
QA Failing - ingest of multi page PDF results in error message showing in UV. selecting OK on error message shows me all three pages of the PDF in the UV browser, but the pages are all blank with a warning sign. 

<img width="1130" alt="Screen Shot 2019-06-05 at 9 47 36 AM" src="https://user-images.githubusercontent.com/9534576/58974329-036f6200-8777-11e9-856c-a0e6e1967ec9.png">

**Comment by jechols** [comment]
Looking into this now.  The frustrating thing is that this works fine locally, even testing the same PDF.  Will keep you updated.

**Comment by jechols** [comment]
@vantuyls: this should be good now, we just had some bad environment settings going on: http://staging.oregondigital.org/concern/documents/7h149p84n?locale=en#?c=0&m=0&s=0&cv=0&xywh=-5550%2C-184%2C13648%2C3666

**Comment by raybrarian** [comment]
QA pass. All three character sheet PDFs appear in the viewer and expected viewer functions work:
![image](https://user-images.githubusercontent.com/4460510/59703306-77b1f880-91ae-11e9-9e92-81732d087996.png)
