### ISSUE TITLE
Metadata properties display repeating 4 times on work show page

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#494]
### Descriptive summary

Metadata properties on a work show page are appearing 4 times: http://staging.oregondigital.org/concern/images/3x816m61d?locale=en#?c=0&m=0&s=0&cv=0

![image](https://user-images.githubusercontent.com/2293544/56056306-a0ca8e80-5d10-11e9-932f-1be905a10e3d.png)

### Expected behavior

Metadata properties display once.

**Comment by vantuyls** [comment]
QA Pass - metadata fields showing the expected number of times.
