### ISSUE TITLE
Combined Facets

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#50]
### Descriptive summary

This is another doozy of a ticket. There is a need in the system to collapse some pieces of metadata into an "umbrella facet" An umbrella facet would be a facet that contains many different pieces of metadata and combines it into one. For instance, Lyricist would be contained under the Creator facet. We would have to devise some way that the system knows how to aggregate a list of solr fields into a single search result to display the proper values associated with all the different facet terms under a single umbrella term.

This also begs the question of disambiguation. We will have to pay close attention to multiple results found, when to combine them under one term or whether they are two separate terms. Several results with the same value could be returned from different facet searches. Are they the same term? Different terms? We have no way of disambiguating them so do we keep them separate? Careful attention would be needed in this part of development.

We will have to decide which piece of metadata is the proper umbrella facet and which other facets go under that one. This may be described in the MAP or somewhere else, but that info should be linked here at some point. Should we be able to configure them from a UI? 

### Expected behavior

When a user looks at the facet for creator or any other facets that are aggregates of many facets, they should be able to see all the information from the many different facets associated with it.

**Comment by mccallum** [comment]
How many of these "umbrellas" are there? Creator and...?

**Comment by wickr** [comment]
Possibly Location with Ranger District and Water Basin.

**Comment by wickr** [comment]
@mccallum is going to do a mockup of what we think this will look like.

**Comment by luisgreg99** [comment]
I will follow up with Ryan Steans from Avalon to gather more design ideas for facets

**Comment by vantuyls** [comment]
@mccallum and @luisgreg99 do either of you have updates on this? do we need to engage the metadata team to discuss further?

**Comment by raybrarian** [comment]
Metadata will review, than hand off to Features (and add label).

**Comment by sseymore** [comment]
See the column in the MAP for combined faceting specifications.

**Comment by sseymore** [comment]
@straleyb @CGillen Here is where we documented the combined facets (column Q in MAP). Let us know if you need this documented in another way or if you have questions.

**Comment by sseymore** [comment]
Combined facets:

Creators 
Scientific Names
Topic 
Location 
Date 
Copyright

Please see column Q in the MAP for predicate mappings.
