### ISSUE TITLE
Show Controlled Vocab Labels and URIs on form

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#500]
### Descriptive summary

In order to understand the metadata in OD while editing a work it is necessary to see both the URI for the metadata element as well as the Label for the URI.

Proposed Behavior when Editing a Work:
1) URI enabled fields show existing URI with the label next to the URI (see mockup below)
2) Entering a URI returns the label IN the label area, while retaining the URI in the URI area
3) URI and Label remain "locked" upon further edit (as is current behavior for URIs)

**Comment by vantuyls** [comment]
<img width="880" alt="Screen Shot 2019-04-15 at 2 01 24 PM" src="https://user-images.githubusercontent.com/9534576/56165116-fe681080-5f86-11e9-87fd-31d26b2258b8.png">

**Comment by straleyb** [comment]
QA: 
- [ ] Save a work with a valid URI
- [ ] Allow the work to process and index its labels
- [ ] Visit edit page of that work and `Label (URI)` should show up in the field.

**Comment by shieldsb** [comment]
QA pass.
