### ISSUE TITLE
Append language codes to labels in Language dropdown

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#501]
### Descriptive summary

It is helpful to have language codes appended to each language in the Language dropdown list. What this should look like is:
English [eng]
Abkhazian [abk]
etc.

**Comment by CGillen** [comment]
QA:
On the work edit/create form, language dropdown
- [ ] Language codes come after every available language
- [ ] Language codes are properly formatted: `[<code>]`
- [ ] (hard mode) Language codes match metadata code - This has been hand verified once here: https://github.com/OregonDigital/OD2/pull/912/files

**Comment by shieldsb** [comment]
QA pass.
