### ISSUE TITLE
Audio/Video Enhancement for Universal Viewer

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#51]
### Descriptive summary

Currently, audio and video files arent set up to run through universal viewer. We would need to do some work on learning more about universal viewer to run the audio and video files through that. There has also been some talks of work being done in hyrax to render different viewers depending on what the format of the file is. This would be a smart mechanism that would make a decision about what to render based on the extension of the file it receives. 

If we want to use UV, we will have to do some work, but by the time we get here, audio and video might be working by default. We will have to track this and make a decision once we get here.

### Expected behavior

Audio and Video works on the show page of a work with an audio or video file.

### Related work

Audio and video configuration or different viewer based on the file associated with the work.

**Comment by vantuyls** [comment]
Check in with Chris Colvard with Indiana University and Avalon to see what direction this is heading and when he expects this work to be folded into Hyrax.

**Comment by shieldsb** [comment]
UV not working for audio and video for user not logged in with an account assigned an admin role.  The works are set to public and work show page is available, but UV is black and there are no play buttons.  Assigned my secondary account an admin role to test and it displayed and played.

**Comment by shieldsb** [comment]
QA pass for audio, text, and image.  Unable to test video currently due to issues on staging. Will come back to testing once the issue is resolved.

**Comment by shieldsb** [comment]
QA pass.
