### ISSUE TITLE
Override on the fly url generation of db url to point to s3 instead of fedora

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#518]
### Descriptive summary

Hydra generates a fedora url on the fly based on some information about the work (id?) and then makes a get request to fedora to grab the data and then use it in hydra. We need to set this mechanism up to generate a proper s3 url instead of a fedora url, so that we can hit s3 to pull items instead of fedora.

**Comment by CGillen** [comment]
Is this solvable by configuring Fedora to store binaries in S3? https://wiki.duraspace.org/display/FEDORA4x/How+to+add+Use+Amazon+Simple+Scalable+Storage+%28S3%29+for+Storing+Fedora+Content

Further, we discussed needed to offload metadata from the filesystem:
https://wiki.duraspace.org/display/FEDORA475/Configuring+JDBC+Object+Store

Those two bits of configuration should turn the Fedora container into a "dumb" wrapper around the repository. Fedora should pass through the S3 URL and, as far as I can tell, we should be able to remove any volume mounting in production.

**Comment by straleyb** [comment]
Not using S3
