### ISSUE TITLE
Translate design for OD2 home page

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#520]
### Descriptive summary

We need to take the page @mccallum drew up and translate it into code. The page can be found here: https://sketch.cloud/s/mEz3z/bgDKb0V

If we can get this to a point thats "close enough" with some of the things not completely working yet (I.E the for educators and for researchers buttons) Then that would be considered "close enough"

**Comment by CGillen** [comment]
Round 1 was #566 
Some more things to work on:
- CSS for images, color changes, etc
- Library Badges to left of intro
- Brand image at top left
- Hero image/background

**Comment by raybrarian** [comment]
Closing this one - the work (in its current, PO/SM-approved simplified form) has been broken into individual tickets based on the new wireframes.
