### ISSUE TITLE
Translate design for OD2 collections page

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#521]
### Descriptive summary

We need to translate the work @mccallum did on the collections landing page into code and get it in line with what is displayed here: https://sketch.cloud/s/mEz3z/xrz72b8 and https://sketch.cloud/s/mEz3z/ELAxjno. 

As long as we can get it "close enough" then thats all we need.

**Comment by mellinma** [comment]
Icon from MAC:  https://drive.google.com/open?id=1xhfw4bGc2s5S7gZBnrJRuYa7HntOtrI8
