### ISSUE TITLE
WC5 - Demystify AWS billing

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#525]
* Collect questions and talk with Northwestern (M. Klein’s group) 
* Set a monthly meeting about billing
* We will set AWS billing alarms on account @ $750 
* Set up notifications in Slack for when Kubernetes is setting up a new instance 
* Adjust the instance types we use to get the optimal match for our workload 
* Look for ways to add spot EC2 spot/reserved instances for EKS to target /use.

**Comment by straleyb** [comment]
@decimalator Can we close this since we arent using aws?
