### ISSUE TITLE
Add Configurable Facets attribute and checkbox to Collection Type Edit form

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#527]
### Descriptive summary
In order to make facets configurable for some collection types, we need  to be able to tell OD2 which collection types allow configurable facets. We should add this functionality to the Edit form for the collection type, under the Settings Tab (see pic below). 

Selecting this checkbox makes the collection facet configuration page available for any collection of that type.

<img width="1419" alt="Screen Shot 2019-05-20 at 11 31 32 AM" src="https://user-images.githubusercontent.com/9534576/58044210-12f27800-7af4-11e9-8307-8962bc663039.png">

### Related work
#528 

### Accessibility Concerns

- Navigation and selection on the Edit page for collection type

**Comment by CGillen** [comment]
Closed by:
#533
