### ISSUE TITLE
Work show page fields with URIs include external links 

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#530]
### Descriptive summary

On a work show page, for controlled fields that have associated URIs, there should be some kind of external link or display of this information. Also decide if certain fields need customized display.

Mockups should be made to help clarify display.

ScholarsArchive@OSU customized some fields this way, so we can look there for examples.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by sseymore** [comment]
QA pass
