### ISSUE TITLE
Collections search should accept facets

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#531]
### Descriptive summary

In order to add custom faceting to collections (#528), collections will need to be able to accept facets.

### Expected behavior

Collections landing (search) page should correctly filter works in the collection when passed facet query params, similar to the works search page.

A concrete example would be http://staging.oregondigital.org/collections/9c67wm80s?f%5Bkeyword_sim%5D%5B%5D=Culture+vulture&locale=en displaying this collection landing page: http://staging.oregondigital.org/collections/9c67wm80s?locale=en
with only this work showing: http://staging.oregondigital.org/concern/images/dr26xx36k?locale=en

### Related work

Part of #528

### Accessibility Concerns

This issue should not alter the search box or search display in any way. A later issue will be generated to deal with displaying and using facets.

**Comment by CGillen** [comment]
QA:
Before QA begins, [this collection](http://staging.oregondigital.org/collections/9c67wm80s?locale=en) should have more than one work in it, a subset of which have the `Culture vulture` keyword.
- [ ] http://staging.oregondigital.org/collections/9c67wm80s?f%5Bkeyword_sim%5D%5B%5D=Culture+vulture&locale=en Displays a search in this [collection](http://staging.oregondigital.org/collections/9c67wm80s?locale=en) and is filtered on `keyword = Culture vulture`

**Comment by vantuyls** [comment]
qa pass on this collection and search - http://staging.oregondigital.org/collections/zs25x8453?utf8=%E2%9C%93&cq=culture+vulture&sort=&locale=en
