### ISSUE TITLE
Create a new option for Collections which enables configurable facets

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#533]
### Descriptive summary

When creating a new collection type, there are multiple options that you can enable in which "append" functionality to the collection type. There needs to be a choice in the settings tab after you create the new collection type that enables that collection type to have configurable facets. 

The workflow would be as follows:
- [x] Go to collection type tab
- [x] Create new collection type
- [x] Immediately after creation, go to settings tab
- [x] Click the check box to enable configurable faceting
- [x] Save the changes

By following these steps, when you create a collection of the previously created work type, it should allow you to configure the facets for that collection. This includes being able to order the facets, change the label, and enable/disable certain facets. This data will need to be tracked per collection and should be configurable per collection.

**Comment by CGillen** [comment]
QA:
- [ ] Collection Type form has a configurable facets checkbox
- [ ] Collection Type form will save with configurable facets checkbox checked
- [ ] Collection Type form will save with configurable facets checkbox unchecked

**Comment by vantuyls** [comment]
QA Pass - though a few side issues have been added
