### ISSUE TITLE
Confirm Bootstrap is in boilerplate "Style Guide Guide."

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#543]
### Descriptive summary

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by mccallum** [comment]
I got Bootstrap in there (see blue link and <head>) but need to work more with flushing cache before posting. Linkage is broken due to lingering cache: https://oregondigital.github.io/oregon-digital-style-guide/

**Comment by raybrarian** [comment]
QA passed
