### ISSUE TITLE
Move in color decisions into style guide.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#544]
### Descriptive summary

The living style guide at https://oregondigital.github.io/oregon-digital-style-guide/ contains the shared truth of color choices and related visual hierarchy. Include swatches, hsla and hex values, and links to examples of use.

### Related work
To find a home here: https://oregondigital.github.io/oregon-digital-style-guide/styles/color

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by mccallum** [comment]
6/14 Facing some learning curve "hills" of Markdown in GatsbyJS on React but no blockers.

**Comment by raybrarian** [comment]
Closing this issue. Color palette exists in placeholder guide. Additional design work will be needed and will get ticketed based on next designer.
