### ISSUE TITLE
Move in typography decisions.

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#545]
### Descriptive summary

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Related work
To find a home here: https://oregondigital.github.io/oregon-digital-style-guide/styles/typography

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by raybrarian** [comment]
Initial typographic exploration completed, but much remains to be done. Closing this issue to clean up - future issues will be ticketed for the next designer.
