### ISSUE TITLE
Hook up collection code to new collection type facet_configurable code

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#547]
### Descriptive summary

With the collection type code set up for a collection type to know if its facets are configurable, we need to set up the ability for a collection to render facets in the proper place. This has to check whether or not a specific collection's collection type allows for configurable facets.

A collection should respond to `collection.facet_configurable?` and return a true or false statement.

**Comment by CGillen** [comment]
QA:
- [ ] Collection edit page offers facet tab iff "configurable facets" is enabled for the collection type
- [ ] Facet options align with facetable from MAP
- [ ] Facets are orderable, enableable, and relabelable
- [ ] Facet order, enable status, and label persists and pre-populates on save and edit page reload.

**Comment by CGillen** [comment]
QA Failed. All Collections dashboard throws Ack error. Creating Collection Type throws Ack error.

**Comment by vantuyls** [comment]
QA Failed - collection facets do not save

**Comment by vantuyls** [comment]
qa pass
