### ISSUE TITLE
Render configured facets for collection on collection landing page

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#550]
### Descriptive summary

The collection landing page for a specific collection should render its configured facets.

**Comment by CGillen** [comment]
Specifically, this involves:
- Moving this initializer hack: https://github.com/OregonDigital/OD2/blob/master/config/initializers/hacks/hyrax_collections_controller_behavior.rb into the overriden collection controller: https://github.com/OregonDigital/OD2/pull/549/files#diff-beaffbb5688963e1779ae35e274eb392R6
- Filling out `#configured_facets` to return information for `#render_facet_partials` from blacklight, based on Facet solr_name and label

**Comment by CGillen** [comment]
QA:
- [ ] Configuring facets from collection edit form should reflect on collection landing page
- [ ] A facet that is configured that is not applicable to any works in the collection should not display
- [ ] A facet that is configured and applicable to at least one work in the collection should display

**Comment by vantuyls** [comment]
QA Fail - looks like collection facet edits are not saving
