### ISSUE TITLE
Reconsider all derivative generation options

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#554]
### Descriptive summary

Generating derivatives has resulted in a lot of hacked-up Hyrax code with fun overrides everywhere, and we only have images and PDFs going.  If we need to do anything fancy with other derivatives, we could end up with even more crazy overriding.

And then there's derivative storage: right now they go to disk, but we need to do more hacking to get them into S3.

### Expected behavior

This ticket is to capture research / discussion around what other options exist.  The expected outcome is simply more information to help decide if we need to change course.

### Related work

Getting files from hyrax: #526 

### Accessibility Concerns

N/A - discussion only

**Comment by jechols** [comment]
Job Queue
---

Currently we use Sidekiq for all background jobs.  We could stick with it, replace it for some jobs, or replace it fully.

I've been looking a bit at faktory: https://github.com/contribsys/faktory.  This is built by sidekiq devs and is a bit less constraining (it can be used from a variety of technologies, not just Ruby).

Job Runners
---

If we want something more scalable than what we have, we should consider spinning up Kubernetes pods instead of just having workers that sit and listen forever (especially workers running the entire Rails + Hyrax stack).

This complicates dev.

Maybe we don't spin up pods from Rails.  What about a separate pod-spinner-upper thing?  This just spawns kubernetes pods when there aren't enough job runners for a given type of job.

In this way:

- Rails queues jobs and doesn't care what handles them
- The spawner is kicking off pods only when there aren't enough pods of a given type
- The job runners are grabbing jobs when necessary
- Something is reaping pods once they're idle (no more items in their queue)

This would make dev basically what it is today.  In dev we always run listeners (as we do today), but we explicitly define the spawner/reaper thing as a prod-only process.

**Comment by jechols** [comment]
faktory has a deal-breaker: it can't signal us when a job dies like sidekiq can: https://github.com/contribsys/faktory_worker_ruby/issues/38.  FetchGraphWorker needs to email somebody when it has tried for too long and hasn't managed to fetch labels.

Sidekiq will work, but it does force us to use Ruby.  We're still investigating options to see if we can at least get a very barebones Ruby derivative generation app.

One problem we need to handle is that Hyrax is actually defining the job handlers, not our code, so we have to override those if we want full control.  This isn't difficult, but it's another place we diverge from Hyrax, so it's not ideal.

**Comment by jechols** [comment]
Facts:

- We have to handle CreateDerivativesJob in our Rails app
  - We could change how Hyrax queues that job, but it would require us to override the CharacterizeJob, which I think is a more dangerous thing to override since it does more low-level work.  I believe we should not do this.
- We have to generate derivatives in such a way that both Hyrax and RAIS can find them
  - Implications for an out-of-band derivative processor:
    - It needs to put files somewhere that can be easily defined solely by data passed to the job
    - Hyrax needs to be able to use logic, not data, to query derivatives for an asset (otherwise we have to store derivative information in the asset metadata, update it properly on changes, etc., and that complicates the app significantly)
    - The derivatives should be stored in a simple enough way that we can expose an S3 URL for JP2s so RAIS can read them.  We could add a more custom plugin to RAIS that has logic to turn a generic id into an S3 path, but that should only happen if we have no other choice.

So here's my newest idea / plan:

- Override Hyrax's CreateDerivativesJob so that it queues up a new `WriteDerivativesToS3` job
  - WriteDerivativesToS3 is in a special queue that the Rails workers never check
  - Depending on needs, this could actually have jobs in queues based on what kind of derivatives are needed.  PDF derivatives can take a long time, but aren't likely to need much RAM.  Image derivatives'  RAM needs are based on the source image size.  Movies and audio have entirely different needs.
- We build a very barebones Ruby app (and an alpine image for it) that just checks the WriteDerivativesToS3 jobs and fires off the necessary shell script(s)
- On success, a new job is queued up to update the asset (basically everything Hyrax does in CreateDerivativesJob after its `file_set.create_derivatives` call)

**Comment by revgum** [comment]
@jechols ship it!

**Comment by jechols** [comment]
I think given the plan has been largely approved, this ticket has succeeded.  Closing.
