### ISSUE TITLE
Configure Controlled Vocabulary Support for Collections

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#570]
### Descriptive summary

In order to configure all the metadata for Collections, Collections need to be able to support controlled vocabularies. There is going to be some extra work involved with allowing it to support the CVs.

**Comment by raybrarian** [comment]
Need to use base Work Types to begin.

**Comment by CGillen** [comment]
Metadata: Determine which fields to be controlled and hand back over to features

**Comment by wickr** [comment]
Metadata to confirm what fields will be controlled for Collections.

**Comment by CGillen** [comment]
Metadata terms added to MAP for collection. Ready for features development: add metadata with appropriate `class_name`
