### ISSUE TITLE
Update the indexing for Collections

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#576]
### Descriptive summary

This will have to be a follow up PR for the collection metadata overhaul. The PR is already getting large and we'll have to split this into multiple tickets. Ill make sure that everything works without erroring in #569 and work on extending the indexing to index the controlled vocabularies as well.

**Comment by straleyb** [comment]
QA: Put data into the form fields and save. Then search

**Comment by vantuyls** [comment]
qa pass
