### ISSUE TITLE
Worktype fetched labels from Getty are not in English

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#578]
### Descriptive summary

Worktype Labels being fetched are not in English.

Example: http://staging.oregondigital.org/concern/images/w0892992w?locale=en#?c=0&m=0&s=0&cv=0&xywh=-1124%2C476%2C4294%2C987

### Expected behavior

Labels should be in English

**Comment by raybrarian** [comment]
QA still fails:
<img width="172" alt="nonenglish-type-labels" src="https://user-images.githubusercontent.com/4460510/61228328-eb2a2580-a6da-11e9-8c89-21fb1793fb8d.png">

**Comment by raybrarian** [comment]
@wickr, @straleyb - this is still failing QA - is there a different PR this is dependent on?

**Comment by raybrarian** [comment]
@straleyb QA still fails - moving back to Ready on the project board.

**Comment by raybrarian** [comment]
@straleyb - Not sure if this is just waiting for an indexing job to complete... Still seeing Work Type Label for this example presenting _fotografías forenses (obra visual)_ I can check again later today or tomorrow, but wanted to give you a heads-up in case it's an indicator there's still an issue.

**Comment by CGillen** [comment]
@raybrarian Last deploy failed, and the work needed re-saving/re-indexing. Should be good to go now.
I only re-saved this specific item, so any others that need to be tested will need to go through an edit->save cycle.

**Comment by straleyb** [comment]
http://staging.oregondigital.org/concern/images/w0892992w?locale=en#?c=0&m=0&s=0&cv=0&xywh=-1914%2C-1%2C5874%2C1536 Work type saved properly as english.

**Comment by raybrarian** [comment]
QA pass.
