### ISSUE TITLE
Creating a new Digital Collection does not work

### ISSUE THREAD

**Issue by kmthorn** [OregonDigital/OD2#589]
### Descriptive summary

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

I am logged in as kmthorn@uoregon.edu (not sure what user group this account is set to). I want to create a new digital collection. From the dashboard, I click on "Collections" then click "New Collection". I then select "Digital Collection" and fill in all the fields except the ones requiring URI lookups. Once the form is filled out, I then click "Save". 

### Expected behavior
The expected behavior is... when kmthorn@uoregon.edu clicks "Save" it confirms the digital collection has been made. Confirmation should be the same as "Admin Set" saving.

### Related work

None?

### Accessibility Concerns
Not sure other than make sure a user can navigate and save using only a keyboard.

**Comment by wickr** [comment]
Try and duplicate this again, after Workcycle 6 work.

**Comment by raybrarian** [comment]
I have walked through Kate's same steps, and get the "Ack, Looks like Oregon Digital is temporarily broken" message. Collection not created. Pushing this back into backlog for WC7

**Comment by straleyb** [comment]
QA'd this, https://staging.oregondigital.org/dashboard/collections/2v23vt362?locale=en
