### ISSUE TITLE
Navbar: Change 'Forgot Your Password?' to 'Help'

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#590]
### Descriptive summary

Help page needs to be on every page in easy to find location, farthest right in the navbar. Forgot Your Password? links will vary by login system and need to go on a bigger login page. Create a placeholder Help page from within Hyrax.

Wireframe mockup: https://www.lucidchart.com/documents/edit/9814ebf7-6286-406c-946b-8fa69ff92cbb/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

'Forgot Your Password?' changed to 'Help'

### Related work

#520

**Comment by raybrarian** [comment]
QA pass.
