### ISSUE TITLE
Navbar: Add text “UO Login” to UO button and text “OSU Login” to OSU button, keep icons

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#591]
### Descriptive summary

Add text to help explain the login icons, after the icon to match the first one.

Wireframe mockup: https://www.lucidchart.com/documents/edit/9814ebf7-6286-406c-946b-8fa69ff92cbb/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Each login icon has text with it.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by raybrarian** [comment]
QA pass.
