### ISSUE TITLE
Homepage: Remove "For Educators" and "For Researchers" buttons

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#592]
### Descriptive summary

These buttons will be replaced by an expanded "How Do I Use?" section.

Wireframe mockup: https://www.lucidchart.com/documents/edit/9814ebf7-6286-406c-946b-8fa69ff92cbb/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

"For Educators" and "For Researchers" buttons no longer exist.

### Related work

Link to related tickets or prior related work here.

**Comment by raybrarian** [comment]
QA pass - removed for authed and unauthed users
