### ISSUE TITLE
Update site title from 'Hyrax' to 'Oregon Digital (Development)'

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#594]
### Descriptive summary

Update site title from 'Hyrax' to 'Oregon Digital (Development)' so it's clearer to folks what the site is during development.

(Information compiled by POSM group from updated wireframes)

### Expected behavior

'Hyrax' should not be the site title anywhere, 'Oregon Digital (Development)' should be.

**Comment by raybrarian** [comment]
QA pass
