### ISSUE TITLE
Search: Add search dropdown filter options for OSU, UO, or Open content only, for all users

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#595]
### Descriptive summary

Add 3 search dropdown filters, available to all users, logged in or not. These give an additional way to limit results to OSU, UO or Open content only.

Wireframe mockup: https://www.lucidchart.com/documents/edit/9814ebf7-6286-406c-946b-8fa69ff92cbb/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Not logged in search dropdown options should be:
  * Search All of Oregon Digital (Development)
  * Search OSU Content Only
  * Search UO Content Only
  * Search Open Content  [limit to Public Domain and CC0 licenses]

Logged in search dropdown options should be:
  * Search All of Oregon Digital (Development)
  * Search OSU Content Only
  * Search UO Content Only
  * Search Open Content  [limit to Public Domain and CC0 licenses]
  * Search My Works
  * Search My Collections

**Comment by raybrarian** [comment]
QA pass - note wording is slightly different (and adheres to UX best practices).

Logged in:
![image](https://user-images.githubusercontent.com/4460510/62225360-24b29000-b36d-11e9-969b-999bad30e229.png)

Unauthenticated:
![image](https://user-images.githubusercontent.com/4460510/62225409-3ac05080-b36d-11e9-96de-9af7ea07ba4c.png)
