### ISSUE TITLE
Homepage: When logged in, remove 'Share Your Work' button

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#596]
### Descriptive summary

When logged in, on Homepage, remove 'Share Your Work' button and 'Terms of Use' link

Wireframe mockup (homepage logged in): https://www.lucidchart.com/documents/edit/a82ebc85-1232-4cf5-8861-0a14e0fb37ba/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

'Share Your Work' button and 'Terms of Use' link do not appear on the homepage when logged in.

**Comment by raybrarian** [comment]
QA pass
