### ISSUE TITLE
Footer: Add links, institution logos

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#597]
### Descriptive summary

Expand content in the footer to have relevant links and branding. Refinements to the layout are likely at a later time.

Wireframe mockup: https://www.lucidchart.com/documents/edit/9814ebf7-6286-406c-946b-8fa69ff92cbb/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Left side:
* **Oregon Digital** is collaboratively managed by the Digital Scholarship Services of the University of Oregon Libraries and by Oregon State University Libraries. [with appropriate links]
* Institution logos
* Policies [page]
* Copyright [page]
* Contact Us [page]
* About [page]
* Donate [page]
* Style Guide [when logged in]

Right side:
* Keep Oregon Digital code release tag
* Add 'Samvera' before 'Hyrax' and make it a link to samvera.org
* Remove 'Copyright © 2019 Samvera...' text

**Comment by raybrarian** [comment]
Samvera link fails accessibility test (color is the only indicator it is a link, and the hover color of dark purple makes it unreadable when moused over). 

Left side text not present (from above): Oregon Digital is collaboratively managed by the Digital Scholarship Services of the University of Oregon Libraries and by Oregon State University Libraries. [with appropriate links]

No style guide link when logged in.

**Comment by raybrarian** [comment]
QA pass.
