### ISSUE TITLE
Homepage: Add Showcase section (with row 1 of 3), remove Latest Collections and Latest Items

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#599]
### Descriptive summary

Instead of the Latest Collections and Latest Items blocks on the homepage, we've decided to change to a Showcase section (with label) that will have one row of four fixed link blocks, and then 2 more rows of curated items (separate ticket).

The first row of the Showcase section will be: 
* OSU items - link to search results of only OSU items
* UO items - link to search results of only UO items
* Free to Use - link to search results of *only* Public Domain license items
* Browse All Collections - link to page with list of all Collections

There will eventually be images with a label span, but for now they can be solid color blocks, using Beaver Orange: #D73F09 ; UO Green: #036936 ; other suitable colors for last 2 blocks.

Wireframe mockup: https://www.lucidchart.com/documents/edit/9814ebf7-6286-406c-946b-8fa69ff92cbb/0

Also see  https://inclusive-components.design/cards/

(Information compiled by POSM group from updated wireframes)

### Expected behavior

New Section will provide 4 fixed links to popular and useful searches, as well as allowing featured things in the following 2 rows.

### Related work

#600 

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by raybrarian** [comment]
@CGillen - need the background colors of the blocks/cards in this row to match to those listed in the issue. Last two blocks can be #09a17d and #690336 for now. Font will likely have to be changed to #ffffff, unless you want them at 25% opacity or similar?

**Comment by CGillen** [comment]
QA:
- [ ] Background colors of boxes are passable

**Comment by raybrarian** [comment]
QA pass. Some of these fail automated checking because the incorrect background color is reported in the tool, but a manual check succeeds. Colors will be adjusted regardless in the design process.
