### ISSUE TITLE
Homepage: Showcase section, rows 2 and 3

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#600]
### Descriptive summary

8 graphic blocks, 2 rows of 4 in same style as 1st row of Showcase. Placeholders for now, to be curated manually by Service Managers. Can be solid grey for background: #6A6C6E

These will be a way to feature new or popular collections, filtered search results, specific items or eventually exhibits, and will give us a lot of flexibility.

Wireframe mockup: https://www.lucidchart.com/documents/edit/9814ebf7-6286-406c-946b-8fa69ff92cbb/0

See: https://inclusive-components.design/cards/

(Information compiled by POSM group from updated wireframes)

### Expected behavior

2 rows with 4 blocks each to feature whatever is relevant for the homepage. 

### Related work

#599

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by raybrarian** [comment]
QA pass.

**Comment by CGillen** [comment]
@raybrarian We had insufficient public collections to test from an anonymous user. I've changed my collection to public and a 3rd row should appear now. Login to view a fully populated row with 8/9 collections shown.

**Comment by raybrarian** [comment]
QA pass.

**Comment by raybrarian** [comment]
QA pass.
