### ISSUE TITLE
Homepage: Add new 'How Do I Use Oregon Digital?' section

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#601]
### Descriptive summary

Similar to the section on http://dp.la and instead of the For Educators and For Researchers buttons we had, add a new section called "How Do I Use Oregon Digital? with 4 image block sections:

4 block links to information pages, styled similar to DPLA homepage, placeholder icons with text for now:
* Students
* Teachers
* Researchers
* Lifelong Learners

We don't have icons designed or selected yet, one option may be Noun Project icons, inquiries on using these have been made.

This will go below the new Showcase section.

Wireframe mockup: https://www.lucidchart.com/documents/edit/9814ebf7-6286-406c-946b-8fa69ff92cbb/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

New section shows links to different information pages relevant to our audiences.

**Comment by raybrarian** [comment]
QA pass.
