### ISSUE TITLE
Work Show Page: Hide display of badges for most users

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#603]
### Descriptive summary

The badges that show after the work title such as "Public" and "Deposited" do not need to display for the public and most authenticated users. Show only to Admins and Curators.

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Badges are hidden for non-authenticated and most authenticated users, show only to curators and above.

**Comment by raybrarian** [comment]
QA pass as admin. @CGillen, I'm assuming we'll need to revisit this in QA for the Curator role, when that's developed?

**Comment by CGillen** [comment]
@raybrarian Yeah, we'll have to come back and fail this once we have the Curator role sorted out. It'll be a quick fix, but no way to preempt it.
