### ISSUE TITLE
Work Show Page: add label to hard-coded Description field

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#606]
### Descriptive summary

Description is hard-coded into the view, but does not have a label. Add a label to this field in the same form as the rest of the descriptive metadata (as much as possible).

Wireframe mockup: https://www.lucidchart.com/documents/edit/944f6fd3-53b5-466b-b49f-f0788ada80aa/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Description field has a label.

**Comment by raybrarian** [comment]
@wickr - Can you QA this? I don't see a label where I would expect it for this item, but maybe I'm wrong?
![image](https://user-images.githubusercontent.com/4460510/61550519-8424ad80-aa07-11e9-90e3-5b86df0db500.png)

**Comment by CGillen** [comment]
@raybrarian Last deploy failed. This and 605+608 should be good to QA now.

**Comment by raybrarian** [comment]
QA pass
