### ISSUE TITLE
Work Show Page: change page layout below viewer

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#607]
### Descriptive summary

Below the Universal Viewer section, change the page layout, keep 2 columns but make the left side larger instead of the right one.

Wireframe mockup: https://www.lucidchart.com/documents/edit/944f6fd3-53b5-466b-b49f-f0788ada80aa/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Metadata display will stay in the larger section, but will be on the left. See mockup.

**Comment by raybrarian** [comment]
QA pass - two columns, larger on left.
