### ISSUE TITLE
Work Show Page: Add placeholder section for MLA Citation

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#609]
### Descriptive summary

Below the descriptive metadata in the wide left column, add a new placeholder section for a static, generated MLA Citation section, and include the label.

Wireframe mockup: https://www.lucidchart.com/documents/edit/944f6fd3-53b5-466b-b49f-f0788ada80aa/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

MLA Citation section displays below descriptive metadata.

**Comment by raybrarian** [comment]
QA pass.
