### ISSUE TITLE
Work Show Page: Add Collection Information section to right column, move content from Relationships section

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#610]
### Descriptive summary

In the narrower right column, add a new section at the top of the column called "Collection Information", move the display under the Relationships section under here (Collections, Admin Sets, etc.)

Wireframe mockup: https://www.lucidchart.com/documents/edit/944f6fd3-53b5-466b-b49f-f0788ada80aa/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Collection Information sections hows Collections and Admin Sets information.

**Comment by CGillen** [comment]
Resolved by #625

**Comment by raybrarian** [comment]
QA pass. Some additional CSS adjustments required - I'll submit a new ticket.
