### ISSUE TITLE
Work Show Page: In right column, move Social Media section, adjust services

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#613]
### Descriptive summary

In the right column, move the Social Media section. Remove Google Plus and Tumblr. Add Instagram.

https://github.com/samvera/hyrax/blob/master/app/views/hyrax/base/_social_media.html.erb

Wireframe mockup: https://www.lucidchart.com/documents/edit/944f6fd3-53b5-466b-b49f-f0788ada80aa/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Social Media section has icons/links for Twitter, Facebook, and Instagram.

**Comment by CGillen** [comment]
Note sure who to ping for POSM, @kmthorn, @petersec, or @jsimic I guess?
I don't believe Insta has a link sharing system, please give me an example if I'm wrong. I can do a copy to clipboard button instead.

**Comment by raybrarian** [comment]
QA pass. Instagram does not allow direct sharing - link copy button works as expected, as do other buttons.
