### ISSUE TITLE
Edit Form: Description field should be labeled as "Description"

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#614]
### Descriptive summary

On the edit form, Description is still labeled as 'Abstract or Summary' the default out of Hyrax. Also need to update the help text.

### Expected behavior

'Description' label appears on the Description field.

**Comment by CGillen** [comment]
Fixed by #624

**Comment by raybrarian** [comment]
@wickr - not sure if this issue is describing edit work or edit collection. They both appear to be displaying as expected. Can you confirm?

**Comment by raybrarian** [comment]
@wickr - assigning this to you to confirm QA

**Comment by wickr** [comment]
This was for edit work.

QA pass. Description field on edit form is correct and there's no longer an 'Abstract or Summary' label anywhere.
