### ISSUE TITLE
Work Show Page: In right column, add Download section

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#615]
### Descriptive summary

In the right column, add a Download section with label.

Options available will be: 
* Standard with Metadata (zip file with standard derivative plus CSV)
* High Resolution with Metadata (zip file with original file (i.e. TIF) and CSV) [when available]
* Metadata Only (CSV)

The first, Standard, should be workable now, but the others can be placeholders until the rest of the features are built, to include zip and CSVs, and control when High Resolution is displayed.

Wireframe mockup: https://www.lucidchart.com/documents/edit/944f6fd3-53b5-466b-b49f-f0788ada80aa/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Download section shows what options are available to the user. High Resolution is included if available to them.

**Comment by raybrarian** [comment]
QA pass with placeholder for image only download as the first option.
