### ISSUE TITLE
Work Show Page: MLA Citation Section, generate and format citation

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#616]
### Descriptive summary

In the new Citation section (#609) below descriptive metadata, generate the citation in MLA format, so it can easily be copied and pasted into a paper or citation manager. There may be Citations code in Hyrax that is partly reusable.

Form: (Up to 3, then et. al) Creators last name, creator first name. Title. Oregon Digital. Date. URL w/PID

Example:
Finley, William. Great blue heron. Oregon Digital. 1904. Web. 15 July 2019. oregondigital.org/concern/images/df718r77q

(Prepared with https://oregondigital.org/catalog/oregondigital:df718r77q)

This will need to account for situations where there's no author or lots of authors. Title should always be there. Date (creation/publication) will not be on all items. Date accessed should be that day's date. The URL to use may be shortened but for now go with what is active.

More specific citation questions can be directed to @kmthorn 

Wireframe mockup: https://www.lucidchart.com/documents/edit/944f6fd3-53b5-466b-b49f-f0788ada80aa/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

MLA Citation is generated with as much information as possible, empty elements are omitted so there's no weird formatting.

### Related work

#609

**Comment by raybrarian** [comment]
@CGillen - QA check - citation URLs still show as localhost. Should they show as staging.oregondigital?

**Comment by raybrarian** [comment]
@CGillen - URL still shows as localhost. I think we determined this might be expected behavior at this stage of development. Can you confirm?

**Comment by CGillen** [comment]
Not expected behavior, I'll continue work on this.

**Comment by raybrarian** [comment]
QA pass
