### ISSUE TITLE
Untangle search functionality from show functionality in catalog controller

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#629]
### Descriptive summary

The way it stands, when something is configured as `:stored_searchable` it both tries to search and add it to the show page. We need to find a neat way of being able to decide whether something wants to just be displayed, just be searched, just be advanced_searched, be displayed and advanced_searched, be displayed and be simple_searched, and every other permutation of those. 

This means looking at the MAP and seeing which fields want to be displayed but not searched, and all the other permutations and making sure the searching is completely aligned with the MAP. 

This will have to be cross checked with the MAP by a metadata person for QA.

**Comment by wickr** [comment]
We should have most of this capability with the other descriptors already defined: 
https://www.rubydoc.info/gems/solrizer/3.4.0/Solrizer/DefaultDescriptors
See also: https://samvera.github.io/customize-metadata-model.html

I think our use of 'advance_search' should be changed, we haven't added the Blacklight Advanced Search plugin yet (but will), so despite the config for that being in the MAP, 'advanced' shouldn't be a part of any of the search code right now.

**Comment by straleyb** [comment]
Thats part of the work. I really want to try to encapsulate the functionality between searching, advanced searching, show, and facet. So most of the work is going to be utilizing what we have access to and tailoring it all to how the MAP wants things. 

There were a lot of properties that were missing from the show page, and wanted to be displayed. But if they get displayed, it also enables search for them. some want to be displayed but not searchable, so im going to detatch all the "advanced_search" stuff and move it over to something more encapsulated and descriptive.

**Comment by raybrarian** [comment]
Metadata will QA.

**Comment by sseymore** [comment]
Seems like this is wrapped up with #272 and #397. Metadata will QA once seed data is ingested.

**Comment by sseymore** [comment]
Please see most recent QA on #272

**Comment by CGillen** [comment]
We're done here. The functionality exists and works, but we need to continue to refine the specifics of the metadata fields. Please continue with #272
