### ISSUE TITLE
Work Show Page: Item+Metadata downloads

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#644]
### Descriptive summary

#615 Added direct download links for items. Links are still needed for Metadata exported as a CSV, the item + CSV metadata (zipped), and the high resolution original + CSV metadata (zipped).

### Expected behavior

- Download link for metadata provides export of work metadata as CSV
- Download link for item(s) + metadata provides a zip with above CSV and item image(s)

### Related work

#615 

### Accessibility Concerns
N/A

**Comment by CGillen** [comment]
Closed by QA on:
- [ ] #668 
- [ ] #669 
- [ ] #666

**Comment by shieldsb** [comment]
While logged in, but without admin credentials, when I tried to download ZIP and CSV files for public items, I received a message stating: "You are not authorized to access this page."  Ryan set me up as an admin and they downloaded with no issues.

**Comment by shieldsb** [comment]
QA pass.
