### ISSUE TITLE
Search: change drop-down label from Public Domain to...

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#650]
### Descriptive summary

Change label for drop down from "Public Domain..." to "Open Content"

**Comment by straleyb** [comment]
@vantuyls Im not sure what you are talking about here. Where is this drop-down? Im not seeing it in the "all drop down" next to the search box.

**Comment by vantuyls** [comment]
<img width="700" alt="Screen Shot 2019-07-29 at 1 15 56 PM" src="https://user-images.githubusercontent.com/9534576/62079190-0892df80-b203-11e9-900a-d7a7bf4e63cb.png">
Where it says "Public Domain Content Only" it should instead read: "Open Content"

**Comment by raybrarian** [comment]
QA pass - confirmed in unauthed and authed users
