### ISSUE TITLE
Export metadata as CSV

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#666]
### Descriptive summary
As part of #644, a work should be able to export its metadata to a temporary CSV file. The first row should be headers of the human readable names for each metadata entry. 
The data should be one row of metadata.
Edit from conversation with Kate:
Multivalue metadata should be a quotes escaped list of values, separated by `|` (bars/pipes). 
~Labels for CVs should not be provided, just URIs.~ Both labels and URIs should be present for CVs.

Use the standard CSV library to avoid issues with the CSV spec: https://ruby-doc.org/stdlib-2.6.1/libdoc/csv/rdoc/CSV.html
And if you still think the format looks off, check the RFC: https://tools.ietf.org/html/rfc4180

### Expected behavior
A work can provide a file pointer to a temporary CSV metadata export. The CSV file is formatted to RFC4180.

For now, ignore file clean up and we'll deal with it in a separate issue (#667).

### Related work
Child of #644 

### Accessibility Concerns
None

**Comment by wickr** [comment]
Discussed in #od2-metadata channel, here's the format to go with for CVs with multiple values, to include labels and URIs: 
`cats [http://id.loc.gov/authorities/subjects/sh85021262]|dogs [http://id.loc.gov/authorities/subjects/sh85038796]|birds [http://id.loc.gov/authorities/subjects/sh85014310]`

**Comment by CGillen** [comment]
No QA. QA to come when user facing interface is hooked up
