### ISSUE TITLE
Export metadata + assets in zip

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#668]
### Descriptive summary
As part of #644, a work should be able to export its metadata and derivatives as a zip file. Use the work from #666 to grab the CSV metadata and zip it together with derivative files.

If grabbing source files is not a pain, use this ticket to do the same thing for the originals. Otherwise open a new issue.

### Expected behavior
A work can provide a file pointer to a temporary zip export.

For now, ignore file clean up and we'll deal with it in #667.

### Related work
Child of #644 
Relies on #666 

### Accessibility Concerns
None

**Comment by CGillen** [comment]
QA requires #669.
- [ ] Files + Metadata (ZIP) download link should provide a zip with all latest files and a csv of metadata
- [ ] Metadata Only (CSV) download link should provide a csv file with only appropriate metadata elements.

**Comment by raybrarian** [comment]
QA pass.
