### ISSUE TITLE
Order deployment information $date-$commit

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#672]
### Descriptive summary
Messages to Honeycomb and the footer of the page should include information about the current deployment in a more sortable order.
`$date-$commit` is much more sortable than the current `$commit-$date`

### Expected behavior
Honeycomb recognizes boots in a sortable order.

### Accessibility Concerns
None

**Comment by CGillen** [comment]
Fixed by #673

**Comment by raybrarian** [comment]
@decimalator - please QA this one - thanks!

**Comment by decimalator** [comment]
QA Pass
