### ISSUE TITLE
Search Results: List View: Move thumbnail up and title over to the side

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#680]
### Descriptive summary

On Search Results, List View, move the work thumbnail up to the 'top' and move the work title over to the side of it.

Wireframe mockup, List View: https://www.lucidchart.com/documents/edit/517560ad-afba-41c5-a2c5-d3ff2b16f2bf/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Thumbnail is top-left aligned, Title is top-aligned but to the right of thumbnail.

### Accessibility Concerns

Work title should probably still remain first in the tab index order.

**Comment by CGillen** [comment]
QA:
- [ ] Search results page list view: Title appears above thumbnail

**Comment by raybrarian** [comment]
Title is currently top-aligned and to the right of the thumbnail, per issue spec (edited listed QA pass criterion to reflect spec).

@cgillen - I know this isn't spec'd explicitly in the issue, but tab order in the results set starts at the title in result 1 (skipping the thumbnail), then tabs to the leading thumbnails. DPLA sends tab order to the left-hand faceting stack, then image, then title. I think if there are links to activate, they should go in (essentially) webpage reading order for the language the page is viewed in, whether or not they are images. Here's the relevant WCAG 2.0 link: https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G59.

**Comment by shieldsb** [comment]
QA pass.  Tab order resolved.
