### ISSUE TITLE
Search Results: List View: Metadata fields update

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#683]
### Descriptive summary

On Search Results, List View, change the metadata fields that are shown (below Title):

  - Creator: show up to 3 creators, display 'and others' when more than 3
  - Date
  - Description: Truncate to 20 words, with ellipsis
  - Resource Type

Wireframe mockup, List View: https://www.lucidchart.com/documents/edit/517560ad-afba-41c5-a2c5-d3ff2b16f2bf/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Metadata fields shown in search results are changed to Creator, Date, Description, and Resource Type.

**Comment by CGillen** [comment]
QA:
- [ ] Search results page list view: Creator field displays at most 3 creators + "and others"
- [ ] Search results page list view: Date field exists, currently displayed as "date modified"
- [ ] Search results page list view: Description field displays at most 20 words
- [ ] Search results page list view: Resource type is not displayed in metadata field, instead displayed below with a relevant icon
