### ISSUE TITLE
Search Results: List View: Create 'Add to My Shelf' button, with 'Select all on page' checkbox below

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#684]
### Descriptive summary

On Search Results, List View, make a "Add to My Shelf" button to the right of the search box (see wireframe). Below that, add a checkbox for "Select all on page" that checks each result.

Wireframe mockup, List View: https://www.lucidchart.com/documents/edit/517560ad-afba-41c5-a2c5-d3ff2b16f2bf/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Add to My Shelf button is similar to the one on the work show page but can add 1 or more works in results directly to My Shelf. 'Select all on page' checkbox selects all boxes across results shown.

### Related work

#685

**Comment by straleyb** [comment]
QA Fail. Verbiage off and check boxes dont check when "Select all on page" is clicked

**Comment by shieldsb** [comment]
QA pass.
