### ISSUE TITLE
Search Results: List View: Create 'Add to My Shelf' checkbox on each result

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#685]
### Descriptive summary

On Search Results, List View, create a 'Add to My Shelf' checkbox for each result listed. Place in top-right of result 'container'.

Wireframe mockup, List View: https://www.lucidchart.com/documents/edit/517560ad-afba-41c5-a2c5-d3ff2b16f2bf/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Each search result has a 'Add to My Shelf' checkbox. 

### Related work

#684

### Accessibility Concerns

Should probably be last in tab order for each search result.

**Comment by shieldsb** [comment]
QA fail.  'Add to My Shelf' checkbox for each result is in the bottom-right of the results container instead of placed in top-right of result 'container.'

**Comment by straleyb** [comment]
@CGillen I think you moved that to the bottom right correct? Due to it overlapping and interfering with titles. I'd propose we keep it at the bottom right for clarity sake. @kmthorn @shieldsb How do you feel about this proposition?

**Comment by CGillen** [comment]
Correct. Long work titles and collections with long titles + badges caused overlapping or bad reflow issues. Major +1 support for bottom right.

**Comment by straleyb** [comment]
I second that +1 support for bottom right as well. Especially for clarity and organizational reasons. It fits much nicer bottom right.

**Comment by raybrarian** [comment]
I think the decision to move for reflow was the correct one, and with no additional comments, I'm marking this as QA pass.
