### ISSUE TITLE
Search Results: Gallery View: Truncate long titles to 5 words

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#686]
### Descriptive summary

On Search Results, Gallery view, there isn't much width for long titles, so truncate those longer than 5 words.

Wireframe mockup, Gallery (or 'Grid') View: https://www.lucidchart.com/documents/edit/b536687b-3acd-4ac4-ad4e-638cde427a4f/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Titles are truncated at 5 words, with an ellipsis at the end.

### Related work

#681

**Comment by CGillen** [comment]
QA:
- [ ] Search results page gallery view: Title displays a maximum of 5 words

**Comment by raybrarian** [comment]
QA pass.
