### ISSUE TITLE
Search Results: Gallery View: Create 'Add to My Shelf' button, with 'Select all on page' checkbox below

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#688]
### Descriptive Summary

On Search Results, Gallery View, make a "Add to My Shelf" button to the right of the search box (see wireframe). Below that, add a checkbox for "Select all on page" that checks each result.

Wireframe mockup, Gallery (or 'Grid') View: https://www.lucidchart.com/documents/edit/b536687b-3acd-4ac4-ad4e-638cde427a4f/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Add to My Shelf button is similar to the one on the work show page but can add 1 or more works in results directly to My Shelf. 'Select all on page' checkbox selects all boxes across results shown.

### Related work

#684

**Comment by shieldsb** [comment]
QA pass. I have a few questions about the 'Select all on page" feature that isn't specifically addressed within this ticket.  

1. When you select all the items on the page or manually select individual items and then switch between gallery and list view, it does not retain those selections (if you haven't added them to the shelf, which we can't test yet).  Should we add that functionality? 

2. When you select all the items on the page or manually select individual items and then click over the other search results pages, it does not retain those selections (if you haven't added them to the shelf, which we can't test yet).  Should we add that functionality?

**Comment by straleyb** [comment]
Good questions. Functionally, im not entirely sure how we would retain the state of the check marks. We have access to the id's so we might be able to do some javascript magic to retain those checked boxes. 

Aside from that, i feel like keeping it more simple would be the way to go and not worry about it. Thats just my opinion though. We should make a new ticket, and label it "question" so we can make sure to discuss this.
