### ISSUE TITLE
Search Results: Gallery View: Create 'Add to My Shelf' checkbox on each result

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#689]
### Descriptive summary

On Search Results, Gallery View, create a 'Add to My Shelf' checkbox for each result listed. Place in top-right of result 'container'.

Wireframe mockup, Gallery (or 'Grid') View: https://www.lucidchart.com/documents/edit/b536687b-3acd-4ac4-ad4e-638cde427a4f/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Each search result has a 'Add to My Shelf' checkbox.

### Related work

#688

### Accessibility Concerns

Should probably be last in tab order for each search result.

**Comment by shieldsb** [comment]
QA fail. Wireframe has the 'Add to My Shelf' checkbox displayed under the icon for resource type. It is currently placed below the title.

**Comment by shieldsb** [comment]
QA pass.
