### ISSUE TITLE
Search Results: Gallery View: Result work title and field label <dt> class formatting match List View

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#690]
### Descriptive summary

On Search Results, Gallery View, the work title and metadata field labels do not have much formatting, and should match the List View styles (title is larger, field labels <dt> are bolded)

Wireframe mockup, Gallery (or 'Grid') View: https://www.lucidchart.com/documents/edit/b536687b-3acd-4ac4-ad4e-638cde427a4f/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Result work title and field label matches List View formatting as much as possible.

### Accessibility Concerns

Helps with consistency and overall appearance.

**Comment by CGillen** [comment]
Fixed by #723 and #724

**Comment by CGillen** [comment]
QA:
- [ ] Search results page gallery view: Title is larger than metadata
- [ ] Search results page gallery view: Metadata labels are bold and emphasized over data

**Comment by shieldsb** [comment]
QA pass.
