### ISSUE TITLE
Frontend work for Roles page

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#694]
### Descriptive summary

The roles page exists in hyrax but is... less than preferable. We need to work on making the page looking in line with the rest of the application. 

### INDEX

The index page should list the role NOT in a bulleted list. The roles should also not be links, because that is unhelpful. Instead, the Role should be listed, and next to the role should be "Edit" and "Delete" buttons. We may also want this page to 

### SHOW

The show page for a role doubles as the edit page. This doesnt make any sense. We can make a decision whether we want a show page for a role, but on the show page we could display the list of users associated with a role with links to their account show pages. We can also expose an edit and delete button on this page as well, but this will be a small page and we wont be displaying much information besides the name of the role and the users associated. 

### EDIT 

The edit page should contain two sections. One section is where you can edit the name of the role. NOTE: MAYBE WE DONT WANT TO ALLOW THE CHANGING OF THE "ADMIN" ROLE. On that same page we should allow the addition and removal of users from that role. Each user should have a button next to it that says "Remove" and somewhere there should be an autocomplete field which allows a user to search for other users. When one is selected, and "Add" is clicked, it adds the user to the role. 

### MOCKUPS

Currently we dont have any mockups for these pages. Maybe we want some mockups and maybe we dont. @kmthorn @mellinma do we want to create mockups for some of these pages? Or can we take some creative liberty on these as long as it aligns with OD2's current "style"

**Comment by raybrarian** [comment]
@straleyb - I'm seeing some differences between the description of the issue and the implementation. Could you add a comment with QA steps, including accessibility impacts, since this is a UI change? Thanks!

**Comment by straleyb** [comment]
QA:

- [ ] Index page should "look nice" with button to manage the role. Roles should exist in a table. Buttons should be aligned
- [ ] Edit page should "look nice" with users in a table and non bulleted. Action buttons should be aligned and should look organized

UNUSED PAGES: NEW, SHOW
UNUSED PAGES

**Comment by raybrarian** [comment]
QA questions for review:

1. CRITICAL: /roles is available to non-logged-in users, and allows access to manage users (including delete or add). I would expect that access would not be available globally.
2. From the description of the index page -  'the Role should be listed, and next to the role should be "Edit" and "Delete" buttons'. Currently the page uses a Manage button only. Is it still expected to delete roles from the index page?
3. I can add and remove users from each Roles page, but currently get no confirmation message. It shows up and is removed in the UI, but I can't tell if the UI is accurate (no way to look at my own profile and see my assigned roles, that I know of). Is that planned functionality?
4. Role edit page allows for editing or deleting the title of the role. My expectation is that I would not (either as an admin user or a non-logged-in user) be able to edit that value. I am able to edit that field (and all the other editable fields) without logging in. 
5. For UO and OSU users, would UO_user and OSU_user roles eventually be added automatically, when signing in the first time?

**Comment by straleyb** [comment]
1: This is because we have it opened completely. https://github.com/OregonDigital/OD2/pull/789 this would lock it down. This is due to testing purposes.

2. "Edit" and "delete" were not quite necessary at this moment. Im not sure we have had discussions about deleting roles, but I dont think its necessary. POSM should make this determination

3. POSM question. That would be "user show page info" updates

4. POSM question. I can lock them down now. Also, this is because I have it opened up for testing purposes.

5. Yes I believe so, but you should still have the option to add/remove users just in case

**Comment by raybrarian** [comment]
Confirming, post-standup discussion:
1. This functionality is currently open to the world to support dev QA and PM QA efforts, but will be locked down to authenticated admin users.
2. Edit and Delete were from an earlier draft. Manage is an acceptable solution for now, pending future review by POSM.
3. POSM will be asked about whether or not to show users' roles on their user "show" page.
4. The title field will be locked down - no need for POSM review.
5. Will be QA'd separately after a UO or OSU-authenticated user is deleted and returns as a new user.

QA pass on front-end changes.
