### ISSUE TITLE
Beeline upgrade causes NoMethodError

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#701]
### Descriptive summary
#677 Replaced rack-honeycomb with beeline-ruby, causing a namespacing issue.
https://github.com/OregonDigital/OD2/blob/master/app/controllers/application_controller.rb#L23-L24
needs to be reworked to `Honeycomb.add_field`

### Expected behavior
Staging stands back up without NoMethodErrors

### Related work
#677 

### Accessibility Concerns
None

**Comment by CGillen** [comment]
QA:
- [ ] Staging is back standing
- [ ] (@decimalator) Honeycomb version and classname fields are still tagged appropriately. Especially regarding environment.

**Comment by decimalator** [comment]
no events are making it to Honeycomb, so this needs looked at again

**Comment by CGillen** [comment]
@decimalator Since when? ~8/9 11AM or ~8/13 10AM or some other time?
And is it 0 events are making it to Honeycomb at all, or does your dashboard have a filter and that view isn't being populated?

**Comment by decimalator** [comment]
Looks good: https://ui.honeycomb.io/osulp/datasets/od2-rails-staging/result/73RAk5uVsCA
