### ISSUE TITLE
Single value Repository does not allow works to be saved

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#707]
### Descriptive summary
#649 Has caused the work edit form to break.
Hyrax does not know how to index deep metadata for fields that are single value. Specifically it assumes deep metadata is multivalue when it goes to fetch external labels: https://github.com/samvera/hyrax/blob/v2.5.0/app/indexers/hyrax/deep_indexing_service.rb#L32

### Expected behavior
Work edit form allows works to create/save.

### Related work
#649 
#462 

### Accessibility Concerns
None

**Comment by raybrarian** [comment]
@CGillen - logged in, and attempting to edit this work (Home-style biscuits): http://staging.oregondigital.org/concern/images/k0698748f?locale=en#?c=0&m=0&s=0&cv=0&xywh=-927%2C-114%2C4853%2C2222 and I still get the error message. I am able to edit this one: http://staging.oregondigital.org/concern/images/zw12z528p?locale=en#?c=0&m=0&s=0&cv=0&xywh=-451%2C-1%2C1860%2C640 - is the biscuits item just irrevocably broken? Do you have a test item I should be looking at, or does the Test for Institutional Restriction have the right metadata to be testing this fix?

**Comment by CGillen** [comment]
@raybrarian Your biscuits are toast and beyond repair.
Any other item that allows you to get to the work edit form (or creating a new one) should be enough to test. As I recall, the work did not need a Repository value, but adding one would be good for coverage.

**Comment by raybrarian** [comment]
QA pass - I can edit existing and save new works with URI repository values.
