### ISSUE TITLE
[1] Configure GenericWork to have a triple powered field.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#71]
### Descriptive summary

Here, we need to make sure to include all the objects in the proper places around the app and actually test if labels are being fetched, indexed, and viewable from the show page. 

https://github.com/osulp/Scholars-Archive/pull/564/files#diff-e11bdaf9116be3911e9557b69e242370
The objects that need files included can be found here and found by a simple ctrl-f look for `include`

Then after all the proper files have been included in the proper places, then you can ingest a work, input a uri such as http://id.loc.gov/authorities/subjects/sh85145447 in the form and it should display "water" as the label.

This will conclude the triplestore configuration and show that triple powered properties and the backend are all working properly. 

### Expected behavior

Generate a work with a uri in the proper field and it should display its label.

**Comment by wickr** [comment]
I'm not sure what this is doing in QA Testing, moving it back.

**Comment by vantuyls** [comment]
@straleyb is this still relevant given the other linked data issues that maybe be more granular?

**Comment by straleyb** [comment]
It may or may not be relevant depending on how we want to hook up the triplestore now. In order to get it to commit to the triplestore, we still have to do something similar to this, but we might be able to override some stuff in hyrax. They use marmotta, but we might be able to change that in config, which means we wouldnt have to do this. Id say we can close this and make a new ticket regarding figuring out how to tie in the triplestore in a more "hyraxy" way

**Comment by straleyb** [comment]
Fixed by #311
