### ISSUE TITLE
Model the work migration process

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#72]
### Descriptive summary

-  Establish a model of the processing steps for migrating a work from OD to OD2
- Should this be a separate Ruby gem, something that can be included to OD2 only while the migration is occurring.. and this gives the gem the ability to use models and hyrax functionality directly

**Comment by revgum** [comment]
Engine/gem repo for building out this functionality: https://github.com/OregonDigital/hyrax-migrator

**Comment by vantuyls** [comment]
@revgum is this still in progress? if so, do you intend to continue working on it in WorkCycle3?

**Comment by revgum** [comment]
I think the model has been established pretty well at this point.. we'll break down each step into tickets in its repo, so I don't thinks this issue is necessary anymore.
