### ISSUE TITLE
In gallery view, three-across tiling presents last row as full column width

### ISSUE THREAD

**Issue by raybrarian** [OregonDigital/OD2#726]
### Descriptive summary

Users expect three-across visual consistency for navigation of gallery results

### Expected behavior

Rows of three are maintained; additional items are either paginated on a different results list page, or are presented in the same column width as other gallery items, across browsers.

### Related work

*May* relate to #686. 

### Accessibility Concerns

None known.

See image attached from: http://staging.oregondigital.org/catalog?locale=en&page=2&q=&search_field=all_fields&sort=system_create_dtsi+asc&view=gallery

Fails the same way in Edge, Chrome, Firefox.

<img width="469" alt="gallery" src="https://user-images.githubusercontent.com/4460510/63179326-b4f50400-c000-11e9-8b09-91a264cab2a0.png">

**Comment by shieldsb** [comment]
See MAC design
