### ISSUE TITLE
Fix File Manager view

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#731]
### Descriptive summary

File manager currently doesn't work:

![image](https://user-images.githubusercontent.com/2157974/63277795-d4876900-c25a-11e9-8809-6f07a501c526.png)

### Expected behavior

I don't even know.  I've never seen the thing work!  I guess I'd like to see a page with files....

**Comment by jechols** [comment]
The naive fix (from @CGillen): override the view to "unwrap" the array - but convert to an array first just in case: `Array(node.label).join(', ')`

**Comment by CGillen** [comment]
QA:
- [ ] File manager page loads again. See below or this direct link: http://staging.oregondigital.org/concern/images/fq977t769/file_manager?locale=en

File manager link can be found on works with more than one file attached
![image](https://user-images.githubusercontent.com/11052958/63279301-9b042d00-c25d-11e9-80a1-5364b8da2407.png)

**Comment by raybrarian** [comment]
File manager link (button) is present for authenticated user and goes to File Manager interface:

![image](https://user-images.githubusercontent.com/4460510/63362206-5395a380-c326-11e9-9b7f-289e5ab940d0.png). 

Function is not present when unauthenticated. QA pass.
