### ISSUE TITLE
Homepage accessibility: search box button widget

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#740]
### Descriptive summary
The dropdown in the search box (pre-filter for 'all works,' 'osu content,' 'uo content,' etc) does not follow the ARIA [menu button pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#menubutton)

### Expected behavior
Searchbox dropdown has `aria-haspopup="true"` or `aria-haspopup="menu"` as per Aria menu button pattern.

### Related work
Audit from #697 

### Accessibility Concerns
Native widgets that act in a different way than their native HTML/Browser implementation are confusing when you can't see or understand any of the visual context provided (shape, CSS, dropdown arrow). Providing hints to screen readers helps to clue the user into what they're interacting with.

**Comment by raybrarian** [comment]
QA pass (10/30 deploy to staging):
![image](https://user-images.githubusercontent.com/4460510/67889869-de580300-fb0c-11e9-9658-b4696d8fe52c.png)
