### ISSUE TITLE
Homepage accessibility: search box button label

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#741]
### Descriptive summary
The dropdown in the search box (pre-filter for 'all works,' 'osu content,' 'uo content,' etc) does not provide a sufficiently descriptive label. Currently, the label is the default value "All." The label should describe the expected input.

### Expected behavior
Searchbox dropdown is labeled as 'collection,' 'scope,' 'filter,' or similar.

### Related work
Audit from #697

### Accessibility Concerns
Labels provide screen readers with hints to announce to the users what the purpose of a form element is. Without a label, the user is left to guess what the element is supposed to do by the context of the possible values (if a mediated field), previous elements, element type, and form function.

**Comment by CGillen** [comment]
QA:
- [ ] Search box pre-filter dropdown button has an aria-label of something similar to "Filter by"

**Comment by raybrarian** [comment]
@straleyb - could this be changed to "Filter results" instead of "Filter Search Dropdown"? Screen reader users don't need to know the input widget type in the label being read, just the function. Thanks!

**Comment by raybrarian** [comment]
@CGillen @straleyb - Moving this into WC8 to change the aria label to "Filter results by"

**Comment by raybrarian** [comment]
QA pass
