### ISSUE TITLE
Setup Role Creation

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#753]
### Descriptive summary

A rake task which generates all required roles in the system
- [ ] Depositor
- [ ] Collection Curator
- [ ] OSU Affiliate
- [ ] OSU User
- [ ] UO Affiliate
- [ ] UO User
- [ ] Community Affiliate
- [ ] Admin

**Comment by CGillen** [comment]
QA:
- [ ] Visit staging.uoregon.edu/roles and see the following roles exist
  - [ ] admin
  - [ ] collection_curator
  - [ ] depositor
  - [ ] osu_affiliate
  - [ ] osu_user
  - [ ] uo_affiliate
  - [ ] uo_user
  - [ ] community_affiliate

**Comment by raybrarian** [comment]
Roles are present. QA pass.
