### ISSUE TITLE
Set up an ability to create a work

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#754]
### Descriptive summary

This ability should be able to return a true value when viewing a certain users roles when that role allows for the creation of a work. Otherwise return false

Depositor, collection curator, and admins should be able to create works. 

`current_ability.can?(:create, solr_document)`

**Comment by straleyb** [comment]
QA is to cover permutations of line 7 (Create a Work) of permissions matrix:
https://docs.google.com/spreadsheets/d/1-Mk0CUBU3guGLDDFyuS2l6rIku5eZjnNVDMxH9HuqoM/edit#gid=0

Useful link: http://staging.oregondigital.org/roles

QA:
- [ ] An anonymous user can not access the create form for a work
- [ ] A logged in user without the Admin, Collection Curator, or Depositor role can not access the create form for a work
- [ ] A logged in user with the Depositor role can access the create form for a work
- [ ] A logged in user with the Admin or Collection Curator role can access the create form for a work

**Comment by shieldsb** [comment]
QA pass.
