### ISSUE TITLE
Ability to be able to search an item

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#755]
### Descriptive summary

This ability should check to see if a user can search items with the caveat that a UO authenticated user can search everything except OSU restricted items. 

`current_ability.can?(:search, solr_document)` which will look at the metadata for what institution it is restricted to. If no restrictions, then it should not filter that work out.

**Comment by CGillen** [comment]
QA:
When I search the catalog;

- As an authenticated user:
  - Without any roles:
    - [ ] I can find public works that have been reviewed
    - [ ] I cannot find public works, that have not been reviewed
    - [ ] I cannot find works that are not public
  - With A UO or OSU role:
    - [ ] I can find public works that have been reviewed
    - [ ] I can find OSU/UO (or) works that have been reviewed
    - [ ] I cannot find works that have not been reviewed
    - [ ] I cannot find works that have been embargoed, passed lease, or privated
  - With a community role
    - [ ] I can find public works that have been reviewed
    - [ ] I can find OSU & UO (and) works that have been reviewed
    - [ ] I cannot find works that have not been reviewed
    - [ ] I cannot find works that have been embargoed, passed lease, or privated
  - With a depositor role
    - [ ] I can find any work that has been reviewed
    - [ ] I can find works that have not been reviewed AND are in an admin set I deposit into
    - [ ] I cannot view any work that has not been reviewed AND is not in an admin set I deposit into
  - With a collection curator role
    - [ ] I can find any work that has been reviewed
    - [ ] I can find works that have not been reviewed AND are in an admin set I manage
    - [ ] I cannot find any work that has not been reviewed AND is not in an admin set I manage
- As an unauthenticated user:
  - [ ] I can find public works that have been reviewed
  - [ ] I cannot find public works, that have not been reviewed
  - [ ] I cannot find works that are not public

**Comment by shieldsb** [comment]
QA pass.
