### ISSUE TITLE
View an item

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#756]
### Descriptive summary

Exact same as #755

**Comment by CGillen** [comment]
QA is slightly different than the other abilities.
The term 'view' means to reach the work show page, NOT see the existence of. It is possible to not be able to 'view' a work and to know that it exists (ie. it shows in search results).

- [ ] Unauthenticated users can NOT view works restricted to Institution
- [ ] Authenticated users not in BOTH a UO and OSU related role can NOT view works restricted to Institution
- [ ] Authenticated users IN BOTH a UO and OSU related role CAN view works restricted to Institution

Final expected behaviour depends on #775. Once this passes QA, feel free to re-open with a note about #775 implementation.

**Comment by shieldsb** [comment]
QA pass, moving back to ready column for #775 implementation.

**Comment by CGillen** [comment]
QA:
- As an authenticated user:
  - Without any roles:
    - [ ] I can view public works that have been reviewed
    - [ ] I cannot view public works, that have not been reviewed
    - [ ] I cannot view works that are not public
  - With A UO or OSU role:
    - [ ] I can view public works that have been reviewed
    - [ ] I can view OSU/UO works that have been reviewed
    - [ ] I cannot view works that have not been reviewed
    - [ ] I cannot view works that have been embargoed, passed lease, or privated
  - With a community role
    - [ ] I can view public works that have been reviewed
    - [ ] I can view OSU & UO works that have been reviewed
    - [ ] I cannot view works that have not been reviewed
    - [ ] I cannot view works that have been embargoed, passed lease, or privated
  - With a depositor role
    - [ ] I can view any work that has been reviewed
    - [ ] I can view works that have not been reviewed AND are in an admin set I deposit into
    - [ ] I cannot view any work that has not been reviewed AND is not in an admin set I deposit into
  - With a collection curator role
    - [ ] I can view any work that has been reviewed
    - [ ] I can view works that have not been reviewed AND are in an admin set I manage
    - [ ] I cannot view any work that has not been reviewed AND is not in an admin set I manage
- As an unauthenticated user:
  - [ ] I can view public works that have been reviewed
  - [ ] I cannot view public works, that have not been reviewed
  - [ ] I cannot view works that are not public

**Comment by shieldsb** [comment]
QA fail.  Some observations: 

As an authenticated user w/o any roles:
- The work restricted by institution for OSU is in search results but not viewable
- The work restricted by institution for UO does not appear in search results 
- I can view an embargoed OSU work (embargo is set to expire 10/23/2019) 
- When I view the "TEST - post-rollback to 10/9" work, the yellow review and approve banner appears and I can click on it to receive the option to comment or request changes (the same is also true when any other role is applied) 

As osu_user or osu affiliate: 
-  I can view an embargoed work

As uo-user or uo affiliate: 
-  I can view an OSU work that has an embargo

As a community affiliate
-  I can view works restricted by institution for both OSU and UO
-  I can view an OSU work that has an embargo

As a depositor:
-  I can view it works restricted by institution for both OSU and UO
-  I cannot view works I have deposited that have not been reviewed (tested before and after being added as a depositor for the collection) 

As a collection curator:
-  I can view works restricted by institution for both OSU and UO
-  I cannot view items in collections I manage that have not been reviewed

**Comment by CGillen** [comment]
@shieldsb So I can debug this, https://staging.oregondigital.org/admin/admin_sets/p8418n20k/edit?locale=en#participants were you added to this admin set before the OSU work you're testing on was deposited? That would probably explain all the odd behavior with specifically OSU works, but it exposes more fragility.

Unfortunately, the matrix asked for checking if a user is a depositor in a _Collection_ but Hyrax is very opinionated on _Admin Sets_ for permissions. So, double checking if you added yourself as depositor to the admin set or collection for your 'not reviewed and in admin set I manage/deposit' test.

**Comment by shieldsb** [comment]
QA Round 2:
- As an authenticated user:
  - Without any roles:
    - [ ] I can view public works that have been reviewed
    - [ ] I cannot view public works, that have not been reviewed
    - [ ] I cannot view works that are not public
  - With A UO or OSU role:
    - [ ] I can view public works that have been reviewed
    - [ ] I can view OSU/UO works that have been reviewed
    - [ ] I cannot view works that have not been reviewed
    - [ ] I cannot view works that have been embargoed, passed lease, or privated
  - With a community role
    - [ ] I can view public works that have been reviewed
    - [ ] I can view OSU & UO works that have been reviewed
    - [ ] I cannot view works that have not been reviewed
    - [ ] I cannot view works that have been embargoed, passed lease, or privated
  - With a depositor role
    - [ ] I can view any work that has been reviewed
    - [ ] I can view works that have not been reviewed AND are in an admin set I deposit into
    - [ ] I cannot view any work that has not been reviewed AND is not in an admin set I deposit into
  - With a collection curator role
    - [ ] I can view any work that has been reviewed
    - [ ] I can view works that have not been reviewed AND are in an admin set I manage
    - [ ] I cannot view any work that has not been reviewed AND is not in an admin set I manage
- As an unauthenticated user:
  - [ ] I can view public works that have been reviewed
  - [ ] I cannot view public works, that have not been reviewed
  - [ ] I cannot view works that are not public

**Comment by CGillen** [comment]
Hrm... I'm having a hard time replicating these issues. I've put my notes in bold and added my reproduction steps. Let me know if I'm off-base.

OSU role: I can view works restricted to UO
UO role: I can view works restricted to OSU
**I cannot replicate this locally or on staging.**
1. Create user A
1. As user A: be given uo_user role
1. As user B (Existing admin): find OSU and UO restricted work
1. As user A: visit OSU and UO restricted work from previous urls.
1. As user A: OSU work gets `Unauthorized`, UO work is fully visible.

Depositor: 
- I could not view works I deposited that had not been reviewed
**View or search? unreviewed works will never appear in catalogue search. The page you are dumped to after deposit is the view page, was that `Unauthorized` or `not available at this time`?**
- I can view works that have been reviewed, but are restricted to UO (and are in collections/admin sets that I do not have permissions to)
**working as intended**

Collection Curator: 
- I could not view works I that have not been reviewed but are in admin sets/collections I manage
**Same as above**
1. As user A: have all previous roles removed
1. As user A: be added to admin set as manager
1. As user A: be given collection_curator role
1. As user B (Existing admin): deposit work to admin set, any visibility
1. As user A: visit newly deposited work page, do not receive `Unauthorized` or `not available at this time`

- I can view works that have been reviewed, but are restricted to UO (and are in collections/admin sets that I do not manage)
**working as intended**

Community role:
- I can view works that are restricted to either OSU or UO 
**working as intended**

**Comment by CGillen** [comment]
#839 Removed the community_affiliate role, this has not been deployed to staging until the footer changes from `Oregon Digital WC3-0.0.1-20191023165215-32aab30`. I don't want to force the removal because some of the code may still be looking for it.

Other than that, assuming that role doesn't have any bearing in the above QA, I think we just need to confirm Depositors should be able to view restricted works.

**Comment by CGillen** [comment]
Changes to depositor and collection_curator QA:
  - With a depositor role
    - [ ] I can view **public** works that has been reviewed
    - [ ] I can view **UO/OSU works** that have been reviewed **IF I am a user/affiliate of that institution**
    - [ ] I can view works **that I deposited** that have not been reviewed AND are in an admin set I deposit into
    - [ ] I cannot view any work that has not been reviewed AND is not in an admin set I deposit into
  - With a collection curator role
    - [ ] I can view **public, embargoed, and pass lease** works that has been reviewed
    - [ ] I can view **UO/OSU works** that have been reviewed **IF I am a user/affiliate of that institution**
    - [ ] I can view works that have not been reviewed AND are in an admin set I manage
    - [ ] I cannot view any work that has not been reviewed AND is not in an admin set I manage

**Comment by shieldsb** [comment]
QA pass.
