### ISSUE TITLE
Editing an item

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#757]
### Descriptive summary

Check to see if a user is an admin or collection curator, they can edit anything. 

If the user is a depositor, they can only edit THEIR deposited items. 

Otherwise, no editing.

**Comment by CGillen** [comment]
QA is to cover permutations of lines 10 and 11 (Edit any and my works) of permissions matrix:
https://docs.google.com/spreadsheets/d/1-Mk0CUBU3guGLDDFyuS2l6rIku5eZjnNVDMxH9HuqoM/edit#gid=0

Useful link: http://staging.oregondigital.org/roles

QA:
- [ ] An anonymous user can not access the edit form for an existing work
- [ ] A logged in user without the Admin, Collection Curator, or Depositor role can not access the edit form for an existing work
- [ ] A logged in user with the Depositor role can access the edit form for only their works
- [ ] A logged in user with the Admin or Collection Curator role can access the edit form for any work

**Comment by shieldsb** [comment]
QA pass.
