### ISSUE TITLE
Delete an item

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#758]
### Descriptive summary

Only collection curators and admins can delete items. No other roles should be allowed to delete items.

**Comment by CGillen** [comment]
QA is to cover permutations of lines 12 (Delete works) of permissions matrix:
https://docs.google.com/spreadsheets/d/1-Mk0CUBU3guGLDDFyuS2l6rIku5eZjnNVDMxH9HuqoM/edit#gid=0

Useful link: http://staging.oregondigital.org/roles

QA:
- [ ] An anonymous user can not delete an existing work
- [ ] A logged in user without the Admin, or Collection Curator role can not delete an existing work
- [ ] A logged in user with the Admin or Collection Curator role can delete any work

**Comment by shieldsb** [comment]
QA pass.
