### ISSUE TITLE
Download Low Res

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#759]
### Descriptive summary

Verify anyone can download low res.

**Comment by CGillen** [comment]
QA:
While QA'ing, a low-res download is identified by the download url ending in `/download_low`. We do not have actual low-res downloads working yet.
High-res are urls ending in `/download`

- As an unauthenticated user
  - [ ] I can download low-res version of any work
- As an authenticated user
  - Without any roles or community role
    - [ ] I can download low-res version of any work
  - With UO or OSU role
    - [ ] I can download high-res version of any work. Restriction for specific admin sets to come when we have set admin sets.
  - With depositor, collection_curator, or admin role
    - [ ] I can download high-res version of any work
