### ISSUE TITLE
Admin Dashboard view of oEmbed enabled items

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#76]
### Descriptive summary

Admins and staff should be able to easily see only all works that have an oEmbed URL included.

### Expected behavior

An Admin Dashboard view can show which works have an oEmbed URL included.

### Related work

#75 Initial configuration of oEmbed

**Comment by vantuyls** [comment]
Probably best to follow current hyrax design for admin dashboard menu and pages. as an initial mockup, this page can show all works with oEmbed URL and the status of the oEmbed in a table similar in design to what is on the Manage Embargoes page.

@wickr can you clarify what content belongs in that table? I'm assuming at least these:
Work Title
Work URI
oEmbed Link
oEmbed Status

**Comment by CGillen** [comment]
@wickr @vantuyls I'm noticing that `/dashboard/works` and `/dashboard/my/works` already has a dashboard that can be limited by facets. If we can add an oEmbed: yes/no facet to that list, would that be a suitable substitute? Adding oEmbed Status to that table would be a little weird, but maybe not egregious.

Otherwise, I'll look into adding a new dashboard under 'Manage Leases' as previously proposed.

**Comment by vantuyls** [comment]
i suspect a new page beneath Manage Leases makes more sense. This is a specific type of management, in the same vein as managing embargoes and managing leases. @wickr @jsimic @petersec thoughts?

**Comment by petersec** [comment]
I think that would be ideal. Right now, OSU/SCARC has over 1,300 items in OSU MediaSpace, and that number will only continue to grow. If all of that is eventually moved over to OD, we would want to have as many tools as possible to manage the content.

**Comment by vantuyls** [comment]
as a clarification @petersec - are we hoping to move all of our mediaspace content into OD directly as part of the OD -> OD2 migration? It will be important to know this for the Migration team (cc @revgum )

**Comment by jsimic** [comment]
I agree with @vantuyls and @petersec, make it simple.

**Comment by petersec** [comment]
Sorry @vantuyls @revgum -- I didn't mean to imply any mediaspace migration as part of the OD2 process. Just thinking long-term and presuming that it's something that we will eventually want to do to centralize more of our content.
