### ISSUE TITLE
Permissions to Review Works

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#761]
### Descriptive summary

Admins can review all works, Collection curators can review only deposits to collections they own.

**Comment by straleyb** [comment]
QA:

- [ ] Login as an admin, submit a work, and it should be reviewable

- [ ] Login as a collection curator, verify you have the approval workflow role, create a work in a collection (relationships tab add to collection), you SHOULD NOT be able to review it since it is your own work.

- [ ] Login as a depositor, verify you have the depositor workflow role, create a work in a collection, you SHOULD NOT be able to review it

- [ ] Log back in as a collection curator, find the depositor's work and you SHOULD be able to review it.

**Comment by straleyb** [comment]
If there are any questions about QA on this, please let me know. 

There is a nuance with Hyrax that a user that gets added as a manager to a workflow CANNOT review works that are in review that existed BEFORE the user was added as a manager. This is a serious oddity in hyrax and needs to be made very obvious for people. So make sure your test collection_curators already exist and are added to the admin set and collection as a manager BEFORE the works are created and added to their respective admin_set and collection.

**Comment by shieldsb** [comment]
QA fail for last item.  

Steps taken:  When creating OSU test collection 3, I added my self as manager and depositor to the collection before creating any works.  Then I followed the steps above.  When I logged back in as collection curator on the last step,  I was not able to review the work submitted as a depositor titled "OSU test 008."

**Comment by shieldsb** [comment]
QA pass.  

The issue with new collection curators/managers not being able to review works that are in review status prior to their designation as a manager is limiting.
