### ISSUE TITLE
Clean up 'No Results Found' text/links on empty search result

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#763]
### Descriptive summary

The text displayed when there's no search results returned ( http://staging.oregondigital.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q=blahblah ) could use some clean up.

Especially the last part "you searched by All Fields - try searching everything" which can probably just be removed. 'searching everything' link wouldn't make sense since 'All Fields' is designed to do that. This goes to a search link hitting the 'contained_in_journal' field.

Also phrasing mismatch with "No entries found" and "No results found..."

### Expected behavior

When no search results are found, helpful tips and other options are displayed.

**Comment by mellinma** [comment]
Follow MAC design.  Review language and consider adding search tips (either on the page or on an external "search tips" page)

**Comment by CGillen** [comment]
Fixed by #2869

**Comment by shieldsb** [comment]
QA pass
