### ISSUE TITLE
Error handling for oEmbed viewers

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#77]
### Descriptive summary

If a work has an oEmbed URL, and the viewer fails to load on the show page, that should be recorded and logged for troubleshooting. Possible reasons are that the source site is down, permissions changed on the media, or it was removed.

### Expected behavior

- [x] Admin Dashboard shows all oEmbed errors, sorted by most recent, and what those errors were.
- [x] Provide a way to mark errors as resolved.
- [ ] Send email to depositor of work with oEmbed URL notifying about error.

### Related work

#75 
#76

**Comment by vantuyls** [comment]
@wickr is there QA required for this?

**Comment by CGillen** [comment]
QA:
- [ ] Errors dashboard makes sense and is usable as expected from maintainer's perspective.
- [ ] Email is sent to depositor on error (or is attempted until emails work).
