### ISSUE TITLE
Configure IIIF Manifest Metadata

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#778]
### Descriptive summary

Configure the metadata to include in the IIIF Manifest. A new column was added to the MAP for this. Need to double check if expectation is fields have predicates and use DC Terms (like OAI) or if they're more open.

### Expected behavior

Selected metadata appears in the IIIF Manifest.
This will also mean it displays in the "More Information" right-hand panel of Universal Viewer.

### Related work

#617

**Comment by CGillen** [comment]
@sseymore Review for MAP freeze. Once frozen, add features and ready for development tag

**Comment by CGillen** [comment]
QA: Read [MAP](https://docs.google.com/spreadsheets/d/1ien3djlZxcctuAE99XweyuNdMiN5YsrKoYBJcK3DjLQ/edit#gid=2011906483) for IIIF Manifest Metadata and compare UV metadata display of a fully populated work (bacon)

**Comment by sseymore** [comment]
Hold QA on this until we can review IIIF manifest on MAP-- team goal for WC17

**Comment by sseymore** [comment]
QA fail-- just listing some changes after the metadata team reviewed the manifest. MAP updated. 

- Add Use Restrictions
- Remove Extent, Format, and Format Label
- Description is duplicated at bottom of viewer

**Comment by straleyb** [comment]
Quick pull out of metadata from the manifest.
