### ISSUE TITLE
Explore best path to override Hyrax visibility

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#780]
### Descriptive summary
This is a ticket to document the process from #775 so far.
Only a handful of of files need to be overridden to give us the ability to add a visibility to the work form.

It's unpredictable what will happen if a code path is hit that doesn't understand our new visibilities. Our expectation is either an exception or defaulting to higher protection, but it is up to the individual implementation.

Our overrides so far upset Rubocop greatly, and is not very sustainable as they are full file overrides for systems that may have impacts by Valkyrie. We are still exploring ways to lessen our technical debt and override burden.

### Expected behavior
Two new visibilities are available for UO and OSU restricted. Institution restriction is removed from the form but left dangling in the system.

### Related work
#775 

### Accessibility Concerns
Badge and label displays may not be a distinctive color, and various displays may break.

**Comment by CGillen** [comment]
QA:
- [ ] Work create/edit form includes two new visibilities
  - [ ] `Oregon State University`
  - [ ] `University of Oregon`
- [ ] `Institution` visibility is removed from Work create/edit form
- [ ] Visibility badges for admins reflect the new visibility settings
- [ ] Collection and admin set visibility settings are not busted

**Comment by shieldsb** [comment]
QA pass.
