### ISSUE TITLE
workType property is defined twice in GenericMetadata

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#781]
### Descriptive summary

@luisgreg99 noticed in https://github.com/OregonDigital/hyrax-migrator/issues/144 that `workType` property is defined twice in Generic Metadata.

### Expected behavior

`workType` property is only defined once. Includes CV declaration.

### Related work

#422 

### Accessibility Concerns

None.

**Comment by wickr** [comment]
QA: just confirm workType is defined only once in https://github.com/OregonDigital/OD2/blob/master/app/models/concerns/oregon_digital/generic_metadata.rb

**Comment by shieldsb** [comment]
QA pass
