### ISSUE TITLE
Apply UO or OSU role on omniauth login

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#798]
### Descriptive summary
Users that login through institutional login should automatically be added to their institutional user role group. This will give them access to institution restricted works.

### Expected behavior
OSU CAS authenticated user is added to osu_user role
UO SAML authenticated user is added to uo_user role

**Comment by CGillen** [comment]
QA:
- [ ] Logging in through OSU cas, I find myself in this list of users: https://staging.oregondigital.org/roles/5/edit
- [ ] Logging in through UO saml, I find myself in this list of users: https://staging.oregondigital.org/roles/7/edit
- [ ] Logging in through community login, I find myself in neither of the previous lists

**Comment by shieldsb** [comment]
QA fail.  OSU log in did not automatically add me to the osu_user role.  Do I need a separate account for the community log in? Trying it with OSU credentials gives me an error message.

**Comment by raybrarian** [comment]
QA fail: removed myself as a user from /roles. Logged back in - now can see the works I'd created, but /roles does not recognize me as a UO-affiliated user.

**Comment by raybrarian** [comment]
Update: QA pass for users in UO/OSU, but I'm getting the "ack" broken message when trying to login as a community user. @CGillen - want me to ticket that separately?

**Comment by CGillen** [comment]
@raybrarian Yeah, go ahead and open a bug. I'm not sure what exactly might be causing that and it may or may not be this.

**Comment by raybrarian** [comment]
QA pass
