### ISSUE TITLE
See that https://github.com/samvera/hydra-editor/pull/181 is pushed through hyrax

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#813]
### Descriptive summary

From what I could see, a large portion of the hyrax community is unaware of the issue regarding simple form. When I tried to update simpleform, it was actually pinned to a specific hydra editor version. This, in turn was pinned to active fedora versions and other small oddities. 

There has been work done regarding this fix in hydra-editor, but this needs to be pushed through hyrax asap.

**Comment by raybrarian** [comment]
https://github.com/samvera/hydra-editor/releases/tag/v5.0.1 - documenting fix merged last night

**Comment by straleyb** [comment]
In the meantime, during dev congress, the backport is being done. Once that is released, ill bump to the newer version of hyrax 2.x and we can close.

**Comment by straleyb** [comment]
Hyrax PR: https://github.com/samvera/hyrax/pull/4120

**Comment by straleyb** [comment]
QA pass if #843 pass

**Comment by raybrarian** [comment]
FYI: Sending #843 back to Ready - can't add an image in the admin dashboard.
