### ISSUE TITLE
Discuss: refresh staging regularly?

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#815]
### Descriptive summary

@raybrarian and I were discussing this - it might be good to help ensure our infrastructure is always ready to deploy if we refresh staging on a regular basis.  As in, fully destroy all data, k8s images, and rebuild it all.

If this is a burden, we need to figure out why, and make sure all non-automatable pieces are very well documented.

Update: this doesn't mean a data refresh mid-work-cycle, because that would likely be extremely disruptive to QA as well as devs (and possible demo needs for stakeholders).  And it's not something we're in a position to do yet.  My hope was more on the lines of a planned pre-work-cycle refresh that we only implement once we've got a system in place that can fully automate setting up staging seed data.  This way there are no surprises, and for QA (or really anybody), data can be added or totally wrecked when testing something without the QAer having to then delete and recreate (or ask a dev to remigrate).

**Comment by straleyb** [comment]
Staging gets auto-deployed

**Comment by jechols** [comment]
@straleyb Unless I'm extremely confused here, the auto-deploy doesn't do anything we were considering here, particularly destroying the data.  And in fact, if it did, that would be very bad.

**Comment by straleyb** [comment]
@jechols Exactly why im thinking, if the auto-deploy is just deploying the new code and keeping it up to date, then everything else is not needed. We dont want to do any of that destruction since our prod deploy should be the same as our staging.

**Comment by jechols** [comment]
This is to discuss specifically the fact that we (@raybrarian and I) thought it would be useful to have a full refresh of data so that staging "starts fresh" on a regular basis.  This allows people to QA stuff and ruin data as needed for testing without having to manually rebuild it, or delete and reingest manually.

If we can do a full tear-down of infrastructure, it also tests out our DR strategy.

To be clear, this is a discussion for the group, so it probably shouldn't be closed until we've had time to actually discuss it.  Possibly at the next quarterly - maybe I'm not making enough sense in plain text.

**Comment by straleyb** [comment]
Sure thats fine. I just don't want to lose sight of it. I thought we had discussions about "starting fresh" at any point in time. Especially since we are migrating works and stuff. Doesn't seem to make sense to blow away those migrations. 

@luisgreg99 @CGillen @raybrarian Any other opinions on this? Lets start a discussion and maybe we can figure it out sooner rather than later.

**Comment by jechols** [comment]
Oh, I think you're thinking of a different thing!  We had a discussion about doing a data refresh mid-sprint, but that was due to some infra problem that I believe @decimalator either fixed or worked around.  No, this was for a more planned data refresh, such as at the end (or beginning) of a new work cycle.

I'll update the description; that's not very clear.

**Comment by CGillen** [comment]
Discussions happen when they need to. We never circled back to this ticket in time
