### ISSUE TITLE
PMOP proposal / documentation: storage options for original files

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#83]
PMOP needs a general recommendation for how we store our large content files: things like an image's raw TIFF, an uncompressed AVI file, etc.

**Comment by jechols** [comment]
Details: I brought up to the group the idea of using glacier for the original TIFFs and other huge images.  It could save us a lot if we don't have to provide direct, immediate access to those source files.  It sounds unlikely to save us enough to be worth the extra work, but I need to write something up with pros/cons, costs (ballpark), etc.

**Comment by jechols** [comment]
https://docs.google.com/document/d/14CyphtohOQaIPUiR7tG_U6qlyGmXv-Or5i4JJgpZ2_Y/edit#

**Comment by jechols** [comment]
The documented options were reviewed and decisions were made, so I'm closing this

**Comment by jechols** [comment]
Actually I'm thinking of a different document, I think (whether to put derivatives on S3, on which a decision was indeed made).  Reopening.

@vantuyls do you know if a decision was made here?

**Comment by vantuyls** [comment]
@raybrarian @kmthorn @mellinma (i don't see Franny here) - thoughts on this decision having been made by PMOP and where we're collecting the results of these decisions?

**Comment by raybrarian** [comment]
@kmthorn @vantuyls @mfgaede @mellinma 

Decision made on S3 - reviewed in PMOP meeting from this doc: [https://docs.google.com/document/d/1p6CeQ57MiB3ZnnOMJMXu799kxf3RYepxVXNIVBrntZk/edit?usp=sharing] Which was linked from Nov. 9 meeting under **infrastructure decisions**. No decision made on this issue though - I'm not sure this got over to PMOP. Will link the gdoc shared in this issue and the issue to the PMOP agenda for 12/21.

I'm assuming the best place to collect the decisions is to document them in the GH issue, then close it?

**Comment by jechols** [comment]
@raybrarian Good question - we should document here for the sake of completeness, IMO, but closed issues tend to get lost, so it might be good to document somewhere else as well.  I don't know where PMOP's documented decisions belong, but maybe just google drive...?

**Comment by mccallum** [comment]
I think non-public to Google Drive, yes. I'd like to see stuff that is helpful to users/public of any level of expertise find its way to something easy to edit. https://oregondigital.gitbook.io/style-guide/changelog  or the github wiki (though I like to look of gitbook)

**Comment by raybrarian** [comment]
Decision in PMOP meeting - use S3-IA for original files. This decision (and the other infrastructure decisions) will go in a doc in the Gdrive PMOP folder, both to keep track and for reporting out.
