### ISSUE TITLE
is part of: metadata not displaying consistently between results and show page

### ISSUE THREAD

**Issue by raybrarian** [OregonDigital/OD2#833]
### Descriptive summary

is part of metadata field should show the same metadata in brief results and on the show page. Currently the search results show collection(s) title(s):
![image](https://user-images.githubusercontent.com/4460510/67421717-eef50000-f585-11e9-935f-38dc61ddf120.png)

But the work show page shows the admin set:
![image](https://user-images.githubusercontent.com/4460510/67421800-12b84600-f586-11e9-8974-c88550495eaa.png)

### Expected behavior
Wherever the label "is part of" appears, that the same information is conveyed. For end-users, it makes more sense that "is part of" identifies set membership, not which workflow is being used. Maybe that means that specific metadata field is not displayed in the show page? Or the label in search results is changed to "Collection(s):"?

### Accessibility Concerns

No additional concerns.

**Comment by straleyb** [comment]
Is this still an issue?

**Comment by CGillen** [comment]
will be or has been fixed by wireframes
