### ISSUE TITLE
Attempting to create user with institutional email gives error message

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#834]
### Descriptive summary
The error message is:
`Not found. Authentication passthru.`

After work done on #749, attempting to create a user with a university email no longer redirects the user to their campus' auth solution. This is because the redirect has the user GET to the url and there's only a POST route.

### Expected behavior
Attempting to create a user with a university email ~redirects them to their university's auth page~ presents the user with an error and nudges them to institutional auth.

### Related work
#749 

### Accessibility Concerns
None

**Comment by CGillen** [comment]
QA: After footer changes from `Oregon Digital WC3-0.0.1-20191023165215-32aab30`
- Attempting to create account with following emails returns user to sign-up page and provides a decent explanation of what to do
  - [ ] `@oregonstate.edu`
  - [ ] `@orst.edu`
  - [ ] `@uoregon.edu`

**Comment by shieldsb** [comment]
QA pass.  We could refer login to the top of the page, instead of adding the link below, but this functions as expected.
