### ISSUE TITLE
Upgrade to hyrax 2.6

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#843]
### Descriptive summary

Hyrax 2.6 contains the fixes for hydra-editor and simple_form. Ill be upgrading.

**Comment by straleyb** [comment]
QA: Verify ingest still works. @luisgreg99 Said he would try and migrate or ingest?

**Comment by raybrarian** [comment]
Can also QA adding items/collections through UI- need to do that before QA pass.

**Comment by luisgreg99** [comment]
I did a migration test (via the console) with this hyrax version, and it worked well. For my local test, I had the chance to test it against the new solr 8.3 coming in #878. I only saw a deprecation message https://github.com/OregonDigital/OD2/issues/885 that got resolved with https://github.com/OregonDigital/OD2/pull/886.

**Comment by raybrarian** [comment]
QA fail - Can't upload images through the form:
![image](https://user-images.githubusercontent.com/4460510/70452910-c012ea80-1a5c-11ea-933a-181281c2447a.png)

I tried .png and .jpg - can try other formats if needed.

**Comment by CGillen** [comment]
This was a misconfiguration on staging from #870 updating FITS.
@raybrarian @shieldsb I've updated staging and QA can restart.

**Comment by shieldsb** [comment]
QA pass.
