### ISSUE TITLE
Removing or disabling users

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#844]
### Descriptive summary
While attempting to remove a user directly from the DB I was presented with Foreign Key Violation on the uploaded_files table (below). This means that once a user uploads a file, most likely while depositing a work, they become difficult or troublesome to scrub from the system. It's probable we don't want to ever fully delete a user for logging reasons, but it brought up the question of disabling a user or tracing their past actions.

For instance, if we have a community user login to deposit works, would we want to close their account after they are done? We probably want to keep the records of who they were and what actions they did, so we don't want to fully delete the user, but we might want to stop them from logging in all-together, or we might be fine with just revoking their permissions.

```
> User.find_by_email('rayh@uoregon.edu').delete
D, [2019-10-28T16:23:04.540337 #36585] DEBUG -- :   User Load (1.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "rayh@uoregon.edu"], ["LIMIT", 1]]
D, [2019-10-28T16:23:04.546319 #36585] DEBUG -- :   SQL (3.5ms)  DELETE FROM "users" WHERE "users"."id" = $1  [["id", 8]]
Traceback (most recent call last):
        1: from (irb):4
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_ece9dfb06e" on table "uploaded_files")
DETAIL:  Key (id)=(8) is still referenced from table "uploaded_files".
: DELETE FROM "users" WHERE "users"."id" = $1
```

### Expected behavior
This is a decision point for POSM to review, whether we want users to be delete-able, disable-able, or just settle on revoking permissions. Specifically users who have uploaded a file (most likely through depositing a work), others, like spam accounts, can probably be cleaned up.

### Related work
Possibly related documentation from Devise: https://github.com/plataformatec/devise/wiki/How-To%3a-Customize-user-account-status-validation-when-logging-in

**Comment by kmthorn** [comment]
If possible add a way to disable any individual users in the admin dashboard. Disabling means the account is prevented from logging in. 

Community users with no workflows should be able to be deleted through the admin UI by admins.

Disabling can only be done by admins via the admin dashboard.

We do not plan on deleting institutional users or people with deposited works or other workflows.

**Comment by mellinma** [comment]
Corey is writing new ticket to make a button for admins to disable users
