### ISSUE TITLE
For community users send verification e-mail on sign up

### ISSUE THREAD

**Issue by kmthorn** [OregonDigital/OD2#848]
### Descriptive summary

Adding this feature helps reduce the number of spam email accounts. 

### Expected behavior

When a community user hits sign up with a valid email address they are sent a confirmation e-mail and presented with the message below.  The message should read:

"Thank you! You will be getting a confirmation e-mail. You will be prompted to click a link and then you will be able to log into Oregon Digital."

### Accessibility Concerns

If there is a UI change then it needs to remain accessible.

**Comment by CGillen** [comment]
QA:
- [ ] Set up a new user with a valid email
- [ ] User may not authenticate
- [ ] Receive an email at email address containing confirmation actionable
- [ ] Confirmation link directs to some welcoming Oregon Digital page
- [ ] User may authenticate

**Comment by raybrarian** [comment]
QA fail - trying to add a new user from https://staging.oregondigital.org/users/sign_up?locale=en results in the default Ack! message. Logging in as UO-affiliated works as expected.

**Comment by CGillen** [comment]
Error message from kube logs
```
I, [2019-12-12T15:05:07.369829 #66]  INFO -- : [3d186e741b074aa0848650b1798be22a] Completed 500 Internal Server Error in 172ms (ActiveRecord: 0.8ms)
F, [2019-12-12T15:05:07.371556 #66] FATAL -- : [3d186e741b074aa0848650b1798be22a]
F, [2019-12-12T15:05:07.371836 #66] FATAL -- : [3d186e741b074aa0848650b1798be22a] NameError (undefined local variable or method `confirmed_at' for #<User:0x00007f21ae01e268>
Did you mean?  confirmed?):
F, [2019-12-12T15:05:07.371868 #66] FATAL -- : [3d186e741b074aa0848650b1798be22a]
F, [2019-12-12T15:05:07.371905 #66] FATAL -- : [3d186e741b074aa0848650b1798be22a] activemodel (5.1.7) lib/active_model/attribute_methods.rb:432:in `method_missing'
[3d186e741b074aa0848650b1798be22a] devise (4.7.1) lib/devise/models/confirmable.rb:107:in `confirmed?'
[3d186e741b074aa0848650b1798be22a] devise (4.7.1) lib/devise/models/confirmable.rb:188:in `confirmation_required?'
...
```

**Comment by straleyb** [comment]
So I think this is due to the user being created before this was in. I just tested a new user logged in through the guest login and I received the email properly, verified and logged in. 

@raybrarian Can you try that? generate a NEW user with a new email and go through the steps to login with verification email. NOTE: the verification email take a minute.... or 5.

**Comment by raybrarian** [comment]
QA pass.

**Comment by straleyb** [comment]
Closing because QA pass
