### ISSUE TITLE
Search Results: Metadata fields: Add Hit Highlighting

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#849]
### Descriptive summary

Add search keyword hit highlighting to help represent relevance and why search results are returned.

https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#highlight

### Expected behavior

For only the following fields: 

* Title is highlighted with any search result hits.
* (IF HIT MATCHES) Description is displayed, in the context of a hit.
* (ONLY IF NO HIT IN DESCRIPTION) Full Text is displayed around the context of a hit.

### Related work

#850 
#851

### Accessibility Concerns

Add any appropriate markup to signify the highlighted keyword in context.

**Comment by CGillen** [comment]
QA:
- [ ] Titles of search results is highlighted when search term is present in title
- [ ] Description is displayed ONLY if there is a hit highlight in it
- [ ] Full Text is displayed and Description is not displayed ONLY if there is a hit highlight in full text (Requires a reindex/resave of a work)

**Comment by shieldsb** [comment]
QA pass.
