### ISSUE TITLE
Search Results: List View: Metadata fields further update

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#850]
### Descriptive summary

We want relevant and appropriate metadata fields to show up in search results.

### Expected behavior

Show below Title:

* Creator(s)
* Date
* (if keyword hit in Description) Description
* (if NOT keyword hit in Description, AND keyword hit in Full Text) Full Text
* Resource Type (with icon)

(display either Description or Full Text, but not both at same time)

All other fields should not be displayed in List View.

### Related work

#683 

### Accessibility Concerns

Have appropriate markup and attributes to represent the page structure.

**Comment by CGillen** [comment]
Can get most of the way there, but blocked by full text extraction and indexing.
#1055

**Comment by CGillen** [comment]
QA:
@sseymore Please QA or ask someone from metadata to fill in.
Only in the context of the list view
- [ ] Titles of search results is highlighted when search term is present in title
- [ ] Description is displayed ONLY if there is a hit highlight in it
- [ ] Full Text is displayed and Description is not displayed ONLY if there is a hit highlight in full text (Requires a reindex/resave of a work)
- [ ] Metadata displayed in search results includes as expected:
  - [ ] Creator
  - [ ] Date

**Comment by sseymore** [comment]
QA fail (I think!) @CGillen Not sure if this is correct. For "Full Text is displayed and Description is not displayed ONLY if there is a hit highlight in full text (Requires a reindex/resave of a work)" I am seeing description NOT being displayed, but there are also no search results highlighting in Full Text for anything other than OSU test 023.

**Comment by CGillen** [comment]
@sseymore For any work to show up as a search result they need to be resaved or a complete reindex job needs to run. @jechols has a new reindexer in place and we need to run a test on it, but it sounds like we might not do that until the WC is over.

**Comment by sseymore** [comment]
@CGillen Ok, then this is a QA pass- with OSU test 023.
