### ISSUE TITLE
Search Results: Gallery View: Metadata fields further update

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#851]
### Descriptive summary

We want relevant and appropriate metadata fields to show up in search results.

### Expected behavior

Show below Title:

* Creator(s)
* Date
* (if keyword hit in Description) Description
* (if NOT keyword hit in Description, AND keyword hit in Full Text) Full Text
* Resource Type (with icon)

(display either Description or Full Text, but not both at same time)

All other fields should not be displayed in List View.

### Related work

#687 

### Accessibility Concerns

Have appropriate markup and attributes to represent the page structure.

**Comment by CGillen** [comment]
QA:
@sseymore Please QA or ask someone from metadata to fill in.
Only in the context of the grid view
- [ ] Titles of search results is highlighted when search term is present in title
- [ ] Description is displayed ONLY if there is a hit highlight in it
- [ ] Full Text is displayed and Description is not displayed ONLY if there is a hit highlight in full text (Requires a reindex/resave of a work)
- [ ] Metadata displayed in search results includes as expected:
  - [ ] Creator
  - [ ] Date

**Comment by sseymore** [comment]
See #850 for Full Text is displayed and Description is not displayed ONLY if there is a hit highlight in full text (Requires a reindex/resave of a work)
