### ISSUE TITLE
auto deploy

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#856]
Now that we're running staging off of our local OD2 cluster, we need to reimplement the CI/CD pipeline (auto deploy). The previous iteration used a tool that scanned ECR repositories, so the new system will need to be able to scan custom `docker-registry` registries.

**Comment by decimalator** [comment]
auto deploy is in place, to QA do a `kubectl logs <jeeves pod name> --follow` and `kubectl get pods --watch` while merging a PR. Once the PR tests pass and the container has been pushed to BCR, Jeeves should emit a log that it is deploying the new image and send a notification to Slack

**Comment by straleyb** [comment]
Worked. Closing

**Comment by straleyb** [comment]
<img width="1590" alt="Screen Shot 2019-11-21 at 11 56 24 AM" src="https://user-images.githubusercontent.com/6424683/69372127-f9beb580-0c55-11ea-86c3-76e62d64eac0.png">
