### ISSUE TITLE
Identify seed dataset for migration testing

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#86]
Collections or parts of collections that represent all Formats, Types and identified Hyrax Work Types

**Comment by jsimic** [comment]
Data seed suggestions from the UO collections: Corazon de Dixie (pdf, mp4, complex object), UO Veterans (pdf, mpeg, complex objects, oral histories), UO Special Collections Manuscripts and Rare Books (pdf, complex objects), Texts and Data (pdf, zip, excel, mpeg), Dan Powell photographs (tiff, jpeg): Total number of objects=566

**Comment by revgum** [comment]
Also see #57

**Comment by wickr** [comment]
Worked with @petersec to generate list for OSU collections. Linked those and annotated them, including UO's collections, to https://github.com/OregonDigital/OD2/wiki/Seed-and-Test-Data
Some annotations by me. I'll use this list to get pids and then export content for everything and that will be covered by #57.

**Comment by jsimic** [comment]
Add Gertrude Bass Warner https://oregondigital.org/sets/gb-warner-papers-ua022 to UO seed data for archival folder structures.

**Comment by jsimic** [comment]
@raybrarian Seed data for both institutions is listed above.
