### ISSUE TITLE
Public work does not show image unless logged in

### ISSUE THREAD

**Issue by raybrarian** [OregonDigital/OD2#863]
### Descriptive summary

Universal viewer spins and does not display image for a deposited, public work: 
URL before logging in - no UV:
https://staging.oregondigital.org/concern/images/zs25x8763?locale=en

URL after - UV displays:
https://staging.oregondigital.org/concern/images/zs25x8763?locale=en#?c=0&m=0&s=0&cv=0&xywh=-3459%2C0%2C8917%2C3067

Note: Thumbnails display in search results

### Expected behavior
UV displays publicly available works. Could this be a permissions issue? Edited to add that the example work is a migrated work.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

If UV doesn't load, screenreaders will only get the metadata announced, and not other information from the UV iframe.

**Comment by shieldsb** [comment]
QA fail.  I tried in Chrome, IE, and Firefox, but the images did not show. Tested migrated works and test works I deposited in WC7.  Display still works when I log in.

**Comment by shieldsb** [comment]
QA pass.
