### ISSUE TITLE
Search Box options on Collection landing pages

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#865]
The search box appearing at the top of a collection landing page should include the option of "This Collection Only" as the top, default option with "All" "OSU Content Only", "UO Content Only", and "Open Content Only" following (with My Works and My Collections at the end for authorized users.)

"This Collection Only" should limit the search to items in that collection.

We will need to wordsmith all the options in the search box pull-down for accessibility.

**Comment by shieldsb** [comment]
See MAC design.
