### ISSUE TITLE
Look at the current rails configuration and trim dev gems

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#870]
### Descriptive summary

We could look at rails production/development/staging configurations and see if these are the configurations we want to move forward with them. 

We can also look at the dev/staging/production gems and see if we can prune those down too.

**Comment by jechols** [comment]
We should also look at our use of the FITS library.  Are we downloading it from the right place (harvard rather than the github page)?  Is the version we're grabbing sensible (it seems old)?  Do we even need this anymore (is it a core part of Hyrax?  Solr does some of this stuff natively....)

**Comment by CGillen** [comment]
@jechols 
Looks like 1.0.5 is no longer necessary: https://github.com/harvard-lts/fits/issues/140
Since 1.2.0 FITS should include a fix that was holding Hyrax back. We could try pulling 1.5.0 from github but from my quick tests it seems to be slightly slower because of the increased size.

Side note: 1.0.5 hosted by github is much faster for me, but this is probably because of some caching/CDN details, I wouldn't rely on it.

**Comment by CGillen** [comment]
From the developers meeting it sounded like we wanted several devs to take a pass at cutting out gems and see if we can all agree on which can go, so I've assigned the smallest group I think should take a look at this. Others are welcome to chime in.

**Comment by CGillen** [comment]
Here's my attempt at removing gems: https://github.com/OregonDigital/OD2/pull/879

- devise-guest, we're not using guest user anywhere yet
- jbuilder, we're not doing any JSON API building yet
- net-http-persistent, we haven't opened any persistent http connections
- debase* & ruby-debug-ide, needed for rubymine IDE integration, don't know if other developers are using rubymine
- rails-controller-testing, we're not using `assigns` or `assert_template` expectations

Side notes:
- shoulda-matchers was pinned to a branch and ~200 commits out of date. The branch has been merged several releases ago
- coffee-rails is a requirement for Hyrax or one of its dependencies but hasn't been added to either gemspecs
- listen is a requirement of puma but isn't part of its gemspec

**Comment by jechols** [comment]
The only thing I can do here is remove a gem we still end up with.  haml is required by some dependency, but *we* don't actually use it.  I figure we may as well ditch it so we aren't implying it's in use by us directly, and we get to remove it from the stack if our dependency changes.

My only other change was that I commented @CGillen's findings directly in the Gemfile so they aren't lost.
