### ISSUE TITLE
Customize metadata for Image work type

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/OD2#88]
### Descriptive summary

Prerequisites:

- [x] Generate Image work type --> done by https://github.com/OregonDigital/OD2/pull/67
- [ ] Define controlled vocabularies in `config/authorities (optional)

Customize metadata given [Metadata Application Profile](https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0)

- [x] 1. Set labels and help text
- [x] 2. Define model, form, and presenter class in controller
- [x] 3. Define metadata in the model
- [x] 4. Modify the Edit Form
- [x] 5. Modify the Show Page (configure a property or properties to be shown in the search results for a work)

### Related work

Resources from Samvera.github.io:
http://samvera.github.io/customize-metadata-generate-work-type.html

Related tickets in OD2:
https://github.com/OregonDigital/OD2/issues/21 (Configurations)
https://github.com/OregonDigital/OD2/issues/87 (Generic work type)

**Comment by simholt** [comment]
Photograph Orientation
View
Orientation
Color Content
Color Space
Height
Resolution
Width

All present & accounted for, QA done.

**Comment by wickr** [comment]
This is not done, see earlier comment at https://github.com/OregonDigital/OD2/issues/88#issuecomment-446026937

Moving back to In Progress.
