### ISSUE TITLE
Add/update new environment variables for hyrax-migrator

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/OD2#881]
### Descriptive summary

We would like to access the following env variables in the workers pod for the hyrax-migrator: SKIP_FIELD_MODE, BROWSEEVERYTHING_FILESYSTEM_PATH, and CROSSWALK_OVERRIDES_FILE

### Expected behavior
```
> ENV['SKIP_FIELD_MODE']
=> "true"
> ENV['BROWSEEVERYTHING_FILESYSTEM_PATH']
=> "/data/tmp/shared"
> ENV['INGEST_LOCAL_PATH']
=> "/data/tmp/shared"
> ENV['CROSSWALK_OVERRIDES_FILE']
=> "/data/config/initializers/migrator/crosswalk_overrides.yml"
```
### Related work

https://github.com/OregonDigital/OD2/pull/877

### Accessibility Concerns

NA

**Comment by decimalator** [comment]
the environment keys have been added to the deployment, ready for QA.

**Comment by raybrarian** [comment]
@luisgreg99 @lsat12357 - can you QA?

**Comment by luisgreg99** [comment]
@raybrarian QA passed, we can close it and move it to done
