### ISSUE TITLE
Solr running out of memory on staging

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#882]
When a bunch of migration jobs are queued up on staging, all the jobs are failing

df71wm04g failed while persisting work: failed persisting work df71wm04g, RSolr::Error::Http - 400 Bad Request
Error: {"responseHeader":{"status":400,"QTime":0},"error":{"metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","java.lang.OutOfMemoryError"],"msg":"Exception writing document id 4c8cabc2-9721-4093-95ae-3178f13011fc to the index; possible analysis error.","code":400}}

I'm hoping this is just a matter of assigning more memory to the heap?

**Comment by luisgreg99** [comment]
It looks like on staging the heap is set to `512m`:
```
cat bin/solr.in.sh | grep SOLR_HEAP
#SOLR_HEAP="512m"
# Comment out SOLR_HEAP if you are using this though, that takes precedence
```
I think we can increase it. The heap got increased to `SOLR_HEAP=2g` on dev in the upcoming solr upgrade.

**Comment by luisgreg99** [comment]
I updated the variable `SOLR_HEAP=2g` in the `solr-test` (solr:6-alpine) pod and that seemed to fix the issue. @decimalator also added it to `solr8`, so the env variable should be ready for the solr upgrade as well.

**Comment by decimalator** [comment]
QA is good. The `solr-test` deployment is creating pods with the right `$SOLR_HEAP` env value (2g) and the SOLR process has the proper `java` command line options for setting a 2g heap 

```
⇨ kubectl exec -it solr-test-6f69b4d8d4-j99vt bash
bash-4.4$ env | grep SOLR_HEAP
SOLR_HEAP=2g
bash-4.4$ ps awwwx
  PID TTY      STAT   TIME COMMAND
    1 ?        Ssl    8:30 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -server -Xms2g -Xmx2g -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ConcGCThreads=4 -XX:ParallelGCThreads=4 -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=64m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=50 -XX:CMSMaxAbortablePrecleanTime=6000 -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:-OmitStackTraceInFastThrow -verbose:gc -XX:+PrintHeapAtGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:/opt/solr/server/logs/solr_gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=9 -XX:GCLogFileSize=20M -Dsolr.log.dir=/opt/solr/server/logs -Djetty.port=8983 -DSTOP.PORT=7983 -DSTOP.KEY=solrrocks -Duser.timezone=UTC -Djetty.home=/opt/solr/server -Dsolr.solr.home=/opt/solr/server/solr -Dsolr.install.dir=/opt/solr -Dsun.net.inetaddr.ttl=60 -Dsun.net.inetaddr.negative.ttl=60 -Xss256k -jar start.jar --module=http```
