### ISSUE TITLE
When editing a work, adding a duplicate CV and then removing the field removes the original and duplicate

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#883]
### Descriptive summary

![dup_cv_removal](https://user-images.githubusercontent.com/6424683/70342297-97df7d80-1809-11ea-91db-610780029183.gif)

**Comment by CGillen** [comment]
QA:
- [ ] Create a work with a controlled vocabulary piece of metadata and save the work
- [ ] Edit the work, add another value for the CV metadata, remove the newly added value, save the work
- [ ] Work show and edit pages STILL has the original value

**Comment by shieldsb** [comment]
QA pass. I'm going to create a new ticket for an issue that appeared during QA. I noticed that when I "Edit the work, add another value for the CV metadata, remove the newly added value, save the work" the original value was retained BUT it still saved the second value and displays it in the show page (even though it was removed prior to saving).  When you go back to the edit work page both values are there.
