### ISSUE TITLE
Coding standards and style guide

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#887]
### Descriptive summary

Create a style guide which nails down our basic coding style practice and github workflow stuff.

**Comment by straleyb** [comment]
https://github.com/OregonDigital/OD2/wiki/Coding-Guidlines-of-the-Oregon-Digital-2-Project

**Comment by straleyb** [comment]
This has been looked over. Living document and can be altered.

**Comment by luisgreg99** [comment]
I read the document [Coding-Guidelines-of-the-Oregon-Digital-2-Project](https://github.com/OregonDigital/OD2/wiki/Coding-Guidelines-of-the-Oregon-Digital-2-Project). Overall, it looks good to me. I've made my edits, extending a bit the section [comment-when-overriding-a-file](https://github.com/OregonDigital/OD2/wiki/Coding-Guidelines-of-the-Oregon-Digital-2-Project#comment-when-overriding-a-file).
