### ISSUE TITLE
Community User verification screen displays incorrect notification

### ISSUE THREAD

**Issue by raybrarian** [OregonDigital/OD2#903]
### Descriptive summary

Community users signing up the first time are sent to a page post-signup displaying a notification that a verification email is pending. Currently community users also get a notification to sign in through their university:
![image](https://user-images.githubusercontent.com/4460510/70734403-0b2d3780-1cc1-11ea-8fca-ffc285050047.png)

### Expected behavior
The university prompt does not show on this page.

### Related work

#848 

### Accessibility Concerns

None additional

**Comment by CGillen** [comment]
QA:
- [ ] Create new account with new non-institution email
- [ ] See above messages, red `Please sign in through your university below` message does not appear

**Comment by shieldsb** [comment]
QA fail.  "Please sign in through your university below" red message appeared

**Comment by CGillen** [comment]
Previous deploy attempt failed. Deploys are working again and this has made it to staging, ready for QA again

**Comment by shieldsb** [comment]
QA pass.  Also confirmed that it will not allow me to login without confirming my email address. Tested the email confirmation and log in process and it also functioned as expected.
