### ISSUE TITLE
Fix derivatives when source image has one bit per channel

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#905]
### Descriptive summary

When a PDF was recently being migrated, the derivatives job failed to produce JP2s.  This turns out to be because of the conversion process: we have to create an intermediate BMP so that the openjpeg tools can read it and create a JP2 with our desired zoom-friendly settings.  The intermediate BMP is usually just fine, but it seems that if the source image is 1 bpc, as is the case with many of the PDFs we have, the BMP ends up being 1bpc, which the openjpeg tools can't handle.

### Expected behavior

No crashing during derivative generation.  Which probably means forcing intermediate BMPs to be 8bpc.

**Comment by jechols** [comment]
QA is probably something @lsat12357 has to do, since she knows the problem better than anybody.  However, if somebody else needs to QA, the seed data that reliably demonstrated this bug was called `student_protest_bags`.  Ingest those files via the migrator and you should not see any problems, and derivatives should be created.

**Comment by lsat12357** [comment]
I ran it against OMA Minorities in the Barometer on Staging.
