### ISSUE TITLE
Configure Blazegraph in docker

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#91]
### Descriptive summary

With the addition of blazegraph and the triplestore adapter to OD2, we will now need to set up a container for blazegraph in the dockerfile. One thing to note is that there will be a reworking of the java shell command to start up blazegraph, as well as a need for java8.

```
nohup java -server -Xmx4g -Dbigdata.propertyFile=config/triplestore_adapter/blazegraph/blazegraph.properties -Dlog4j.configuration=file:config/triplestore_adapter/blazegraph/log4j.properties -jar blazegraph/blazegraph.jar > log/blazegraph.log 2>&1&
```

### Expected behavior

When docker is fired up, it spins up a blazegraph container.

**Comment by revgum** [comment]
closed in #102
