### ISSUE TITLE
Compare Solr behavior against base Hyrax

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#910]
### Descriptive summary
While reindexing everything in solr for the solr8 upgrade, @jechols discovered we have a lot of AccessControl and related objects indexed that don't seem to need to be searchable.
We should check the behavior of base Hyrax when a work is ingested and a workflow is setup.

### Expected behavior
Exploration

### Accessibility Concerns
N/A

**Comment by jechols** [comment]
I'd add that the only real action we can take from this is that if Hyrax by default *doesn't* do so much indexing, we have a new ticket to try to figure out how to clean up what we're indexing.

**Comment by CGillen** [comment]
Looks like Josh dockerized nurax a while ago, so it looks pretty much just like our setup. Spun that up and checked Solr, 2 documents existed, one for the default adminset and one AccessControl.
Ingested a work, added 5 documents, 4 of which were AccessControl related.

Conclusion: These documents ARE indexed into Solr by default. Still not sure they need to be, but without poking deep into the interior of Hyrax, we're stuck with all these AccessControl related documents bloating Solr. We also "found" a way to spin up Nurax locally to compare behavior.
