### ISSUE TITLE
Structured logs for Rails / Workers

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#913]
### Descriptive summary

To enhance our logs and allow them to be more easily ingested into analysis systems and aggregators, we should structure them either with key='value' or JSON formats. Logs that look like this

```
D, [2019-12-16T21:32:22.432537 #67] DEBUG -- : [133a782e3ba42948a2a63d12ced8a40a]   User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 4], ["LIMIT", 1]]
```

would look either like this:
```
time='2019-12-16T21:32:22.432537' level='DEBUG' reqid='133a782e3ba42948a2a63d12ced8a40a' message='User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 4], ["LIMIT", 1]]'
```

or this:
```
{
  time:'2019-12-16T21:32:22.432537'
  level:'DEBUG',
  reqid:'133a782e3ba42948a2a63d12ced8a40a',
  message='User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 4], ["LIMIT", 1]]'
}
```

**Comment by jechols** [comment]
I don't see any problem with this if Rails can be configured globally to do it, but I suspect there are still going to be places, especially deep in the dependency tree, where things do their own logging straight to STDERR.  And, of course, stack traces will be problematic as always.

So I guess the question is this: if we structure most of the logs, what happens to the rest?  If they're simply lost, that would be worse (for debugging) than just having the raw logs puked out somewhere.

**Comment by jechols** [comment]
Also: I don't know how Honeycomb parses stuff, but it might be worth pinging Andy or Duncan.  They've done a lot of work to get unstructured logs parsed into Kibana in some way that still preserves the "unknown" logs in a "meh, good enough" format.

**Comment by decimalator** [comment]
closing this for now. we have unstructured logs flowing into Honeycomb, in addition to the code level instrumentations. still looking for simple improvements but this is good to close for now.
