### ISSUE TITLE
Deleting a CV value deletes the value for other fields

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#919]
### Descriptive summary
When a CV value is deleted all other fields with the same URI are deleted where the field is defined before the field being deleted in `generic_metadata.rb`.

Example: Filling Arranger, Creator, and Contributor (in order they are defined) with the same value. Deleting Arranger will delete only Arranger. Deleting Creator will delete Creator and Arranger. Deleting Contributor will delete all values.

### Expected behavior
Only the field that is marked for deletion is deleted.

### Related work
Discovered during QA of #883 but not related by code.

### Accessibility Concerns
N/A

**Comment by straleyb** [comment]
https://github.com/samvera/hyrax/issues/4173

Ticket in Hyrax.
