### ISSUE TITLE
Cannot upload certain file types in the admin dashboard 

### ISSUE THREAD

**Issue by shieldsb** [OregonDigital/OD2#924]
### Descriptive summary

As an admin user attempting to add certain file types (see list below) through the dashboard on staging.uoregon.edu, I get an "unknown error" message when using the file upload function. 

File types that result in errors: pdf, mp3, mp4
File types that sucessfully upload: jpeg, xls, docx, xml 

### Expected behavior

All of the above files should upload, and give a confirmation message.

### Related work

#817 (Cannot upload files in the admin dashboard)

**Comment by raybrarian** [comment]
Hey @jechols  - when you get a chance, can you look at this? Does it make sense that pdf/mp3/mp4 files aren't uploading properly through the dashboard, though they seem to work in migrated works? Thanks!

**Comment by jechols** [comment]
If it were just PDFs I'd assume something I did in the custom PDF derivative processing, but audio and video I haven't touched in any way.  I'll see if I can dig anything up in logs.

**Comment by jechols** [comment]
I'm not able to reproduce this.  I get errors if I upload large files of any kind, but the type doesn't seem to matter, and the error message is that the file is too large, not "unknown error".  Small files of various types seem to work just fine, though.

**Comment by shieldsb** [comment]
![image](https://user-images.githubusercontent.com/53542788/71600769-5343bb00-2b05-11ea-89fe-08567f5ad270.png)

**Comment by jechols** [comment]
Yeah, definitely not seeing that.  Can you attach the specific files giving you trouble?  (Or email them to me or drop 'em in google drive or something)  I suspect there's some oddity with the files themselves - maybe my PDF encoder is having trouble or something.

Though looking at your screenshot, it looks like the PDF actually worked.  Was there more than one PDF you tried to attach?

**Comment by jechols** [comment]
Okay, this is the "entity too large" problem - it seems the error message depends on one's browser.  Which is odd, but makes sense given how the simples case use of the File API works.

The problem here is that something is misconfigured.  I don't know where, but it's been a problem since October.  I believe we have something in our frontend akin to the PHP `post_max_size` and `upload_max_filesize` settings.  Except this isn't PHP, so I honestly have no idea what could be limiting it.  This will require more in-depth investigation.

**Comment by jechols** [comment]
I got at the raw response, it's definitely a 413 (entity too large) in all browsers; Chrome just doesn't display it the same as Firefox.  I'm going to assign this to @decimalator - he says this is an nginx ingress issue, and that's got no meaning to me :)

**Comment by shieldsb** [comment]
QA pass.  All file types, regardless of size, will now upload.
