### ISSUE TITLE
cache mechanism when fetching label URIs

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/OD2#927]
### Descriptive summary

When migrating assets, caching labels can help during migration. Currently, migrating an asset can take a while to process since it tries to fetch all labels every time a new asset is created even if they were already fetched in previous assets.

### Expected behavior

It would be nice to be able to fetch labels from cache instead when creating or updating a work. @wickr has suggested the option of using a job to take care of fetching as done in OD1 (See https://github.com/OregonDigital/oregondigital/blob/master/lib/oregon_digital/rdf/deep_fetch.rb and  https://github.com/OregonDigital/oregondigital/blob/master/app/jobs/fetch_all_job.rb)

### Related work

Related issues on GitHub
https://github.com/OregonDigital/OD2/issues/502

### Accessibility Concerns

NA

**Comment by straleyb** [comment]
Non-issue. Cache is working as expected. 
```
I, [2020-01-07T16:44:53.491408 #67]  INFO -- : [12dde38c24189ceeae405ffc6a21ecd4] Fetched From Cache
I, [2020-01-07T16:44:53.505715 #67]  INFO -- : [12dde38c24189ceeae405ffc6a21ecd4] ["", 0.0057939999999980785, 0.002630999999999162, 0.0, 0.0, 0.014199905097484589]
I, [2020-01-07T16:44:53.521146 #67]  INFO -- : [12dde38c24189ceeae405ffc6a21ecd4] Fetched From Source
[INFO] fetch_cached_graph(http://opaquenamespace.org/ns/creator/AmericanTradingCo) not found in triplestore cache (http://blazegraph.default.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
I, [2020-01-07T16:44:53.692308 #67]  INFO -- : [12dde38c24189ceeae405ffc6a21ecd4] ["", 0.04242699999999999, 0.012437000000000253, 0.0, 0.0, 0.17104939557611942]
```
