### ISSUE TITLE
Make sure all references to #fetch are shoveled off into jobs

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#928]
### Descriptive summary

We have a job for fetching controlled vocabularies from an endpoint. We will need to update this job to pull a work, fetch the graph from blazegraph OR the endpoint, then update the index with the new label and uri combo. 

This object should accept a list of all CVs and fetch them all then do an update all in one go.

**Comment by straleyb** [comment]
QA: Add a bunch of locations to a new work, preferably 4+ locations, and any other CVs that you can drum up. You should be able to hit save and not have to sit for 12 minutes waiting for it to save. 

Bonus points: you can go to /sidekiq and watch the busy job running and wait for it to finish. Once it does, the show page should be updated with labels.

**Comment by raybrarian** [comment]
Info box appears:
![image](https://user-images.githubusercontent.com/4460510/73462593-ece2d000-4330-11ea-8cd1-545f2f50b3f6.png)

No labels appear after 10 minutes. Will retry.

**Comment by raybrarian** [comment]
@straleyb - Here is the job that's running and trying to fetch Geonames:
![image](https://user-images.githubusercontent.com/4460510/73465307-0c7bf780-4335-11ea-8014-84523b350550.png)

I don't think these will resolve with this error, so dropping this one back into Ready.

**Comment by straleyb** [comment]
Yep Im assuming you were making images possibly?

**Comment by raybrarian** [comment]
Yep!

**Comment by raybrarian** [comment]
@straleyb I see your #974 PR - feel free to drop this right back into QA after it gets merged

**Comment by straleyb** [comment]
Will do! It should work as expected. Once again, we run into, since there is no base model, we have to add the dupe code into a gazillion spots. Im going to architect a better way to do this tomorrow I think.

**Comment by raybrarian** [comment]
@straleyb - locations show now, but the display has reverted to the URI (not the user-friendly text):
![image](https://user-images.githubusercontent.com/4460510/73474738-ced29b00-4343-11ea-8041-ab9e40bc2f51.png)

I think @luisgreg99 had a PR that fixed that very recently?

**Comment by raybrarian** [comment]
Making a note: added one location to existing work: https://staging.oregondigital.org/concern/images/5d86p027h 

FYI @straleyb - QA process not complete yet. As soon as I resaved the work, none of the previous location info shows on the show page. Sidekiq has 1 thread assigned, which has been busy for (so far) 36 minutes. That wait seems unreasonably long to me, in terms of curators being able to check their work in a reasonable time. Especially so if the process blows away all of the other metadata.

**Comment by raybrarian** [comment]
@straleyb - finally got the locations showing on the show page for the example work, including the new one and no dupes, but we're back at the pre-fix experience:
![image](https://user-images.githubusercontent.com/4460510/73573756-06674300-4429-11ea-9faa-1ae62cd3af10.png)

Related: #943, #956, #966 

Link text should be something like _United States, Oregon, Lane County, Eugene (Populated Area)_, not the URI

**Comment by raybrarian** [comment]
Hmmm - is #978 a fix for this? I will keep this in QA for now and look at it again next week.

**Comment by straleyb** [comment]
@raybrarian Wanna try something for me? Do just 2 locations.

**Comment by raybrarian** [comment]
@straleyb - in a new work? Or dump the old Locations and try two new ones?

**Comment by straleyb** [comment]
Sure, in a new work. Or you could update the existing one to only have two. Both should theoretically work.

**Comment by raybrarian** [comment]
Let me try it - I'll ping you here with the results. I'll blow away the old locs and try two new ones in this work. Fingers crossed!

**Comment by raybrarian** [comment]
Kicked off (deleted existing locs and chose two new ones; saved work): 
![image](https://user-images.githubusercontent.com/4460510/73575063-277d6300-442c-11ea-9a10-305f72ab1a6b.png)

**Comment by straleyb** [comment]
https://staging.oregondigital.org/concern/generics/zp38wc63s?locale=en Here is a work I just ingested

**Comment by raybrarian** [comment]
Nice aquarium! Or maybe terrarium? :) Those look good to me - was getting #978 merged the fix? Or is it something else?

**Comment by straleyb** [comment]
Aquarium. :D and yeah, it was. 

But see, what happens is sometimes the job sticks. And when it does, it takes about 15 minutes for it to fail the actual job. Im not sure if its because geonames blocks it after a certain amount of requests or what. I would have to dig into why these jobs are sticking here and there. But its not all the time, and it happens mostly when there are too many location labels. 

There is more refinement that needs to happen around this but I think this particular issue is fixed. I can spawn another one from what we've found.

**Comment by raybrarian** [comment]
Awesome - I will move this to done and keep my eyes open for the follow-on issue. Thanks, @straleyb!
