### ISSUE TITLE
osu key not found bug

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#929]
### Descriptive summary

After a file is changed, there is some autoload error which doesnt allow for osu key to be found in the form visibility component

**Comment by lsat12357** [comment]
Just got this error on staging:
- : df661w344 failed while persisting work: failed persisting work df661w344, uninitialized constant OregonDigital::AccessControls::AccessRight
Did you mean?  OregonDigital::AccessControls : ["/data/app/models/concerns/oregon_digital/access_controls/visibility.rb:32:in `visibility'", "/usr/local/bundle/gems/hydra-access-controls-10.7.0/app/models/concerns/hydra/access_controls/visibility.rb:55:in `registered_visibility!'", "/data/app/models/concerns/oregon_digital/access_controls/visibility.rb:15:in `visibility='",

**Comment by jechols** [comment]
I've stolen this because I was fixing autoload issues in my own code already, and a single "autoload fix" PR made a lot more sense to get migration unblocked

**Comment by luisgreg99** [comment]
fixed by https://github.com/OregonDigital/OD2/pull/1002
