### ISSUE TITLE
Create code to generate signed URLs for S3 assets we want to keep private

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#93]
### Descriptive summary

OD1 reads all assets from disk and then writes them out to the client (browser).  This is necessary to check access restrictions.  But it's slow and can block other requests coming in, which is especially bad for huge file downloads.

If we store our content in S3, we can have it be private, but generate short-lived "signed URLs".  These can then be used in a redirect request from our app after all the access checks have been made.

- User requests an asset's full size / original content
- App verifies user can get asset
  - If not, this is easy: 403 response
- App generates a signed URL that lasts a short while.  Ten minutes?
- App redirects to the signed URL

### Expected behavior

- [ ] Users can get at protected and public assets "content" datastream
- [ ] Signed URLs live long enough for users to get the data
- [ ] Signed URLs properly expire (e.g., we don't have a bug that generates 10 *week* URLs)

**Comment by raybrarian** [comment]
POSM review - closed (S3 not an option anymore)
