### ISSUE TITLE
no space left on device error for shared

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#932]
occurred while migrating pdfs
E, [2019-12-21T01:41:50.892211 #1] ERROR -- : [ActiveJob] [CreateDerivativesJob] [e620e157-83f5-4e54-94a8-b285954d88b5] Error performing CreateDerivativesJob (Job ID: e620e157-83f5-4e54-94
a8-b285954d88b5) from Sidekiq(default) in 599289.38ms: MiniMagick::Error (`gm convert -density 300 /data/tmp/shared/uploads/hyrax/uploaded_file/file/1102/bv73c0887_content.pdf[119] -depth 
8 /tmp/od220191221-1-6w8pjg.bmp` failed with error:
gm convert: An error has occurred writing to file (/data/tmp/shared/uploads/hyrax/uploaded_file/file/1102/bv73c0887_content.pdf) [No space left on device].

**Comment by lsat12357** [comment]
I did go back and delete the tars, but I would like to be able to leave the bags and the temp files in shared until we've had a chance to verify assets.

**Comment by decimalator** [comment]
duplicate of #935 the `shared` volume isn't full, it looks like the full filesystem error is from /tmp being full?
