### ISSUE TITLE
Change logging to suggest cache is being used. 

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#934]
### Descriptive summary

https://github.com/OregonDigital/OD2/blob/master/app/indexers/oregon_digital/deep_indexing_service.rb#L17

Should say "Fetching from triplestore." Or something along those lines, to suggest OUR triplestore is being used. Doesnt actually suggest that #fetch is using only the authoritative source

**Comment by CGillen** [comment]
QA:
- [ ] Perform migration or reindex job of a work with linked data that exists on another work (Should be in blazegraph).
- [ ] See indexing attempts to fetch from cache and succeeds (from logs)
- [ ] Create work with linked data that does not exist on another work (Should not be in blazegraph)
- [ ] See indexing attempts to fetch from cache, fails, attempts to fetch from authorative source (from logs)

**Comment by lsat12357** [comment]
I, [2020-01-23T18:10:18.853612 #17849]  INFO -- : Attempting to fetch http://dbpedia.org/resource/University_of_Oregon from local graph cache.
I, [2020-01-23T18:10:18.940234 #17849]  INFO -- : Fetched From Cache
I, [2020-01-23T18:10:19.007994 #17849]  INFO -- : Attempting to fetch http://id.loc.gov/authorities/names/no2015117493 from local graph cache.
I, [2020-01-23T18:10:19.018935 #17849]  INFO -- : Fetched From Cache
I, [2020-01-23T18:10:19.028330 #17849]  INFO -- : Attempting to fetch http://id.loc.gov/authorities/subjects/sh2007100691 from local graph cache.
I, [2020-01-23T18:10:19.067021 #17849]  INFO -- : Fetched From Cache
I, [2020-01-23T18:10:19.102712 #17849]  INFO -- : Attempting to fetch http://id.loc.gov/authorities/subjects/sh2009113787 from local graph cache.
I, [2020-01-23T18:10:19.130927 #17849]  INFO -- : Fetched From Cache

**Comment by lsat12357** [comment]
I, [2020-01-24T17:41:16.269193 #67]  INFO -- : [6ec05eea96df9906ab91ef4277394ade] Attempting to fetch http://id.loc.gov/authorities/names/n87831333 from local graph cache.
[INFO] fetch_cached_graph(http://id.loc.gov/authorities/names/n87831333) not found in triplestore cache (http://blazegraph.default.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
I, [2020-01-24T17:41:16.279558 #67]  INFO -- : [6ec05eea96df9906ab91ef4277394ade] Fetching http://id.loc.gov/authorities/names/n87831333 from the authorative source. (this is slow)
[INFO] fetch_cached_graph(http://id.loc.gov/authorities/names/n87831333) not found in triplestore cache (http://blazegraph.default.svc.cluster.local:8080/bigdata/namespace/kb/sparql)
I, [2020-01-24T17:41:17.443129 #67]  INFO -- : Finished "/notifications/endpoint/" [WebSocket] for 128.223.87.141 at 2020-01-24 17:41:17 +0000
I, [2020-01-24T17:41:17.443276 #67]  INFO -- : Hyrax::NotificationsChannel stopped streaming from hyrax:notifications:Z2lkOi8vb2QyL1VzZXIvNw
I, [2020-01-24T17:41:17.846557 #67]  INFO -- : [6ec05eea96df9906ab91ef4277394ade] Fetched From Source
