### ISSUE TITLE
Run a profiler against some key processes

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#936]
### Descriptive summary

We don't know why key parts of the app are so incredibly slow, and we need to figure this out.  Even if we can't do much about some areas, it could help us know where we should focus.  And maybe there are ways to tweak settings for other libraries or even push up code to improve things that are hurting us more than we would realize.

A promising stack-based profiler is at https://github.com/tmm1/stackprof.

I suggest profiling reindexing an asset as well as migrating an asset.  Other profile target may make sense, but offhand these two seem the most abusive operations.  (migration may in fact be a red herring if the indexing is the real culprit)

### Expected behavior

Know our stack a little better.  Maybe make new tickets to address shortcomings.

**Comment by jechols** [comment]
Update: I've profiled the indexing code using stackprof in a variety of ways, and it looks like the problems are almost entirely CPU, and quite like to do with the sheer volume of calls to RDF and EBNF gems' functions.  The garbage collector alone accounts for 10-15% of the runtime for indexing, which is an exceptionally large percentage, even for Ruby.  Object profiling showed me that there are millions of instantiations of very small objects over the course of 5-30 seconds.  Looking over the graphviz output, the tendrils of Hyrax -> RDF code are vast, terrifying, and all but impossible to trace in any meaningful way.

Short story here is that we're not likely to find a quick win.  There's just a ridiculous amount of stuff happening.  It's likely that a ton of this "stuff" isn't necessary, but it may require finding clever hacks to drastically reduce the amount of parsing of RDF that we do.  Which means figuring out why so much RDF is being parsed for a single asset index into solr.

Some options I could see:

- When we need to reindex, we spin up many worker containers.  Like... 20+ so we're running hundreds of jobs simultaneously.  If the stack is able to handle it (a big "if"), we could turn a 1000-hour reindex job into a 50-hour job.  Benchmarking / load testing would be necessary to see how much concurrency we can actually handle.
- Dig deeper to see what RDF terms are being parsed.  Maybe Hyrax could just get some caching love somehow (probably not, but maybe).  Maybe we could change what RDF is visible to the indexer.  I dunno.  Maybe we could hack the index process and extract our own logic so we're skipping whatever is so expensive in the Hyrax stack.

**Comment by straleyb** [comment]
tesseract ticket.

**Comment by jechols** [comment]
I'm not sure why this was closed - this has nothing to do with tesseract.  Is the comment accidental?  If this is being closed due to a solution having been found or something, that's the comment we need in here.

Also if you feel this is being addressed by another ticket, please link to that ticket so we have a clear connection.  "tesseract ticket" requires I go look through issues and find one related to tesseract....
