### ISSUE TITLE
Look into kubernetes for local development

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#94]
### Descriptive summary

Development workflow is currently all docker-based.  Production is kubernetes.  This separation means two things:

- Changes to services requires two separate configuration changes, which could get out of sync
- Developers who need to do ops work in a pinch may not know how to do them since k8s isn't something most of us know

If we can reuse enough of the production k8s config for local dev, we could start easing devs into that flow.

- We need to identify what bits of config need to be created that are development-specific
- We should come up with simple scripts (or at least README docs) for starting and stopping the stack

### Expected behavior

Devs can spin up the stack with kubernetes commands

**Comment by revgum** [comment]
See #121 for comments on the consideration of getting this to work

**Comment by jechols** [comment]
After the last failures and out-of-sync problems, I'm going to look at this a second time and hopefully we can find a way around the problems Josh had :-/

**Comment by jechols** [comment]
Some notes before I forget:

Pros
---

It looks like there are tools that could help us manage this stack using kubernetes, specifically `minikube` and `skaffold`.  These would let us run on staging-like infrastructure config while still having somewhat real-time development.  So while there are difficulties going this route, it's not impossible.

We have a lot of odd problems in staging, and most of the devs aren't generally sure where to look to help out.  Sometimes this results in trial-and-error fixing.  It's possible that having a local k8s stack would alleviate this some.

Cons
---

One problem we may have is trying to keep dev and staging infrastructure code in sync.  The autodeploy system will automatically redeploy to staging whenever something gets through the CI/CD layer, and that redeploy changes the image definition.  If people change the web pod, this could introduce annoying, though not insurmountable, merge conflicts.  I think the bigger problem with this is simply orchestrating it on the infra side, because instead of something just pushing a new deploy config, we'll have to have something that has to pull the latest state down from github and quickly pushes its changes up.  This could introduce really obnoxious race conditions anytime anybody pushes something between the infrastructure auto-sync steps (`git pull`, `git add .`, `git push`).  I'm opposed to having something like that, because it will introduce something that can break hard and becomes a pain when it does.

We shouldn't be able to run into problems where major versions change in dev without changing in staging / production, but the way our infrastructure code is currently set up, we would probably need to have a separate setup for development and staging, at least for things like the web pod, in order to account for changes to the environment.  It looks like we specify the environment in a more hard-coded way for kubernetes whereas with docker-compose, we can expose environment variables and let them pass into the containers.

All developers will need to install and learn multiple new tools (`minikube` and `skaffold` in addition to the differences between `kubectl` and `docker-compose`).  `minikube` seems pretty solid, but it's slow as dirt to start up.  `skaffold` feels very beta to me despite being built by google to handle problems like the problem we have.  Automatically syncing dev files into the container isn't as seamless as I had been hoping - in docker-compose, they're shared, but with this setup, `skaffold` has to actually watch the files and copy them into the container when they change.

We'll have a new configuration to keep track of (skaffold.yml).  If we don't update the skaffold config properly, we could end up with dev-versus-prod drift again.

We'll have to manually ensure dev and prod are running the same version of kubernetes due to backward-incompatible changes I've run into just while testing.

Summary
---

I'm worried we'll be trading one set of problems for another.  kubernetes just may not be a developer-friendly environment.  I plan to keep looking into some of these pain points and we will discuss more at quarterly, but this isn't the "no brainer" I thought it would be.

**Comment by raybrarian** [comment]
Hey @decimalator - is this issue closeable now? Thanks!

**Comment by decimalator** [comment]
Yeah I think so

**Comment by jechols** [comment]
Totally closable - I think the cons outweighed the pros (given we're not using k8s for local dev :P)
