### ISSUE TITLE
workers pod is dying on staging

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#940]
When a running script that iterates through a bunch of pids, opens objects, modifies and saves them and for each, enqueues the job that starts the derivatives process, the worker pod dies (This latest time, after about 20 items have been enqueued?)
The pod died, was replaced, and that one died as well: some of the jobs that had been launched were still in sidekiq. The third pod survived and finished up the remaining jobs.

**Comment by raybrarian** [comment]
Related issue that is hopefully a fix for this one: #935

**Comment by lsat12357** [comment]
I was able to run two batches concurrently, one of 20 tiffs and one of 20 pdfs on the OD2020 cluster, from start to finish without the workers pod getting evicted.

**Comment by raybrarian** [comment]
Per @lsato, QA pass
