### ISSUE TITLE
location field not displaying label in the show page

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/OD2#943]
### Descriptive summary

Location field doesn't seem to be fetching labels properly in the show pages. The fetching works well in the edit/new forms, but after saving the work, labels don't show up in the view. @wickr found a possible related PR https://github.com/samvera/questioning_authority/pull/307 (it looks like it hasn't been released yet) possibly coming up in an upcoming release of hyrax. The PR suggests that the protocol got changed to https in the response, so https://github.com/OregonDigital/OD2/blob/master/lib/oregon_digital/feature_class_uri_to_label.rb#L6 might need to be updated as well.

### Expected behavior

It should display the location label in the show page.

### Related work
https://github.com/samvera/questioning_authority/pull/307

### Accessibility Concerns

NA

**Comment by raybrarian** [comment]
Hi @luisgreg99 - do you have an example of a work where the Location label should show? I've looked at the "all fields" work visible for UO users (https://staging.oregondigital.org/concern/generics/p5547r392?locale=en) and I do see some location fields, but not one labeled "Location."

**Comment by luisgreg99** [comment]
@raybrarian Yes, here's an example that I've used for testing https://staging.oregondigital.org/concern/images/pz50gw11f?locale=en Also, I had to edit this asset and removed the old location URI, which still included the old `http` protocol (this seems to be the issue in the asset https://staging.oregondigital.org/concern/generics/p5547r392?locale=en as well), in order to fix the display on the show page. 

There is still an issue with existing assets that have the old protocol. For existing assets, I think we can get a script to cleanup these assets. I'll work on this one next.

**Comment by raybrarian** [comment]
@luisgreg99 - ah, got it. It was in review, so I published your test example (https://staging.oregondigital.org/concern/images/pz50gw11f?locale=en#?c=0&m=0&s=0&cv=0&xywh=-272%2C-1%2C1743%2C600) to make sure it looks like it should for public users as part of QA. Looks like the text in Location is showing as well, but is linking to a repository search: 
https://staging.oregondigital.org/catalog?locale=en&q=Eugene+%2C+Lane+%2C+Oregon+%2C+West+%2C+United+States+%2C+Northern+America+%2C+North+America+%2C+Americas+%2C+Earth+++++++%2C+%28%29+&search_field=location_label

So Location shows as a label and has content - do you want me to close this one and the issues we've raised can go in another ticket, or do you want me to boot this one back to backlog?

**Comment by luisgreg99** [comment]
@raybrarian Yes, I think we can close this one. We can have separate GitHub issues for the remaining ones. I'll make a new one for the issue with existing assets.

**Comment by raybrarian** [comment]
@luisgreg99 - got it, thanks! Moving this to Done.
