### ISSUE TITLE
require identifier in the model

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#950]
currently, identifier is required in the form, but not the model? This came to light when we migrated seed data assets that don't have an identifier and no errors were thrown. It only became evident when the assets were opened in the front end.

Making identifier required in the model will ensure that regardless of how the asset is generated, identifier will be present.

**Comment by CGillen** [comment]
QA:
Create a work by CLI or migration and find the following metadata can not be blank:
- [ ] title
- [ ] resource_type
- [ ] rights_statement
- [ ] identifier

**Comment by luisgreg99** [comment]
@CGillen I did a small batch of Baseball_jpegs collection (images) to test it with migration (locally), and it didn't validate the presence of `identifier`. I tried with the console, and it looks like `Image` model needs the requirement as well. I tried adding the line 
```
validates_presence_of Hyrax::GenericForm.required_fields
```
in app/models/image.rb as well and that seemed to work for my test in the console. I think the other models might also need this line.

**Comment by raybrarian** [comment]
@luisgreg99 - could you or @lsat12357 take another look at this when you get a chance?

**Comment by luisgreg99** [comment]
@CGillen I did another test run with migration and it still didn't validate the field properly. This test did well in the console after the change:
```
> test = Image.new({ title: ["test-image6"], depositor: "admin@example.org", resource_type: 'myType', rights_statement: ['http://rightsstatements.org/vocab/InC/1.0/']})
> test.save!
ActiveFedora::RecordInvalid: Validation failed: Identifier can't be blank
from /usr/local/bundle/gems/active-fedora-11.5.4/lib/active_fedora/validations.rb:89:in `raise_validation_error'
```
But when I run migration, `Hyrax::Migrator::Jobs::MigrateWorkJob` keeps failing with
```
NoMethodError: undefined method `generic_properties' for Generic:Class
```
Then on retries, it gets stuck with:
```
LoadError: Unable to autoload constant Vocab::FedoraResourceStatus, expected /usr/local/bundle/bundler/gems/hyrax-da1b6ffd7c0e/app/models/vocab/fedora_resource_status.rb to define it
```
I suspect that the model doesn't like the call to `Hyrax::GenericForm` because I tried replacing the `validates_presence_of` line with the actual list of required fields, and it worked as expected (The error also went away for my test):
```
validates_presence_of [:title, :resource_type, :rights_statement, :identifier]
```
I wonder if it would be a good idea to reference the actual list in this line for the models, or maybe extract the list from the forms and call them in both places (forms and models).

**Comment by luisgreg99** [comment]
QA pass

Tested identifier for `xp68kg588` (identifier is blank):
```
i = Hyrax::Migrator::Services::BagIngestService.new(['test_identifier'], Hyrax::Migrator.config)
i.ingest
=> {"test_identifier"=>["/data/tmp/test_identifier/xp68kg588.zip"]}
 w = Hyrax::Migrator::Work.find_by_pid("xp68kg588").status_message
=> "Work xp68kg588 failed publishing to the repository."
```

Tested other fields:
```
test = Image.new({depositor: "admin@example.org"})
test.save!
ActiveFedora::RecordInvalid: Validation failed: Title can't be blank, Title Your work must have a title., Resource type can't be blank, Rights statement can't be blank, Identifier can't be blank
from /usr/local/bundle/gems/active-fedora-11.5.4/lib/active_fedora/validations.rb:89:in `raise_validation_error'
```
