### ISSUE TITLE
fields not fetching labels on create and update

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/OD2#960]
### Descriptive summary

I found a few fields that got saved successfully, but the labels didn't get fetched. I found these while testing PR https://github.com/OregonDigital/OD2/pull/939 locally.

- [ ] Form of work
- [ ] Military branch
- [ ] Repository
- [ ] Place of production

### Expected behavior

I think it should fetch the labels and display them in the show page when available.

### Related work

NA

### Accessibility Concerns

None

**Comment by straleyb** [comment]
QA: Ingest these Controlled Vocabularies with proper URIs and they should show labels instead of URIs on the show page.

**Comment by raybrarian** [comment]
@luisgreg99 @lsat12357 - do those CVs need to be ingested through work y'all do, or is this a @wickr question?

**Comment by luisgreg99** [comment]
@raybrarian I think so, I found them when testing Fairbanks collection, and noticed that the labels were missing. I can do another test run to QA this one.

**Comment by raybrarian** [comment]
Great - thanks, @luisgreg99!

**Comment by luisgreg99** [comment]
QA pass
