### ISSUE TITLE
task to update protocol on existing location values

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/OD2#963]
### Descriptive summary
cleanup to update protocol on existing works with http

### Expected behavior
location on existing assets should include https

### Related work

https://github.com/OregonDigital/OD2/issues/943

### Accessibility Concerns

NA

**Comment by luisgreg99** [comment]
This is ready for QA on staging. Steps for QA:

- [ ] Browse to an existing item with a location: https://staging.oregondigital.org/concern/documents/fx719q28r Location field should be visible
- [ ] Browse to an existing item with location and click "Edit": https://staging.oregondigital.org/concern/documents/fx719q28r/edit?locale=en Under Location, it should list geonames URIs, which should start with `https://`

**Comment by raybrarian** [comment]
QA pass.
