### ISSUE TITLE
add predicate changes to crosswalk overrides

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#977]
It looks like some of the predicate changes for lesser used properties are not in crosswalk overrides file. Confirmed with jsimic that unless there is some indication in the map that remediation is planned, the changeover happens in migration so the OD1 predicates do need to be added.

**Comment by lsat12357** [comment]
I checked this time that anything being added that is expected to be controlled is already controlled in OD2:
form_of_work -> form_of_work
place_of_production -> location
tgn -> historic_place

**Comment by raybrarian** [comment]
Assigned to Greg for QA

**Comment by luisgreg99** [comment]
QA results:

@lsat12357 I double checked the items with the MAP to confirm the expected changes. I checked

(a) "Obligation"  in the MAP and `multiple` in the overrides
(b) "Controlled Vocabulary" in the MAP and `attributes_data` in the overrides
(c) "OD1 Predicate" and "Remediation needed" in the MAP to compare the expected `predicate` in the overrides

- [x] access_restrictions_attributes
- [x] is_volume (1)
- [x] has_number (1)
- [x] biographical_information
- [x] description_of_manifestation
- [x] form_of_work_attributes
- [x] inscription
- [x] layout
- [x] mode_of_issuance
- [ ] style_or_period (2) 
- [ ] cultural_context (2) 
- [x] tgn_attributes
- [x] use_restrictions
- [x] contained_in_journal *
- [x] place_of_production_attributes
- [x] material
- [x] technique
- [x] color_content
- [x] original_filename

Notes:

(1) Found a deprecated message in the MAP for "swpo Semantic Word Portal Ontology" in "Namespaces" sheet: "Deprecated and migrating to new preds; see changed predicate column". For now I think these should be good (There is already a ticket in https://github.com/OregonDigital/oregondigital/issues/1241 that would affect these fields in the future):
- is_volume
- has_number
- contained_in_journal

(2) It looks like the fields `style_or_period` ([StylePeriod](https://github.com/OregonDigital/OD2/blob/master/app/models/concerns/oregon_digital/generic_metadata.rb#L515) vocabulary) and `cultural_context` ([Culture](https://github.com/OregonDigital/OD2/blob/master/app/models/concerns/oregon_digital/generic_metadata.rb#L505) vocabulary) are missing the `attributes_data` function and the `_attributes` suffix in the property name.
