### ISSUE TITLE
Design options for OD2 homepage

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#98]
### Descriptive summary

It would be nice to start getting some design options in front of PMOP and Service Managers for what the OD2 homepage could look like. These don't need to be finalized 100% soon, but if we could possibly have a new landing page up at the end of Workcycle2 that would make an impact for a demo.

### Expected behavior
Nice looking homepage

### Current behavior
Hyrax homepage

**Comment by mccallum** [comment]
Yeah. I thought today that I might regret turning over the Slack channel for UI that kept things a bit clearer. I'll be at PMPO meeting tomorrow with a homepage wireframe and some ideas to pitch that I shared with Franny.

**Comment by mccallum** [comment]
https://sketch.cloud/s/mEz3z/52L8bmy

**Comment by jsimic** [comment]
Like it overall. The login icons may need more clarification.

**Comment by raybrarian** [comment]
@mccallum @jsimic - who else needs to review this? @petersec or @kmthorn? And has this already had a discussion happen in Features? 

One comment from me - for accessibility, we can't have function only communicated by a difference in color, so ideally the logins will also need to have designators in text - "UO users" or "affiliates" or something similar. Could just be UO and OSU, I suppose!

**Comment by petersec** [comment]
I like it as well, though the browse and advanced options get lost against the current graphic. I agree with Julia that the login icons are also not clear. The big philosophical shift between the OD1 homepage and this draft is an exchange of facets for latest collection/latest items. I wonder if a balance could instead be struck between these two approaches? I would certainly prefer that the OD2 homepage not have a full rundown of all facets as is currently the case, but I think a short curated list of commonly used (and useful) facets would be good to keep in a prominent location.

**Comment by jsimic** [comment]
@raybrarian : As many people as we can who deal with the public, @sseymore @kmthorn @mfgaede from UO

**Comment by mccallum** [comment]
A free-for-all comment period on a 3/4-baked homepage screen isn't on the chart of what we seemed to agree on: https://app.milanote.com/1F3OUF1608VX5U  In a proactive flash of reining things a bit, are there parts of our chart that needs more explanation or breakdown? Addition or excision (or exorcism)? I'm totally open to working through that with anyone... in a shared vision way.  

@vantuyls @raybrarian PMs - Would you two like me for an hour with PO/SO for a quick state-of-the-UX/UI-design-process sesh? Let me know. I know I'd like 10-15 to present at the quarterly in April.

I understand the eagerness and excitement... and even feel it occasionally. :)

**Comment by raybrarian** [comment]
@mccallum - yep, this is supporting that prototype/refine/feedback/iterate phase in your design process doc - happy to work with you to clarify how you want to to get that feedback from the stakeholders and users and move on to refine/iterate, especially in terms of closing GitHub issues. 

I don't think there's a need for a state of the process session yet, though you may want to find a half-hour on my schedule sometime this week so we can work together on the specifics of this phase!

**Comment by kmthorn** [comment]
I agree with @petersec the browse and advanced options get lost against the current graphic. I also recommend changing "browse" to "browse collections" to give more context to an end user.

I agree with @jsimic that the login icons are also not clear. 

"All" in the search box could be confusing to users -- "All of what"?  Here are two examples to help contextualize the all of what. Digital Commonwealth with "all fields" https://www.digitalcommonwealth.org/ and DPLA, which is "search the collection". https://www.digitalcommonwealth.org/ UW Madison uses "search collections".

What does the "?" in the top right corner do?

Also, something I run into when working with faculty and student is... they want to browse by formats to reuse in their digital scholarship projects. I really like how Digital Commonwealth highlights this need on their homepage. https://www.digitalcommonwealth.org/

Will there be an "About" page or a page for contacting Oregon Digital institutional contacts linked from the home page?

**Comment by raybrarian** [comment]
what the heck I need to stay out of GH

**Comment by raybrarian** [comment]
Hey @mccallum - please ignore my accidental closures of this ticket! 

This is one of the pages scheduled to be implemented on the Features workcycle goals - can you give an update/attach the completed page mockup? If this is the final design: [https://sketch.cloud/s/mEz3z/52L8bmy](https://sketch.cloud/s/mEz3z/52L8bmy) can you let us know, and write up some of the design decisions (including expected functionality of links/buttons) as a comment here, then create an implementation ticket to put into the Ready section of the board?

I'd also like to flag that some of the text as it is in the linked mockup doesn't appear to be compliant with [https://webaim.org/articles/contrast/](WCAG 2.0 contrast rules), so you may want to spec hex/rgb/hsl colors as well. With the card- or tile-based features on this page, you may also want to spell out expected reflow behavior for mobile with some wireframes. Or maybe this is all in a design document elsewhere? I'm not finding anything in the Google Drive folder or in the Sketch Cloud doc, so if you could point to that (or to CSS/SCSS files), that would be great.  Thanks!

**Comment by jsimic** [comment]
POSM Wireframe: https://www.lucidchart.com/invitations/accept/d28325a6-71df-45cc-af48-b520b49ede65

**Comment by shieldsb** [comment]
See MAC design
