### ISSUE TITLE
Update hyrax-migrator to bring recent updates and configurations

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/OD2#985]
### Descriptive summary

Update hyrax-migrator to bring recent updates and adjust configurations as needed for the updates.

### Expected behavior

The gem will have the most recent version and configurations.

### Related work
https://github.com/OregonDigital/hyrax-migrator/pull/176
https://github.com/OregonDigital/hyrax-migrator/pull/177
https://github.com/OregonDigital/hyrax-migrator/pull/178

### Accessibility Concerns

NA

**Comment by raybrarian** [comment]
ASsigning to @lsat12357 to QA

**Comment by lsat12357** [comment]
QA: successfully reingested lichens on staging
