### ISSUE TITLE
Geonames limit is ACTUALLY being hit. Locally for me

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#991]
### Descriptive summary

So we need to make sure we do a couple things. 

1) What do we do with works that can't fetch from geonames because limit is reached
2) How can we make sure that the limit doesn't get hit? Can we register with geonames to remove this limit?
3) How is Scholars Archive set up such that this doesn't happen?

<img width="1667" alt="Screen Shot 2020-02-05 at 7 56 00 AM" src="https://user-images.githubusercontent.com/6424683/73858412-34fc6980-47ed-11ea-884c-8fd614f5b31f.png">

**Comment by raybrarian** [comment]
@shieldsb - in standup today, we discussed this. @straleyb will keep digging for how these queries are maxing out this "credit" amount in GeoNames, and you and I can check into what the cost of moving to a commercial account might be (and if we in fact need one).

**Comment by shieldsb** [comment]
Pricing for additional credits: http://www.geonames.org/commercial-webservices.html

**Comment by wickr** [comment]
If each request uses at least one credit, then our nested fetching that goes up the hierarchy will use several credits for a single URI. Caching on our end will obviously help with this.

If the hourly (or daily) limit is hit, the request should be queued again for later.

ScholarsArchive overall has a small amount of Geonames URIs, and adding a few here and there wouldn't get anywhere close to the limit.

I think we have 3 options:

1) extract URIs from our data and start pre-warming our cache now and keep it running over time, so when we ingest data our cache already has (most of) it and doesn't have to hit Geonames much
2) download Geonames data locally and query it somehow: https://download.geonames.org/export/dump/readme.txt
3) buy additional credits

**Comment by CGillen** [comment]
From @wickr's comment above, can we get the Geonames dump & put it in our cache?
If it's too slow or blows up our cache, can we make it a separate service?

It sounds like the first path we want to explore is populating our own cache, either pre-warming from Geonames directly or from the Geonames data dump.

**Comment by CGillen** [comment]
@lsat12357 Are we hitting geonames limits while migrating so far? How are you feeling about this ticket?

**Comment by lsat12357** [comment]
I dumped alll geonames uris in use on od1 in June and put them in the cache over the course of several days, so it hasn't been a migration issue.

**Comment by lsat12357** [comment]
After this work was done https://github.com/OregonDigital/OD2/issues/2244, the number of fetches we required during an ingest went down, and post migration this is unlikely to be a problem
