### ISSUE TITLE
Don't send verification email for institutional login

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#992]
### Descriptive summary
#848 Added verification emails for community groups. I recently logged in as a new institutional user and was required to verify my email. Institutional emails should already be verified and guaranteed by the institution's SSO.

### Expected behavior
No verification email goes out and user is not blocked from first sign in as a new user through institutional SSO.

### Related work
#848 

### Accessibility Concerns
N/A

**Comment by straleyb** [comment]
QA: Login with a new UO or OSU account and it should work without needing to verify through email.

**Comment by shieldsb** [comment]
QA fail.  Margaret tested first time log in and still received an email.
 
![image](https://user-images.githubusercontent.com/53542788/79263208-50b46980-7e47-11ea-96e8-3cb633504a31.png)

**Comment by shieldsb** [comment]
QA pass. Tested by Dave Manela.
