### ISSUE TITLE
A parent work should show universal viewer for child works it has even if the parent doesn't have a fileset associated

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#998]
### Descriptive summary

Universal viewer depends on a work having a file set in order to show universal viewer. When works are migrated, the parent works don't have file sets associated with it. We still want to show universal viewer for a parent work even if it does not have a file set to display its children in universal viewer.

**Comment by CGillen** [comment]
https://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb19646045%2Fmanifest&xywh=-313%2C-479%2C4590%2C4144
This example includes using the index to point to different "ranges" of images. By default all parent and child images show in UV, so ranges can be used to point out which ones are the parent's images, and each child's images.
This is easily done by implementing `#ranges` on IIIFPresenter
https://github.com/samvera/iiif_manifest/tree/v0.5.0

The other challenge is getting UV to display if the parent has no works. Right now there's two paths for this. If the work is a generic, `GenericPresenter#iiif_viewer?` is looking for `#file_set_presenters` to not be empty and to be presenting an image or PDF. Any other work has `#iiif_viewer?` checking for a representative id and presenter that presents a viewable image: https://github.com/samvera/hyrax/blob/v2.7.0/app/presenters/hyrax/work_show_presenter.rb#L59-L65

**Comment by CGillen** [comment]
QA:
- [ ] Compound objects exist on staging
- [ ] A parent work without files and with children with files will display Universal Viewer
- [ ] A parent work without files and with children without files will NOT display Universal Viewer
- [ ] A work without children and without files will NOT display Universal Viewer
- [ ] A work without children and with files will display Universal Viewer

**Comment by shieldsb** [comment]
QA pass.
