### ISSUE TITLE
Look into IIIF and how to generate manifests that link to other manifests

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#999]
### Descriptive summary

We need to be able to display metadata for child works FileSets for a parent work. This happens, theoretically, by linking manifests together in some way. We need to explore the possibilities of this in order to figure out a way to display separate metadata per FileSet per child of a parent work. This would be progress toward fully utilizing IIIF and Universal Viewer.

**Comment by CGillen** [comment]
https://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb19646045%2Fmanifest&xywh=-313%2C-479%2C4590%2C4144
This example includes using the index to point to different "ranges" of images. By default all parent and child images show in UV, so ranges can be used to point out which ones are the parent's images, and each child's images.
This is easily done by implementing #ranges on IIIFPresenter
https://github.com/samvera/iiif_manifest/tree/v0.5.0

I also found out that parent works without filesets will display UV similarly except it won't show all the files in the thumbnails tab. The index tab will display the children and cause a reload when a child is selected, after the reload the thumbnails tab will only have images for that child. Emulating this and adding the parent to the index may be preferable.

The other challenge is getting UV to display if the parent has no works. Right now there's two paths for this. If the work is a generic, GenericPresenter#iiif_viewer? is looking for #file_set_presenters to not be empty and to be presenting an image or PDF. Any other work has #iiif_viewer? checking for a representative id and presenter that presents a viewable image: https://github.com/samvera/hyrax/blob/v2.7.0/app/presenters/hyrax/work_show_presenter.rb#L59-L65
